
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Nov 16 2025 15:14:45 IST (Nov 16 2025 09:44:45 UTC)

// Verification Directory fv/toll_gate 

module account_balance(clk, reset, id_to_check, fsm_check_req,
     fsm_charge_req, sufficient_balance, charge_done, DFT_sdi, DFT_sen,
     DFT_sdo, DFT_sdi_1);
  input clk, reset, fsm_check_req, fsm_charge_req, DFT_sdi, DFT_sen,
       DFT_sdi_1;
  input [7:0] id_to_check;
  output sufficient_balance, charge_done, DFT_sdo;
  wire clk, reset, fsm_check_req, fsm_charge_req, DFT_sdi, DFT_sen,
       DFT_sdi_1;
  wire [7:0] id_to_check;
  wire sufficient_balance, charge_done, DFT_sdo;
  wire [15:0] \balance_db[0] ;
  wire [15:0] \balance_db[4] ;
  wire [15:0] \balance_db[5] ;
  wire [15:0] \balance_db[6] ;
  wire [15:0] \balance_db[7] ;
  wire [15:0] \balance_db[8] ;
  wire [15:0] \balance_db[9] ;
  wire [15:0] \balance_db[10] ;
  wire [15:0] \balance_db[11] ;
  wire [15:0] \balance_db[12] ;
  wire [15:0] \balance_db[13] ;
  wire [15:0] \balance_db[14] ;
  wire [15:0] \balance_db[15] ;
  wire [15:0] \balance_db[3] ;
  wire [15:0] \balance_db[1] ;
  wire [15:0] \balance_db[2] ;
  wire n_6, n_80, n_96, n_115, n_133, n_146, n_149, n_151;
  wire n_201, n_208, n_232, n_242, n_256, n_279, n_368, n_369;
  wire n_370, n_383, n_393, n_396, n_397, n_409, n_410, n_411;
  wire n_412, n_413, n_414, n_415, n_416, n_417, n_418, n_419;
  wire n_420, n_421, n_422, n_423, n_424, n_425, n_426, n_427;
  wire n_428, n_429, n_430, n_431, n_432, n_433, n_434, n_435;
  wire n_436, n_437, n_438, n_439, n_440, n_441, n_442, n_443;
  wire n_444, n_445, n_446, n_448, n_449, n_450, n_451, n_452;
  wire n_453, n_454, n_455, n_456, n_457, n_458, n_459, n_460;
  wire n_461, n_463, n_464, n_465, n_467, n_468, n_469, n_470;
  wire n_471, n_472, n_473, n_474, n_475, n_476, n_477, n_478;
  wire n_479, n_480, n_481, n_482, n_483, n_484, n_485, n_487;
  wire n_488, n_489, n_490, n_491, n_495, n_496, n_497, n_498;
  wire n_499, n_500, n_501, n_502, n_503, n_504, n_506, n_508;
  wire n_509, n_510, n_511, n_512, n_514, n_515, n_516, n_517;
  wire n_519, n_520, n_521, n_522, n_523, n_524, n_525, n_526;
  wire n_527, n_528, n_529, n_530, n_531, n_533, n_534, n_535;
  wire n_536, n_537, n_538, n_539, n_540, n_541, n_542, n_543;
  wire n_544, n_545, n_546, n_547, n_548, n_549, n_550, n_551;
  wire n_552, n_553, n_554, n_555, n_556, n_557, n_558, n_560;
  wire n_561, n_562, n_564, n_565, n_566, n_567, n_568, n_570;
  wire n_572, n_574, n_575, n_576, n_578, n_579, n_580, n_581;
  wire n_582, n_583, n_584, n_585, n_586, n_587, n_588, n_589;
  wire n_590, n_591, n_592, n_593, n_594, n_596, n_597, n_598;
  wire n_599, n_600, n_601, n_602, n_603, n_604, n_605, n_606;
  wire n_607, n_608, n_609, n_610, n_612, n_613, n_614, n_615;
  wire n_616, n_617, n_618, n_619, n_620, n_621, n_623, n_624;
  wire n_626, n_627, n_628, n_629, n_630, n_631, n_632, n_633;
  wire n_634, n_635, n_637, n_639, n_640, n_641, n_642, n_643;
  wire n_644, n_645, n_646, n_647, n_648, n_649, n_650, n_651;
  wire n_652, n_653, n_654, n_655, n_656, n_657, n_658, n_659;
  wire n_660, n_661, n_662, n_663, n_664, n_666, n_667, n_668;
  wire n_669, n_671, n_672, n_673, n_674, n_675, n_676, n_677;
  wire n_678, n_679, n_680, n_681, n_682, n_683, n_684, n_685;
  wire n_686, n_687, n_688, n_689, n_690, n_691, n_692, n_693;
  wire n_694, n_695, n_696, n_697, n_698, n_699, n_700, n_701;
  wire n_702, n_703, n_704, n_705, n_706, n_707, n_708, n_709;
  wire n_710, n_711, n_712, n_714, n_715, n_716, n_717, n_718;
  wire n_719, n_720, n_721, n_722, n_723, n_724, n_725, n_726;
  wire n_727, n_728, n_729, n_730, n_731, n_732, n_733, n_734;
  wire n_735, n_736, n_739, n_742, n_743, n_744, n_745, n_746;
  wire n_747, n_748, n_749, n_750, n_751, n_752, n_753, n_754;
  wire n_755, n_756, n_757, n_758, n_760, n_762, n_763, n_764;
  wire n_765, n_766, n_767, n_768, n_769, n_770, n_771, n_773;
  wire n_779, n_780, n_781, n_784, n_785, n_786, n_788, n_789;
  wire n_790, n_791, n_792, n_793, n_794, n_795, n_796, n_797;
  wire n_798, n_799, n_800, n_802, n_803, n_804, n_805, n_806;
  wire n_807, n_808, n_809, n_810, n_811, n_812, n_813, n_814;
  wire n_815, n_816, n_817, n_818, n_819, n_820, n_821, n_1938_BAR;
  wire n_1939_BAR, n_1948_BAR, n_1949_BAR;
  SDFFQX1 \balance_db_reg[0][1] (.CK (clk), .D (n_764), .SI
       (\balance_db[0] [1]), .SE (n_791), .Q (\balance_db[0] [1]));
  SDFFQX1 \balance_db_reg[0][2] (.CK (clk), .D (n_800), .SI
       (\balance_db[0] [2]), .SE (n_791), .Q (\balance_db[0] [2]));
  SDFFQX1 \balance_db_reg[0][3] (.CK (clk), .D (n_784), .SI
       (\balance_db[0] [3]), .SE (n_791), .Q (\balance_db[0] [3]));
  SDFFQX1 \balance_db_reg[0][4] (.CK (clk), .D (n_1949_BAR), .SI
       (\balance_db[0] [4]), .SE (n_791), .Q (\balance_db[0] [4]));
  SDFFQX1 \balance_db_reg[0][5] (.CK (clk), .D (n_786), .SI
       (\balance_db[0] [5]), .SE (n_791), .Q (\balance_db[0] [5]));
  SDFFQX1 \balance_db_reg[0][6] (.CK (clk), .D (n_1939_BAR), .SI
       (\balance_db[0] [6]), .SE (n_791), .Q (\balance_db[0] [6]));
  SDFFQX1 \balance_db_reg[0][7] (.CK (clk), .D (n_780), .SI
       (\balance_db[0] [7]), .SE (n_791), .Q (\balance_db[0] [7]));
  SDFFQX1 \balance_db_reg[0][8] (.CK (clk), .D (n_1948_BAR), .SI
       (\balance_db[0] [8]), .SE (n_791), .Q (\balance_db[0] [8]));
  SDFFQX1 \balance_db_reg[0][9] (.CK (clk), .D (n_785), .SI
       (\balance_db[0] [9]), .SE (n_791), .Q (\balance_db[0] [9]));
  SDFFQX1 \balance_db_reg[0][10] (.CK (clk), .D (n_1938_BAR), .SI
       (\balance_db[0] [10]), .SE (n_791), .Q (\balance_db[0] [10]));
  SDFFQX1 \balance_db_reg[0][11] (.CK (clk), .D (n_779), .SI
       (\balance_db[0] [11]), .SE (n_791), .Q (\balance_db[0] [11]));
  SDFFQX1 \balance_db_reg[0][12] (.CK (clk), .D (n_765), .SI
       (\balance_db[0] [12]), .SE (n_791), .Q (\balance_db[0] [12]));
  SDFFQX1 \balance_db_reg[0][13] (.CK (clk), .D (n_781), .SI
       (\balance_db[0] [13]), .SE (n_791), .Q (\balance_db[0] [13]));
  SDFFQX1 \balance_db_reg[0][14] (.CK (clk), .D (n_788), .SI
       (\balance_db[0] [14]), .SE (n_791), .Q (\balance_db[0] [14]));
  SDFFQX1 \balance_db_reg[0][15] (.CK (clk), .D (n_771), .SI
       (\balance_db[0] [15]), .SE (n_791), .Q (\balance_db[0] [15]));
  SDFFQX1 \balance_db_reg[4][1] (.CK (clk), .D (\balance_db[4] [1]),
       .SI (n_764), .SE (n_794), .Q (\balance_db[4] [1]));
  SDFFQX1 \balance_db_reg[4][2] (.CK (clk), .D (\balance_db[4] [2]),
       .SI (n_800), .SE (n_794), .Q (\balance_db[4] [2]));
  SDFFQX1 \balance_db_reg[4][3] (.CK (clk), .D (\balance_db[4] [3]),
       .SI (n_784), .SE (n_794), .Q (\balance_db[4] [3]));
  SDFFQX1 \balance_db_reg[4][4] (.CK (clk), .D (\balance_db[4] [4]),
       .SI (n_1949_BAR), .SE (n_794), .Q (\balance_db[4] [4]));
  SDFFQX1 \balance_db_reg[4][5] (.CK (clk), .D (\balance_db[4] [5]),
       .SI (n_786), .SE (n_794), .Q (\balance_db[4] [5]));
  SDFFQX1 \balance_db_reg[4][6] (.CK (clk), .D (\balance_db[4] [6]),
       .SI (n_1939_BAR), .SE (n_794), .Q (\balance_db[4] [6]));
  SDFFQX1 \balance_db_reg[4][7] (.CK (clk), .D (\balance_db[4] [7]),
       .SI (n_780), .SE (n_794), .Q (\balance_db[4] [7]));
  SDFFQX1 \balance_db_reg[4][8] (.CK (clk), .D (\balance_db[4] [8]),
       .SI (n_1948_BAR), .SE (n_794), .Q (\balance_db[4] [8]));
  SDFFQX1 \balance_db_reg[4][9] (.CK (clk), .D (\balance_db[4] [9]),
       .SI (n_785), .SE (n_794), .Q (\balance_db[4] [9]));
  SDFFQX1 \balance_db_reg[4][10] (.CK (clk), .D (\balance_db[4] [10]),
       .SI (n_1938_BAR), .SE (n_794), .Q (\balance_db[4] [10]));
  SDFFQX1 \balance_db_reg[4][11] (.CK (clk), .D (\balance_db[4] [11]),
       .SI (n_779), .SE (n_794), .Q (\balance_db[4] [11]));
  SDFFQX1 \balance_db_reg[4][12] (.CK (clk), .D (\balance_db[4] [12]),
       .SI (n_765), .SE (n_794), .Q (\balance_db[4] [12]));
  SDFFQX1 \balance_db_reg[4][13] (.CK (clk), .D (\balance_db[4] [13]),
       .SI (n_781), .SE (n_794), .Q (\balance_db[4] [13]));
  SDFFQX1 \balance_db_reg[4][14] (.CK (clk), .D (\balance_db[4] [14]),
       .SI (n_788), .SE (n_794), .Q (\balance_db[4] [14]));
  SDFFQX1 \balance_db_reg[4][15] (.CK (clk), .D (\balance_db[4] [15]),
       .SI (n_771), .SE (n_794), .Q (\balance_db[4] [15]));
  SDFFQX1 \balance_db_reg[5][1] (.CK (clk), .D (\balance_db[5] [1]),
       .SI (n_764), .SE (n_796), .Q (\balance_db[5] [1]));
  SDFFQX1 \balance_db_reg[5][2] (.CK (clk), .D (\balance_db[5] [2]),
       .SI (n_800), .SE (n_796), .Q (\balance_db[5] [2]));
  SDFFQX1 \balance_db_reg[5][3] (.CK (clk), .D (\balance_db[5] [3]),
       .SI (n_784), .SE (n_796), .Q (\balance_db[5] [3]));
  SDFFQX1 \balance_db_reg[5][4] (.CK (clk), .D (\balance_db[5] [4]),
       .SI (n_1949_BAR), .SE (n_796), .Q (\balance_db[5] [4]));
  SDFFQX1 \balance_db_reg[5][5] (.CK (clk), .D (\balance_db[5] [5]),
       .SI (n_786), .SE (n_796), .Q (\balance_db[5] [5]));
  SDFFQX1 \balance_db_reg[5][6] (.CK (clk), .D (\balance_db[5] [6]),
       .SI (n_1939_BAR), .SE (n_796), .Q (\balance_db[5] [6]));
  SDFFQX1 \balance_db_reg[5][7] (.CK (clk), .D (\balance_db[5] [7]),
       .SI (n_780), .SE (n_796), .Q (\balance_db[5] [7]));
  SDFFQX1 \balance_db_reg[5][8] (.CK (clk), .D (\balance_db[5] [8]),
       .SI (n_1948_BAR), .SE (n_796), .Q (\balance_db[5] [8]));
  SDFFQX1 \balance_db_reg[5][9] (.CK (clk), .D (\balance_db[5] [9]),
       .SI (n_785), .SE (n_796), .Q (\balance_db[5] [9]));
  SDFFQX1 \balance_db_reg[5][10] (.CK (clk), .D (\balance_db[5] [10]),
       .SI (n_1938_BAR), .SE (n_796), .Q (\balance_db[5] [10]));
  SDFFQX1 \balance_db_reg[5][11] (.CK (clk), .D (\balance_db[5] [11]),
       .SI (n_779), .SE (n_796), .Q (\balance_db[5] [11]));
  SDFFQX1 \balance_db_reg[5][12] (.CK (clk), .D (\balance_db[5] [12]),
       .SI (n_765), .SE (n_796), .Q (\balance_db[5] [12]));
  SDFFQX1 \balance_db_reg[5][13] (.CK (clk), .D (\balance_db[5] [13]),
       .SI (n_781), .SE (n_796), .Q (\balance_db[5] [13]));
  SDFFQX1 \balance_db_reg[5][14] (.CK (clk), .D (\balance_db[5] [14]),
       .SI (n_788), .SE (n_796), .Q (\balance_db[5] [14]));
  SDFFQX1 \balance_db_reg[5][15] (.CK (clk), .D (\balance_db[5] [15]),
       .SI (n_771), .SE (n_796), .Q (\balance_db[5] [15]));
  SDFFQX1 \balance_db_reg[6][1] (.CK (clk), .D (\balance_db[6] [1]),
       .SI (n_764), .SE (n_803), .Q (\balance_db[6] [1]));
  SDFFQX1 \balance_db_reg[6][2] (.CK (clk), .D (\balance_db[6] [2]),
       .SI (n_800), .SE (n_803), .Q (\balance_db[6] [2]));
  SDFFQX1 \balance_db_reg[6][3] (.CK (clk), .D (\balance_db[6] [3]),
       .SI (n_784), .SE (n_803), .Q (\balance_db[6] [3]));
  SDFFQX1 \balance_db_reg[6][4] (.CK (clk), .D (\balance_db[6] [4]),
       .SI (n_1949_BAR), .SE (n_803), .Q (\balance_db[6] [4]));
  SDFFQX1 \balance_db_reg[6][5] (.CK (clk), .D (\balance_db[6] [5]),
       .SI (n_786), .SE (n_803), .Q (\balance_db[6] [5]));
  SDFFQX1 \balance_db_reg[6][6] (.CK (clk), .D (\balance_db[6] [6]),
       .SI (n_1939_BAR), .SE (n_803), .Q (\balance_db[6] [6]));
  SDFFQX1 \balance_db_reg[6][7] (.CK (clk), .D (\balance_db[6] [7]),
       .SI (n_780), .SE (n_803), .Q (\balance_db[6] [7]));
  SDFFQX1 \balance_db_reg[6][8] (.CK (clk), .D (\balance_db[6] [8]),
       .SI (n_1948_BAR), .SE (n_803), .Q (\balance_db[6] [8]));
  SDFFQX1 \balance_db_reg[6][9] (.CK (clk), .D (\balance_db[6] [9]),
       .SI (n_785), .SE (n_803), .Q (\balance_db[6] [9]));
  SDFFQX1 \balance_db_reg[6][10] (.CK (clk), .D (\balance_db[6] [10]),
       .SI (n_1938_BAR), .SE (n_803), .Q (\balance_db[6] [10]));
  SDFFQX1 \balance_db_reg[6][11] (.CK (clk), .D (\balance_db[6] [11]),
       .SI (n_779), .SE (n_803), .Q (\balance_db[6] [11]));
  SDFFQX1 \balance_db_reg[6][12] (.CK (clk), .D (\balance_db[6] [12]),
       .SI (n_765), .SE (n_803), .Q (\balance_db[6] [12]));
  SDFFQX1 \balance_db_reg[6][13] (.CK (clk), .D (\balance_db[6] [13]),
       .SI (n_781), .SE (n_803), .Q (\balance_db[6] [13]));
  SDFFQX1 \balance_db_reg[6][14] (.CK (clk), .D (\balance_db[6] [14]),
       .SI (n_788), .SE (n_803), .Q (\balance_db[6] [14]));
  SDFFQX1 \balance_db_reg[6][15] (.CK (clk), .D (\balance_db[6] [15]),
       .SI (n_771), .SE (n_803), .Q (\balance_db[6] [15]));
  SDFFQX1 \balance_db_reg[7][1] (.CK (clk), .D (\balance_db[7] [1]),
       .SI (n_764), .SE (n_799), .Q (\balance_db[7] [1]));
  SDFFQX1 \balance_db_reg[7][2] (.CK (clk), .D (\balance_db[7] [2]),
       .SI (n_800), .SE (n_799), .Q (\balance_db[7] [2]));
  SDFFQX1 \balance_db_reg[7][3] (.CK (clk), .D (\balance_db[7] [3]),
       .SI (n_784), .SE (n_799), .Q (\balance_db[7] [3]));
  SDFFQX1 \balance_db_reg[7][4] (.CK (clk), .D (\balance_db[7] [4]),
       .SI (n_1949_BAR), .SE (n_799), .Q (\balance_db[7] [4]));
  SDFFQX1 \balance_db_reg[7][5] (.CK (clk), .D (\balance_db[7] [5]),
       .SI (n_786), .SE (n_799), .Q (\balance_db[7] [5]));
  SDFFQX1 \balance_db_reg[7][6] (.CK (clk), .D (\balance_db[7] [6]),
       .SI (n_1939_BAR), .SE (n_799), .Q (\balance_db[7] [6]));
  SDFFQX1 \balance_db_reg[7][7] (.CK (clk), .D (\balance_db[7] [7]),
       .SI (n_780), .SE (n_799), .Q (\balance_db[7] [7]));
  SDFFQX1 \balance_db_reg[7][8] (.CK (clk), .D (\balance_db[7] [8]),
       .SI (n_1948_BAR), .SE (n_799), .Q (\balance_db[7] [8]));
  SDFFQX1 \balance_db_reg[7][9] (.CK (clk), .D (\balance_db[7] [9]),
       .SI (n_785), .SE (n_799), .Q (\balance_db[7] [9]));
  SDFFQX1 \balance_db_reg[7][10] (.CK (clk), .D (\balance_db[7] [10]),
       .SI (n_1938_BAR), .SE (n_799), .Q (\balance_db[7] [10]));
  SDFFQX1 \balance_db_reg[7][11] (.CK (clk), .D (\balance_db[7] [11]),
       .SI (n_779), .SE (n_799), .Q (\balance_db[7] [11]));
  SDFFQX1 \balance_db_reg[7][12] (.CK (clk), .D (\balance_db[7] [12]),
       .SI (n_765), .SE (n_799), .Q (\balance_db[7] [12]));
  SDFFQX1 \balance_db_reg[7][13] (.CK (clk), .D (\balance_db[7] [13]),
       .SI (n_781), .SE (n_799), .Q (\balance_db[7] [13]));
  SDFFQX1 \balance_db_reg[7][14] (.CK (clk), .D (\balance_db[7] [14]),
       .SI (n_788), .SE (n_799), .Q (\balance_db[7] [14]));
  SDFFQX1 \balance_db_reg[7][15] (.CK (clk), .D (\balance_db[7] [15]),
       .SI (n_771), .SE (n_799), .Q (\balance_db[7] [15]));
  SDFFQX1 \balance_db_reg[8][1] (.CK (clk), .D (\balance_db[8] [1]),
       .SI (n_764), .SE (n_789), .Q (\balance_db[8] [1]));
  SDFFQX1 \balance_db_reg[8][2] (.CK (clk), .D (\balance_db[8] [2]),
       .SI (n_800), .SE (n_789), .Q (\balance_db[8] [2]));
  SDFFQX1 \balance_db_reg[8][3] (.CK (clk), .D (\balance_db[8] [3]),
       .SI (n_784), .SE (n_789), .Q (\balance_db[8] [3]));
  SDFFQX1 \balance_db_reg[8][4] (.CK (clk), .D (\balance_db[8] [4]),
       .SI (n_1949_BAR), .SE (n_789), .Q (\balance_db[8] [4]));
  SDFFQX1 \balance_db_reg[8][5] (.CK (clk), .D (\balance_db[8] [5]),
       .SI (n_786), .SE (n_789), .Q (\balance_db[8] [5]));
  SDFFQX1 \balance_db_reg[8][6] (.CK (clk), .D (\balance_db[8] [6]),
       .SI (n_1939_BAR), .SE (n_789), .Q (\balance_db[8] [6]));
  SDFFQX1 \balance_db_reg[8][7] (.CK (clk), .D (\balance_db[8] [7]),
       .SI (n_780), .SE (n_789), .Q (\balance_db[8] [7]));
  SDFFQXL \balance_db_reg[8][8] (.CK (clk), .D (\balance_db[8] [8]),
       .SI (n_1948_BAR), .SE (n_789), .Q (\balance_db[8] [8]));
  SDFFQX1 \balance_db_reg[8][9] (.CK (clk), .D (\balance_db[8] [9]),
       .SI (n_785), .SE (n_789), .Q (\balance_db[8] [9]));
  SDFFQXL \balance_db_reg[8][10] (.CK (clk), .D (\balance_db[8] [10]),
       .SI (n_1938_BAR), .SE (n_789), .Q (\balance_db[8] [10]));
  SDFFQXL \balance_db_reg[8][11] (.CK (clk), .D (\balance_db[8] [11]),
       .SI (n_779), .SE (n_789), .Q (\balance_db[8] [11]));
  SDFFQXL \balance_db_reg[8][12] (.CK (clk), .D (\balance_db[8] [12]),
       .SI (n_765), .SE (n_789), .Q (\balance_db[8] [12]));
  SDFFQX1 \balance_db_reg[8][13] (.CK (clk), .D (\balance_db[8] [13]),
       .SI (n_781), .SE (n_789), .Q (\balance_db[8] [13]));
  SDFFQX1 \balance_db_reg[8][14] (.CK (clk), .D (\balance_db[8] [14]),
       .SI (n_788), .SE (n_789), .Q (\balance_db[8] [14]));
  SDFFQX1 \balance_db_reg[8][15] (.CK (clk), .D (\balance_db[8] [15]),
       .SI (n_771), .SE (n_789), .Q (\balance_db[8] [15]));
  SDFFQX1 \balance_db_reg[9][1] (.CK (clk), .D (\balance_db[9] [1]),
       .SI (n_764), .SE (n_802), .Q (\balance_db[9] [1]));
  SDFFQX1 \balance_db_reg[9][2] (.CK (clk), .D (\balance_db[9] [2]),
       .SI (n_800), .SE (n_802), .Q (\balance_db[9] [2]));
  SDFFQX1 \balance_db_reg[9][3] (.CK (clk), .D (\balance_db[9] [3]),
       .SI (n_784), .SE (n_802), .Q (\balance_db[9] [3]));
  SDFFQX1 \balance_db_reg[9][4] (.CK (clk), .D (\balance_db[9] [4]),
       .SI (n_1949_BAR), .SE (n_802), .Q (\balance_db[9] [4]));
  SDFFQX1 \balance_db_reg[9][5] (.CK (clk), .D (\balance_db[9] [5]),
       .SI (n_786), .SE (n_802), .Q (\balance_db[9] [5]));
  SDFFQXL \balance_db_reg[9][6] (.CK (clk), .D (\balance_db[9] [6]),
       .SI (n_1939_BAR), .SE (n_802), .Q (\balance_db[9] [6]));
  SDFFQXL \balance_db_reg[9][7] (.CK (clk), .D (\balance_db[9] [7]),
       .SI (n_780), .SE (n_802), .Q (\balance_db[9] [7]));
  SDFFQXL \balance_db_reg[9][8] (.CK (clk), .D (\balance_db[9] [8]),
       .SI (n_1948_BAR), .SE (n_802), .Q (\balance_db[9] [8]));
  SDFFQXL \balance_db_reg[9][9] (.CK (clk), .D (\balance_db[9] [9]),
       .SI (n_785), .SE (n_802), .Q (\balance_db[9] [9]));
  SDFFQXL \balance_db_reg[9][10] (.CK (clk), .D (\balance_db[9] [10]),
       .SI (n_1938_BAR), .SE (n_802), .Q (\balance_db[9] [10]));
  SDFFQXL \balance_db_reg[9][11] (.CK (clk), .D (\balance_db[9] [11]),
       .SI (n_779), .SE (n_802), .Q (\balance_db[9] [11]));
  SDFFQXL \balance_db_reg[9][12] (.CK (clk), .D (\balance_db[9] [12]),
       .SI (n_765), .SE (n_802), .Q (\balance_db[9] [12]));
  SDFFQXL \balance_db_reg[9][13] (.CK (clk), .D (\balance_db[9] [13]),
       .SI (n_781), .SE (n_802), .Q (\balance_db[9] [13]));
  SDFFQXL \balance_db_reg[9][14] (.CK (clk), .D (\balance_db[9] [14]),
       .SI (n_788), .SE (n_802), .Q (\balance_db[9] [14]));
  SDFFQX1 \balance_db_reg[9][15] (.CK (clk), .D (\balance_db[9] [15]),
       .SI (n_771), .SE (n_802), .Q (\balance_db[9] [15]));
  SDFFQX1 \balance_db_reg[10][1] (.CK (clk), .D (\balance_db[10] [1]),
       .SI (n_764), .SE (n_792), .Q (\balance_db[10] [1]));
  SDFFQX1 \balance_db_reg[10][2] (.CK (clk), .D (\balance_db[10] [2]),
       .SI (n_800), .SE (n_792), .Q (\balance_db[10] [2]));
  SDFFQX1 \balance_db_reg[10][3] (.CK (clk), .D (\balance_db[10] [3]),
       .SI (n_784), .SE (n_792), .Q (\balance_db[10] [3]));
  SDFFQX1 \balance_db_reg[10][4] (.CK (clk), .D (\balance_db[10] [4]),
       .SI (n_1949_BAR), .SE (n_792), .Q (\balance_db[10] [4]));
  SDFFQX1 \balance_db_reg[10][5] (.CK (clk), .D (\balance_db[10] [5]),
       .SI (n_786), .SE (n_792), .Q (\balance_db[10] [5]));
  SDFFQX1 \balance_db_reg[10][6] (.CK (clk), .D (\balance_db[10] [6]),
       .SI (n_1939_BAR), .SE (n_792), .Q (\balance_db[10] [6]));
  SDFFQX1 \balance_db_reg[10][7] (.CK (clk), .D (\balance_db[10] [7]),
       .SI (n_780), .SE (n_792), .Q (\balance_db[10] [7]));
  SDFFQXL \balance_db_reg[10][8] (.CK (clk), .D (\balance_db[10] [8]),
       .SI (n_1948_BAR), .SE (n_792), .Q (\balance_db[10] [8]));
  SDFFQXL \balance_db_reg[10][9] (.CK (clk), .D (\balance_db[10] [9]),
       .SI (n_785), .SE (n_792), .Q (\balance_db[10] [9]));
  SDFFQX1 \balance_db_reg[10][10] (.CK (clk), .D (\balance_db[10]
       [10]), .SI (n_1938_BAR), .SE (n_792), .Q (\balance_db[10] [10]));
  SDFFQXL \balance_db_reg[10][11] (.CK (clk), .D (\balance_db[10]
       [11]), .SI (n_779), .SE (n_792), .Q (\balance_db[10] [11]));
  SDFFQXL \balance_db_reg[10][12] (.CK (clk), .D (\balance_db[10]
       [12]), .SI (n_765), .SE (n_792), .Q (\balance_db[10] [12]));
  SDFFQXL \balance_db_reg[10][13] (.CK (clk), .D (\balance_db[10]
       [13]), .SI (n_781), .SE (n_792), .Q (\balance_db[10] [13]));
  SDFFQXL \balance_db_reg[10][14] (.CK (clk), .D (\balance_db[10]
       [14]), .SI (n_788), .SE (n_792), .Q (\balance_db[10] [14]));
  SDFFQX1 \balance_db_reg[10][15] (.CK (clk), .D (\balance_db[10]
       [15]), .SI (n_771), .SE (n_792), .Q (\balance_db[10] [15]));
  SDFFQX1 \balance_db_reg[11][1] (.CK (clk), .D (n_764), .SI
       (\balance_db[11] [1]), .SE (n_798), .Q (\balance_db[11] [1]));
  SDFFQXL \balance_db_reg[11][2] (.CK (clk), .D (n_800), .SI
       (\balance_db[11] [2]), .SE (n_798), .Q (\balance_db[11] [2]));
  SDFFQXL \balance_db_reg[11][3] (.CK (clk), .D (n_784), .SI
       (\balance_db[11] [3]), .SE (n_798), .Q (\balance_db[11] [3]));
  SDFFQXL \balance_db_reg[11][4] (.CK (clk), .D (n_1949_BAR), .SI
       (\balance_db[11] [4]), .SE (n_798), .Q (\balance_db[11] [4]));
  SDFFQXL \balance_db_reg[11][5] (.CK (clk), .D (n_786), .SI
       (\balance_db[11] [5]), .SE (n_798), .Q (\balance_db[11] [5]));
  SDFFQXL \balance_db_reg[11][6] (.CK (clk), .D (n_1939_BAR), .SI
       (\balance_db[11] [6]), .SE (n_798), .Q (\balance_db[11] [6]));
  SDFFQXL \balance_db_reg[11][7] (.CK (clk), .D (n_780), .SI
       (\balance_db[11] [7]), .SE (n_798), .Q (\balance_db[11] [7]));
  SDFFQXL \balance_db_reg[11][8] (.CK (clk), .D (n_1948_BAR), .SI
       (\balance_db[11] [8]), .SE (n_798), .Q (\balance_db[11] [8]));
  SDFFQXL \balance_db_reg[11][9] (.CK (clk), .D (n_785), .SI
       (\balance_db[11] [9]), .SE (n_798), .Q (\balance_db[11] [9]));
  SDFFQXL \balance_db_reg[11][10] (.CK (clk), .D (n_1938_BAR), .SI
       (\balance_db[11] [10]), .SE (n_798), .Q (\balance_db[11] [10]));
  SDFFQXL \balance_db_reg[11][11] (.CK (clk), .D (n_779), .SI
       (\balance_db[11] [11]), .SE (n_798), .Q (\balance_db[11] [11]));
  SDFFQXL \balance_db_reg[11][12] (.CK (clk), .D (n_765), .SI
       (\balance_db[11] [12]), .SE (n_798), .Q (\balance_db[11] [12]));
  SDFFQXL \balance_db_reg[11][13] (.CK (clk), .D (n_781), .SI
       (\balance_db[11] [13]), .SE (n_798), .Q (\balance_db[11] [13]));
  SDFFQXL \balance_db_reg[11][14] (.CK (clk), .D (n_788), .SI
       (\balance_db[11] [14]), .SE (n_798), .Q (\balance_db[11] [14]));
  SDFFQXL \balance_db_reg[11][15] (.CK (clk), .D (n_771), .SI
       (\balance_db[11] [15]), .SE (n_798), .Q (\balance_db[11] [15]));
  SDFFQX1 \balance_db_reg[12][1] (.CK (clk), .D (\balance_db[12] [1]),
       .SI (n_764), .SE (n_793), .Q (\balance_db[12] [1]));
  SDFFQX1 \balance_db_reg[12][2] (.CK (clk), .D (\balance_db[12] [2]),
       .SI (n_800), .SE (n_793), .Q (\balance_db[12] [2]));
  SDFFQX1 \balance_db_reg[12][3] (.CK (clk), .D (\balance_db[12] [3]),
       .SI (n_784), .SE (n_793), .Q (\balance_db[12] [3]));
  SDFFQX1 \balance_db_reg[12][4] (.CK (clk), .D (\balance_db[12] [4]),
       .SI (n_1949_BAR), .SE (n_793), .Q (\balance_db[12] [4]));
  SDFFQXL \balance_db_reg[12][5] (.CK (clk), .D (\balance_db[12] [5]),
       .SI (n_786), .SE (n_793), .Q (\balance_db[12] [5]));
  SDFFQXL \balance_db_reg[12][6] (.CK (clk), .D (\balance_db[12] [6]),
       .SI (n_1939_BAR), .SE (n_793), .Q (\balance_db[12] [6]));
  SDFFQX1 \balance_db_reg[12][7] (.CK (clk), .D (\balance_db[12] [7]),
       .SI (n_780), .SE (n_793), .Q (\balance_db[12] [7]));
  SDFFQXL \balance_db_reg[12][8] (.CK (clk), .D (\balance_db[12] [8]),
       .SI (n_1948_BAR), .SE (n_793), .Q (\balance_db[12] [8]));
  SDFFQXL \balance_db_reg[12][9] (.CK (clk), .D (\balance_db[12] [9]),
       .SI (n_785), .SE (n_793), .Q (\balance_db[12] [9]));
  SDFFQXL \balance_db_reg[12][10] (.CK (clk), .D (\balance_db[12]
       [10]), .SI (n_1938_BAR), .SE (n_793), .Q (\balance_db[12] [10]));
  SDFFQXL \balance_db_reg[12][11] (.CK (clk), .D (\balance_db[12]
       [11]), .SI (n_779), .SE (n_793), .Q (\balance_db[12] [11]));
  SDFFQXL \balance_db_reg[12][12] (.CK (clk), .D (\balance_db[12]
       [12]), .SI (n_765), .SE (n_793), .Q (\balance_db[12] [12]));
  SDFFQXL \balance_db_reg[12][13] (.CK (clk), .D (\balance_db[12]
       [13]), .SI (n_781), .SE (n_793), .Q (\balance_db[12] [13]));
  SDFFQXL \balance_db_reg[12][14] (.CK (clk), .D (\balance_db[12]
       [14]), .SI (n_788), .SE (n_793), .Q (\balance_db[12] [14]));
  SDFFQX1 \balance_db_reg[12][15] (.CK (clk), .D (\balance_db[12]
       [15]), .SI (n_771), .SE (n_793), .Q (\balance_db[12] [15]));
  SDFFQX1 \balance_db_reg[13][1] (.CK (clk), .D (n_764), .SI
       (\balance_db[13] [1]), .SE (n_797), .Q (\balance_db[13] [1]));
  SDFFQX1 \balance_db_reg[13][2] (.CK (clk), .D (n_800), .SI
       (\balance_db[13] [2]), .SE (n_797), .Q (\balance_db[13] [2]));
  SDFFQXL \balance_db_reg[13][3] (.CK (clk), .D (n_784), .SI
       (\balance_db[13] [3]), .SE (n_797), .Q (\balance_db[13] [3]));
  SDFFQXL \balance_db_reg[13][4] (.CK (clk), .D (n_1949_BAR), .SI
       (\balance_db[13] [4]), .SE (n_797), .Q (\balance_db[13] [4]));
  SDFFQXL \balance_db_reg[13][5] (.CK (clk), .D (n_786), .SI
       (\balance_db[13] [5]), .SE (n_797), .Q (\balance_db[13] [5]));
  SDFFQXL \balance_db_reg[13][6] (.CK (clk), .D (n_1939_BAR), .SI
       (\balance_db[13] [6]), .SE (n_797), .Q (\balance_db[13] [6]));
  SDFFQXL \balance_db_reg[13][7] (.CK (clk), .D (n_780), .SI
       (\balance_db[13] [7]), .SE (n_797), .Q (\balance_db[13] [7]));
  SDFFQXL \balance_db_reg[13][8] (.CK (clk), .D (n_1948_BAR), .SI
       (\balance_db[13] [8]), .SE (n_797), .Q (\balance_db[13] [8]));
  SDFFQXL \balance_db_reg[13][9] (.CK (clk), .D (n_785), .SI
       (\balance_db[13] [9]), .SE (n_797), .Q (\balance_db[13] [9]));
  SDFFQXL \balance_db_reg[13][10] (.CK (clk), .D (n_1938_BAR), .SI
       (\balance_db[13] [10]), .SE (n_797), .Q (\balance_db[13] [10]));
  SDFFQXL \balance_db_reg[13][11] (.CK (clk), .D (n_779), .SI
       (\balance_db[13] [11]), .SE (n_797), .Q (\balance_db[13] [11]));
  SDFFQXL \balance_db_reg[13][12] (.CK (clk), .D (n_765), .SI
       (\balance_db[13] [12]), .SE (n_797), .Q (\balance_db[13] [12]));
  SDFFQXL \balance_db_reg[13][13] (.CK (clk), .D (n_781), .SI
       (\balance_db[13] [13]), .SE (n_797), .Q (\balance_db[13] [13]));
  SDFFQXL \balance_db_reg[13][14] (.CK (clk), .D (n_788), .SI
       (\balance_db[13] [14]), .SE (n_797), .Q (\balance_db[13] [14]));
  SDFFQXL \balance_db_reg[13][15] (.CK (clk), .D (n_771), .SI
       (\balance_db[13] [15]), .SE (n_797), .Q (\balance_db[13] [15]));
  SDFFQX1 \balance_db_reg[14][1] (.CK (clk), .D (\balance_db[14] [1]),
       .SI (n_764), .SE (n_790), .Q (\balance_db[14] [1]));
  SDFFQX1 \balance_db_reg[14][2] (.CK (clk), .D (\balance_db[14] [2]),
       .SI (n_800), .SE (n_790), .Q (\balance_db[14] [2]));
  SDFFQX1 \balance_db_reg[14][3] (.CK (clk), .D (\balance_db[14] [3]),
       .SI (n_784), .SE (n_790), .Q (\balance_db[14] [3]));
  SDFFQX1 \balance_db_reg[14][4] (.CK (clk), .D (\balance_db[14] [4]),
       .SI (n_1949_BAR), .SE (n_790), .Q (\balance_db[14] [4]));
  SDFFQXL \balance_db_reg[14][5] (.CK (clk), .D (\balance_db[14] [5]),
       .SI (n_786), .SE (n_790), .Q (\balance_db[14] [5]));
  SDFFQX1 \balance_db_reg[14][6] (.CK (clk), .D (\balance_db[14] [6]),
       .SI (n_1939_BAR), .SE (n_790), .Q (\balance_db[14] [6]));
  SDFFQX1 \balance_db_reg[14][7] (.CK (clk), .D (\balance_db[14] [7]),
       .SI (n_780), .SE (n_790), .Q (\balance_db[14] [7]));
  SDFFQX1 \balance_db_reg[14][8] (.CK (clk), .D (\balance_db[14] [8]),
       .SI (n_1948_BAR), .SE (n_790), .Q (\balance_db[14] [8]));
  SDFFQXL \balance_db_reg[14][9] (.CK (clk), .D (\balance_db[14] [9]),
       .SI (n_785), .SE (n_790), .Q (\balance_db[14] [9]));
  SDFFQXL \balance_db_reg[14][10] (.CK (clk), .D (\balance_db[14]
       [10]), .SI (n_1938_BAR), .SE (n_790), .Q (\balance_db[14] [10]));
  SDFFQXL \balance_db_reg[14][11] (.CK (clk), .D (\balance_db[14]
       [11]), .SI (n_779), .SE (n_790), .Q (\balance_db[14] [11]));
  SDFFQXL \balance_db_reg[14][12] (.CK (clk), .D (\balance_db[14]
       [12]), .SI (n_765), .SE (n_790), .Q (\balance_db[14] [12]));
  SDFFQXL \balance_db_reg[14][13] (.CK (clk), .D (\balance_db[14]
       [13]), .SI (n_781), .SE (n_790), .Q (\balance_db[14] [13]));
  SDFFQXL \balance_db_reg[14][14] (.CK (clk), .D (\balance_db[14]
       [14]), .SI (n_788), .SE (n_790), .Q (\balance_db[14] [14]));
  SDFFQX1 \balance_db_reg[14][15] (.CK (clk), .D (\balance_db[14]
       [15]), .SI (n_771), .SE (n_790), .Q (\balance_db[14] [15]));
  SDFFQXL \balance_db_reg[15][1] (.CK (clk), .D (n_764), .SI
       (\balance_db[15] [1]), .SE (n_795), .Q (\balance_db[15] [1]));
  SDFFQXL \balance_db_reg[15][2] (.CK (clk), .D (n_800), .SI
       (\balance_db[15] [2]), .SE (n_795), .Q (\balance_db[15] [2]));
  SDFFQXL \balance_db_reg[15][3] (.CK (clk), .D (n_784), .SI
       (\balance_db[15] [3]), .SE (n_795), .Q (\balance_db[15] [3]));
  SDFFQXL \balance_db_reg[15][4] (.CK (clk), .D (n_1949_BAR), .SI
       (\balance_db[15] [4]), .SE (n_795), .Q (\balance_db[15] [4]));
  SDFFQXL \balance_db_reg[15][5] (.CK (clk), .D (n_786), .SI
       (\balance_db[15] [5]), .SE (n_795), .Q (\balance_db[15] [5]));
  SDFFQXL \balance_db_reg[15][6] (.CK (clk), .D (n_1939_BAR), .SI
       (\balance_db[15] [6]), .SE (n_795), .Q (\balance_db[15] [6]));
  SDFFQXL \balance_db_reg[15][7] (.CK (clk), .D (n_780), .SI
       (\balance_db[15] [7]), .SE (n_795), .Q (\balance_db[15] [7]));
  SDFFQXL \balance_db_reg[15][8] (.CK (clk), .D (n_1948_BAR), .SI
       (\balance_db[15] [8]), .SE (n_795), .Q (\balance_db[15] [8]));
  SDFFQXL \balance_db_reg[15][9] (.CK (clk), .D (n_785), .SI
       (\balance_db[15] [9]), .SE (n_795), .Q (\balance_db[15] [9]));
  SDFFQXL \balance_db_reg[15][10] (.CK (clk), .D (n_1938_BAR), .SI
       (\balance_db[15] [10]), .SE (n_795), .Q (\balance_db[15] [10]));
  SDFFQXL \balance_db_reg[15][11] (.CK (clk), .D (n_779), .SI
       (\balance_db[15] [11]), .SE (n_795), .Q (\balance_db[15] [11]));
  SDFFQXL \balance_db_reg[15][12] (.CK (clk), .D (n_765), .SI
       (\balance_db[15] [12]), .SE (n_795), .Q (\balance_db[15] [12]));
  SDFFQXL \balance_db_reg[15][13] (.CK (clk), .D (n_781), .SI
       (\balance_db[15] [13]), .SE (n_795), .Q (\balance_db[15] [13]));
  SDFFQXL \balance_db_reg[15][14] (.CK (clk), .D (n_788), .SI
       (\balance_db[15] [14]), .SE (n_795), .Q (\balance_db[15] [14]));
  SDFFQXL \balance_db_reg[15][15] (.CK (clk), .D (n_771), .SI
       (\balance_db[15] [15]), .SE (n_795), .Q (\balance_db[15] [15]));
  CLKINVX1 g3408(.A (n_1938_BAR), .Y (n_763));
  CLKINVX1 g3406(.A (n_1948_BAR), .Y (n_762));
  CLKINVX1 g3407(.A (n_809), .Y (n_764));
  CLKINVX1 g3403(.A (n_768), .Y (n_765));
  CLKINVX1 g3409(.A (n_773), .Y (sufficient_balance));
  CLKINVX1 g3405(.A (n_1949_BAR), .Y (n_760));
  SDFFQX1 charge_done_reg(.CK (clk), .D (n_749), .SI
       (\balance_db[3] [14]), .SE (DFT_sen), .Q (charge_done));
  OAI21X1 g13137(.A0 (n_718), .A1 (n_757), .B0 (n_743), .Y (n_771));
  OAI21X1 g13138(.A0 (n_724), .A1 (n_755), .B0 (n_739), .Y (n_779));
  NAND2BX1 g13139(.AN (n_758), .B (n_756), .Y (n_788));
  NOR2XL g13140(.A (n_716), .B (n_754), .Y (n_758));
  INVXL g13141(.A (n_756), .Y (n_757));
  AO21X1 g13142(.A0 (n_722), .A1 (n_751), .B0 (n_755), .Y (n_1938_BAR));
  NAND2XL g13143(.A (n_716), .B (n_754), .Y (n_756));
  NOR2XL g13144(.A (n_722), .B (n_751), .Y (n_755));
  OR2X1 g13145(.A (n_495), .B (n_753), .Y (n_795));
  OR2X1 g13146(.A (n_490), .B (n_753), .Y (n_797));
  OR2X1 g13147(.A (n_488), .B (n_753), .Y (n_798));
  AND2X1 g13148(.A (n_498), .B (n_752), .Y (n_802));
  AO21X1 g13149(.A0 (n_721), .A1 (n_747), .B0 (n_754), .Y (n_781));
  INVX1 g13150(.A (n_752), .Y (n_753));
  AND3X1 g13152(.A (id_to_check[1]), .B (n_770), .C (n_468), .Y
       (n_803));
  AND3X1 g13153(.A (id_to_check[1]), .B (n_499), .C (n_468), .Y
       (n_799));
  AND2X1 g13154(.A (n_469), .B (n_468), .Y (n_794));
  NOR2XL g13155(.A (n_721), .B (n_747), .Y (n_754));
  NOR2XL g13156(.A (n_769), .B (n_470), .Y (n_752));
  OAI21X1 g13157(.A0 (n_727), .A1 (n_742), .B0 (n_751), .Y (n_785));
  AND3X1 g13158(.A (id_to_check[2]), .B (n_469), .C (n_750), .Y
       (n_793));
  AND3X1 g13159(.A (n_770), .B (n_489), .C (n_750), .Y (n_792));
  AND2X1 g13160(.A (n_565), .B (n_750), .Y (n_789));
  AND3X1 g13161(.A (n_770), .B (n_496), .C (n_750), .Y (n_790));
  AND3X1 g13162(.A (n_477), .B (n_499), .C (n_468), .Y (n_796));
  CLKINVX1 g13163(.A (n_470), .Y (n_750));
  NOR2XL g13164(.A (reset), .B (n_748), .Y (n_749));
  NAND2XL g13165(.A (n_727), .B (n_742), .Y (n_751));
  OR2X1 g13167(.A (n_568), .B (n_748), .Y (n_791));
  OAI21X1 g13168(.A0 (n_729), .A1 (n_745), .B0 (n_472), .Y (n_780));
  NAND2X1 g13170(.A (fsm_check_req), .B (n_743), .Y (n_773));
  NOR2BX1 g13172(.AN (n_747), .B (n_744), .Y (n_768));
  NAND3X1 g13173(.A (fsm_check_req), .B (fsm_charge_req), .C (n_743),
       .Y (n_748));
  CLKINVX1 g13174(.A (n_746), .Y (n_1939_BAR));
  ADDHX1 g13175(.A (n_719), .B (n_471), .CO (n_745), .S (n_746));
  NOR2BX1 g13176(.AN (n_739), .B (n_717), .Y (n_744));
  NAND2BX1 g13177(.AN (n_739), .B (n_717), .Y (n_747));
  AO21X1 g13178(.A0 (n_728), .A1 (n_472), .B0 (n_742), .Y (n_1948_BAR));
  OR2X1 g13179(.A (n_734), .B (n_739), .Y (n_743));
  NOR2XL g13180(.A (n_728), .B (n_472), .Y (n_742));
  OR4X1 g13184(.A (n_726), .B (n_728), .C (n_730), .D (n_472), .Y
       (n_739));
  NAND2X1 g13187(.A (n_732), .B (n_471), .Y (n_472));
  AO21X1 g13188(.A0 (n_733), .A1 (n_736), .B0 (n_471), .Y (n_786));
  NOR2X1 g13192(.A (n_733), .B (n_736), .Y (n_471));
  OAI21X1 g13193(.A0 (n_723), .A1 (n_735), .B0 (n_736), .Y
       (n_1949_BAR));
  OAI21X1 g13194(.A0 (n_720), .A1 (n_731), .B0 (n_723), .Y (n_736));
  CLKXOR2X1 g13195(.A (n_720), .B (n_731), .Y (n_784));
  OR2XL g13196(.A (n_720), .B (n_731), .Y (n_735));
  AO21X1 g13197(.A0 (n_712), .A1 (n_809), .B0 (n_731), .Y (n_800));
  NAND4BXL g13198(.AN (n_721), .B (n_718), .C (n_716), .D (n_717), .Y
       (n_734));
  AND2XL g13199(.A (n_719), .B (n_729), .Y (n_732));
  NAND2XL g13200(.A (n_725), .B (n_692), .Y (n_733));
  NAND2BXL g13201(.AN (n_722), .B (n_724), .Y (n_730));
  NOR2X2 g13202(.A (n_712), .B (n_809), .Y (n_731));
  CLKINVX1 g13203(.A (n_726), .Y (n_727));
  AOI211X1 g13204(.A0 (\balance_db[5] [5]), .A1 (n_808), .B0 (n_572),
       .C0 (n_710), .Y (n_725));
  NOR3X1 g13205(.A (n_706), .B (n_680), .C (n_705), .Y (n_729));
  NAND4XL g13206(.A (n_594), .B (n_659), .C (n_673), .D (n_810), .Y
       (n_728));
  NAND4XL g13207(.A (n_639), .B (n_641), .C (n_654), .D (n_714), .Y
       (n_726));
  NOR3BX1 g13209(.AN (n_658), .B (n_697), .C (n_693), .Y (n_724));
  NOR2X1 g13210(.A (n_704), .B (n_709), .Y (n_723));
  NAND3X1 g13211(.A (n_664), .B (n_703), .C (n_689), .Y (n_722));
  NAND4XL g13212(.A (n_632), .B (n_630), .C (n_666), .D (n_708), .Y
       (n_721));
  NOR3X1 g13213(.A (n_655), .B (n_669), .C (n_707), .Y (n_720));
  NOR2XL g13214(.A (n_690), .B (n_715), .Y (n_719));
  NAND4XL g13215(.A (n_668), .B (n_585), .C (n_642), .D (n_644), .Y
       (n_715));
  NOR2XL g13216(.A (n_700), .B (n_678), .Y (n_714));
  AND4X1 g13218(.A (n_596), .B (n_598), .C (n_661), .D (n_702), .Y
       (n_718));
  NOR2XL g13219(.A (n_694), .B (n_688), .Y (n_717));
  NOR2XL g13220(.A (n_691), .B (n_695), .Y (n_716));
  NOR2X2 g13221(.A (n_677), .B (n_686), .Y (n_711));
  NAND2X1 g13222(.A (n_699), .B (n_814), .Y (n_710));
  NAND2XL g13223(.A (n_597), .B (n_696), .Y (n_709));
  NOR2XL g13224(.A (n_684), .B (n_701), .Y (n_708));
  OAI22X1 g13225(.A0 (n_488), .A1 (n_656), .B0 (n_495), .B1 (n_646), .Y
       (n_707));
  NAND2XL g13226(.A (n_685), .B (n_687), .Y (n_712));
  OAI211X1 g13227(.A0 (n_495), .A1 (n_554), .B0 (n_574), .C0 (n_631),
       .Y (n_706));
  NAND2XL g13228(.A (n_667), .B (n_679), .Y (n_705));
  OAI22X1 g13229(.A0 (n_497), .A1 (n_650), .B0 (n_495), .B1 (n_651), .Y
       (n_704));
  AOI221X1 g13230(.A0 (\balance_db[8] [10]), .A1 (n_541), .B0
       (\balance_db[6] [10]), .B1 (n_533), .C0 (n_660), .Y (n_703));
  AOI221X1 g13231(.A0 (\balance_db[6] [15]), .A1 (n_533), .B0
       (\balance_db[7] [15]), .B1 (n_543), .C0 (n_674), .Y (n_702));
  NAND2XL g13232(.A (n_626), .B (n_811), .Y (n_701));
  NAND2XL g13233(.A (n_663), .B (n_624), .Y (n_700));
  AOI21X1 g13234(.A0 (\balance_db[13] [5]), .A1 (n_535), .B0 (n_683),
       .Y (n_699));
  NAND2XL g13235(.A (n_662), .B (n_604), .Y (n_698));
  OAI211X1 g13236(.A0 (n_495), .A1 (n_553), .B0 (n_576), .C0 (n_592),
       .Y (n_697));
  NOR2XL g13237(.A (n_682), .B (n_681), .Y (n_696));
  NAND4XL g13238(.A (n_605), .B (n_603), .C (n_602), .D (n_606), .Y
       (n_695));
  NAND4XL g13239(.A (n_616), .B (n_618), .C (n_619), .D (n_653), .Y
       (n_694));
  NAND4XL g13240(.A (n_590), .B (n_643), .C (n_637), .D (n_601), .Y
       (n_693));
  NOR2XL g13241(.A (n_676), .B (n_675), .Y (n_692));
  NAND4XL g13242(.A (n_610), .B (n_608), .C (n_612), .D (n_614), .Y
       (n_691));
  NAND3X1 g13243(.A (n_587), .B (n_589), .C (n_657), .Y (n_690));
  NOR2XL g13244(.A (n_672), .B (n_671), .Y (n_689));
  NAND4XL g13245(.A (n_649), .B (n_623), .C (n_620), .D (n_621), .Y
       (n_688));
  AOI22X1 g13246(.A0 (n_498), .A1 (n_583), .B0 (n_489), .B1 (n_584), .Y
       (n_687));
  OAI22X1 g13247(.A0 (n_497), .A1 (n_581), .B0 (n_488), .B1 (n_582), .Y
       (n_686));
  AOI22X1 g13248(.A0 (n_491), .A1 (n_579), .B0 (n_496), .B1 (n_580), .Y
       (n_685));
  NAND2XL g13249(.A (n_628), .B (n_627), .Y (n_684));
  NOR2XL g13250(.A (n_497), .B (n_648), .Y (n_683));
  AOI21X1 g13251(.A0 (n_528), .A1 (n_549), .B0 (n_490), .Y (n_682));
  NOR2XL g13252(.A (n_488), .B (n_647), .Y (n_681));
  NAND2XL g13253(.A (n_634), .B (n_635), .Y (n_680));
  NOR2XL g13254(.A (n_812), .B (n_813), .Y (n_679));
  NAND2XL g13255(.A (n_633), .B (n_629), .Y (n_678));
  NOR3X1 g13256(.A (n_490), .B (n_562), .C (n_557), .Y (n_677));
  NAND2XL g13257(.A (n_615), .B (n_613), .Y (n_676));
  NAND2XL g13258(.A (n_607), .B (n_609), .Y (n_675));
  NAND2XL g13259(.A (n_600), .B (n_599), .Y (n_674));
  AOI221X1 g13260(.A0 (\balance_db[8] [8]), .A1 (n_541), .B0
       (\balance_db[9] [8]), .B1 (n_542), .C0 (n_815), .Y (n_673));
  NAND2XL g13261(.A (n_593), .B (n_591), .Y (n_672));
  NAND2XL g13262(.A (n_586), .B (n_588), .Y (n_671));
  AOI211X1 g13264(.A0 (id_to_check[0]), .A1 (n_506), .B0 (n_526), .C0
       (n_564), .Y (n_669));
  AOI22XL g13265(.A0 (n_816), .A1 (n_496), .B0 (n_543), .B1
       (\balance_db[7] [6]), .Y (n_668));
  AOI21XL g13266(.A0 (\balance_db[11] [7]), .A1 (n_534), .B0 (n_640),
       .Y (n_667));
  AOI222XL g13267(.A0 (\balance_db[1] [13]), .A1 (n_540), .B0
       (\balance_db[0] [13]), .B1 (n_539), .C0 (n_542), .C1
       (\balance_db[9] [13]), .Y (n_666));
  AOI222XL g13269(.A0 (\balance_db[2] [10]), .A1 (n_538), .B0
       (\balance_db[12] [10]), .B1 (n_517), .C0 (n_534), .C1
       (\balance_db[11] [10]), .Y (n_664));
  AOI22X1 g13270(.A0 (n_496), .A1 (n_551), .B0 (\balance_db[14] [9]),
       .B1 (n_545), .Y (n_663));
  AOI21X1 g13271(.A0 (\balance_db[7] [8]), .A1 (n_543), .B0 (n_617), .Y
       (n_662));
  AOI222XL g13272(.A0 (\balance_db[0] [15]), .A1 (n_539), .B0
       (\balance_db[4] [15]), .B1 (n_537), .C0 (n_517), .C1
       (\balance_db[12] [15]), .Y (n_661));
  OAI21X1 g13273(.A0 (n_488), .A1 (n_548), .B0 (n_570), .Y (n_660));
  AOI222XL g13274(.A0 (\balance_db[0] [8]), .A1 (n_539), .B0
       (\balance_db[1] [8]), .B1 (n_540), .C0 (n_519), .C1
       (\balance_db[10] [8]), .Y (n_659));
  AOI222XL g13275(.A0 (\balance_db[0] [11]), .A1 (n_539), .B0
       (\balance_db[8] [11]), .B1 (n_541), .C0 (n_540), .C1
       (\balance_db[1] [11]), .Y (n_658));
  AOI22X1 g13276(.A0 (n_498), .A1 (n_546), .B0 (\balance_db[13] [6]),
       .B1 (n_535), .Y (n_657));
  AOI21X1 g13277(.A0 (\balance_db[10] [3]), .A1 (n_481), .B0 (n_645),
       .Y (n_656));
  AOI211X1 g13278(.A0 (id_to_check[0]), .A1 (n_509), .B0 (n_529), .C0
       (n_578), .Y (n_655));
  AOI222XL g13279(.A0 (\balance_db[0] [9]), .A1 (n_539), .B0
       (\balance_db[5] [9]), .B1 (n_808), .C0 (n_519), .C1
       (\balance_db[10] [9]), .Y (n_654));
  AOI22X1 g13280(.A0 (\balance_db[4] [12]), .A1 (n_537), .B0
       (\balance_db[5] [12]), .B1 (n_808), .Y (n_653));
  NAND2XL g13281(.A (n_558), .B (n_560), .Y (n_652));
  AND2X1 g13282(.A (n_550), .B (n_547), .Y (n_651));
  NOR2BX1 g13283(.AN (n_555), .B (n_556), .Y (n_650));
  AOI32XL g13284(.A0 (n_481), .A1 (\balance_db[14] [12]), .A2 (n_496),
       .B0 (n_544), .B1 (\balance_db[15] [12]), .Y (n_649));
  AOI21X1 g13285(.A0 (\balance_db[9] [5]), .A1 (n_482), .B0 (n_552), .Y
       (n_648));
  AOI221X1 g13286(.A0 (\balance_db[3] [4]), .A1 (n_487), .B0
       (\balance_db[11] [4]), .B1 (n_482), .C0 (n_527), .Y (n_647));
  AOI221X1 g13287(.A0 (\balance_db[14] [3]), .A1 (n_481), .B0
       (\balance_db[15] [3]), .B1 (n_482), .C0 (n_566), .Y (n_646));
  OAI22X1 g13288(.A0 (id_to_check[3]), .A1 (n_500), .B0 (n_478), .B1
       (n_483), .Y (n_645));
  AOI22X1 g13289(.A0 (\balance_db[2] [6]), .A1 (n_538), .B0
       (\balance_db[5] [6]), .B1 (n_808), .Y (n_644));
  AOI22X1 g13290(.A0 (\balance_db[2] [11]), .A1 (n_538), .B0
       (\balance_db[12] [11]), .B1 (n_517), .Y (n_643));
  AOI22X1 g13291(.A0 (\balance_db[4] [6]), .A1 (n_537), .B0
       (\balance_db[6] [6]), .B1 (n_533), .Y (n_642));
  AOI22X1 g13292(.A0 (\balance_db[9] [9]), .A1 (n_542), .B0
       (\balance_db[13] [9]), .B1 (n_535), .Y (n_641));
  OAI22XL g13293(.A0 (n_536), .A1 (n_474), .B0 (n_520), .B1 (n_473), .Y
       (n_640));
  AOI22X1 g13294(.A0 (\balance_db[1] [9]), .A1 (n_540), .B0
       (\balance_db[11] [9]), .B1 (n_534), .Y (n_639));
  AOI22X1 g13296(.A0 (\balance_db[4] [11]), .A1 (n_537), .B0
       (\balance_db[5] [11]), .B1 (n_808), .Y (n_637));
  AOI22X1 g13298(.A0 (\balance_db[8] [7]), .A1 (n_541), .B0
       (\balance_db[9] [7]), .B1 (n_542), .Y (n_635));
  AOI22X1 g13299(.A0 (\balance_db[0] [7]), .A1 (n_539), .B0
       (\balance_db[2] [7]), .B1 (n_538), .Y (n_634));
  AOI22X1 g13300(.A0 (\balance_db[2] [9]), .A1 (n_538), .B0
       (\balance_db[12] [9]), .B1 (n_517), .Y (n_633));
  AOI22XL g13301(.A0 (n_545), .A1 (\balance_db[14] [13]), .B0 (n_544),
       .B1 (\balance_db[15] [13]), .Y (n_632));
  AOI21X1 g13302(.A0 (\balance_db[1] [7]), .A1 (n_540), .B0 (n_575), .Y
       (n_631));
  AOI22X1 g13303(.A0 (\balance_db[6] [13]), .A1 (n_533), .B0
       (\balance_db[7] [13]), .B1 (n_543), .Y (n_630));
  AOI22X1 g13304(.A0 (\balance_db[4] [9]), .A1 (n_537), .B0
       (\balance_db[6] [9]), .B1 (n_533), .Y (n_629));
  AOI22X1 g13305(.A0 (\balance_db[12] [13]), .A1 (n_517), .B0
       (\balance_db[10] [13]), .B1 (n_519), .Y (n_628));
  AOI22X1 g13306(.A0 (\balance_db[2] [13]), .A1 (n_538), .B0
       (\balance_db[5] [13]), .B1 (n_808), .Y (n_627));
  AOI22X1 g13307(.A0 (\balance_db[4] [13]), .A1 (n_537), .B0
       (\balance_db[13] [13]), .B1 (n_535), .Y (n_626));
  AOI22X1 g13309(.A0 (\balance_db[8] [9]), .A1 (n_541), .B0
       (\balance_db[3] [9]), .B1 (n_521), .Y (n_624));
  AOI22XL g13310(.A0 (n_540), .A1 (\balance_db[1] [12]), .B0 (n_535),
       .B1 (\balance_db[13] [12]), .Y (n_623));
  AOI22XL g13312(.A0 (n_517), .A1 (\balance_db[12] [12]), .B0 (n_534),
       .B1 (\balance_db[11] [12]), .Y (n_621));
  AOI22X1 g13313(.A0 (\balance_db[6] [12]), .A1 (n_533), .B0
       (\balance_db[7] [12]), .B1 (n_543), .Y (n_620));
  AOI22X1 g13314(.A0 (\balance_db[8] [12]), .A1 (n_541), .B0
       (\balance_db[9] [12]), .B1 (n_542), .Y (n_619));
  AOI22X1 g13315(.A0 (\balance_db[2] [12]), .A1 (n_538), .B0
       (\balance_db[10] [12]), .B1 (n_519), .Y (n_618));
  NOR2XL g13316(.A (n_495), .B (n_561), .Y (n_617));
  AOI22X1 g13317(.A0 (\balance_db[0] [12]), .A1 (n_539), .B0
       (\balance_db[3] [12]), .B1 (n_521), .Y (n_616));
  AOI22XL g13318(.A0 (n_545), .A1 (\balance_db[14] [5]), .B0 (n_544),
       .B1 (\balance_db[15] [5]), .Y (n_615));
  AOI22X1 g13319(.A0 (\balance_db[5] [14]), .A1 (n_808), .B0
       (\balance_db[13] [14]), .B1 (n_535), .Y (n_614));
  AOI22X1 g13320(.A0 (\balance_db[4] [5]), .A1 (n_537), .B0
       (\balance_db[3] [5]), .B1 (n_521), .Y (n_613));
  AOI22X1 g13321(.A0 (\balance_db[6] [14]), .A1 (n_533), .B0
       (\balance_db[7] [14]), .B1 (n_543), .Y (n_612));
  AOI22XL g13323(.A0 (n_545), .A1 (\balance_db[14] [14]), .B0 (n_544),
       .B1 (\balance_db[15] [14]), .Y (n_610));
  AOI22X1 g13324(.A0 (\balance_db[6] [5]), .A1 (n_533), .B0
       (\balance_db[7] [5]), .B1 (n_543), .Y (n_609));
  AOI22X1 g13325(.A0 (\balance_db[0] [14]), .A1 (n_539), .B0
       (\balance_db[1] [14]), .B1 (n_540), .Y (n_608));
  AOI22X1 g13326(.A0 (\balance_db[2] [5]), .A1 (n_538), .B0
       (\balance_db[12] [5]), .B1 (n_517), .Y (n_607));
  AOI22XL g13327(.A0 (n_519), .A1 (\balance_db[10] [14]), .B0 (n_534),
       .B1 (\balance_db[11] [14]), .Y (n_606));
  AOI22X1 g13328(.A0 (DFT_sdo), .A1 (n_538), .B0 (\balance_db[12]
       [14]), .B1 (n_517), .Y (n_605));
  AOI22X1 g13329(.A0 (\balance_db[12] [8]), .A1 (n_517), .B0
       (\balance_db[13] [8]), .B1 (n_535), .Y (n_604));
  AOI22X1 g13330(.A0 (\balance_db[8] [14]), .A1 (n_541), .B0
       (\balance_db[9] [14]), .B1 (n_542), .Y (n_603));
  AOI22X1 g13331(.A0 (\balance_db[4] [14]), .A1 (n_537), .B0
       (\balance_db[3] [14]), .B1 (n_521), .Y (n_602));
  AOI22X1 g13332(.A0 (\balance_db[3] [11]), .A1 (n_521), .B0
       (\balance_db[13] [11]), .B1 (n_535), .Y (n_601));
  AOI22X1 g13333(.A0 (\balance_db[14] [15]), .A1 (n_545), .B0
       (\balance_db[15] [15]), .B1 (n_544), .Y (n_600));
  AOI22XL g13334(.A0 (n_519), .A1 (\balance_db[10] [15]), .B0 (n_534),
       .B1 (\balance_db[11] [15]), .Y (n_599));
  AOI22XL g13335(.A0 (n_808), .A1 (\balance_db[5] [15]), .B0 (n_535),
       .B1 (\balance_db[13] [15]), .Y (n_598));
  AOI22X1 g13336(.A0 (\balance_db[12] [4]), .A1 (n_517), .B0
       (\balance_db[10] [4]), .B1 (n_519), .Y (n_597));
  AOI22XL g13337(.A0 (n_541), .A1 (\balance_db[8] [15]), .B0 (n_542),
       .B1 (\balance_db[9] [15]), .Y (n_596));
  AOI22X1 g13339(.A0 (\balance_db[2] [8]), .A1 (n_538), .B0
       (\balance_db[11] [8]), .B1 (n_534), .Y (n_594));
  AOI22XL g13340(.A0 (n_545), .A1 (\balance_db[14] [10]), .B0 (n_544),
       .B1 (\balance_db[15] [10]), .Y (n_593));
  AOI22X1 g13341(.A0 (\balance_db[6] [11]), .A1 (n_533), .B0
       (\balance_db[9] [11]), .B1 (n_542), .Y (n_592));
  AOI22X1 g13342(.A0 (\balance_db[9] [10]), .A1 (n_542), .B0
       (\balance_db[13] [10]), .B1 (n_535), .Y (n_591));
  AOI22X1 g13343(.A0 (\balance_db[10] [11]), .A1 (n_519), .B0
       (\balance_db[11] [11]), .B1 (n_534), .Y (n_590));
  AOI22X1 g13344(.A0 (\balance_db[12] [6]), .A1 (n_517), .B0
       (\balance_db[3] [6]), .B1 (n_521), .Y (n_589));
  AOI22X1 g13345(.A0 (\balance_db[4] [10]), .A1 (n_537), .B0
       (\balance_db[5] [10]), .B1 (n_808), .Y (n_588));
  AOI22X1 g13346(.A0 (\balance_db[0] [6]), .A1 (n_539), .B0
       (\balance_db[1] [6]), .B1 (n_540), .Y (n_587));
  AOI22X1 g13347(.A0 (\balance_db[0] [10]), .A1 (n_539), .B0
       (\balance_db[1] [10]), .B1 (n_540), .Y (n_586));
  AOI22X1 g13348(.A0 (\balance_db[10] [6]), .A1 (n_519), .B0
       (\balance_db[11] [6]), .B1 (n_534), .Y (n_585));
  MXI2XL g13349(.A (n_512), .B (n_514), .S0 (id_to_check[0]), .Y
       (n_584));
  MXI2XL g13350(.A (n_510), .B (n_511), .S0 (id_to_check[0]), .Y
       (n_583));
  AOI21X1 g13351(.A0 (id_to_check[0]), .A1 (n_817), .B0 (n_567), .Y
       (n_582));
  MXI2XL g13352(.A (n_818), .B (n_819), .S0 (id_to_check[0]), .Y
       (n_581));
  MXI2XL g13353(.A (n_503), .B (n_504), .S0 (id_to_check[0]), .Y
       (n_580));
  MXI2XL g13354(.A (n_501), .B (n_502), .S0 (id_to_check[0]), .Y
       (n_579));
  OAI21X1 g13355(.A0 (\balance_db[4] [3]), .A1 (n_484), .B0 (n_491), .Y
       (n_578));
  NAND2XL g13357(.A (\balance_db[15] [11]), .B (n_544), .Y (n_576));
  NOR2BXL g13358(.AN (\balance_db[12] [7]), .B (n_516), .Y (n_575));
  NAND2XL g13359(.A (\balance_db[13] [7]), .B (n_535), .Y (n_574));
  AND2X1 g13361(.A (\balance_db[11] [5]), .B (n_534), .Y (n_572));
  NAND2XL g13363(.A (\balance_db[7] [10]), .B (n_543), .Y (n_570));
  NAND2XL g13365(.A (n_767), .B (n_469), .Y (n_568));
  NOR2XL g13366(.A (id_to_check[0]), .B (n_508), .Y (n_567));
  NOR2XL g13367(.A (id_to_check[3]), .B (n_515), .Y (n_566));
  NOR2BX1 g13368(.AN (n_469), .B (id_to_check[2]), .Y (n_565));
  OAI21X1 g13369(.A0 (\balance_db[0] [3]), .A1 (n_484), .B0 (n_498), .Y
       (n_564));
  AOI221X1 g13371(.A0 (\balance_db[5] [1]), .A1 (n_475), .B0
       (\balance_db[13] [1]), .B1 (id_to_check[3]), .C0 (n_476), .Y
       (n_562));
  AOI22XL g13372(.A0 (n_481), .A1 (\balance_db[14] [8]), .B0 (n_482),
       .B1 (\balance_db[15] [8]), .Y (n_561));
  AOI22X1 g13373(.A0 (\balance_db[14] [1]), .A1 (n_481), .B0
       (\balance_db[7] [1]), .B1 (n_487), .Y (n_560));
  AOI22X1 g13375(.A0 (\balance_db[6] [1]), .A1 (n_485), .B0
       (\balance_db[15] [1]), .B1 (n_482), .Y (n_558));
  OAI21X1 g13376(.A0 (\balance_db[4] [1]), .A1 (n_484), .B0 (n_531), .Y
       (n_557));
  AO22XL g13377(.A0 (\balance_db[1] [4]), .A1 (n_487), .B0
       (\balance_db[9] [4]), .B1 (n_482), .Y (n_556));
  AOI22XL g13378(.A0 (n_485), .A1 (\balance_db[0] [4]), .B0 (n_481),
       .B1 (\balance_db[8] [4]), .Y (n_555));
  AOI22XL g13379(.A0 (n_481), .A1 (\balance_db[14] [7]), .B0 (n_482),
       .B1 (\balance_db[15] [7]), .Y (n_554));
  AOI22X1 g13380(.A0 (\balance_db[14] [11]), .A1 (n_481), .B0
       (\balance_db[7] [11]), .B1 (n_487), .Y (n_553));
  OAI21X1 g13381(.A0 (n_479), .A1 (n_480), .B0 (n_530), .Y (n_552));
  AO22XL g13382(.A0 (\balance_db[7] [9]), .A1 (n_487), .B0
       (\balance_db[15] [9]), .B1 (n_482), .Y (n_551));
  AOI22XL g13383(.A0 (n_485), .A1 (\balance_db[6] [4]), .B0 (n_481),
       .B1 (\balance_db[14] [4]), .Y (n_550));
  AOI22X1 g13384(.A0 (\balance_db[5] [4]), .A1 (n_487), .B0
       (\balance_db[13] [4]), .B1 (n_482), .Y (n_549));
  AOI22X1 g13385(.A0 (\balance_db[10] [10]), .A1 (n_481), .B0
       (\balance_db[3] [10]), .B1 (n_487), .Y (n_548));
  AOI22XL g13386(.A0 (n_487), .A1 (\balance_db[7] [4]), .B0 (n_482),
       .B1 (\balance_db[15] [4]), .Y (n_547));
  AO22XL g13387(.A0 (\balance_db[8] [6]), .A1 (n_481), .B0
       (\balance_db[9] [6]), .B1 (n_482), .Y (n_546));
  INVX2 g13388(.A (n_525), .Y (n_543));
  CLKINVX1 g13389(.A (n_524), .Y (n_542));
  CLKINVX1 g13390(.A (n_536), .Y (n_537));
  CLKINVX1 g13391(.A (n_523), .Y (n_535));
  CLKINVX1 g13392(.A (n_522), .Y (n_534));
  NAND2BX1 g13394(.AN (\balance_db[12] [1]), .B (n_481), .Y (n_531));
  NAND2XL g13395(.A (\balance_db[0] [5]), .B (n_485), .Y (n_530));
  NOR2XL g13396(.A (\balance_db[12] [3]), .B (n_480), .Y (n_529));
  NAND2XL g13397(.A (\balance_db[4] [4]), .B (n_485), .Y (n_528));
  NOR2BXL g13398(.AN (\balance_db[2] [4]), .B (n_484), .Y (n_527));
  NOR2XL g13399(.A (\balance_db[8] [3]), .B (n_480), .Y (n_526));
  NOR2XL g13401(.A (n_495), .B (n_480), .Y (n_545));
  NOR2XL g13402(.A (n_495), .B (n_483), .Y (n_544));
  NAND2XL g13403(.A (n_496), .B (n_487), .Y (n_525));
  NAND2XL g13404(.A (n_498), .B (n_482), .Y (n_524));
  NOR2X1 g13405(.A (n_480), .B (n_497), .Y (n_541));
  AND2X1 g13406(.A (n_498), .B (n_487), .Y (n_540));
  AND2X1 g13407(.A (n_498), .B (n_485), .Y (n_539));
  AND2X1 g13408(.A (n_489), .B (n_485), .Y (n_538));
  NAND2XL g13409(.A (n_491), .B (n_485), .Y (n_536));
  NAND2XL g13410(.A (n_491), .B (n_482), .Y (n_523));
  NAND2XL g13411(.A (n_489), .B (n_482), .Y (n_522));
  AND2X1 g13412(.A (n_496), .B (n_485), .Y (n_533));
  CLKINVX1 g13413(.A (n_520), .Y (n_521));
  CLKINVX1 g13414(.A (n_516), .Y (n_517));
  AOI22X1 g13415(.A0 (\balance_db[6] [3]), .A1 (n_476), .B0
       (\balance_db[7] [3]), .B1 (id_to_check[0]), .Y (n_515));
  AOI22XL g13416(.A0 (n_475), .A1 (\balance_db[3] [2]), .B0
       (id_to_check[3]), .B1 (\balance_db[11] [2]), .Y (n_514));
  AOI22XL g13418(.A0 (n_475), .A1 (\balance_db[2] [2]), .B0
       (id_to_check[3]), .B1 (\balance_db[10] [2]), .Y (n_512));
  AOI22XL g13419(.A0 (n_475), .A1 (\balance_db[1] [2]), .B0
       (id_to_check[3]), .B1 (\balance_db[9] [2]), .Y (n_511));
  AOI22X1 g13420(.A0 (\balance_db[0] [2]), .A1 (n_475), .B0
       (\balance_db[8] [2]), .B1 (id_to_check[3]), .Y (n_510));
  OAI22X1 g13421(.A0 (\balance_db[5] [3]), .A1 (id_to_check[3]), .B0
       (\balance_db[13] [3]), .B1 (n_475), .Y (n_509));
  AOI22X1 g13422(.A0 (\balance_db[2] [1]), .A1 (n_475), .B0
       (\balance_db[10] [1]), .B1 (id_to_check[3]), .Y (n_508));
  OAI22X1 g13424(.A0 (\balance_db[1] [3]), .A1 (id_to_check[3]), .B0
       (\balance_db[9] [3]), .B1 (n_475), .Y (n_506));
  AOI22X1 g13426(.A0 (\balance_db[7] [2]), .A1 (n_475), .B0
       (\balance_db[15] [2]), .B1 (id_to_check[3]), .Y (n_504));
  AOI22X1 g13427(.A0 (\balance_db[6] [2]), .A1 (n_475), .B0
       (\balance_db[14] [2]), .B1 (id_to_check[3]), .Y (n_503));
  AOI22X1 g13428(.A0 (\balance_db[5] [2]), .A1 (n_475), .B0
       (\balance_db[13] [2]), .B1 (id_to_check[3]), .Y (n_502));
  AOI22X1 g13429(.A0 (\balance_db[4] [2]), .A1 (n_475), .B0
       (\balance_db[12] [2]), .B1 (id_to_check[3]), .Y (n_501));
  AOI22X1 g13430(.A0 (\balance_db[2] [3]), .A1 (n_476), .B0
       (\balance_db[3] [3]), .B1 (id_to_check[0]), .Y (n_500));
  NAND2XL g13431(.A (n_489), .B (n_487), .Y (n_520));
  AND2X1 g13432(.A (n_489), .B (n_481), .Y (n_519));
  NAND2XL g13434(.A (n_491), .B (n_481), .Y (n_516));
  CLKINVX1 g13435(.A (n_769), .Y (n_499));
  CLKINVX1 g13437(.A (n_498), .Y (n_497));
  CLKINVX1 g13438(.A (n_496), .Y (n_495));
  NAND2XL g13442(.A (n_766), .B (id_to_check[0]), .Y (n_769));
  NOR2XL g13443(.A (reset), .B (id_to_check[0]), .Y (n_770));
  NOR2X1 g13444(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_498));
  AND2X1 g13445(.A (id_to_check[1]), .B (id_to_check[2]), .Y (n_496));
  CLKINVX1 g13446(.A (n_491), .Y (n_490));
  CLKINVX1 g13447(.A (n_489), .Y (n_488));
  CLKINVX2 g13449(.A (n_485), .Y (n_484));
  CLKINVX2 g13450(.A (n_483), .Y (n_482));
  CLKINVX1 g13451(.A (n_481), .Y (n_480));
  NOR2XL g13452(.A (id_to_check[2]), .B (id_to_check[3]), .Y (n_767));
  AND2X1 g13453(.A (id_to_check[2]), .B (n_477), .Y (n_491));
  NOR2XL g13454(.A (id_to_check[2]), .B (n_477), .Y (n_489));
  CLKAND2X2 g13455(.A (id_to_check[0]), .B (n_475), .Y (n_487));
  CLKAND2X3 g13456(.A (n_476), .B (n_475), .Y (n_485));
  NAND2X1 g13457(.A (id_to_check[0]), .B (id_to_check[3]), .Y (n_483));
  AND2X6 g13458(.A (n_476), .B (id_to_check[3]), .Y (n_481));
  INVX1 g13459(.A (\balance_db[8] [5]), .Y (n_479));
  INVX1 g13460(.A (\balance_db[11] [3]), .Y (n_478));
  CLKINVX1 g13461(.A (id_to_check[1]), .Y (n_477));
  CLKINVX2 g13462(.A (id_to_check[0]), .Y (n_476));
  INVX8 g13463(.A (id_to_check[3]), .Y (n_475));
  INVXL g13464(.A (\balance_db[4] [7]), .Y (n_474));
  INVX1 g13465(.A (\balance_db[3] [7]), .Y (n_473));
  NAND2BX1 g2(.AN (n_748), .B (id_to_check[3]), .Y (n_470));
  NOR2BX1 g13468(.AN (n_770), .B (id_to_check[1]), .Y (n_469));
  NOR3BX1 g13469(.AN (id_to_check[2]), .B (id_to_check[3]), .C (n_748),
       .Y (n_468));
  SDFFQX1 \balance_db_reg[1][1] (.CK (clk), .D (n_464), .SI (DFT_sdi),
       .SE (DFT_sen), .Q (\balance_db[1] [1]));
  SDFFQX1 \balance_db_reg[1][2] (.CK (clk), .D (n_807), .SI
       (\balance_db[1] [1]), .SE (DFT_sen), .Q (\balance_db[1] [2]));
  SDFFQX1 \balance_db_reg[1][3] (.CK (clk), .D (n_442), .SI
       (\balance_db[1] [2]), .SE (DFT_sen), .Q (\balance_db[1] [3]));
  SDFFQX1 \balance_db_reg[1][4] (.CK (clk), .D (n_458), .SI
       (\balance_db[1] [3]), .SE (DFT_sen), .Q (\balance_db[1] [4]));
  SDFFQX1 \balance_db_reg[1][5] (.CK (clk), .D (n_465), .SI
       (\balance_db[1] [4]), .SE (DFT_sen), .Q (\balance_db[1] [5]));
  SDFFQX1 \balance_db_reg[1][6] (.CK (clk), .D (n_427), .SI
       (\balance_db[1] [5]), .SE (DFT_sen), .Q (\balance_db[1] [6]));
  SDFFQX1 \balance_db_reg[1][7] (.CK (clk), .D (n_437), .SI
       (\balance_db[1] [6]), .SE (DFT_sen), .Q (\balance_db[1] [7]));
  SDFFQX1 \balance_db_reg[1][8] (.CK (clk), .D (n_454), .SI
       (\balance_db[1] [7]), .SE (DFT_sen), .Q (\balance_db[1] [8]));
  SDFFQX1 \balance_db_reg[1][9] (.CK (clk), .D (n_434), .SI
       (\balance_db[1] [8]), .SE (DFT_sen), .Q (\balance_db[1] [9]));
  SDFFQX1 \balance_db_reg[1][10] (.CK (clk), .D (n_451), .SI
       (\balance_db[1] [9]), .SE (DFT_sen), .Q (\balance_db[1] [10]));
  SDFFQX1 \balance_db_reg[1][11] (.CK (clk), .D (n_431), .SI
       (\balance_db[1] [10]), .SE (DFT_sen), .Q (\balance_db[1] [11]));
  SDFFQX1 \balance_db_reg[1][12] (.CK (clk), .D (n_449), .SI
       (\balance_db[1] [11]), .SE (DFT_sen), .Q (\balance_db[1] [12]));
  SDFFQX1 \balance_db_reg[1][13] (.CK (clk), .D (n_428), .SI
       (\balance_db[1] [12]), .SE (DFT_sen), .Q (\balance_db[1] [13]));
  SDFFQX1 \balance_db_reg[1][14] (.CK (clk), .D (n_426), .SI
       (\balance_db[1] [13]), .SE (DFT_sen), .Q (\balance_db[1] [14]));
  SDFFQX1 \balance_db_reg[2][1] (.CK (clk), .D (n_463), .SI
       (\balance_db[1] [14]), .SE (DFT_sen), .Q (\balance_db[2] [1]));
  SDFFQX1 \balance_db_reg[2][2] (.CK (clk), .D (n_821), .SI
       (\balance_db[2] [1]), .SE (DFT_sen), .Q (\balance_db[2] [2]));
  SDFFQX1 \balance_db_reg[2][3] (.CK (clk), .D (n_445), .SI
       (\balance_db[2] [2]), .SE (DFT_sen), .Q (\balance_db[2] [3]));
  SDFFQX1 \balance_db_reg[2][4] (.CK (clk), .D (n_461), .SI
       (\balance_db[2] [3]), .SE (DFT_sen), .Q (\balance_db[2] [4]));
  SDFFQX1 \balance_db_reg[2][5] (.CK (clk), .D (n_444), .SI
       (\balance_db[2] [4]), .SE (DFT_sen), .Q (\balance_db[2] [5]));
  SDFFQX1 \balance_db_reg[2][6] (.CK (clk), .D (n_460), .SI
       (\balance_db[2] [5]), .SE (DFT_sen), .Q (\balance_db[2] [6]));
  SDFFQX1 \balance_db_reg[2][7] (.CK (clk), .D (n_443), .SI
       (\balance_db[2] [6]), .SE (DFT_sen), .Q (\balance_db[2] [7]));
  SDFFQX1 \balance_db_reg[2][8] (.CK (clk), .D (n_459), .SI
       (\balance_db[2] [7]), .SE (DFT_sen), .Q (\balance_db[2] [8]));
  SDFFQX1 \balance_db_reg[2][9] (.CK (clk), .D (n_441), .SI
       (\balance_db[2] [8]), .SE (DFT_sen), .Q (\balance_db[2] [9]));
  SDFFQX1 \balance_db_reg[2][10] (.CK (clk), .D (n_457), .SI
       (\balance_db[2] [9]), .SE (DFT_sen), .Q (\balance_db[2] [10]));
  SDFFQX1 \balance_db_reg[2][11] (.CK (clk), .D (n_440), .SI
       (\balance_db[2] [10]), .SE (DFT_sen), .Q (\balance_db[2] [11]));
  SDFFQX1 \balance_db_reg[2][12] (.CK (clk), .D (n_456), .SI
       (\balance_db[2] [11]), .SE (DFT_sen), .Q (\balance_db[2] [12]));
  SDFFQX1 \balance_db_reg[2][13] (.CK (clk), .D (n_439), .SI
       (\balance_db[2] [12]), .SE (DFT_sen), .Q (\balance_db[2] [13]));
  SDFFQX1 \balance_db_reg[2][14] (.CK (clk), .D (n_438), .SI
       (\balance_db[2] [13]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFQX1 \balance_db_reg[3][1] (.CK (clk), .D (n_455), .SI
       (DFT_sdi_1), .SE (DFT_sen), .Q (\balance_db[3] [1]));
  SDFFQX1 \balance_db_reg[3][2] (.CK (clk), .D (n_805), .SI
       (\balance_db[3] [1]), .SE (DFT_sen), .Q (\balance_db[3] [2]));
  SDFFQX1 \balance_db_reg[3][3] (.CK (clk), .D (n_436), .SI
       (\balance_db[3] [2]), .SE (DFT_sen), .Q (\balance_db[3] [3]));
  SDFFQX1 \balance_db_reg[3][4] (.CK (clk), .D (n_446), .SI
       (\balance_db[3] [3]), .SE (DFT_sen), .Q (\balance_db[3] [4]));
  SDFFQX1 \balance_db_reg[3][5] (.CK (clk), .D (n_435), .SI
       (\balance_db[3] [4]), .SE (DFT_sen), .Q (\balance_db[3] [5]));
  SDFFQX1 \balance_db_reg[3][6] (.CK (clk), .D (n_453), .SI
       (\balance_db[3] [5]), .SE (DFT_sen), .Q (\balance_db[3] [6]));
  SDFFQX1 \balance_db_reg[3][7] (.CK (clk), .D (n_433), .SI
       (\balance_db[3] [6]), .SE (DFT_sen), .Q (\balance_db[3] [7]));
  SDFFQX1 \balance_db_reg[3][8] (.CK (clk), .D (n_452), .SI
       (\balance_db[3] [7]), .SE (DFT_sen), .Q (\balance_db[3] [8]));
  SDFFQX1 \balance_db_reg[3][9] (.CK (clk), .D (n_432), .SI
       (\balance_db[3] [8]), .SE (DFT_sen), .Q (\balance_db[3] [9]));
  SDFFQX1 \balance_db_reg[3][10] (.CK (clk), .D (n_450), .SI
       (\balance_db[3] [9]), .SE (DFT_sen), .Q (\balance_db[3] [10]));
  SDFFQX1 \balance_db_reg[3][11] (.CK (clk), .D (n_430), .SI
       (\balance_db[3] [10]), .SE (DFT_sen), .Q (\balance_db[3] [11]));
  SDFFQX1 \balance_db_reg[3][12] (.CK (clk), .D (n_448), .SI
       (\balance_db[3] [11]), .SE (DFT_sen), .Q (\balance_db[3] [12]));
  SDFFQX1 \balance_db_reg[3][13] (.CK (clk), .D (n_429), .SI
       (\balance_db[3] [12]), .SE (DFT_sen), .Q (\balance_db[3] [13]));
  SDFFQX1 \balance_db_reg[3][14] (.CK (clk), .D (n_467), .SI
       (\balance_db[3] [13]), .SE (DFT_sen), .Q (\balance_db[3] [14]));
  AO22XL g4280(.A0 (n_383), .A1 (\balance_db[3] [14]), .B0 (n_149), .B1
       (n_788), .Y (n_467));
  OAI211X1 g4282(.A0 (n_6), .A1 (n_151), .B0 (n_766), .C0 (n_369), .Y
       (n_465));
  OAI21XL g4283(.A0 (n_809), .A1 (n_256), .B0 (n_424), .Y (n_464));
  OAI21XL g4284(.A0 (n_809), .A1 (n_242), .B0 (n_417), .Y (n_463));
  OAI21XL g4286(.A0 (n_760), .A1 (n_242), .B0 (n_423), .Y (n_461));
  OAI21XL g4287(.A0 (n_746), .A1 (n_242), .B0 (n_420), .Y (n_460));
  OAI21XL g4288(.A0 (n_762), .A1 (n_242), .B0 (n_419), .Y (n_459));
  OAI21XL g4289(.A0 (n_760), .A1 (n_256), .B0 (n_425), .Y (n_458));
  OAI21XL g4290(.A0 (n_763), .A1 (n_242), .B0 (n_416), .Y (n_457));
  OAI21XL g4291(.A0 (n_768), .A1 (n_242), .B0 (n_415), .Y (n_456));
  OAI21XL g4292(.A0 (n_809), .A1 (n_146), .B0 (n_414), .Y (n_455));
  OAI21XL g4293(.A0 (n_762), .A1 (n_256), .B0 (n_412), .Y (n_454));
  OAI21XL g4294(.A0 (n_746), .A1 (n_146), .B0 (n_421), .Y (n_453));
  OAI21XL g4295(.A0 (n_762), .A1 (n_146), .B0 (n_411), .Y (n_452));
  OAI21XL g4296(.A0 (n_763), .A1 (n_256), .B0 (n_413), .Y (n_451));
  OAI21XL g4297(.A0 (n_763), .A1 (n_146), .B0 (n_410), .Y (n_450));
  OAI21XL g4298(.A0 (n_768), .A1 (n_256), .B0 (n_418), .Y (n_449));
  OAI21XL g4299(.A0 (n_768), .A1 (n_146), .B0 (n_409), .Y (n_448));
  OAI211X1 g4301(.A0 (n_760), .A1 (n_368), .B0 (n_766), .C0 (n_396), .Y
       (n_446));
  AO22XL g4302(.A0 (n_397), .A1 (\balance_db[2] [3]), .B0 (n_232), .B1
       (n_784), .Y (n_445));
  OAI21XL g4303(.A0 (n_6), .A1 (n_242), .B0 (n_422), .Y (n_444));
  AO22XL g4304(.A0 (n_397), .A1 (\balance_db[2] [7]), .B0 (n_232), .B1
       (n_780), .Y (n_443));
  AO22XL g4305(.A0 (n_393), .A1 (\balance_db[1] [3]), .B0 (n_279), .B1
       (n_784), .Y (n_442));
  AO22XL g4306(.A0 (n_397), .A1 (\balance_db[2] [9]), .B0 (n_232), .B1
       (n_785), .Y (n_441));
  AO22XL g4307(.A0 (n_397), .A1 (\balance_db[2] [11]), .B0 (n_232), .B1
       (n_779), .Y (n_440));
  AO22XL g4308(.A0 (n_397), .A1 (\balance_db[2] [13]), .B0 (n_232), .B1
       (n_781), .Y (n_439));
  AO22XL g4309(.A0 (n_397), .A1 (DFT_sdo), .B0 (n_232), .B1 (n_788), .Y
       (n_438));
  AO22XL g4310(.A0 (n_393), .A1 (\balance_db[1] [7]), .B0 (n_279), .B1
       (n_780), .Y (n_437));
  AO22XL g4311(.A0 (n_383), .A1 (\balance_db[3] [3]), .B0 (n_149), .B1
       (n_784), .Y (n_436));
  AO22XL g4312(.A0 (n_383), .A1 (\balance_db[3] [5]), .B0 (n_149), .B1
       (n_786), .Y (n_435));
  AO22XL g4313(.A0 (n_393), .A1 (\balance_db[1] [9]), .B0 (n_279), .B1
       (n_785), .Y (n_434));
  AO22XL g4314(.A0 (n_383), .A1 (\balance_db[3] [7]), .B0 (n_149), .B1
       (n_780), .Y (n_433));
  AO22XL g4315(.A0 (n_383), .A1 (\balance_db[3] [9]), .B0 (n_149), .B1
       (n_785), .Y (n_432));
  AO22XL g4316(.A0 (n_393), .A1 (\balance_db[1] [11]), .B0 (n_279), .B1
       (n_779), .Y (n_431));
  AO22XL g4317(.A0 (n_383), .A1 (\balance_db[3] [11]), .B0 (n_149), .B1
       (n_779), .Y (n_430));
  AO22XL g4318(.A0 (n_383), .A1 (\balance_db[3] [13]), .B0 (n_149), .B1
       (n_781), .Y (n_429));
  AO22XL g4319(.A0 (n_393), .A1 (\balance_db[1] [13]), .B0 (n_279), .B1
       (n_781), .Y (n_428));
  OAI211X1 g4320(.A0 (n_746), .A1 (n_151), .B0 (n_766), .C0 (n_370), .Y
       (n_427));
  AO22X1 g4321(.A0 (n_393), .A1 (\balance_db[1] [14]), .B0 (n_279), .B1
       (n_788), .Y (n_426));
  NAND2XL g4322(.A (n_393), .B (\balance_db[1] [4]), .Y (n_425));
  NAND2XL g4323(.A (n_393), .B (\balance_db[1] [1]), .Y (n_424));
  NAND2XL g4324(.A (n_397), .B (\balance_db[2] [4]), .Y (n_423));
  NAND2XL g4325(.A (n_397), .B (\balance_db[2] [5]), .Y (n_422));
  NAND2XL g4326(.A (n_383), .B (\balance_db[3] [6]), .Y (n_421));
  NAND2XL g4327(.A (n_397), .B (\balance_db[2] [6]), .Y (n_420));
  NAND2XL g4328(.A (n_397), .B (\balance_db[2] [8]), .Y (n_419));
  NAND2XL g4329(.A (n_393), .B (\balance_db[1] [12]), .Y (n_418));
  NAND2XL g4330(.A (n_397), .B (\balance_db[2] [1]), .Y (n_417));
  NAND2XL g4331(.A (n_397), .B (\balance_db[2] [10]), .Y (n_416));
  NAND2XL g4332(.A (n_397), .B (\balance_db[2] [12]), .Y (n_415));
  NAND2XL g4333(.A (n_383), .B (\balance_db[3] [1]), .Y (n_414));
  NAND2XL g4334(.A (n_393), .B (\balance_db[1] [10]), .Y (n_413));
  NAND2XL g4335(.A (n_393), .B (\balance_db[1] [8]), .Y (n_412));
  NAND2XL g4336(.A (n_383), .B (\balance_db[3] [8]), .Y (n_411));
  NAND2XL g4337(.A (n_383), .B (\balance_db[3] [10]), .Y (n_410));
  NAND2XL g4338(.A (n_383), .B (\balance_db[3] [12]), .Y (n_409));
  NAND2XL g4341(.A (\balance_db[3] [4]), .B (n_368), .Y (n_396));
  NAND2XL g4343(.A (n_201), .B (n_769), .Y (n_397));
  NAND2XL g4344(.A (\balance_db[1] [6]), .B (n_151), .Y (n_370));
  NAND2XL g4345(.A (\balance_db[1] [5]), .B (n_151), .Y (n_369));
  AO21X1 g4346(.A0 (n_766), .A1 (n_96), .B0 (n_770), .Y (n_393));
  NAND2BX1 g4347(.AN (n_770), .B (n_201), .Y (n_383));
  CLKINVX1 g4349(.A (n_279), .Y (n_256));
  CLKINVX1 g4350(.A (n_242), .Y (n_232));
  NAND2XL g4351(.A (id_to_check[0]), .B (n_115), .Y (n_368));
  NOR2XL g4352(.A (n_769), .B (n_96), .Y (n_279));
  NAND2XL g4353(.A (n_770), .B (n_115), .Y (n_242));
  CLKINVX1 g4355(.A (n_149), .Y (n_146));
  NOR2XL g4356(.A (id_to_check[0]), .B (n_133), .Y (n_208));
  NAND2XL g4357(.A (n_766), .B (n_133), .Y (n_201));
  NAND2BX1 g4358(.AN (n_96), .B (id_to_check[0]), .Y (n_151));
  NOR2XL g4359(.A (n_769), .B (n_133), .Y (n_149));
  INVX1 g4360(.A (n_133), .Y (n_115));
  OR2X1 g4361(.A (n_80), .B (n_773), .Y (n_133));
  NAND4BBXL g4362(.AN (id_to_check[1]), .BN (n_773), .C (n_767), .D
       (fsm_charge_req), .Y (n_96));
  NAND3X1 g4363(.A (id_to_check[1]), .B (n_767), .C (fsm_charge_req),
       .Y (n_80));
  CLKINVX1 g4365(.A (reset), .Y (n_766));
  CLKINVX1 g4366(.A (n_786), .Y (n_6));
  NAND2BX1 g13470(.AN (reset), .B (n_804), .Y (n_805));
  MXI2XL g3(.A (n_800), .B (\balance_db[3] [2]), .S0 (n_368), .Y
       (n_804));
  NAND2BX1 g13471(.AN (reset), .B (n_806), .Y (n_807));
  MXI2XL g13472(.A (n_800), .B (\balance_db[1] [2]), .S0 (n_151), .Y
       (n_806));
  NOR2BX2 g13473(.AN (n_487), .B (n_490), .Y (n_808));
  OAI2BB1X2 g13474(.A0N (n_496), .A1N (n_652), .B0 (n_711), .Y (n_809));
  AOI221X1 g13475(.A0 (\balance_db[4] [8]), .A1 (n_537), .B0
       (\balance_db[6] [8]), .B1 (n_533), .C0 (n_698), .Y (n_810));
  AOI222XL g13476(.A0 (\balance_db[11] [13]), .A1 (n_534), .B0
       (\balance_db[8] [13]), .B1 (n_541), .C0 (\balance_db[3] [13]),
       .C1 (n_521), .Y (n_811));
  AO22XL g13477(.A0 (\balance_db[7] [7]), .A1 (n_543), .B0
       (\balance_db[6] [7]), .B1 (n_533), .Y (n_812));
  AO22XL g13478(.A0 (\balance_db[5] [7]), .A1 (n_808), .B0
       (\balance_db[10] [7]), .B1 (n_519), .Y (n_813));
  AOI22X1 g13479(.A0 (\balance_db[1] [5]), .A1 (n_540), .B0
       (\balance_db[10] [5]), .B1 (n_519), .Y (n_814));
  AO22XL g13480(.A0 (\balance_db[5] [8]), .A1 (n_808), .B0
       (\balance_db[3] [8]), .B1 (n_521), .Y (n_815));
  AO22XL g13481(.A0 (\balance_db[15] [6]), .A1 (n_482), .B0
       (\balance_db[14] [6]), .B1 (n_481), .Y (n_816));
  AO22XL g13482(.A0 (\balance_db[11] [1]), .A1 (id_to_check[3]), .B0
       (\balance_db[3] [1]), .B1 (n_475), .Y (n_817));
  AO22XL g13483(.A0 (\balance_db[8] [1]), .A1 (id_to_check[3]), .B0
       (\balance_db[0] [1]), .B1 (n_475), .Y (n_818));
  AO22XL g13484(.A0 (\balance_db[9] [1]), .A1 (id_to_check[3]), .B0
       (\balance_db[1] [1]), .B1 (n_475), .Y (n_819));
  NAND2XL g13485(.A (n_820), .B (n_766), .Y (n_821));
  MXI2XL g13486(.A (\balance_db[2] [2]), .B (n_800), .S0 (n_208), .Y
       (n_820));
endmodule

module barrier_ctrl(clk, reset, fsm_open_en, fsm_close_en,
     barrier_open_cmd, barrier_close_cmd, gate_is_open, gate_is_closed,
     DFT_sdi, DFT_sen, DFT_sdo);
  input clk, reset, fsm_open_en, fsm_close_en, DFT_sdi, DFT_sen;
  output barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed, DFT_sdo;
  wire clk, reset, fsm_open_en, fsm_close_en, DFT_sdi, DFT_sen;
  wire barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed, DFT_sdo;
  wire [2:0] barrier_position_counter;
  wire n_3, n_6, n_9, n_10, n_20, n_21, n_28, n_29;
  wire n_30, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_44, n_45, n_46;
  INVXL g152(.A (n_45), .Y (gate_is_closed));
  SDFFQX1 barrier_close_cmd_reg(.CK (clk), .D (n_42), .SI (DFT_sdi),
       .SE (DFT_sen), .Q (barrier_close_cmd));
  SDFFQX1 barrier_open_cmd_reg(.CK (clk), .D (n_41), .SI
       (barrier_close_cmd), .SE (DFT_sen), .Q (barrier_open_cmd));
  AO21X1 g214(.A0 (n_40), .A1 (fsm_close_en), .B0 (reset), .Y (n_42));
  OAI31X1 g215(.A0 (reset), .A1 (n_38), .A2 (fsm_close_en), .B0 (n_40),
       .Y (n_41));
  CLKINVX1 g216(.A (n_44), .Y (n_40));
  NOR2XL g217(.A (reset), .B (n_46), .Y (n_44));
  NAND2XL g218(.A (n_39), .B (fsm_open_en), .Y (n_46));
  NAND3X1 g219(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .C (DFT_sdo), .Y (n_39));
  OR3X1 g220(.A (barrier_position_counter[1]), .B (DFT_sdo), .C
       (barrier_position_counter[0]), .Y (n_45));
  INVXL g221(.A (fsm_open_en), .Y (n_38));
  SDFFQX1 \barrier_position_counter_reg[2] (.CK (clk), .D (n_37), .SI
       (barrier_position_counter[1]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFQX1 \barrier_position_counter_reg[0] (.CK (clk), .D (n_35), .SI
       (barrier_open_cmd), .SE (DFT_sen), .Q
       (barrier_position_counter[0]));
  OAI2BB1X1 g324(.A0N (n_44), .A1N (n_3), .B0 (n_36), .Y (n_37));
  SDFFQX1 \barrier_position_counter_reg[1] (.CK (clk), .D (n_34), .SI
       (barrier_position_counter[0]), .SE (DFT_sen), .Q
       (barrier_position_counter[1]));
  OAI31X1 g326(.A0 (n_9), .A1 (n_44), .A2 (n_30), .B0 (DFT_sdo), .Y
       (n_36));
  MXI2XL g327(.A (n_29), .B (n_10), .S0 (barrier_position_counter[0]),
       .Y (n_35));
  OAI21X1 g328(.A0 (n_21), .A1 (n_20), .B0 (n_28), .Y (n_34));
  NOR2XL g329(.A (n_21), .B (n_6), .Y (n_30));
  NOR2BXL g330(.AN (n_21), .B (n_44), .Y (n_29));
  AOI22X1 g331(.A0 (n_44), .A1 (n_20), .B0 (n_9), .B1
       (barrier_position_counter[1]), .Y (n_28));
  NAND4BXL g332(.AN (reset), .B (n_45), .C (fsm_close_en), .D (n_46),
       .Y (n_21));
  NOR2XL g333(.A (n_3), .B (n_6), .Y (n_20));
  INVX1 g334(.A (n_9), .Y (n_10));
  NOR3BX1 g335(.AN (n_46), .B (reset), .C (fsm_close_en), .Y (n_9));
  NOR2XL g336(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_6));
  AND2X1 g337(.A (barrier_position_counter[1]), .B
       (barrier_position_counter[0]), .Y (n_3));
endmodule

module vehicle_interface(clk, reset, fsm_read_en, vehicle_id_in,
     id_to_check, id_valid, DFT_sdi, DFT_sen);
  input clk, reset, fsm_read_en, DFT_sdi, DFT_sen;
  input [7:0] vehicle_id_in;
  output [3:0] id_to_check;
  output id_valid;
  wire clk, reset, fsm_read_en, DFT_sdi, DFT_sen;
  wire [7:0] vehicle_id_in;
  wire [3:0] id_to_check;
  wire id_valid;
  wire n_8, n_10, n_11, n_12, n_13, n_28;
  SDFFQX1 id_valid_reg(.CK (clk), .D (n_28), .SI (id_to_check[3]), .SE
       (DFT_sen), .Q (id_valid));
  SDFFHQX4 \id_to_check_reg[0] (.CK (clk), .D (n_12), .SI (DFT_sdi),
       .SE (DFT_sen), .Q (id_to_check[0]));
  SDFFQX1 \id_to_check_reg[1] (.CK (clk), .D (n_13), .SI
       (id_to_check[0]), .SE (DFT_sen), .Q (id_to_check[1]));
  SDFFQX1 \id_to_check_reg[2] (.CK (clk), .D (n_11), .SI
       (id_to_check[1]), .SE (DFT_sen), .Q (id_to_check[2]));
  SDFFQX1 \id_to_check_reg[3] (.CK (clk), .D (n_10), .SI
       (id_to_check[2]), .SE (DFT_sen), .Q (id_to_check[3]));
  AO22XL g196(.A0 (n_8), .A1 (id_to_check[1]), .B0 (vehicle_id_in[1]),
       .B1 (n_28), .Y (n_13));
  AO22XL g197(.A0 (n_8), .A1 (id_to_check[0]), .B0 (vehicle_id_in[0]),
       .B1 (n_28), .Y (n_12));
  AO22XL g198(.A0 (n_8), .A1 (id_to_check[2]), .B0 (vehicle_id_in[2]),
       .B1 (n_28), .Y (n_11));
  AO22XL g199(.A0 (n_8), .A1 (id_to_check[3]), .B0 (vehicle_id_in[3]),
       .B1 (n_28), .Y (n_10));
  NOR2XL g201(.A (reset), .B (fsm_read_en), .Y (n_8));
  NOR2BX1 g202(.AN (fsm_read_en), .B (reset), .Y (n_28));
endmodule

module toll_gate(clk, reset, sensor_vehicle_enter, sensor_vehicle_exit,
     vehicle_id_in, barrier_open_cmd, barrier_close_cmd, led_status,
     display_out, scan_en, DFT_sdi_1, DFT_sdo_1, DFT_sdi_2, DFT_sdo_2);
  input clk, reset, sensor_vehicle_enter, sensor_vehicle_exit, scan_en,
       DFT_sdi_1, DFT_sdi_2;
  input [7:0] vehicle_id_in;
  output barrier_open_cmd, barrier_close_cmd, DFT_sdo_1, DFT_sdo_2;
  output [1:0] led_status;
  output [7:0] display_out;
  wire clk, reset, sensor_vehicle_enter, sensor_vehicle_exit, scan_en,
       DFT_sdi_1, DFT_sdi_2;
  wire [7:0] vehicle_id_in;
  wire barrier_open_cmd, barrier_close_cmd, DFT_sdo_1, DFT_sdo_2;
  wire [1:0] led_status;
  wire [7:0] display_out;
  wire [3:0] id_to_check;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire charge_done, gate_is_closed, gate_is_open, id_valid, n_17, n_23,
       n_25, n_26;
  wire n_27, n_28, n_29, n_32, n_33, n_35, n_36, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_48;
  wire n_49, n_50, n_51, n_52, n_56, n_64, n_65, n_68;
  wire n_71, n_72, n_82, sufficient_balance;
  assign display_out[4] = 1'b0;
  assign display_out[7] = 1'b0;
  account_balance u_account_balance(.clk (clk), .reset (reset),
       .id_to_check ({UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED, n_52, id_to_check[2:0]}), .fsm_check_req (n_72),
       .fsm_charge_req (n_65), .sufficient_balance
       (sufficient_balance), .charge_done (charge_done), .DFT_sdi
       (DFT_sdi_1), .DFT_sen (scan_en), .DFT_sdo (DFT_sdo_1),
       .DFT_sdi_1 (DFT_sdi_2));
  barrier_ctrl u_barrier_ctrl(.clk (clk), .reset (reset), .fsm_open_en
       (n_68), .fsm_close_en (n_71), .barrier_open_cmd
       (barrier_open_cmd), .barrier_close_cmd (barrier_close_cmd),
       .gate_is_open (gate_is_open), .gate_is_closed (gate_is_closed),
       .DFT_sdi (charge_done), .DFT_sen (scan_en), .DFT_sdo (n_82));
  vehicle_interface u_vehicle_interface(.clk (clk), .reset (reset),
       .fsm_read_en (n_64), .vehicle_id_in ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       vehicle_id_in[3:0]}), .id_to_check (id_to_check), .id_valid
       (id_valid), .DFT_sdi (n_82), .DFT_sen (scan_en));
  INVXL g223(.A (n_68), .Y (led_status[0]));
  INVXL g221(.A (display_out[5]), .Y (display_out[6]));
  BUFX6 g222(.A (id_to_check[3]), .Y (n_52));
  INVXL g224(.A (sensor_vehicle_enter), .Y (n_51));
  OR2X1 g348(.A (n_68), .B (n_65), .Y (led_status[1]));
  NAND2BXL g349(.AN (n_68), .B (display_out[2]), .Y (display_out[1]));
  NOR2XL g350(.A (state[1]), .B (n_49), .Y (n_68));
  NOR2XL g351(.A (n_56), .B (n_49), .Y (display_out[5]));
  OAI211XL g352(.A0 (state[0]), .A1 (DFT_sdo_2), .B0 (n_56), .C0
       (n_49), .Y (display_out[0]));
  OAI2BB1XL g353(.A0N (DFT_sdo_2), .A1N (n_48), .B0 (display_out[2]),
       .Y (display_out[3]));
  OAI22X1 g354(.A0 (state[0]), .A1 (n_50), .B0 (n_46), .B1 (n_48), .Y
       (n_71));
  NOR2XL g355(.A (n_23), .B (n_50), .Y (n_64));
  AND2X1 g356(.A (state[0]), .B (n_72), .Y (n_65));
  OR2X1 g357(.A (DFT_sdo_2), .B (n_48), .Y (display_out[2]));
  NAND2XL g358(.A (n_56), .B (n_46), .Y (n_50));
  NAND2XL g359(.A (DFT_sdo_2), .B (state[0]), .Y (n_49));
  NOR2XL g360(.A (DFT_sdo_2), .B (n_56), .Y (n_72));
  NAND2XL g361(.A (state[1]), .B (n_23), .Y (n_48));
  CLKINVX1 g363(.A (state[1]), .Y (n_56));
  CLKINVX1 g364(.A (DFT_sdo_2), .Y (n_46));
  SDFFQX1 \state_reg[0] (.CK (clk), .D (n_45), .SI (id_valid), .SE
       (scan_en), .Q (state[0]));
  SDFFQX1 \state_reg[2] (.CK (clk), .D (n_43), .SI (state[1]), .SE
       (scan_en), .Q (DFT_sdo_2));
  SDFFQX1 \state_reg[1] (.CK (clk), .D (n_44), .SI (state[0]), .SE
       (scan_en), .Q (state[1]));
  OAI221X1 g413(.A0 (n_36), .A1 (n_25), .B0 (sensor_vehicle_exit), .B1
       (n_35), .C0 (n_42), .Y (n_45));
  OAI221X1 g414(.A0 (n_36), .A1 (n_33), .B0 (n_40), .B1 (n_29), .C0
       (n_41), .Y (n_44));
  OAI211X1 g415(.A0 (n_36), .A1 (n_32), .B0 (n_35), .C0 (n_41), .Y
       (n_43));
  NAND2XL g416(.A (n_28), .B (n_39), .Y (n_42));
  OR4XL g417(.A (n_27), .B (state[0]), .C (n_56), .D (gate_is_closed),
       .Y (n_41));
  AOI22X1 g418(.A0 (n_28), .A1 (id_valid), .B0 (sensor_vehicle_exit),
       .B1 (n_26), .Y (n_40));
  OAI32X1 g419(.A0 (n_51), .A1 (state[0]), .A2 (state[1]), .B0
       (id_valid), .B1 (n_23), .Y (n_39));
  NAND2XL g420(.A (n_28), .B (state[1]), .Y (n_36));
  INVX1 g421(.A (n_32), .Y (n_33));
  OR2X1 g422(.A (n_27), .B (n_29), .Y (n_35));
  OAI22X1 g423(.A0 (charge_done), .A1 (n_23), .B0 (state[0]), .B1
       (n_17), .Y (n_32));
  NAND2BX1 g424(.AN (state[1]), .B (state[0]), .Y (n_29));
  NOR2XL g425(.A (reset), .B (DFT_sdo_2), .Y (n_28));
  INVXL g426(.A (n_27), .Y (n_26));
  NOR2XL g427(.A (state[0]), .B (sufficient_balance), .Y (n_25));
  NAND2BX1 g428(.AN (reset), .B (DFT_sdo_2), .Y (n_27));
  INVX1 g429(.A (state[0]), .Y (n_23));
  INVX1 g430(.A (sufficient_balance), .Y (n_17));
endmodule

