
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 11 2025 18:28:08 IST (Oct 11 2025 12:58:08 UTC)

// Verification Directory fv/toll_gate 

module account_balance(clk, reset, id_to_check, fsm_check_req,
     fsm_charge_req, sufficient_balance, charge_done);
  input clk, reset, fsm_check_req, fsm_charge_req;
  input [7:0] id_to_check;
  output sufficient_balance, charge_done;
  wire clk, reset, fsm_check_req, fsm_charge_req;
  wire [7:0] id_to_check;
  wire sufficient_balance, charge_done;
  wire [15:0] \balance_db[3] ;
  wire [15:0] \balance_db[8] ;
  wire [15:0] \balance_db[14] ;
  wire [15:0] \balance_db[11] ;
  wire [15:0] \balance_db[10] ;
  wire [15:0] \balance_db[4] ;
  wire [15:0] \balance_db[0] ;
  wire [15:0] \balance_db[1] ;
  wire [15:0] \balance_db[12] ;
  wire [15:0] \balance_db[5] ;
  wire [15:0] \balance_db[9] ;
  wire [15:0] \balance_db[7] ;
  wire [15:0] \balance_db[6] ;
  wire [15:0] \balance_db[15] ;
  wire [15:0] \balance_db[13] ;
  wire [15:0] \balance_db[2] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_63, n_65, n_66;
  wire n_67, n_68, n_69, n_70, n_71, n_72, n_74, n_75;
  wire n_77, n_78, n_79, n_80, n_81, n_82, n_83, n_85;
  wire n_86, n_87, n_88, n_89, n_90, n_91, n_92, n_93;
  wire n_94, n_95, n_96, n_97, n_98, n_99, n_100, n_101;
  wire n_102, n_103, n_105, n_106, n_107, n_108, n_109, n_110;
  wire n_111, n_112, n_113, n_114, n_115, n_116, n_117, n_118;
  wire n_119, n_120, n_121, n_123, n_124, n_125, n_126, n_127;
  wire n_128, n_129, n_130, n_131, n_132, n_133, n_134, n_138;
  wire n_139, n_140, n_141, n_160, n_161, n_162, n_163, n_164;
  wire n_165, n_166, n_167, n_168, n_170, n_171, n_172, n_173;
  wire n_174, n_175, n_176, n_177, n_178, n_179, n_180, n_181;
  wire n_182, n_183, n_184, n_185, n_186, n_187, n_188, n_189;
  wire n_190, n_191, n_192, n_193, n_194, n_195, n_196, n_197;
  wire n_198, n_199, n_200, n_201, n_202, n_203, n_204, n_205;
  wire n_206, n_207, n_208, n_209, n_210, n_211, n_212, n_213;
  wire n_214, n_215, n_216, n_217, n_218, n_220, n_221, n_222;
  wire n_223, n_224, n_225, n_226, n_227, n_228, n_229, n_230;
  wire n_231, n_232, n_233, n_234, n_235, n_236, n_237, n_238;
  wire n_239, n_240, n_241, n_242, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_256, n_257, n_258, n_259, n_260, n_261, n_262;
  wire n_263, n_264, n_265, n_266, n_267, n_268, n_269, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_279;
  wire n_280, n_281, n_282, n_283, n_284, n_285, n_286, n_287;
  wire n_288, n_289, n_290, n_291, n_292, n_293, n_294, n_295;
  wire n_296, n_297, n_298, n_299, n_300, n_301, n_302, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_348, n_349, n_350, n_351, n_352, n_353;
  wire n_354, n_355, n_356, n_357, n_358, n_359, n_360, n_361;
  wire n_362, n_363, n_365, n_366, n_367, n_368, n_369, n_370;
  wire n_371, n_372, n_373, n_374, n_375, n_376, n_377, n_378;
  wire n_379, n_380, n_381, n_382, n_383, n_384, n_385, n_386;
  wire n_387, n_388, n_389, n_390, n_391, n_392, n_393, n_394;
  wire n_398, n_399, n_400, n_401, n_402, n_403, n_405, n_406;
  wire n_407, n_408, n_409, n_410, n_411, n_412, n_413, n_414;
  wire n_415, n_416, n_417, n_419, n_422, n_425, n_426, n_427;
  wire n_428, n_429, n_430, n_431, n_432, n_433, n_434;
  INVXL g1597(.A (n_411), .Y (sufficient_balance));
  DFFQX1 charge_done_reg(.CK (clk), .D (n_425), .Q (charge_done));
  NOR2BX2 g18368(.AN (fsm_charge_req), .B (n_411), .Y (n_412));
  OAI21X2 g18369(.A0 (n_415), .A1 (n_394), .B0 (fsm_check_req), .Y
       (n_411));
  NAND2XL g18370(.A (n_132), .B (n_414), .Y (n_394));
  NOR3X1 g18371(.A (n_405), .B (n_406), .C (n_393), .Y (n_414));
  NAND3BX2 g18372(.AN (n_416), .B (n_389), .C (n_391), .Y (n_415));
  NAND2BX1 g18374(.AN (n_403), .B (n_392), .Y (n_393));
  NOR2BX1 g18378(.AN (n_419), .B (n_402), .Y (n_391));
  NOR2BX1 g18379(.AN (n_300), .B (n_390), .Y (n_392));
  NOR2XL g18380(.A (n_407), .B (n_408), .Y (n_417));
  NAND3X1 g18381(.A (n_306), .B (n_337), .C (n_388), .Y (n_406));
  NAND2XL g18382(.A (n_387), .B (n_375), .Y (n_405));
  AOI2BB1X1 g18383(.A0N (n_413), .A1N (n_398), .B0 (n_422), .Y (n_416));
  NAND2XL g18384(.A (n_383), .B (n_430), .Y (n_390));
  NAND3X1 g18385(.A (n_330), .B (n_360), .C (n_384), .Y (n_410));
  NAND2XL g18386(.A (n_381), .B (n_386), .Y (n_403));
  AOI2BB1X1 g18387(.A0N (n_171), .A1N (n_327), .B0 (n_378), .Y (n_422));
  NOR2XL g18388(.A (n_399), .B (n_400), .Y (n_419));
  INVX1 g18389(.A (n_401), .Y (n_389));
  AOI211X1 g18390(.A0 (\balance_db[3] [11]), .A1 (n_138), .B0 (n_310),
       .C0 (n_382), .Y (n_388));
  AOI211X1 g18391(.A0 (\balance_db[3] [10]), .A1 (n_138), .B0 (n_320),
       .C0 (n_380), .Y (n_387));
  NAND3X1 g18392(.A (n_368), .B (n_333), .C (n_379), .Y (n_409));
  NAND2XL g18393(.A (n_385), .B (n_377), .Y (n_401));
  OAI211X1 g18394(.A0 (n_174), .A1 (n_336), .B0 (n_367), .C0 (n_370),
       .Y (n_402));
  NAND3X1 g18395(.A (n_335), .B (n_369), .C (n_376), .Y (n_408));
  NOR3X1 g18396(.A (n_346), .B (n_348), .C (n_349), .Y (n_386));
  AOI211X1 g18397(.A0 (\balance_db[8] [6]), .A1 (n_235), .B0 (n_339),
       .C0 (n_374), .Y (n_385));
  AOI221X1 g18398(.A0 (\balance_db[14] [15]), .A1 (n_247), .B0
       (\balance_db[11] [15]), .B1 (n_237), .C0 (n_363), .Y (n_384));
  NAND2X1 g18399(.A (n_372), .B (n_373), .Y (n_407));
  NAND2XL g18400(.A (n_361), .B (n_357), .Y (n_399));
  NAND2XL g18401(.A (n_359), .B (n_355), .Y (n_400));
  NAND2XL g18402(.A (n_365), .B (n_356), .Y (n_398));
  AOI221X1 g18403(.A0 (n_172), .A1 (n_281), .B0 (\balance_db[10] [9]),
       .B1 (n_246), .C0 (n_345), .Y (n_383));
  OAI22X1 g18404(.A0 (n_173), .A1 (n_324), .B0 (n_131), .B1 (n_325), .Y
       (n_382));
  AOI2BB1X1 g18405(.A0N (n_171), .A1N (n_314), .B0 (n_371), .Y (n_381));
  OAI22X1 g18406(.A0 (n_173), .A1 (n_322), .B0 (n_131), .B1 (n_323), .Y
       (n_380));
  AOI211X1 g18407(.A0 (\balance_db[4] [14]), .A1 (n_234), .B0 (n_351),
       .C0 (n_366), .Y (n_379));
  OAI222XL g18408(.A0 (n_174), .A1 (n_285), .B0 (n_173), .B1 (n_326),
       .C0 (n_131), .C1 (n_286), .Y (n_378));
  AOI211X1 g18409(.A0 (\balance_db[4] [6]), .A1 (n_234), .B0 (n_353),
       .C0 (n_344), .Y (n_377));
  NAND2XL g18410(.A (n_362), .B (n_358), .Y (n_413));
  NOR2XL g18411(.A (n_354), .B (n_342), .Y (n_376));
  AND2X1 g18412(.A (n_298), .B (n_329), .Y (n_375));
  AOI21X1 g18413(.A0 (n_229), .A1 (n_307), .B0 (n_131), .Y (n_374));
  NOR3X1 g18414(.A (n_302), .B (n_328), .C (n_431), .Y (n_373));
  NOR2XL g18415(.A (n_340), .B (n_343), .Y (n_372));
  NOR2XL g18416(.A (n_131), .B (n_331), .Y (n_371));
  NOR2XL g18417(.A (n_338), .B (n_341), .Y (n_370));
  NOR2XL g18418(.A (n_334), .B (n_301), .Y (n_369));
  AOI221X1 g18419(.A0 (\balance_db[0] [14]), .A1 (n_245), .B0
       (\balance_db[11] [14]), .B1 (n_237), .C0 (n_332), .Y (n_368));
  AOI21X1 g18420(.A0 (\balance_db[8] [7]), .A1 (n_235), .B0 (n_352), .Y
       (n_367));
  OAI21X1 g18421(.A0 (n_174), .A1 (n_316), .B0 (n_272), .Y (n_366));
  AOI22X1 g18422(.A0 (n_175), .A1 (n_292), .B0 (n_176), .B1 (n_296), .Y
       (n_365));
  OAI22X1 g18424(.A0 (n_171), .A1 (n_312), .B0 (n_131), .B1 (n_313), .Y
       (n_363));
  AOI22X1 g18425(.A0 (n_175), .A1 (n_284), .B0 (n_176), .B1 (n_294), .Y
       (n_362));
  AOI22X1 g18426(.A0 (n_175), .A1 (n_295), .B0 (n_176), .B1 (n_297), .Y
       (n_361));
  AOI221X1 g18427(.A0 (\balance_db[0] [15]), .A1 (n_245), .B0
       (\balance_db[1] [15]), .B1 (n_243), .C0 (n_350), .Y (n_360));
  AOI22X1 g18428(.A0 (n_170), .A1 (n_287), .B0 (n_176), .B1 (n_289), .Y
       (n_359));
  AOI22X1 g18429(.A0 (n_172), .A1 (n_279), .B0 (n_170), .B1 (n_291), .Y
       (n_358));
  AOI22X1 g18430(.A0 (n_172), .A1 (n_290), .B0 (n_170), .B1 (n_293), .Y
       (n_357));
  AOI22X1 g18431(.A0 (n_172), .A1 (n_278), .B0 (n_170), .B1 (n_299), .Y
       (n_356));
  AOI22X1 g18432(.A0 (n_172), .A1 (n_280), .B0 (n_175), .B1 (n_283), .Y
       (n_355));
  AOI21X1 g18433(.A0 (n_256), .A1 (n_262), .B0 (n_174), .Y (n_354));
  NOR2XL g18434(.A (n_171), .B (n_318), .Y (n_353));
  NOR2XL g18435(.A (n_173), .B (n_317), .Y (n_352));
  NOR2XL g18436(.A (n_131), .B (n_315), .Y (n_351));
  NOR2XL g18437(.A (n_174), .B (n_321), .Y (n_350));
  NOR2XL g18438(.A (n_166), .B (n_311), .Y (n_349));
  AOI21X1 g18439(.A0 (n_231), .A1 (n_265), .B0 (n_173), .Y (n_348));
  NOR2XL g18441(.A (n_174), .B (n_309), .Y (n_346));
  NOR2XL g18442(.A (n_131), .B (n_282), .Y (n_345));
  NAND2XL g18443(.A (n_304), .B (n_305), .Y (n_344));
  AOI21X1 g18444(.A0 (n_264), .A1 (n_263), .B0 (n_131), .Y (n_343));
  AOI21X1 g18445(.A0 (n_258), .A1 (n_257), .B0 (n_131), .Y (n_342));
  AOI21X1 g18446(.A0 (n_253), .A1 (n_252), .B0 (n_131), .Y (n_341));
  AOI21X1 g18447(.A0 (n_255), .A1 (n_261), .B0 (n_174), .Y (n_340));
  NOR2XL g18448(.A (n_173), .B (n_319), .Y (n_339));
  AOI21XL g18449(.A0 (n_251), .A1 (n_250), .B0 (n_171), .Y (n_338));
  AOI222XL g18450(.A0 (\balance_db[4] [11]), .A1 (n_234), .B0
       (\balance_db[12] [11]), .B1 (n_241), .C0 (n_242), .C1
       (\balance_db[5] [11]), .Y (n_337));
  AOI222XL g18451(.A0 (\balance_db[4] [7]), .A1 (n_167), .B0
       (id_to_check[0]), .B1 (n_225), .C0 (n_163), .C1
       (\balance_db[12] [7]), .Y (n_336));
  AOI221X1 g18452(.A0 (\balance_db[1] [13]), .A1 (n_243), .B0
       (\balance_db[8] [13]), .B1 (n_235), .C0 (n_275), .Y (n_335));
  OAI21XL g18453(.A0 (n_254), .A1 (n_171), .B0 (n_273), .Y (n_334));
  AOI222XL g18454(.A0 (\balance_db[8] [14]), .A1 (n_235), .B0
       (\balance_db[1] [14]), .B1 (n_243), .C0 (n_239), .C1
       (\balance_db[9] [14]), .Y (n_333));
  OAI21X1 g18455(.A0 (n_171), .A1 (n_249), .B0 (n_271), .Y (n_332));
  AOI222XL g18456(.A0 (id_to_check[3]), .A1 (n_180), .B0
       (\balance_db[7] [8]), .B1 (n_164), .C0 (\balance_db[6] [8]), .C1
       (n_167), .Y (n_331));
  AOI222XL g18457(.A0 (\balance_db[4] [15]), .A1 (n_234), .B0
       (\balance_db[8] [15]), .B1 (n_235), .C0 (n_239), .C1
       (\balance_db[9] [15]), .Y (n_330));
  AOI221X1 g18458(.A0 (\balance_db[4] [10]), .A1 (n_234), .B0
       (\balance_db[5] [10]), .B1 (n_242), .C0 (n_269), .Y (n_329));
  OAI22X1 g18459(.A0 (n_173), .A1 (n_259), .B0 (n_171), .B1 (n_260), .Y
       (n_328));
  AOI222XL g18460(.A0 (n_134), .A1 (n_177), .B0 (\balance_db[11] [3]),
       .B1 (n_160), .C0 (n_163), .C1 (\balance_db[10] [3]), .Y (n_327));
  AOI222XL g18461(.A0 (n_134), .A1 (n_178), .B0 (\balance_db[9] [3]),
       .B1 (n_160), .C0 (\balance_db[8] [3]), .C1 (n_163), .Y (n_326));
  AOI221X1 g18462(.A0 (\balance_db[15] [11]), .A1 (n_160), .B0
       (\balance_db[7] [11]), .B1 (n_164), .C0 (n_268), .Y (n_325));
  AOI221X1 g18463(.A0 (\balance_db[9] [11]), .A1 (n_160), .B0
       (\balance_db[1] [11]), .B1 (n_164), .C0 (n_267), .Y (n_324));
  AOI222XL g18464(.A0 (n_139), .A1 (n_181), .B0 (\balance_db[15] [10]),
       .B1 (n_160), .C0 (\balance_db[7] [10]), .C1 (n_164), .Y (n_323));
  AOI222XL g18465(.A0 (n_139), .A1 (n_432), .B0 (\balance_db[9] [10]),
       .B1 (n_160), .C0 (\balance_db[1] [10]), .C1 (n_164), .Y (n_322));
  AOI222XL g18466(.A0 (\balance_db[12] [15]), .A1 (n_163), .B0
       (\balance_db[13] [15]), .B1 (n_160), .C0 (n_164), .C1
       (\balance_db[5] [15]), .Y (n_321));
  NOR2XL g18467(.A (n_171), .B (n_248), .Y (n_320));
  AOI222XL g18468(.A0 (\balance_db[1] [6]), .A1 (n_168), .B0
       (\balance_db[9] [6]), .B1 (n_160), .C0 (n_167), .C1
       (\balance_db[0] [6]), .Y (n_319));
  AOI222XL g18469(.A0 (\balance_db[3] [6]), .A1 (n_164), .B0
       (\balance_db[10] [6]), .B1 (n_163), .C0 (n_160), .C1
       (\balance_db[11] [6]), .Y (n_318));
  AOI222XL g18470(.A0 (\balance_db[1] [7]), .A1 (n_168), .B0
       (\balance_db[9] [7]), .B1 (n_160), .C0 (n_167), .C1
       (\balance_db[0] [7]), .Y (n_317));
  AOI222XL g18471(.A0 (\balance_db[12] [14]), .A1 (n_163), .B0
       (\balance_db[13] [14]), .B1 (n_160), .C0 (n_164), .C1
       (\balance_db[5] [14]), .Y (n_316));
  AOI222XL g18472(.A0 (\balance_db[6] [14]), .A1 (n_167), .B0
       (\balance_db[15] [14]), .B1 (n_160), .C0 (n_164), .C1
       (\balance_db[7] [14]), .Y (n_315));
  AOI221X1 g18473(.A0 (\balance_db[3] [8]), .A1 (n_164), .B0
       (\balance_db[11] [8]), .B1 (n_160), .C0 (n_232), .Y (n_314));
  AOI222XL g18474(.A0 (\balance_db[6] [15]), .A1 (n_167), .B0
       (\balance_db[15] [15]), .B1 (n_160), .C0 (n_164), .C1
       (\balance_db[7] [15]), .Y (n_313));
  AOI222XL g18475(.A0 (\balance_db[2] [15]), .A1 (n_167), .B0
       (\balance_db[10] [15]), .B1 (n_163), .C0 (n_164), .C1
       (\balance_db[3] [15]), .Y (n_312));
  AOI221X1 g18476(.A0 (\balance_db[4] [8]), .A1 (n_175), .B0
       (\balance_db[2] [8]), .B1 (n_170), .C0 (n_222), .Y (n_311));
  NOR2XL g18477(.A (n_171), .B (n_266), .Y (n_310));
  AOI22X1 g18478(.A0 (n_133), .A1 (n_179), .B0 (\balance_db[5] [8]),
       .B1 (n_164), .Y (n_309));
  AOI221X1 g18479(.A0 (\balance_db[3] [9]), .A1 (n_168), .B0
       (\balance_db[2] [9]), .B1 (n_167), .C0 (n_230), .Y (n_308));
  AOI222XL g18480(.A0 (\balance_db[7] [6]), .A1 (n_164), .B0
       (\balance_db[14] [6]), .B1 (n_163), .C0 (\balance_db[15] [6]),
       .C1 (n_160), .Y (n_307));
  AOI22XL g18481(.A0 (n_244), .A1 (\balance_db[13] [11]), .B0 (n_237),
       .B1 (\balance_db[11] [11]), .Y (n_306));
  AOI22X1 g18482(.A0 (\balance_db[12] [6]), .A1 (n_241), .B0
       (\balance_db[13] [6]), .B1 (n_244), .Y (n_305));
  AOI22X1 g18483(.A0 (\balance_db[2] [6]), .A1 (n_212), .B0
       (\balance_db[5] [6]), .B1 (n_242), .Y (n_304));
  OAI2BB1X1 g18485(.A0N (\balance_db[10] [12]), .A1N (n_246), .B0
       (n_276), .Y (n_302));
  OAI21XL g18486(.A0 (n_236), .A1 (n_140), .B0 (n_274), .Y (n_301));
  AOI22XL g18487(.A0 (n_242), .A1 (\balance_db[5] [9]), .B0 (n_244),
       .B1 (\balance_db[13] [9]), .Y (n_300));
  OAI22X1 g18488(.A0 (id_to_check[0]), .A1 (n_195), .B0 (n_139), .B1
       (n_197), .Y (n_299));
  AOI22XL g18489(.A0 (n_244), .A1 (\balance_db[13] [10]), .B0 (n_237),
       .B1 (\balance_db[11] [10]), .Y (n_298));
  OAI22X1 g18490(.A0 (id_to_check[0]), .A1 (n_215), .B0 (n_139), .B1
       (n_217), .Y (n_297));
  OAI22X1 g18491(.A0 (id_to_check[0]), .A1 (n_196), .B0 (n_139), .B1
       (n_224), .Y (n_296));
  OAI22X1 g18492(.A0 (id_to_check[0]), .A1 (n_227), .B0 (n_139), .B1
       (n_221), .Y (n_295));
  OAI22X1 g18493(.A0 (id_to_check[0]), .A1 (n_184), .B0 (n_139), .B1
       (n_205), .Y (n_294));
  OAI22X1 g18494(.A0 (id_to_check[0]), .A1 (n_218), .B0 (n_139), .B1
       (n_223), .Y (n_293));
  OAI22X1 g18495(.A0 (id_to_check[0]), .A1 (n_228), .B0 (n_139), .B1
       (n_210), .Y (n_292));
  OAI22X1 g18496(.A0 (id_to_check[0]), .A1 (n_203), .B0 (n_139), .B1
       (n_209), .Y (n_291));
  OAI22X1 g18497(.A0 (id_to_check[0]), .A1 (n_207), .B0 (n_139), .B1
       (n_208), .Y (n_290));
  OAI22X1 g18498(.A0 (id_to_check[0]), .A1 (n_226), .B0 (n_139), .B1
       (n_204), .Y (n_289));
  OAI21XL g18499(.A0 (n_233), .A1 (n_141), .B0 (n_277), .Y (n_288));
  OAI22X1 g18500(.A0 (id_to_check[0]), .A1 (n_198), .B0 (n_139), .B1
       (n_201), .Y (n_287));
  MX2X1 g18501(.A (n_206), .B (n_202), .S0 (id_to_check[0]), .Y
       (n_286));
  MX2X1 g18502(.A (n_199), .B (n_200), .S0 (id_to_check[0]), .Y
       (n_285));
  OAI22X1 g18503(.A0 (id_to_check[0]), .A1 (n_214), .B0 (n_139), .B1
       (n_188), .Y (n_284));
  OAI22X1 g18504(.A0 (id_to_check[0]), .A1 (n_191), .B0 (n_139), .B1
       (n_194), .Y (n_283));
  MX2X1 g18505(.A (n_192), .B (n_193), .S0 (id_to_check[0]), .Y
       (n_282));
  OAI22X1 g18506(.A0 (id_to_check[0]), .A1 (n_189), .B0 (n_139), .B1
       (n_190), .Y (n_281));
  OAI22X1 g18507(.A0 (id_to_check[0]), .A1 (n_183), .B0 (n_139), .B1
       (n_186), .Y (n_280));
  OAI22X1 g18508(.A0 (id_to_check[0]), .A1 (n_220), .B0 (n_139), .B1
       (n_185), .Y (n_279));
  OAI22X1 g18509(.A0 (id_to_check[0]), .A1 (n_182), .B0 (n_139), .B1
       (n_187), .Y (n_278));
  NAND3XL g18510(.A (\balance_db[12] [9]), .B (n_163), .C (n_175), .Y
       (n_277));
  NAND3XL g18511(.A (\balance_db[2] [12]), .B (n_170), .C (n_167), .Y
       (n_276));
  NOR2BXL g18512(.AN (\balance_db[9] [13]), .B (n_238), .Y (n_275));
  NAND3XL g18513(.A (\balance_db[0] [13]), .B (n_167), .C (n_172), .Y
       (n_274));
  NAND2XL g18514(.A (\balance_db[3] [13]), .B (n_138), .Y (n_273));
  NAND2XL g18515(.A (\balance_db[14] [14]), .B (n_247), .Y (n_272));
  NAND2XL g18516(.A (\balance_db[3] [14]), .B (n_138), .Y (n_271));
  NOR2BXL g18518(.AN (\balance_db[12] [10]), .B (n_240), .Y (n_269));
  NOR2XL g18519(.A (id_to_check[0]), .B (n_216), .Y (n_268));
  NOR2XL g18520(.A (id_to_check[0]), .B (n_213), .Y (n_267));
  AOI22X1 g18521(.A0 (\balance_db[2] [11]), .A1 (n_167), .B0
       (\balance_db[10] [11]), .B1 (n_163), .Y (n_266));
  AOI22X1 g18522(.A0 (\balance_db[8] [8]), .A1 (n_163), .B0
       (\balance_db[9] [8]), .B1 (n_160), .Y (n_265));
  AOI22X1 g18523(.A0 (\balance_db[14] [12]), .A1 (n_163), .B0
       (\balance_db[15] [12]), .B1 (n_160), .Y (n_264));
  AOI22X1 g18524(.A0 (\balance_db[6] [12]), .A1 (n_167), .B0
       (\balance_db[7] [12]), .B1 (n_164), .Y (n_263));
  AOI22X1 g18525(.A0 (\balance_db[4] [13]), .A1 (n_167), .B0
       (\balance_db[5] [13]), .B1 (n_164), .Y (n_262));
  AOI22X1 g18526(.A0 (\balance_db[4] [12]), .A1 (n_167), .B0
       (\balance_db[5] [12]), .B1 (n_164), .Y (n_261));
  AOI22X1 g18527(.A0 (\balance_db[3] [12]), .A1 (n_164), .B0
       (\balance_db[11] [12]), .B1 (n_160), .Y (n_260));
  AOI22X1 g18528(.A0 (\balance_db[0] [12]), .A1 (n_167), .B0
       (\balance_db[8] [12]), .B1 (n_163), .Y (n_259));
  AOI22X1 g18529(.A0 (\balance_db[14] [13]), .A1 (n_163), .B0
       (\balance_db[15] [13]), .B1 (n_160), .Y (n_258));
  AOI22X1 g18530(.A0 (\balance_db[6] [13]), .A1 (n_167), .B0
       (\balance_db[7] [13]), .B1 (n_164), .Y (n_257));
  AOI22X1 g18531(.A0 (\balance_db[12] [13]), .A1 (n_163), .B0
       (\balance_db[13] [13]), .B1 (n_160), .Y (n_256));
  AOI22X1 g18532(.A0 (\balance_db[12] [12]), .A1 (n_163), .B0
       (\balance_db[13] [12]), .B1 (n_160), .Y (n_255));
  AOI22XL g18533(.A0 (n_167), .A1 (\balance_db[2] [13]), .B0 (n_163),
       .B1 (\balance_db[10] [13]), .Y (n_254));
  AOI22X1 g18534(.A0 (\balance_db[14] [7]), .A1 (n_163), .B0
       (\balance_db[15] [7]), .B1 (n_160), .Y (n_253));
  AOI22X1 g18535(.A0 (\balance_db[6] [7]), .A1 (n_167), .B0
       (\balance_db[7] [7]), .B1 (n_164), .Y (n_252));
  AOI22XL g18536(.A0 (n_168), .A1 (\balance_db[3] [7]), .B0 (n_160),
       .B1 (\balance_db[11] [7]), .Y (n_251));
  AOI22X1 g18537(.A0 (\balance_db[2] [7]), .A1 (n_167), .B0
       (\balance_db[10] [7]), .B1 (n_163), .Y (n_250));
  AOI22X1 g18538(.A0 (\balance_db[2] [14]), .A1 (n_167), .B0
       (\balance_db[10] [14]), .B1 (n_163), .Y (n_249));
  AOI22X1 g18539(.A0 (\balance_db[2] [10]), .A1 (n_167), .B0
       (\balance_db[10] [10]), .B1 (n_163), .Y (n_248));
  CLKINVX1 g18543(.A (n_240), .Y (n_241));
  INVX1 g18544(.A (n_238), .Y (n_239));
  CLKINVX1 g18545(.A (n_236), .Y (n_237));
  CLKINVX1 g18546(.A (n_211), .Y (n_235));
  CLKINVX1 g18547(.A (n_233), .Y (n_234));
  NOR2BXL g18548(.AN (\balance_db[10] [8]), .B (n_162), .Y (n_232));
  NAND2XL g18549(.A (\balance_db[1] [8]), .B (n_164), .Y (n_231));
  NOR2BXL g18550(.AN (\balance_db[11] [9]), .B (n_161), .Y (n_230));
  NAND2XL g18551(.A (\balance_db[6] [6]), .B (n_167), .Y (n_229));
  AOI22X1 g18552(.A0 (\balance_db[4] [2]), .A1 (n_134), .B0
       (\balance_db[12] [2]), .B1 (n_133), .Y (n_228));
  AOI22X1 g18553(.A0 (\balance_db[4] [4]), .A1 (n_134), .B0
       (\balance_db[12] [4]), .B1 (id_to_check[3]), .Y (n_227));
  AOI22X1 g18554(.A0 (\balance_db[6] [5]), .A1 (n_134), .B0
       (\balance_db[14] [5]), .B1 (id_to_check[3]), .Y (n_226));
  MX2X1 g18555(.A (\balance_db[5] [7]), .B (\balance_db[13] [7]), .S0
       (id_to_check[3]), .Y (n_225));
  AOI22X1 g18556(.A0 (\balance_db[7] [2]), .A1 (n_134), .B0
       (\balance_db[15] [2]), .B1 (id_to_check[3]), .Y (n_224));
  AOI22X1 g18557(.A0 (\balance_db[3] [4]), .A1 (n_134), .B0
       (\balance_db[11] [4]), .B1 (id_to_check[3]), .Y (n_223));
  NOR2BXL g18558(.AN (\balance_db[0] [8]), .B (n_173), .Y (n_222));
  AOI22X1 g18559(.A0 (\balance_db[5] [4]), .A1 (n_134), .B0
       (\balance_db[13] [4]), .B1 (n_133), .Y (n_221));
  AOI22X1 g18560(.A0 (\balance_db[0] [1]), .A1 (n_134), .B0
       (\balance_db[8] [1]), .B1 (n_133), .Y (n_220));
  AOI22X1 g18562(.A0 (\balance_db[2] [4]), .A1 (n_134), .B0
       (\balance_db[10] [4]), .B1 (id_to_check[3]), .Y (n_218));
  AOI22X1 g18563(.A0 (\balance_db[7] [4]), .A1 (n_134), .B0
       (\balance_db[15] [4]), .B1 (id_to_check[3]), .Y (n_217));
  AOI22XL g18564(.A0 (n_134), .A1 (\balance_db[6] [11]), .B0
       (id_to_check[3]), .B1 (\balance_db[14] [11]), .Y (n_216));
  AOI22X1 g18565(.A0 (\balance_db[6] [4]), .A1 (n_134), .B0
       (\balance_db[14] [4]), .B1 (n_133), .Y (n_215));
  AOI22X1 g18566(.A0 (\balance_db[4] [1]), .A1 (n_134), .B0
       (\balance_db[12] [1]), .B1 (n_133), .Y (n_214));
  AOI22XL g18567(.A0 (n_134), .A1 (\balance_db[0] [11]), .B0
       (id_to_check[3]), .B1 (\balance_db[8] [11]), .Y (n_213));
  NOR2XL g18568(.A (n_131), .B (n_162), .Y (n_247));
  NOR2XL g18569(.A (n_171), .B (n_166), .Y (n_212));
  NOR2XL g18570(.A (n_171), .B (n_162), .Y (n_246));
  NOR2XL g18571(.A (n_166), .B (n_173), .Y (n_245));
  NOR2XL g18572(.A (n_161), .B (n_174), .Y (n_244));
  NOR2XL g18573(.A (n_165), .B (n_173), .Y (n_243));
  NOR2XL g18574(.A (n_165), .B (n_174), .Y (n_242));
  NOR2XL g18575(.A (n_165), .B (n_171), .Y (n_138));
  NAND2XL g18576(.A (n_163), .B (n_175), .Y (n_240));
  NAND2XL g18577(.A (n_160), .B (n_172), .Y (n_238));
  NAND2XL g18578(.A (n_160), .B (n_170), .Y (n_236));
  NAND2XL g18579(.A (n_163), .B (n_172), .Y (n_211));
  NAND2XL g18580(.A (n_175), .B (n_167), .Y (n_233));
  AOI22X1 g18581(.A0 (\balance_db[5] [2]), .A1 (n_134), .B0
       (\balance_db[13] [2]), .B1 (n_133), .Y (n_210));
  AOI22X1 g18582(.A0 (\balance_db[3] [1]), .A1 (n_134), .B0
       (\balance_db[11] [1]), .B1 (id_to_check[3]), .Y (n_209));
  AOI22X1 g18583(.A0 (\balance_db[1] [4]), .A1 (n_134), .B0
       (\balance_db[9] [4]), .B1 (id_to_check[3]), .Y (n_208));
  AOI22X1 g18584(.A0 (\balance_db[0] [4]), .A1 (n_134), .B0
       (\balance_db[8] [4]), .B1 (n_133), .Y (n_207));
  AOI22XL g18585(.A0 (n_134), .A1 (\balance_db[6] [3]), .B0 (n_133),
       .B1 (\balance_db[14] [3]), .Y (n_206));
  AOI22X1 g18586(.A0 (\balance_db[7] [1]), .A1 (n_134), .B0
       (\balance_db[15] [1]), .B1 (n_133), .Y (n_205));
  AOI22X1 g18587(.A0 (\balance_db[7] [5]), .A1 (n_134), .B0
       (\balance_db[15] [5]), .B1 (id_to_check[3]), .Y (n_204));
  AOI22X1 g18588(.A0 (\balance_db[2] [1]), .A1 (n_134), .B0
       (\balance_db[10] [1]), .B1 (n_133), .Y (n_203));
  AOI22XL g18589(.A0 (n_134), .A1 (\balance_db[7] [3]), .B0 (n_133),
       .B1 (\balance_db[15] [3]), .Y (n_202));
  AOI22X1 g18590(.A0 (\balance_db[3] [5]), .A1 (n_134), .B0
       (\balance_db[11] [5]), .B1 (id_to_check[3]), .Y (n_201));
  AOI22XL g18591(.A0 (n_134), .A1 (\balance_db[5] [3]), .B0
       (id_to_check[3]), .B1 (\balance_db[13] [3]), .Y (n_200));
  AOI22XL g18592(.A0 (n_134), .A1 (\balance_db[4] [3]), .B0
       (id_to_check[3]), .B1 (\balance_db[12] [3]), .Y (n_199));
  AOI22X1 g18593(.A0 (\balance_db[2] [5]), .A1 (n_134), .B0
       (\balance_db[10] [5]), .B1 (n_133), .Y (n_198));
  AOI22X1 g18594(.A0 (\balance_db[3] [2]), .A1 (n_134), .B0
       (\balance_db[11] [2]), .B1 (id_to_check[3]), .Y (n_197));
  AOI22X1 g18595(.A0 (\balance_db[6] [2]), .A1 (n_134), .B0
       (\balance_db[14] [2]), .B1 (id_to_check[3]), .Y (n_196));
  AOI22X1 g18596(.A0 (\balance_db[2] [2]), .A1 (n_134), .B0
       (\balance_db[10] [2]), .B1 (id_to_check[3]), .Y (n_195));
  AOI22X1 g18597(.A0 (\balance_db[5] [5]), .A1 (n_134), .B0
       (\balance_db[13] [5]), .B1 (id_to_check[3]), .Y (n_194));
  AOI22XL g18598(.A0 (n_134), .A1 (\balance_db[7] [9]), .B0
       (id_to_check[3]), .B1 (\balance_db[15] [9]), .Y (n_193));
  AOI22XL g18599(.A0 (n_134), .A1 (\balance_db[6] [9]), .B0
       (id_to_check[3]), .B1 (\balance_db[14] [9]), .Y (n_192));
  AOI22X1 g18600(.A0 (\balance_db[4] [5]), .A1 (n_134), .B0
       (\balance_db[12] [5]), .B1 (id_to_check[3]), .Y (n_191));
  AOI22X1 g18601(.A0 (\balance_db[1] [9]), .A1 (n_134), .B0
       (\balance_db[9] [9]), .B1 (n_133), .Y (n_190));
  AOI22X1 g18602(.A0 (\balance_db[0] [9]), .A1 (n_134), .B0
       (\balance_db[8] [9]), .B1 (id_to_check[3]), .Y (n_189));
  AOI22X1 g18603(.A0 (\balance_db[5] [1]), .A1 (n_134), .B0
       (\balance_db[13] [1]), .B1 (id_to_check[3]), .Y (n_188));
  AOI22X1 g18604(.A0 (\balance_db[1] [2]), .A1 (n_134), .B0
       (\balance_db[9] [2]), .B1 (id_to_check[3]), .Y (n_187));
  AOI22X1 g18605(.A0 (\balance_db[1] [5]), .A1 (n_134), .B0
       (\balance_db[9] [5]), .B1 (n_133), .Y (n_186));
  AOI22X1 g18606(.A0 (\balance_db[1] [1]), .A1 (n_134), .B0
       (\balance_db[9] [1]), .B1 (n_133), .Y (n_185));
  AOI22X1 g18607(.A0 (\balance_db[6] [1]), .A1 (n_134), .B0
       (\balance_db[14] [1]), .B1 (id_to_check[3]), .Y (n_184));
  AOI22X1 g18608(.A0 (\balance_db[0] [5]), .A1 (n_134), .B0
       (\balance_db[8] [5]), .B1 (n_133), .Y (n_183));
  AOI22X1 g18609(.A0 (\balance_db[0] [2]), .A1 (n_134), .B0
       (\balance_db[8] [2]), .B1 (id_to_check[3]), .Y (n_182));
  AO22XL g18610(.A0 (\balance_db[6] [10]), .A1 (n_134), .B0
       (\balance_db[14] [10]), .B1 (id_to_check[3]), .Y (n_181));
  AO22XL g18611(.A0 (\balance_db[14] [8]), .A1 (n_139), .B0
       (\balance_db[15] [8]), .B1 (id_to_check[0]), .Y (n_180));
  MX2X1 g18612(.A (\balance_db[12] [8]), .B (\balance_db[13] [8]), .S0
       (id_to_check[0]), .Y (n_179));
  MX2X1 g18613(.A (\balance_db[0] [3]), .B (\balance_db[1] [3]), .S0
       (id_to_check[0]), .Y (n_178));
  MX2X1 g18614(.A (\balance_db[2] [3]), .B (\balance_db[3] [3]), .S0
       (id_to_check[0]), .Y (n_177));
  CLKINVX1 g18615(.A (n_131), .Y (n_176));
  CLKINVX1 g18616(.A (n_175), .Y (n_174));
  CLKINVX1 g18617(.A (n_173), .Y (n_172));
  CLKINVX1 g18618(.A (n_171), .Y (n_170));
  NOR2X2 g18621(.A (n_7), .B (id_to_check[1]), .Y (n_175));
  OR2X2 g18622(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_173));
  NAND2BX2 g18623(.AN (id_to_check[2]), .B (id_to_check[1]), .Y
       (n_171));
  INVX1 g18624(.A (n_167), .Y (n_166));
  CLKINVX2 g18625(.A (n_165), .Y (n_164));
  CLKINVX1 g18626(.A (n_163), .Y (n_162));
  CLKINVX2 g18627(.A (n_161), .Y (n_160));
  NOR2XL g18628(.A (n_139), .B (n_133), .Y (n_168));
  CLKAND2X3 g18629(.A (n_139), .B (n_134), .Y (n_167));
  NAND2X2 g18630(.A (id_to_check[0]), .B (n_134), .Y (n_165));
  AND2X4 g18631(.A (n_139), .B (id_to_check[3]), .Y (n_163));
  NAND2X1 g18632(.A (id_to_check[0]), .B (id_to_check[3]), .Y (n_161));
  CLKINVX1 g18634(.A (id_to_check[2]), .Y (n_7));
  INVX8 g18655(.A (id_to_check[3]), .Y (n_134));
  INVX3 g18673(.A (n_134), .Y (n_133));
  INVX1 g18681(.A (\balance_db[4] [9]), .Y (n_141));
  INVX1 g18682(.A (\balance_db[11] [13]), .Y (n_140));
  CLKINVX8 g18683(.A (id_to_check[0]), .Y (n_139));
  NOR3BXL g2(.AN (n_417), .B (n_410), .C (n_409), .Y (n_132));
  NAND2BX2 g18684(.AN (n_7), .B (id_to_check[1]), .Y (n_131));
  SDFFQX1 \balance_db_reg[0][1] (.CK (clk), .D (n_5), .SI
       (\balance_db[0] [1]), .SE (n_55), .Q (\balance_db[0] [1]));
  SDFFQX1 \balance_db_reg[0][2] (.CK (clk), .D (n_26), .SI
       (\balance_db[0] [2]), .SE (n_55), .Q (\balance_db[0] [2]));
  SDFFQX1 \balance_db_reg[0][3] (.CK (clk), .D (n_65), .SI
       (\balance_db[0] [3]), .SE (n_55), .Q (\balance_db[0] [3]));
  SDFFQX1 \balance_db_reg[0][4] (.CK (clk), .D (n_52), .SI
       (\balance_db[0] [4]), .SE (n_55), .Q (\balance_db[0] [4]));
  SDFFQX1 \balance_db_reg[0][5] (.CK (clk), .D (n_63), .SI
       (\balance_db[0] [5]), .SE (n_55), .Q (\balance_db[0] [5]));
  SDFFQX1 \balance_db_reg[0][6] (.CK (clk), .D (n_61), .SI
       (\balance_db[0] [6]), .SE (n_55), .Q (\balance_db[0] [6]));
  SDFFQX1 \balance_db_reg[0][7] (.CK (clk), .D (n_80), .SI
       (\balance_db[0] [7]), .SE (n_55), .Q (\balance_db[0] [7]));
  SDFFQX1 \balance_db_reg[0][8] (.CK (clk), .D (n_25), .SI
       (\balance_db[0] [8]), .SE (n_55), .Q (\balance_db[0] [8]));
  SDFFQX1 \balance_db_reg[0][9] (.CK (clk), .D (n_429), .SI
       (\balance_db[0] [9]), .SE (n_55), .Q (\balance_db[0] [9]));
  SDFFQX1 \balance_db_reg[0][10] (.CK (clk), .D (n_42), .SI
       (\balance_db[0] [10]), .SE (n_55), .Q (\balance_db[0] [10]));
  SDFFQX1 \balance_db_reg[0][11] (.CK (clk), .D (n_81), .SI
       (\balance_db[0] [11]), .SE (n_55), .Q (\balance_db[0] [11]));
  SDFFQX1 \balance_db_reg[0][12] (.CK (clk), .D (n_49), .SI
       (\balance_db[0] [12]), .SE (n_55), .Q (\balance_db[0] [12]));
  SDFFQX1 \balance_db_reg[0][13] (.CK (clk), .D (n_79), .SI
       (\balance_db[0] [13]), .SE (n_55), .Q (\balance_db[0] [13]));
  SDFFQX1 \balance_db_reg[0][14] (.CK (clk), .D (n_58), .SI
       (\balance_db[0] [14]), .SE (n_55), .Q (\balance_db[0] [14]));
  SDFFQX1 \balance_db_reg[0][15] (.CK (clk), .D (n_85), .SI
       (\balance_db[0] [15]), .SE (n_55), .Q (\balance_db[0] [15]));
  DFFQX1 \balance_db_reg[1][1] (.CK (clk), .D (n_114), .Q
       (\balance_db[1] [1]));
  DFFQX1 \balance_db_reg[1][2] (.CK (clk), .D (n_125), .Q
       (\balance_db[1] [2]));
  DFFQX1 \balance_db_reg[1][3] (.CK (clk), .D (n_113), .Q
       (\balance_db[1] [3]));
  DFFQX1 \balance_db_reg[1][4] (.CK (clk), .D (n_112), .Q
       (\balance_db[1] [4]));
  DFFQX1 \balance_db_reg[1][5] (.CK (clk), .D (n_427), .Q
       (\balance_db[1] [5]));
  DFFQX1 \balance_db_reg[1][6] (.CK (clk), .D (n_126), .Q
       (\balance_db[1] [6]));
  DFFQX1 \balance_db_reg[1][7] (.CK (clk), .D (n_111), .Q
       (\balance_db[1] [7]));
  DFFQX1 \balance_db_reg[1][8] (.CK (clk), .D (n_110), .Q
       (\balance_db[1] [8]));
  DFFQX1 \balance_db_reg[1][9] (.CK (clk), .D (n_109), .Q
       (\balance_db[1] [9]));
  DFFQX1 \balance_db_reg[1][10] (.CK (clk), .D (n_108), .Q
       (\balance_db[1] [10]));
  DFFQX1 \balance_db_reg[1][11] (.CK (clk), .D (n_107), .Q
       (\balance_db[1] [11]));
  DFFQX1 \balance_db_reg[1][12] (.CK (clk), .D (n_106), .Q
       (\balance_db[1] [12]));
  DFFQX1 \balance_db_reg[1][13] (.CK (clk), .D (n_105), .Q
       (\balance_db[1] [13]));
  DFFQX1 \balance_db_reg[1][14] (.CK (clk), .D (n_127), .Q
       (\balance_db[1] [14]));
  DFFQX1 \balance_db_reg[1][15] (.CK (clk), .D (n_129), .Q
       (\balance_db[1] [15]));
  DFFQX1 \balance_db_reg[2][1] (.CK (clk), .D (n_103), .Q
       (\balance_db[2] [1]));
  DFFQX1 \balance_db_reg[2][2] (.CK (clk), .D (n_434), .Q
       (\balance_db[2] [2]));
  DFFQX1 \balance_db_reg[2][3] (.CK (clk), .D (n_102), .Q
       (\balance_db[2] [3]));
  DFFQX1 \balance_db_reg[2][4] (.CK (clk), .D (n_101), .Q
       (\balance_db[2] [4]));
  DFFQX1 \balance_db_reg[2][5] (.CK (clk), .D (n_100), .Q
       (\balance_db[2] [5]));
  DFFQX1 \balance_db_reg[2][6] (.CK (clk), .D (n_99), .Q
       (\balance_db[2] [6]));
  DFFQX1 \balance_db_reg[2][7] (.CK (clk), .D (n_98), .Q
       (\balance_db[2] [7]));
  DFFQX1 \balance_db_reg[2][8] (.CK (clk), .D (n_97), .Q
       (\balance_db[2] [8]));
  DFFQX1 \balance_db_reg[2][9] (.CK (clk), .D (n_96), .Q
       (\balance_db[2] [9]));
  DFFQX1 \balance_db_reg[2][10] (.CK (clk), .D (n_95), .Q
       (\balance_db[2] [10]));
  DFFQX1 \balance_db_reg[2][11] (.CK (clk), .D (n_94), .Q
       (\balance_db[2] [11]));
  DFFQX1 \balance_db_reg[2][12] (.CK (clk), .D (n_93), .Q
       (\balance_db[2] [12]));
  DFFQX1 \balance_db_reg[2][13] (.CK (clk), .D (n_92), .Q
       (\balance_db[2] [13]));
  DFFQX1 \balance_db_reg[2][14] (.CK (clk), .D (n_121), .Q
       (\balance_db[2] [14]));
  DFFQX1 \balance_db_reg[2][15] (.CK (clk), .D (n_128), .Q
       (\balance_db[2] [15]));
  DFFQX1 \balance_db_reg[3][1] (.CK (clk), .D (n_120), .Q
       (\balance_db[3] [1]));
  DFFQX1 \balance_db_reg[3][2] (.CK (clk), .D (n_123), .Q
       (\balance_db[3] [2]));
  DFFQX1 \balance_db_reg[3][3] (.CK (clk), .D (n_91), .Q
       (\balance_db[3] [3]));
  DFFQX1 \balance_db_reg[3][4] (.CK (clk), .D (n_124), .Q
       (\balance_db[3] [4]));
  DFFQX1 \balance_db_reg[3][5] (.CK (clk), .D (n_90), .Q
       (\balance_db[3] [5]));
  DFFQX1 \balance_db_reg[3][6] (.CK (clk), .D (n_119), .Q
       (\balance_db[3] [6]));
  DFFQX1 \balance_db_reg[3][7] (.CK (clk), .D (n_89), .Q
       (\balance_db[3] [7]));
  DFFQX1 \balance_db_reg[3][8] (.CK (clk), .D (n_118), .Q
       (\balance_db[3] [8]));
  DFFQX1 \balance_db_reg[3][9] (.CK (clk), .D (n_88), .Q
       (\balance_db[3] [9]));
  DFFQX1 \balance_db_reg[3][10] (.CK (clk), .D (n_117), .Q
       (\balance_db[3] [10]));
  DFFQX1 \balance_db_reg[3][11] (.CK (clk), .D (n_87), .Q
       (\balance_db[3] [11]));
  DFFQX1 \balance_db_reg[3][12] (.CK (clk), .D (n_116), .Q
       (\balance_db[3] [12]));
  DFFQX1 \balance_db_reg[3][13] (.CK (clk), .D (n_86), .Q
       (\balance_db[3] [13]));
  DFFQX1 \balance_db_reg[3][14] (.CK (clk), .D (n_115), .Q
       (\balance_db[3] [14]));
  DFFQX1 \balance_db_reg[3][15] (.CK (clk), .D (n_130), .Q
       (\balance_db[3] [15]));
  SDFFQX1 \balance_db_reg[4][1] (.CK (clk), .D (\balance_db[4] [1]),
       .SI (n_5), .SE (n_48), .Q (\balance_db[4] [1]));
  SDFFQX1 \balance_db_reg[4][2] (.CK (clk), .D (\balance_db[4] [2]),
       .SI (n_26), .SE (n_48), .Q (\balance_db[4] [2]));
  SDFFQX1 \balance_db_reg[4][3] (.CK (clk), .D (\balance_db[4] [3]),
       .SI (n_65), .SE (n_48), .Q (\balance_db[4] [3]));
  SDFFQX1 \balance_db_reg[4][4] (.CK (clk), .D (\balance_db[4] [4]),
       .SI (n_52), .SE (n_48), .Q (\balance_db[4] [4]));
  SDFFQX1 \balance_db_reg[4][5] (.CK (clk), .D (\balance_db[4] [5]),
       .SI (n_63), .SE (n_48), .Q (\balance_db[4] [5]));
  SDFFQX1 \balance_db_reg[4][6] (.CK (clk), .D (\balance_db[4] [6]),
       .SI (n_61), .SE (n_48), .Q (\balance_db[4] [6]));
  SDFFQX1 \balance_db_reg[4][7] (.CK (clk), .D (\balance_db[4] [7]),
       .SI (n_80), .SE (n_48), .Q (\balance_db[4] [7]));
  SDFFQX1 \balance_db_reg[4][8] (.CK (clk), .D (\balance_db[4] [8]),
       .SI (n_25), .SE (n_48), .Q (\balance_db[4] [8]));
  SDFFQX1 \balance_db_reg[4][9] (.CK (clk), .D (\balance_db[4] [9]),
       .SI (n_429), .SE (n_48), .Q (\balance_db[4] [9]));
  SDFFQX1 \balance_db_reg[4][10] (.CK (clk), .D (\balance_db[4] [10]),
       .SI (n_42), .SE (n_48), .Q (\balance_db[4] [10]));
  SDFFQX1 \balance_db_reg[4][11] (.CK (clk), .D (\balance_db[4] [11]),
       .SI (n_81), .SE (n_48), .Q (\balance_db[4] [11]));
  SDFFQX1 \balance_db_reg[4][12] (.CK (clk), .D (\balance_db[4] [12]),
       .SI (n_49), .SE (n_48), .Q (\balance_db[4] [12]));
  SDFFQX1 \balance_db_reg[4][13] (.CK (clk), .D (\balance_db[4] [13]),
       .SI (n_79), .SE (n_48), .Q (\balance_db[4] [13]));
  SDFFQX1 \balance_db_reg[4][14] (.CK (clk), .D (\balance_db[4] [14]),
       .SI (n_58), .SE (n_48), .Q (\balance_db[4] [14]));
  SDFFQX1 \balance_db_reg[4][15] (.CK (clk), .D (\balance_db[4] [15]),
       .SI (n_85), .SE (n_48), .Q (\balance_db[4] [15]));
  SDFFQX1 \balance_db_reg[5][1] (.CK (clk), .D (\balance_db[5] [1]),
       .SI (n_5), .SE (n_39), .Q (\balance_db[5] [1]));
  SDFFQX1 \balance_db_reg[5][2] (.CK (clk), .D (\balance_db[5] [2]),
       .SI (n_26), .SE (n_39), .Q (\balance_db[5] [2]));
  SDFFQX1 \balance_db_reg[5][3] (.CK (clk), .D (\balance_db[5] [3]),
       .SI (n_65), .SE (n_39), .Q (\balance_db[5] [3]));
  SDFFQX1 \balance_db_reg[5][4] (.CK (clk), .D (\balance_db[5] [4]),
       .SI (n_52), .SE (n_39), .Q (\balance_db[5] [4]));
  SDFFQX1 \balance_db_reg[5][5] (.CK (clk), .D (\balance_db[5] [5]),
       .SI (n_63), .SE (n_39), .Q (\balance_db[5] [5]));
  SDFFQX1 \balance_db_reg[5][6] (.CK (clk), .D (\balance_db[5] [6]),
       .SI (n_61), .SE (n_39), .Q (\balance_db[5] [6]));
  SDFFQX1 \balance_db_reg[5][7] (.CK (clk), .D (\balance_db[5] [7]),
       .SI (n_80), .SE (n_39), .Q (\balance_db[5] [7]));
  SDFFQX1 \balance_db_reg[5][8] (.CK (clk), .D (\balance_db[5] [8]),
       .SI (n_25), .SE (n_39), .Q (\balance_db[5] [8]));
  SDFFQX1 \balance_db_reg[5][9] (.CK (clk), .D (\balance_db[5] [9]),
       .SI (n_429), .SE (n_39), .Q (\balance_db[5] [9]));
  SDFFQX1 \balance_db_reg[5][10] (.CK (clk), .D (\balance_db[5] [10]),
       .SI (n_42), .SE (n_39), .Q (\balance_db[5] [10]));
  SDFFQX1 \balance_db_reg[5][11] (.CK (clk), .D (\balance_db[5] [11]),
       .SI (n_81), .SE (n_39), .Q (\balance_db[5] [11]));
  SDFFQX1 \balance_db_reg[5][12] (.CK (clk), .D (\balance_db[5] [12]),
       .SI (n_49), .SE (n_39), .Q (\balance_db[5] [12]));
  SDFFQX1 \balance_db_reg[5][13] (.CK (clk), .D (\balance_db[5] [13]),
       .SI (n_79), .SE (n_39), .Q (\balance_db[5] [13]));
  SDFFQX1 \balance_db_reg[5][14] (.CK (clk), .D (\balance_db[5] [14]),
       .SI (n_58), .SE (n_39), .Q (\balance_db[5] [14]));
  SDFFQX1 \balance_db_reg[5][15] (.CK (clk), .D (\balance_db[5] [15]),
       .SI (n_85), .SE (n_39), .Q (\balance_db[5] [15]));
  SDFFQX1 \balance_db_reg[6][1] (.CK (clk), .D (\balance_db[6] [1]),
       .SI (n_5), .SE (n_2), .Q (\balance_db[6] [1]));
  SDFFQX1 \balance_db_reg[6][2] (.CK (clk), .D (\balance_db[6] [2]),
       .SI (n_26), .SE (n_2), .Q (\balance_db[6] [2]));
  SDFFQX1 \balance_db_reg[6][3] (.CK (clk), .D (\balance_db[6] [3]),
       .SI (n_65), .SE (n_2), .Q (\balance_db[6] [3]));
  SDFFQX1 \balance_db_reg[6][4] (.CK (clk), .D (\balance_db[6] [4]),
       .SI (n_52), .SE (n_2), .Q (\balance_db[6] [4]));
  SDFFQX1 \balance_db_reg[6][5] (.CK (clk), .D (\balance_db[6] [5]),
       .SI (n_63), .SE (n_2), .Q (\balance_db[6] [5]));
  SDFFQX1 \balance_db_reg[6][6] (.CK (clk), .D (\balance_db[6] [6]),
       .SI (n_61), .SE (n_2), .Q (\balance_db[6] [6]));
  SDFFQX1 \balance_db_reg[6][7] (.CK (clk), .D (\balance_db[6] [7]),
       .SI (n_80), .SE (n_2), .Q (\balance_db[6] [7]));
  SDFFQX1 \balance_db_reg[6][8] (.CK (clk), .D (\balance_db[6] [8]),
       .SI (n_25), .SE (n_2), .Q (\balance_db[6] [8]));
  SDFFQX1 \balance_db_reg[6][9] (.CK (clk), .D (\balance_db[6] [9]),
       .SI (n_429), .SE (n_2), .Q (\balance_db[6] [9]));
  SDFFQX1 \balance_db_reg[6][10] (.CK (clk), .D (\balance_db[6] [10]),
       .SI (n_42), .SE (n_2), .Q (\balance_db[6] [10]));
  SDFFQX1 \balance_db_reg[6][11] (.CK (clk), .D (\balance_db[6] [11]),
       .SI (n_81), .SE (n_2), .Q (\balance_db[6] [11]));
  SDFFQX1 \balance_db_reg[6][12] (.CK (clk), .D (\balance_db[6] [12]),
       .SI (n_49), .SE (n_2), .Q (\balance_db[6] [12]));
  SDFFQX1 \balance_db_reg[6][13] (.CK (clk), .D (\balance_db[6] [13]),
       .SI (n_79), .SE (n_2), .Q (\balance_db[6] [13]));
  SDFFQX1 \balance_db_reg[6][14] (.CK (clk), .D (\balance_db[6] [14]),
       .SI (n_58), .SE (n_2), .Q (\balance_db[6] [14]));
  SDFFQX1 \balance_db_reg[6][15] (.CK (clk), .D (\balance_db[6] [15]),
       .SI (n_85), .SE (n_2), .Q (\balance_db[6] [15]));
  SDFFQX1 \balance_db_reg[7][1] (.CK (clk), .D (\balance_db[7] [1]),
       .SI (n_5), .SE (n_36), .Q (\balance_db[7] [1]));
  SDFFQX1 \balance_db_reg[7][2] (.CK (clk), .D (\balance_db[7] [2]),
       .SI (n_26), .SE (n_36), .Q (\balance_db[7] [2]));
  SDFFQX1 \balance_db_reg[7][3] (.CK (clk), .D (\balance_db[7] [3]),
       .SI (n_65), .SE (n_36), .Q (\balance_db[7] [3]));
  SDFFQX1 \balance_db_reg[7][4] (.CK (clk), .D (\balance_db[7] [4]),
       .SI (n_52), .SE (n_36), .Q (\balance_db[7] [4]));
  SDFFQX1 \balance_db_reg[7][5] (.CK (clk), .D (\balance_db[7] [5]),
       .SI (n_63), .SE (n_36), .Q (\balance_db[7] [5]));
  SDFFQX1 \balance_db_reg[7][6] (.CK (clk), .D (\balance_db[7] [6]),
       .SI (n_61), .SE (n_36), .Q (\balance_db[7] [6]));
  SDFFQX1 \balance_db_reg[7][7] (.CK (clk), .D (\balance_db[7] [7]),
       .SI (n_80), .SE (n_36), .Q (\balance_db[7] [7]));
  SDFFQX1 \balance_db_reg[7][8] (.CK (clk), .D (\balance_db[7] [8]),
       .SI (n_25), .SE (n_36), .Q (\balance_db[7] [8]));
  SDFFQX1 \balance_db_reg[7][9] (.CK (clk), .D (\balance_db[7] [9]),
       .SI (n_429), .SE (n_36), .Q (\balance_db[7] [9]));
  SDFFQX1 \balance_db_reg[7][10] (.CK (clk), .D (\balance_db[7] [10]),
       .SI (n_42), .SE (n_36), .Q (\balance_db[7] [10]));
  SDFFQX1 \balance_db_reg[7][11] (.CK (clk), .D (\balance_db[7] [11]),
       .SI (n_81), .SE (n_36), .Q (\balance_db[7] [11]));
  SDFFQX1 \balance_db_reg[7][12] (.CK (clk), .D (\balance_db[7] [12]),
       .SI (n_49), .SE (n_36), .Q (\balance_db[7] [12]));
  SDFFQX1 \balance_db_reg[7][13] (.CK (clk), .D (\balance_db[7] [13]),
       .SI (n_79), .SE (n_36), .Q (\balance_db[7] [13]));
  SDFFQX1 \balance_db_reg[7][14] (.CK (clk), .D (\balance_db[7] [14]),
       .SI (n_58), .SE (n_36), .Q (\balance_db[7] [14]));
  SDFFQX1 \balance_db_reg[7][15] (.CK (clk), .D (\balance_db[7] [15]),
       .SI (n_85), .SE (n_36), .Q (\balance_db[7] [15]));
  SDFFQX1 \balance_db_reg[8][1] (.CK (clk), .D (\balance_db[8] [1]),
       .SI (n_5), .SE (n_57), .Q (\balance_db[8] [1]));
  SDFFQX1 \balance_db_reg[8][2] (.CK (clk), .D (\balance_db[8] [2]),
       .SI (n_26), .SE (n_57), .Q (\balance_db[8] [2]));
  SDFFQX1 \balance_db_reg[8][3] (.CK (clk), .D (\balance_db[8] [3]),
       .SI (n_65), .SE (n_57), .Q (\balance_db[8] [3]));
  SDFFQX1 \balance_db_reg[8][4] (.CK (clk), .D (\balance_db[8] [4]),
       .SI (n_52), .SE (n_57), .Q (\balance_db[8] [4]));
  SDFFQX1 \balance_db_reg[8][5] (.CK (clk), .D (\balance_db[8] [5]),
       .SI (n_63), .SE (n_57), .Q (\balance_db[8] [5]));
  SDFFQX1 \balance_db_reg[8][6] (.CK (clk), .D (\balance_db[8] [6]),
       .SI (n_61), .SE (n_57), .Q (\balance_db[8] [6]));
  SDFFQX1 \balance_db_reg[8][7] (.CK (clk), .D (\balance_db[8] [7]),
       .SI (n_80), .SE (n_57), .Q (\balance_db[8] [7]));
  SDFFQX1 \balance_db_reg[8][8] (.CK (clk), .D (\balance_db[8] [8]),
       .SI (n_25), .SE (n_57), .Q (\balance_db[8] [8]));
  SDFFQX1 \balance_db_reg[8][9] (.CK (clk), .D (\balance_db[8] [9]),
       .SI (n_429), .SE (n_57), .Q (\balance_db[8] [9]));
  SDFFQX1 \balance_db_reg[8][10] (.CK (clk), .D (\balance_db[8] [10]),
       .SI (n_42), .SE (n_57), .Q (\balance_db[8] [10]));
  SDFFQX1 \balance_db_reg[8][11] (.CK (clk), .D (\balance_db[8] [11]),
       .SI (n_81), .SE (n_57), .Q (\balance_db[8] [11]));
  SDFFQX1 \balance_db_reg[8][12] (.CK (clk), .D (\balance_db[8] [12]),
       .SI (n_49), .SE (n_57), .Q (\balance_db[8] [12]));
  SDFFQX1 \balance_db_reg[8][13] (.CK (clk), .D (\balance_db[8] [13]),
       .SI (n_79), .SE (n_57), .Q (\balance_db[8] [13]));
  SDFFQX1 \balance_db_reg[8][14] (.CK (clk), .D (\balance_db[8] [14]),
       .SI (n_58), .SE (n_57), .Q (\balance_db[8] [14]));
  SDFFQX1 \balance_db_reg[8][15] (.CK (clk), .D (\balance_db[8] [15]),
       .SI (n_85), .SE (n_57), .Q (\balance_db[8] [15]));
  SDFFQX1 \balance_db_reg[9][1] (.CK (clk), .D (\balance_db[9] [1]),
       .SI (n_5), .SE (n_1), .Q (\balance_db[9] [1]));
  SDFFQX1 \balance_db_reg[9][2] (.CK (clk), .D (\balance_db[9] [2]),
       .SI (n_26), .SE (n_1), .Q (\balance_db[9] [2]));
  SDFFQX1 \balance_db_reg[9][3] (.CK (clk), .D (\balance_db[9] [3]),
       .SI (n_65), .SE (n_1), .Q (\balance_db[9] [3]));
  SDFFQX1 \balance_db_reg[9][4] (.CK (clk), .D (\balance_db[9] [4]),
       .SI (n_52), .SE (n_1), .Q (\balance_db[9] [4]));
  SDFFQX1 \balance_db_reg[9][5] (.CK (clk), .D (\balance_db[9] [5]),
       .SI (n_63), .SE (n_1), .Q (\balance_db[9] [5]));
  SDFFQX1 \balance_db_reg[9][6] (.CK (clk), .D (\balance_db[9] [6]),
       .SI (n_61), .SE (n_1), .Q (\balance_db[9] [6]));
  SDFFQX1 \balance_db_reg[9][7] (.CK (clk), .D (\balance_db[9] [7]),
       .SI (n_80), .SE (n_1), .Q (\balance_db[9] [7]));
  SDFFQX1 \balance_db_reg[9][8] (.CK (clk), .D (\balance_db[9] [8]),
       .SI (n_25), .SE (n_1), .Q (\balance_db[9] [8]));
  SDFFQX1 \balance_db_reg[9][9] (.CK (clk), .D (\balance_db[9] [9]),
       .SI (n_429), .SE (n_1), .Q (\balance_db[9] [9]));
  SDFFQX1 \balance_db_reg[9][10] (.CK (clk), .D (\balance_db[9] [10]),
       .SI (n_42), .SE (n_1), .Q (\balance_db[9] [10]));
  SDFFQX1 \balance_db_reg[9][11] (.CK (clk), .D (\balance_db[9] [11]),
       .SI (n_81), .SE (n_1), .Q (\balance_db[9] [11]));
  SDFFQX1 \balance_db_reg[9][12] (.CK (clk), .D (\balance_db[9] [12]),
       .SI (n_49), .SE (n_1), .Q (\balance_db[9] [12]));
  SDFFQX1 \balance_db_reg[9][13] (.CK (clk), .D (\balance_db[9] [13]),
       .SI (n_79), .SE (n_1), .Q (\balance_db[9] [13]));
  SDFFQX1 \balance_db_reg[9][14] (.CK (clk), .D (\balance_db[9] [14]),
       .SI (n_58), .SE (n_1), .Q (\balance_db[9] [14]));
  SDFFQX1 \balance_db_reg[9][15] (.CK (clk), .D (\balance_db[9] [15]),
       .SI (n_85), .SE (n_1), .Q (\balance_db[9] [15]));
  SDFFQX1 \balance_db_reg[10][1] (.CK (clk), .D (\balance_db[10] [1]),
       .SI (n_5), .SE (n_54), .Q (\balance_db[10] [1]));
  SDFFQX1 \balance_db_reg[10][2] (.CK (clk), .D (\balance_db[10] [2]),
       .SI (n_26), .SE (n_54), .Q (\balance_db[10] [2]));
  SDFFQX1 \balance_db_reg[10][3] (.CK (clk), .D (\balance_db[10] [3]),
       .SI (n_65), .SE (n_54), .Q (\balance_db[10] [3]));
  SDFFQX1 \balance_db_reg[10][4] (.CK (clk), .D (\balance_db[10] [4]),
       .SI (n_52), .SE (n_54), .Q (\balance_db[10] [4]));
  SDFFQX1 \balance_db_reg[10][5] (.CK (clk), .D (\balance_db[10] [5]),
       .SI (n_63), .SE (n_54), .Q (\balance_db[10] [5]));
  SDFFQX1 \balance_db_reg[10][6] (.CK (clk), .D (\balance_db[10] [6]),
       .SI (n_61), .SE (n_54), .Q (\balance_db[10] [6]));
  SDFFQX1 \balance_db_reg[10][7] (.CK (clk), .D (\balance_db[10] [7]),
       .SI (n_80), .SE (n_54), .Q (\balance_db[10] [7]));
  SDFFQX1 \balance_db_reg[10][8] (.CK (clk), .D (\balance_db[10] [8]),
       .SI (n_25), .SE (n_54), .Q (\balance_db[10] [8]));
  SDFFQX1 \balance_db_reg[10][9] (.CK (clk), .D (\balance_db[10] [9]),
       .SI (n_429), .SE (n_54), .Q (\balance_db[10] [9]));
  SDFFQX1 \balance_db_reg[10][10] (.CK (clk), .D (\balance_db[10]
       [10]), .SI (n_42), .SE (n_54), .Q (\balance_db[10] [10]));
  SDFFQX1 \balance_db_reg[10][11] (.CK (clk), .D (\balance_db[10]
       [11]), .SI (n_81), .SE (n_54), .Q (\balance_db[10] [11]));
  SDFFQX1 \balance_db_reg[10][12] (.CK (clk), .D (\balance_db[10]
       [12]), .SI (n_49), .SE (n_54), .Q (\balance_db[10] [12]));
  SDFFQX1 \balance_db_reg[10][13] (.CK (clk), .D (\balance_db[10]
       [13]), .SI (n_79), .SE (n_54), .Q (\balance_db[10] [13]));
  SDFFQX1 \balance_db_reg[10][14] (.CK (clk), .D (\balance_db[10]
       [14]), .SI (n_58), .SE (n_54), .Q (\balance_db[10] [14]));
  SDFFQX1 \balance_db_reg[10][15] (.CK (clk), .D (\balance_db[10]
       [15]), .SI (n_85), .SE (n_54), .Q (\balance_db[10] [15]));
  SDFFQX1 \balance_db_reg[11][1] (.CK (clk), .D (n_5), .SI
       (\balance_db[11] [1]), .SE (n_37), .Q (\balance_db[11] [1]));
  SDFFQX1 \balance_db_reg[11][2] (.CK (clk), .D (n_26), .SI
       (\balance_db[11] [2]), .SE (n_37), .Q (\balance_db[11] [2]));
  SDFFQX1 \balance_db_reg[11][3] (.CK (clk), .D (n_65), .SI
       (\balance_db[11] [3]), .SE (n_37), .Q (\balance_db[11] [3]));
  SDFFQX1 \balance_db_reg[11][4] (.CK (clk), .D (n_52), .SI
       (\balance_db[11] [4]), .SE (n_37), .Q (\balance_db[11] [4]));
  SDFFQX1 \balance_db_reg[11][5] (.CK (clk), .D (n_63), .SI
       (\balance_db[11] [5]), .SE (n_37), .Q (\balance_db[11] [5]));
  SDFFQX1 \balance_db_reg[11][6] (.CK (clk), .D (n_61), .SI
       (\balance_db[11] [6]), .SE (n_37), .Q (\balance_db[11] [6]));
  SDFFQX1 \balance_db_reg[11][7] (.CK (clk), .D (n_80), .SI
       (\balance_db[11] [7]), .SE (n_37), .Q (\balance_db[11] [7]));
  SDFFQX1 \balance_db_reg[11][8] (.CK (clk), .D (n_25), .SI
       (\balance_db[11] [8]), .SE (n_37), .Q (\balance_db[11] [8]));
  SDFFQX1 \balance_db_reg[11][9] (.CK (clk), .D (n_429), .SI
       (\balance_db[11] [9]), .SE (n_37), .Q (\balance_db[11] [9]));
  SDFFQX1 \balance_db_reg[11][10] (.CK (clk), .D (n_42), .SI
       (\balance_db[11] [10]), .SE (n_37), .Q (\balance_db[11] [10]));
  SDFFQX1 \balance_db_reg[11][11] (.CK (clk), .D (n_81), .SI
       (\balance_db[11] [11]), .SE (n_37), .Q (\balance_db[11] [11]));
  SDFFQX1 \balance_db_reg[11][12] (.CK (clk), .D (n_49), .SI
       (\balance_db[11] [12]), .SE (n_37), .Q (\balance_db[11] [12]));
  SDFFQX1 \balance_db_reg[11][13] (.CK (clk), .D (n_79), .SI
       (\balance_db[11] [13]), .SE (n_37), .Q (\balance_db[11] [13]));
  SDFFQX1 \balance_db_reg[11][14] (.CK (clk), .D (n_58), .SI
       (\balance_db[11] [14]), .SE (n_37), .Q (\balance_db[11] [14]));
  SDFFQX1 \balance_db_reg[11][15] (.CK (clk), .D (n_85), .SI
       (\balance_db[11] [15]), .SE (n_37), .Q (\balance_db[11] [15]));
  SDFFQX1 \balance_db_reg[12][1] (.CK (clk), .D (\balance_db[12] [1]),
       .SI (n_5), .SE (n_53), .Q (\balance_db[12] [1]));
  SDFFQX1 \balance_db_reg[12][2] (.CK (clk), .D (\balance_db[12] [2]),
       .SI (n_26), .SE (n_53), .Q (\balance_db[12] [2]));
  SDFFQX1 \balance_db_reg[12][3] (.CK (clk), .D (\balance_db[12] [3]),
       .SI (n_65), .SE (n_53), .Q (\balance_db[12] [3]));
  SDFFQX1 \balance_db_reg[12][4] (.CK (clk), .D (\balance_db[12] [4]),
       .SI (n_52), .SE (n_53), .Q (\balance_db[12] [4]));
  SDFFQX1 \balance_db_reg[12][5] (.CK (clk), .D (\balance_db[12] [5]),
       .SI (n_63), .SE (n_53), .Q (\balance_db[12] [5]));
  SDFFQX1 \balance_db_reg[12][6] (.CK (clk), .D (\balance_db[12] [6]),
       .SI (n_61), .SE (n_53), .Q (\balance_db[12] [6]));
  SDFFQX1 \balance_db_reg[12][7] (.CK (clk), .D (\balance_db[12] [7]),
       .SI (n_80), .SE (n_53), .Q (\balance_db[12] [7]));
  SDFFQX1 \balance_db_reg[12][8] (.CK (clk), .D (\balance_db[12] [8]),
       .SI (n_25), .SE (n_53), .Q (\balance_db[12] [8]));
  SDFFQX1 \balance_db_reg[12][9] (.CK (clk), .D (\balance_db[12] [9]),
       .SI (n_429), .SE (n_53), .Q (\balance_db[12] [9]));
  SDFFQX1 \balance_db_reg[12][10] (.CK (clk), .D (\balance_db[12]
       [10]), .SI (n_42), .SE (n_53), .Q (\balance_db[12] [10]));
  SDFFQX1 \balance_db_reg[12][11] (.CK (clk), .D (\balance_db[12]
       [11]), .SI (n_81), .SE (n_53), .Q (\balance_db[12] [11]));
  SDFFQX1 \balance_db_reg[12][12] (.CK (clk), .D (\balance_db[12]
       [12]), .SI (n_49), .SE (n_53), .Q (\balance_db[12] [12]));
  SDFFQX1 \balance_db_reg[12][13] (.CK (clk), .D (\balance_db[12]
       [13]), .SI (n_79), .SE (n_53), .Q (\balance_db[12] [13]));
  SDFFQX1 \balance_db_reg[12][14] (.CK (clk), .D (\balance_db[12]
       [14]), .SI (n_58), .SE (n_53), .Q (\balance_db[12] [14]));
  SDFFQX1 \balance_db_reg[12][15] (.CK (clk), .D (\balance_db[12]
       [15]), .SI (n_85), .SE (n_53), .Q (\balance_db[12] [15]));
  SDFFQX1 \balance_db_reg[13][1] (.CK (clk), .D (n_5), .SI
       (\balance_db[13] [1]), .SE (n_38), .Q (\balance_db[13] [1]));
  SDFFQX1 \balance_db_reg[13][2] (.CK (clk), .D (n_26), .SI
       (\balance_db[13] [2]), .SE (n_38), .Q (\balance_db[13] [2]));
  SDFFQX1 \balance_db_reg[13][3] (.CK (clk), .D (n_65), .SI
       (\balance_db[13] [3]), .SE (n_38), .Q (\balance_db[13] [3]));
  SDFFQX1 \balance_db_reg[13][4] (.CK (clk), .D (n_52), .SI
       (\balance_db[13] [4]), .SE (n_38), .Q (\balance_db[13] [4]));
  SDFFQX1 \balance_db_reg[13][5] (.CK (clk), .D (n_63), .SI
       (\balance_db[13] [5]), .SE (n_38), .Q (\balance_db[13] [5]));
  SDFFQX1 \balance_db_reg[13][6] (.CK (clk), .D (n_61), .SI
       (\balance_db[13] [6]), .SE (n_38), .Q (\balance_db[13] [6]));
  SDFFQX1 \balance_db_reg[13][7] (.CK (clk), .D (n_80), .SI
       (\balance_db[13] [7]), .SE (n_38), .Q (\balance_db[13] [7]));
  SDFFQX1 \balance_db_reg[13][8] (.CK (clk), .D (n_25), .SI
       (\balance_db[13] [8]), .SE (n_38), .Q (\balance_db[13] [8]));
  SDFFQX1 \balance_db_reg[13][9] (.CK (clk), .D (n_429), .SI
       (\balance_db[13] [9]), .SE (n_38), .Q (\balance_db[13] [9]));
  SDFFQX1 \balance_db_reg[13][10] (.CK (clk), .D (n_42), .SI
       (\balance_db[13] [10]), .SE (n_38), .Q (\balance_db[13] [10]));
  SDFFQX1 \balance_db_reg[13][11] (.CK (clk), .D (n_81), .SI
       (\balance_db[13] [11]), .SE (n_38), .Q (\balance_db[13] [11]));
  SDFFQX1 \balance_db_reg[13][12] (.CK (clk), .D (n_49), .SI
       (\balance_db[13] [12]), .SE (n_38), .Q (\balance_db[13] [12]));
  SDFFQX1 \balance_db_reg[13][13] (.CK (clk), .D (n_79), .SI
       (\balance_db[13] [13]), .SE (n_38), .Q (\balance_db[13] [13]));
  SDFFQX1 \balance_db_reg[13][14] (.CK (clk), .D (n_58), .SI
       (\balance_db[13] [14]), .SE (n_38), .Q (\balance_db[13] [14]));
  SDFFQX1 \balance_db_reg[13][15] (.CK (clk), .D (n_85), .SI
       (\balance_db[13] [15]), .SE (n_38), .Q (\balance_db[13] [15]));
  SDFFQX1 \balance_db_reg[14][1] (.CK (clk), .D (\balance_db[14] [1]),
       .SI (n_5), .SE (n_56), .Q (\balance_db[14] [1]));
  SDFFQX1 \balance_db_reg[14][2] (.CK (clk), .D (\balance_db[14] [2]),
       .SI (n_26), .SE (n_56), .Q (\balance_db[14] [2]));
  SDFFQX1 \balance_db_reg[14][3] (.CK (clk), .D (\balance_db[14] [3]),
       .SI (n_65), .SE (n_56), .Q (\balance_db[14] [3]));
  SDFFQX1 \balance_db_reg[14][4] (.CK (clk), .D (\balance_db[14] [4]),
       .SI (n_52), .SE (n_56), .Q (\balance_db[14] [4]));
  SDFFQX1 \balance_db_reg[14][5] (.CK (clk), .D (\balance_db[14] [5]),
       .SI (n_63), .SE (n_56), .Q (\balance_db[14] [5]));
  SDFFQX1 \balance_db_reg[14][6] (.CK (clk), .D (\balance_db[14] [6]),
       .SI (n_61), .SE (n_56), .Q (\balance_db[14] [6]));
  SDFFQX1 \balance_db_reg[14][7] (.CK (clk), .D (\balance_db[14] [7]),
       .SI (n_80), .SE (n_56), .Q (\balance_db[14] [7]));
  SDFFQX1 \balance_db_reg[14][8] (.CK (clk), .D (\balance_db[14] [8]),
       .SI (n_25), .SE (n_56), .Q (\balance_db[14] [8]));
  SDFFQX1 \balance_db_reg[14][9] (.CK (clk), .D (\balance_db[14] [9]),
       .SI (n_429), .SE (n_56), .Q (\balance_db[14] [9]));
  SDFFQX1 \balance_db_reg[14][10] (.CK (clk), .D (\balance_db[14]
       [10]), .SI (n_42), .SE (n_56), .Q (\balance_db[14] [10]));
  SDFFQX1 \balance_db_reg[14][11] (.CK (clk), .D (\balance_db[14]
       [11]), .SI (n_81), .SE (n_56), .Q (\balance_db[14] [11]));
  SDFFQX1 \balance_db_reg[14][12] (.CK (clk), .D (\balance_db[14]
       [12]), .SI (n_49), .SE (n_56), .Q (\balance_db[14] [12]));
  SDFFQX1 \balance_db_reg[14][13] (.CK (clk), .D (\balance_db[14]
       [13]), .SI (n_79), .SE (n_56), .Q (\balance_db[14] [13]));
  SDFFQX1 \balance_db_reg[14][14] (.CK (clk), .D (\balance_db[14]
       [14]), .SI (n_58), .SE (n_56), .Q (\balance_db[14] [14]));
  SDFFQX1 \balance_db_reg[14][15] (.CK (clk), .D (\balance_db[14]
       [15]), .SI (n_85), .SE (n_56), .Q (\balance_db[14] [15]));
  SDFFQX1 \balance_db_reg[15][1] (.CK (clk), .D (n_5), .SI
       (\balance_db[15] [1]), .SE (n_40), .Q (\balance_db[15] [1]));
  SDFFQX1 \balance_db_reg[15][2] (.CK (clk), .D (n_26), .SI
       (\balance_db[15] [2]), .SE (n_40), .Q (\balance_db[15] [2]));
  SDFFQX1 \balance_db_reg[15][3] (.CK (clk), .D (n_65), .SI
       (\balance_db[15] [3]), .SE (n_40), .Q (\balance_db[15] [3]));
  SDFFQX1 \balance_db_reg[15][4] (.CK (clk), .D (n_52), .SI
       (\balance_db[15] [4]), .SE (n_40), .Q (\balance_db[15] [4]));
  SDFFQX1 \balance_db_reg[15][5] (.CK (clk), .D (n_63), .SI
       (\balance_db[15] [5]), .SE (n_40), .Q (\balance_db[15] [5]));
  SDFFQX1 \balance_db_reg[15][6] (.CK (clk), .D (n_61), .SI
       (\balance_db[15] [6]), .SE (n_40), .Q (\balance_db[15] [6]));
  SDFFQX1 \balance_db_reg[15][7] (.CK (clk), .D (n_80), .SI
       (\balance_db[15] [7]), .SE (n_40), .Q (\balance_db[15] [7]));
  SDFFQX1 \balance_db_reg[15][8] (.CK (clk), .D (n_25), .SI
       (\balance_db[15] [8]), .SE (n_40), .Q (\balance_db[15] [8]));
  SDFFQX1 \balance_db_reg[15][9] (.CK (clk), .D (n_429), .SI
       (\balance_db[15] [9]), .SE (n_40), .Q (\balance_db[15] [9]));
  SDFFQX1 \balance_db_reg[15][10] (.CK (clk), .D (n_42), .SI
       (\balance_db[15] [10]), .SE (n_40), .Q (\balance_db[15] [10]));
  SDFFQX1 \balance_db_reg[15][11] (.CK (clk), .D (n_81), .SI
       (\balance_db[15] [11]), .SE (n_40), .Q (\balance_db[15] [11]));
  SDFFQX1 \balance_db_reg[15][12] (.CK (clk), .D (n_49), .SI
       (\balance_db[15] [12]), .SE (n_40), .Q (\balance_db[15] [12]));
  SDFFQX1 \balance_db_reg[15][13] (.CK (clk), .D (n_79), .SI
       (\balance_db[15] [13]), .SE (n_40), .Q (\balance_db[15] [13]));
  SDFFQX1 \balance_db_reg[15][14] (.CK (clk), .D (n_58), .SI
       (\balance_db[15] [14]), .SE (n_40), .Q (\balance_db[15] [14]));
  SDFFQX1 \balance_db_reg[15][15] (.CK (clk), .D (n_85), .SI
       (\balance_db[15] [15]), .SE (n_40), .Q (\balance_db[15] [15]));
  AO22XL g3333(.A0 (n_66), .A1 (n_85), .B0 (n_82), .B1
       (\balance_db[3] [15]), .Y (n_130));
  AO22X1 g3334(.A0 (n_69), .A1 (n_85), .B0 (n_83), .B1
       (\balance_db[1] [15]), .Y (n_129));
  AO22XL g3335(.A0 (n_68), .A1 (n_85), .B0 (n_4), .B1
       (\balance_db[2] [15]), .Y (n_128));
  AO22X1 g3422(.A0 (n_69), .A1 (n_58), .B0 (n_83), .B1
       (\balance_db[1] [14]), .Y (n_127));
  OAI211XL g3423(.A0 (n_70), .A1 (n_41), .B0 (n_6), .C0 (n_77), .Y
       (n_126));
  OAI211XL g3424(.A0 (n_70), .A1 (n_51), .B0 (n_6), .C0 (n_75), .Y
       (n_125));
  OAI211XL g3425(.A0 (n_71), .A1 (n_24), .B0 (n_6), .C0 (n_74), .Y
       (n_124));
  OAI211XL g3426(.A0 (n_71), .A1 (n_51), .B0 (n_6), .C0 (n_78), .Y
       (n_123));
  AO22XL g3428(.A0 (n_68), .A1 (n_58), .B0 (n_4), .B1
       (\balance_db[2] [14]), .Y (n_121));
  AO22XL g3429(.A0 (n_82), .A1 (\balance_db[3] [1]), .B0 (n_66), .B1
       (n_5), .Y (n_120));
  AO22XL g3430(.A0 (n_66), .A1 (n_61), .B0 (n_82), .B1
       (\balance_db[3] [6]), .Y (n_119));
  AO22XL g3431(.A0 (n_66), .A1 (n_25), .B0 (n_82), .B1
       (\balance_db[3] [8]), .Y (n_118));
  AO22XL g3432(.A0 (n_66), .A1 (n_42), .B0 (n_82), .B1
       (\balance_db[3] [10]), .Y (n_117));
  AO22XL g3433(.A0 (n_66), .A1 (n_49), .B0 (n_82), .B1
       (\balance_db[3] [12]), .Y (n_116));
  AO22XL g3434(.A0 (n_66), .A1 (n_58), .B0 (n_82), .B1
       (\balance_db[3] [14]), .Y (n_115));
  AO22XL g3435(.A0 (n_83), .A1 (\balance_db[1] [1]), .B0 (n_69), .B1
       (n_5), .Y (n_114));
  AO22XL g3436(.A0 (n_69), .A1 (n_65), .B0 (n_83), .B1
       (\balance_db[1] [3]), .Y (n_113));
  AO22XL g3437(.A0 (n_69), .A1 (n_52), .B0 (n_83), .B1
       (\balance_db[1] [4]), .Y (n_112));
  AO22XL g3438(.A0 (n_69), .A1 (n_80), .B0 (n_83), .B1
       (\balance_db[1] [7]), .Y (n_111));
  AO22XL g3439(.A0 (n_69), .A1 (n_25), .B0 (n_83), .B1
       (\balance_db[1] [8]), .Y (n_110));
  AO22XL g3440(.A0 (n_69), .A1 (n_429), .B0 (n_83), .B1
       (\balance_db[1] [9]), .Y (n_109));
  AO22XL g3441(.A0 (n_69), .A1 (n_42), .B0 (n_83), .B1
       (\balance_db[1] [10]), .Y (n_108));
  AO22XL g3442(.A0 (n_69), .A1 (n_81), .B0 (n_83), .B1
       (\balance_db[1] [11]), .Y (n_107));
  AO22XL g3443(.A0 (n_69), .A1 (n_49), .B0 (n_83), .B1
       (\balance_db[1] [12]), .Y (n_106));
  AO22XL g3444(.A0 (n_69), .A1 (n_79), .B0 (n_83), .B1
       (\balance_db[1] [13]), .Y (n_105));
  AO22XL g3446(.A0 (n_4), .A1 (\balance_db[2] [1]), .B0 (n_68), .B1
       (n_5), .Y (n_103));
  AO22XL g3447(.A0 (n_68), .A1 (n_65), .B0 (n_4), .B1
       (\balance_db[2] [3]), .Y (n_102));
  AO22XL g3448(.A0 (n_68), .A1 (n_52), .B0 (n_4), .B1
       (\balance_db[2] [4]), .Y (n_101));
  AO22XL g3449(.A0 (n_68), .A1 (n_63), .B0 (n_4), .B1
       (\balance_db[2] [5]), .Y (n_100));
  AO22XL g3450(.A0 (n_68), .A1 (n_61), .B0 (n_4), .B1
       (\balance_db[2] [6]), .Y (n_99));
  AO22XL g3451(.A0 (n_68), .A1 (n_80), .B0 (n_4), .B1
       (\balance_db[2] [7]), .Y (n_98));
  AO22XL g3452(.A0 (n_68), .A1 (n_25), .B0 (n_4), .B1
       (\balance_db[2] [8]), .Y (n_97));
  AO22XL g3453(.A0 (n_68), .A1 (n_429), .B0 (n_4), .B1
       (\balance_db[2] [9]), .Y (n_96));
  AO22XL g3454(.A0 (n_68), .A1 (n_42), .B0 (n_4), .B1
       (\balance_db[2] [10]), .Y (n_95));
  AO22XL g3455(.A0 (n_68), .A1 (n_81), .B0 (n_4), .B1
       (\balance_db[2] [11]), .Y (n_94));
  AO22XL g3456(.A0 (n_68), .A1 (n_49), .B0 (n_4), .B1
       (\balance_db[2] [12]), .Y (n_93));
  AO22XL g3457(.A0 (n_68), .A1 (n_79), .B0 (n_4), .B1
       (\balance_db[2] [13]), .Y (n_92));
  AO22XL g3458(.A0 (n_66), .A1 (n_65), .B0 (n_82), .B1
       (\balance_db[3] [3]), .Y (n_91));
  AO22XL g3459(.A0 (n_66), .A1 (n_63), .B0 (n_82), .B1
       (\balance_db[3] [5]), .Y (n_90));
  AO22XL g3460(.A0 (n_66), .A1 (n_80), .B0 (n_82), .B1
       (\balance_db[3] [7]), .Y (n_89));
  AO22XL g3461(.A0 (n_66), .A1 (n_429), .B0 (n_82), .B1
       (\balance_db[3] [9]), .Y (n_88));
  AO22XL g3462(.A0 (n_66), .A1 (n_81), .B0 (n_82), .B1
       (\balance_db[3] [11]), .Y (n_87));
  AO22XL g3463(.A0 (n_66), .A1 (n_79), .B0 (n_82), .B1
       (\balance_db[3] [13]), .Y (n_86));
  CLKXOR2X1 g3529(.A (n_410), .B (n_50), .Y (n_85));
  NAND2XL g3551(.A (\balance_db[3] [2]), .B (n_71), .Y (n_78));
  NAND2XL g3552(.A (\balance_db[1] [6]), .B (n_70), .Y (n_77));
  NAND2XL g3554(.A (\balance_db[1] [2]), .B (n_70), .Y (n_75));
  NAND2XL g3555(.A (\balance_db[3] [4]), .B (n_71), .Y (n_74));
  OAI21X1 g3567(.A0 (reset), .A1 (n_3), .B0 (n_13), .Y (n_83));
  OR2X1 g3568(.A (n_67), .B (n_14), .Y (n_82));
  CLKXOR2X1 g3570(.A (n_406), .B (n_32), .Y (n_81));
  CLKXOR2X1 g3571(.A (n_402), .B (n_34), .Y (n_80));
  CLKXOR2X1 g3572(.A (n_408), .B (n_33), .Y (n_79));
  NOR2XL g3574(.A (id_to_check[0]), .B (n_60), .Y (n_72));
  NAND2XL g3575(.A (id_to_check[0]), .B (n_59), .Y (n_71));
  NAND2XL g3576(.A (id_to_check[0]), .B (n_3), .Y (n_70));
  AND2X1 g3577(.A (n_11), .B (n_3), .Y (n_69));
  NOR2XL g3578(.A (n_13), .B (n_60), .Y (n_68));
  NOR2XL g3581(.A (reset), .B (n_59), .Y (n_67));
  AND2X1 g3582(.A (n_11), .B (n_59), .Y (n_66));
  CLKXOR2X1 g3583(.A (n_422), .B (n_19), .Y (n_65));
  CLKXOR2X1 g3585(.A (n_400), .B (n_17), .Y (n_63));
  CLKINVX1 g3586(.A (n_41), .Y (n_61));
  INVX1 g3587(.A (n_60), .Y (n_59));
  NAND2XL g3589(.A (id_to_check[1]), .B (n_43), .Y (n_60));
  AO21X1 g3590(.A0 (n_409), .A1 (n_35), .B0 (n_50), .Y (n_58));
  AND2X1 g3591(.A (n_46), .B (n_16), .Y (n_57));
  AND2X1 g3592(.A (n_47), .B (n_16), .Y (n_56));
  NAND2BX1 g3593(.AN (n_45), .B (n_412), .Y (n_55));
  AND2X1 g3594(.A (n_44), .B (n_16), .Y (n_54));
  AND3X1 g3595(.A (n_28), .B (id_to_check[2]), .C (n_16), .Y (n_53));
  CLKINVX1 g3596(.A (n_24), .Y (n_52));
  CLKINVX1 g3597(.A (n_26), .Y (n_51));
  NOR2XL g3598(.A (n_31), .B (n_7), .Y (n_47));
  NOR2BX1 g3599(.AN (n_28), .B (id_to_check[2]), .Y (n_46));
  NAND2XL g3600(.A (n_28), .B (n_22), .Y (n_45));
  NOR2XL g3601(.A (n_31), .B (id_to_check[2]), .Y (n_44));
  NOR2XL g3602(.A (n_409), .B (n_35), .Y (n_50));
  AO21X1 g3603(.A0 (n_407), .A1 (n_20), .B0 (n_33), .Y (n_49));
  AND2X1 g3605(.A (n_28), .B (n_29), .Y (n_48));
  NOR2XL g3607(.A (n_30), .B (n_411), .Y (n_43));
  AO21X1 g3608(.A0 (n_405), .A1 (n_428), .B0 (n_32), .Y (n_42));
  AOI21X1 g3609(.A0 (n_401), .A1 (n_15), .B0 (n_34), .Y (n_41));
  OR2X2 g3610(.A (n_27), .B (n_9), .Y (n_40));
  AND2X1 g3611(.A (n_23), .B (n_29), .Y (n_39));
  OR2X2 g3613(.A (n_27), .B (n_0), .Y (n_38));
  OR2X2 g3614(.A (n_27), .B (n_10), .Y (n_37));
  AND3X1 g3615(.A (n_11), .B (id_to_check[1]), .C (n_29), .Y (n_36));
  NAND2XL g3616(.A (n_22), .B (fsm_charge_req), .Y (n_30));
  NAND2BX1 g3617(.AN (n_20), .B (n_417), .Y (n_35));
  NOR2XL g3618(.A (n_401), .B (n_15), .Y (n_34));
  NOR2XL g3619(.A (n_407), .B (n_20), .Y (n_33));
  NOR2XL g3620(.A (n_405), .B (n_428), .Y (n_32));
  NAND2XL g3621(.A (n_14), .B (id_to_check[1]), .Y (n_31));
  NOR2XL g3624(.A (n_12), .B (id_to_check[1]), .Y (n_23));
  NOR3BX1 g3625(.AN (n_412), .B (id_to_check[3]), .C (n_7), .Y (n_29));
  NOR2XL g3626(.A (n_13), .B (id_to_check[1]), .Y (n_28));
  NAND2X1 g3627(.A (n_11), .B (n_16), .Y (n_27));
  AO21X1 g3628(.A0 (n_398), .A1 (n_413), .B0 (n_19), .Y (n_26));
  AO21X1 g3629(.A0 (n_403), .A1 (n_415), .B0 (n_18), .Y (n_25));
  AOI21X1 g3630(.A0 (n_399), .A1 (n_416), .B0 (n_17), .Y (n_24));
  NOR2XL g3631(.A (id_to_check[3]), .B (id_to_check[2]), .Y (n_22));
  NAND2BX1 g3633(.AN (n_415), .B (n_414), .Y (n_20));
  NOR2XL g3634(.A (n_398), .B (n_413), .Y (n_19));
  NOR2XL g3635(.A (n_403), .B (n_415), .Y (n_18));
  NOR2XL g3636(.A (n_399), .B (n_416), .Y (n_17));
  AND2X1 g3637(.A (id_to_check[3]), .B (n_412), .Y (n_16));
  CLKINVX1 g3638(.A (n_14), .Y (n_13));
  CLKINVX1 g3639(.A (n_12), .Y (n_11));
  NAND2XL g3641(.A (n_7), .B (id_to_check[1]), .Y (n_10));
  NAND2XL g3642(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_9));
  NOR2XL g3643(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_8));
  NAND2BX1 g3644(.AN (n_416), .B (n_419), .Y (n_15));
  NOR2XL g3645(.A (reset), .B (id_to_check[0]), .Y (n_14));
  NAND2XL g3646(.A (n_6), .B (id_to_check[0]), .Y (n_12));
  CLKINVX1 g3648(.A (reset), .Y (n_6));
  CLKINVX1 g3650(.A (n_413), .Y (n_5));
  NAND2BX1 g18685(.AN (n_67), .B (n_12), .Y (n_4));
  NOR2BX1 g3651(.AN (n_43), .B (id_to_check[1]), .Y (n_3));
  NOR2BX2 g3652(.AN (n_29), .B (n_31), .Y (n_2));
  NOR2BX2 g3653(.AN (n_8), .B (n_27), .Y (n_1));
  NAND2BX1 g3654(.AN (id_to_check[1]), .B (id_to_check[2]), .Y (n_0));
  NOR2BXL g18686(.AN (n_412), .B (reset), .Y (n_425));
  NAND2XL g18687(.A (n_426), .B (n_6), .Y (n_427));
  MXI2XL g3(.A (n_63), .B (\balance_db[1] [5]), .S0 (n_70), .Y (n_426));
  OR2XL g18688(.A (n_415), .B (n_393), .Y (n_428));
  XNOR2X1 g18689(.A (n_392), .B (n_18), .Y (n_429));
  AOI2BB1XL g18690(.A0N (n_171), .A1N (n_308), .B0 (n_288), .Y (n_430));
  AO22XL g18691(.A0 (\balance_db[9] [12]), .A1 (n_239), .B0
       (\balance_db[1] [12]), .B1 (n_243), .Y (n_431));
  AO22XL g18692(.A0 (\balance_db[8] [10]), .A1 (id_to_check[3]), .B0
       (\balance_db[0] [10]), .B1 (n_134), .Y (n_432));
  NAND2BX1 g18693(.AN (reset), .B (n_433), .Y (n_434));
  MXI2XL g18694(.A (\balance_db[2] [2]), .B (n_26), .S0 (n_72), .Y
       (n_433));
endmodule

module barrier_ctrl(clk, reset, fsm_open_en, fsm_close_en,
     barrier_open_cmd, barrier_close_cmd, gate_is_open, gate_is_closed);
  input clk, reset, fsm_open_en, fsm_close_en;
  output barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed;
  wire clk, reset, fsm_open_en, fsm_close_en;
  wire barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed;
  wire [2:0] barrier_position_counter;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_8, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_22, n_23, n_24, n_25, n_26, n_31, n_32, n_33;
  INVXL g223(.A (n_23), .Y (gate_is_closed));
  DFFQXL barrier_close_cmd_reg(.CK (clk), .D (n_19), .Q
       (barrier_close_cmd));
  DFFQXL barrier_open_cmd_reg(.CK (clk), .D (n_18), .Q
       (barrier_open_cmd));
  OAI21X1 g317(.A0 (n_25), .A1 (n_24), .B0 (n_15), .Y (n_19));
  INVXL g318(.A (n_17), .Y (n_18));
  AOI31X1 g319(.A0 (n_15), .A1 (fsm_open_en), .A2 (n_24), .B0 (n_25),
       .Y (n_17));
  NOR2XL g320(.A (reset), .B (n_22), .Y (n_25));
  NAND2XL g321(.A (n_16), .B (fsm_open_en), .Y (n_22));
  NAND3X1 g322(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .C (barrier_position_counter[2]),
       .Y (n_16));
  OR3X1 g323(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[2]), .C (barrier_position_counter[1]),
       .Y (n_23));
  CLKINVX1 g324(.A (fsm_close_en), .Y (n_24));
  INVXL g325(.A (barrier_position_counter[0]), .Y (n_26));
  INVX1 g326(.A (reset), .Y (n_15));
  DFFQX1 \barrier_position_counter_reg[2] (.CK (clk), .D (n_14), .Q
       (barrier_position_counter[2]));
  DFFQX1 \barrier_position_counter_reg[1] (.CK (clk), .D (n_12), .Q
       (barrier_position_counter[1]));
  MXI2XL g464(.A (n_31), .B (n_32), .S0 (barrier_position_counter[2]),
       .Y (n_14));
  DFFQX1 \barrier_position_counter_reg[0] (.CK (clk), .D (n_13), .Q
       (barrier_position_counter[0]));
  OAI2BB1XL g466(.A0N (n_33), .A1N (barrier_position_counter[0]), .B0
       (n_11), .Y (n_13));
  OAI2BB1X1 g467(.A0N (n_33), .A1N (barrier_position_counter[1]), .B0
       (n_8), .Y (n_12));
  OAI21XL g468(.A0 (n_25), .A1 (n_5), .B0 (n_26), .Y (n_11));
  MXI2XL g471(.A (n_25), .B (n_5), .S0 (n_4), .Y (n_8));
  NOR2BX1 g472(.AN (n_5), .B (n_1), .Y (n_7));
  NOR4BX1 g474(.AN (n_23), .B (reset), .C (n_24), .D (n_0), .Y (n_5));
  NAND2BX1 g475(.AN (n_1), .B (n_2), .Y (n_4));
  NAND2XL g477(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_2));
  NOR2XL g478(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_1));
  INVX1 g479(.A (n_22), .Y (n_0));
  NAND2BX1 g2(.AN (n_2), .B (n_25), .Y (n_31));
  NOR3XL g480(.A (n_25), .B (n_33), .C (n_7), .Y (n_32));
  NOR3X1 g481(.A (fsm_close_en), .B (reset), .C (n_0), .Y (n_33));
endmodule

module vehicle_interface(clk, reset, fsm_read_en, vehicle_id_in,
     id_to_check, id_valid);
  input clk, reset, fsm_read_en;
  input [7:0] vehicle_id_in;
  output [3:0] id_to_check;
  output id_valid;
  wire clk, reset, fsm_read_en;
  wire [7:0] vehicle_id_in;
  wire [3:0] id_to_check;
  wire id_valid;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_16;
  DFFQX1 id_valid_reg(.CK (clk), .D (n_16), .Q (id_valid));
  DFFQX4 \id_to_check_reg[0] (.CK (clk), .D (n_6), .Q (id_to_check[0]));
  DFFQX4 \id_to_check_reg[1] (.CK (clk), .D (n_7), .Q (id_to_check[1]));
  DFFQX4 \id_to_check_reg[3] (.CK (clk), .D (n_4), .Q (id_to_check[3]));
  DFFQX1 \id_to_check_reg[2] (.CK (clk), .D (n_5), .Q (id_to_check[2]));
  NOR2XL g25(.A (reset), .B (n_3), .Y (n_7));
  NOR2XL g26(.A (reset), .B (n_2), .Y (n_6));
  NOR2XL g27(.A (reset), .B (n_1), .Y (n_5));
  NOR2XL g28(.A (reset), .B (n_0), .Y (n_4));
  MXI2XL g29(.A (id_to_check[1]), .B (vehicle_id_in[1]), .S0
       (fsm_read_en), .Y (n_3));
  MXI2XL g30(.A (id_to_check[0]), .B (vehicle_id_in[0]), .S0
       (fsm_read_en), .Y (n_2));
  MXI2XL g31(.A (id_to_check[2]), .B (vehicle_id_in[2]), .S0
       (fsm_read_en), .Y (n_1));
  MXI2XL g32(.A (id_to_check[3]), .B (vehicle_id_in[3]), .S0
       (fsm_read_en), .Y (n_0));
  NOR2BXL g2(.AN (fsm_read_en), .B (reset), .Y (n_16));
endmodule

module toll_gate(clk, reset, sensor_vehicle_enter, sensor_vehicle_exit,
     vehicle_id_in, barrier_open_cmd, barrier_close_cmd, led_status,
     display_out);
  input clk, reset, sensor_vehicle_enter, sensor_vehicle_exit;
  input [7:0] vehicle_id_in;
  output barrier_open_cmd, barrier_close_cmd;
  output [1:0] led_status;
  output [7:0] display_out;
  wire clk, reset, sensor_vehicle_enter, sensor_vehicle_exit;
  wire [7:0] vehicle_id_in;
  wire barrier_open_cmd, barrier_close_cmd;
  wire [1:0] led_status;
  wire [7:0] display_out;
  wire [3:0] id_to_check;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire charge_done, gate_is_closed, gate_is_open, id_valid, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_18, n_19, n_20;
  wire n_21, n_22, n_29, n_30, n_33, n_36, n_37, sufficient_balance;
  assign display_out[4] = 1'b0;
  assign display_out[7] = 1'b0;
  account_balance u_account_balance(.clk (clk), .reset (reset),
       .id_to_check ({UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED, id_to_check}), .fsm_check_req (n_29),
       .fsm_charge_req (n_36), .sufficient_balance
       (sufficient_balance), .charge_done (charge_done));
  barrier_ctrl u_barrier_ctrl(.clk (clk), .reset (reset), .fsm_open_en
       (n_33), .fsm_close_en (n_30), .barrier_open_cmd
       (barrier_open_cmd), .barrier_close_cmd (barrier_close_cmd),
       .gate_is_open (gate_is_open), .gate_is_closed (gate_is_closed));
  vehicle_interface u_vehicle_interface(.clk (clk), .reset (reset),
       .fsm_read_en (n_37), .vehicle_id_in ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       vehicle_id_in[3:0]}), .id_to_check (id_to_check), .id_valid
       (id_valid));
  INVXL g482(.A (n_33), .Y (led_status[0]));
  INVXL g481(.A (display_out[5]), .Y (display_out[6]));
  INVXL g484(.A (sensor_vehicle_enter), .Y (n_22));
  OR2X1 g652(.A (n_36), .B (n_33), .Y (led_status[1]));
  NAND2BXL g653(.AN (n_33), .B (display_out[2]), .Y (display_out[1]));
  NOR2XL g654(.A (state[1]), .B (n_19), .Y (n_33));
  NOR2XL g655(.A (n_1), .B (n_19), .Y (display_out[5]));
  OAI211XL g656(.A0 (state[0]), .A1 (state[2]), .B0 (n_1), .C0 (n_19),
       .Y (display_out[0]));
  OAI2BB1XL g657(.A0N (state[2]), .A1N (n_18), .B0 (display_out[2]), .Y
       (display_out[3]));
  OAI2BB1X1 g658(.A0N (n_0), .A1N (n_20), .B0 (n_21), .Y (n_30));
  AND2X1 g659(.A (state[0]), .B (n_20), .Y (n_37));
  OR2X1 g660(.A (state[2]), .B (n_18), .Y (display_out[2]));
  NAND2BX1 g661(.AN (n_18), .B (state[2]), .Y (n_21));
  AND2X1 g662(.A (state[0]), .B (n_29), .Y (n_36));
  NOR2XL g663(.A (state[1]), .B (state[2]), .Y (n_20));
  NAND2XL g664(.A (state[2]), .B (state[0]), .Y (n_19));
  NOR2XL g665(.A (state[2]), .B (n_1), .Y (n_29));
  NAND2XL g666(.A (state[1]), .B (n_0), .Y (n_18));
  INVX1 g667(.A (state[0]), .Y (n_0));
  INVX1 g668(.A (state[1]), .Y (n_1));
  DFFQX1 \state_reg[1] (.CK (clk), .D (n_16), .Q (state[1]));
  DFFQX1 \state_reg[0] (.CK (clk), .D (n_15), .Q (state[0]));
  OAI221XL g773(.A0 (n_8), .A1 (n_6), .B0 (n_12), .B1 (n_0), .C0
       (n_10), .Y (n_16));
  DFFQX1 \state_reg[2] (.CK (clk), .D (n_14), .Q (state[2]));
  OAI221X1 g775(.A0 (n_8), .A1 (n_2), .B0 (sensor_vehicle_exit), .B1
       (n_11), .C0 (n_13), .Y (n_15));
  OAI211X1 g776(.A0 (n_8), .A1 (n_5), .B0 (n_10), .C0 (n_11), .Y
       (n_14));
  NAND2XL g777(.A (n_4), .B (n_9), .Y (n_13));
  AOI32X1 g778(.A0 (n_4), .A1 (id_valid), .A2 (n_1), .B0
       (sensor_vehicle_exit), .B1 (n_7), .Y (n_12));
  NAND2BX1 g779(.AN (n_0), .B (n_7), .Y (n_11));
  OAI32X1 g780(.A0 (n_22), .A1 (state[1]), .A2 (state[0]), .B0
       (id_valid), .B1 (n_0), .Y (n_9));
  OR4XL g781(.A (n_3), .B (state[0]), .C (n_1), .D (gate_is_closed), .Y
       (n_10));
  NAND2XL g782(.A (n_4), .B (state[1]), .Y (n_8));
  INVXL g783(.A (n_5), .Y (n_6));
  NOR2XL g784(.A (n_3), .B (state[1]), .Y (n_7));
  AOI21X1 g785(.A0 (charge_done), .A1 (state[0]), .B0 (n_2), .Y (n_5));
  NOR2XL g786(.A (reset), .B (state[2]), .Y (n_4));
  NAND2BX1 g787(.AN (reset), .B (state[2]), .Y (n_3));
  NOR2XL g788(.A (state[0]), .B (sufficient_balance), .Y (n_2));
endmodule

