
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 11 2025 18:21:35 IST (Oct 11 2025 12:51:35 UTC)

// Verification Directory fv/toll_gate 

module account_balance(clk, reset, id_to_check, fsm_check_req,
     fsm_charge_req, sufficient_balance, charge_done);
  input clk, reset, fsm_check_req, fsm_charge_req;
  input [7:0] id_to_check;
  output sufficient_balance, charge_done;
  wire clk, reset, fsm_check_req, fsm_charge_req;
  wire [7:0] id_to_check;
  wire sufficient_balance, charge_done;
  wire [15:0] \balance_db[0] ;
  wire [15:0] \balance_db[1] ;
  wire [15:0] \balance_db[6] ;
  wire [15:0] \balance_db[13] ;
  wire [15:0] \balance_db[5] ;
  wire [15:0] \balance_db[2] ;
  wire [15:0] \balance_db[3] ;
  wire [15:0] \balance_db[11] ;
  wire [15:0] \balance_db[12] ;
  wire [15:0] \balance_db[8] ;
  wire [15:0] \balance_db[9] ;
  wire [15:0] \balance_db[7] ;
  wire [15:0] \balance_db[4] ;
  wire [15:0] \balance_db[15] ;
  wire [15:0] \balance_db[10] ;
  wire [15:0] \balance_db[14] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_63, n_64;
  wire n_65, n_66, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_78, n_79, n_80, n_81;
  wire n_82, n_83, n_84, n_85, n_86, n_87, n_88, n_89;
  wire n_90, n_91, n_92, n_93, n_94, n_95, n_96, n_97;
  wire n_98, n_99, n_100, n_101, n_102, n_103, n_104, n_105;
  wire n_106, n_107, n_108, n_109, n_110, n_111, n_112, n_113;
  wire n_115, n_116, n_117, n_118, n_119, n_120, n_121, n_122;
  wire n_123, n_124, n_125, n_126, n_127, n_128, n_129, n_130;
  wire n_131, n_132, n_133, n_134, n_135, n_136, n_137, n_138;
  wire n_139, n_140, n_141, n_142, n_143, n_144, n_145, n_146;
  wire n_147, n_148, n_149, n_150, n_151, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_201, n_202;
  wire n_203, n_204, n_205, n_206, n_207, n_208, n_209, n_210;
  wire n_211, n_212, n_213, n_214, n_215, n_216, n_217, n_218;
  wire n_219, n_220, n_221, n_222, n_223, n_224, n_225, n_226;
  wire n_227, n_228, n_229, n_230, n_231, n_232, n_233, n_234;
  wire n_235, n_236, n_237, n_238, n_239, n_240, n_241, n_242;
  wire n_243, n_244, n_245, n_246, n_247, n_248, n_249, n_250;
  wire n_251, n_252, n_253, n_254, n_255, n_256, n_257, n_258;
  wire n_259, n_260, n_261, n_262, n_263, n_264, n_265, n_266;
  wire n_267, n_268, n_269, n_270, n_271, n_272, n_273, n_274;
  wire n_275, n_276, n_277, n_278, n_279, n_280, n_281, n_282;
  wire n_283, n_284, n_285, n_286, n_287, n_288, n_289, n_290;
  wire n_291, n_292, n_293, n_296, n_297, n_298, n_299, n_300;
  wire n_301, n_302, n_303, n_304, n_305, n_306, n_307, n_308;
  wire n_309, n_310, n_311, n_312, n_313, n_314, n_315, n_316;
  wire n_317, n_320, n_323, n_324, n_325;
  INVXL g1597(.A (n_309), .Y (sufficient_balance));
  DFFQX1 charge_done_reg(.CK (clk), .D (n_323), .Q (charge_done));
  NOR2BX1 g16885(.AN (fsm_charge_req), .B (n_309), .Y (n_310));
  OAI31X1 g16886(.A0 (n_307), .A1 (n_308), .A2 (n_293), .B0
       (fsm_check_req), .Y (n_309));
  NAND3BX1 g16887(.AN (n_313), .B (n_315), .C (n_312), .Y (n_293));
  OR4X1 g16888(.A (n_314), .B (n_299), .C (n_292), .D (n_300), .Y
       (n_313));
  NOR3BX1 g16889(.AN (n_316), .B (n_303), .C (n_304), .Y (n_312));
  INVX1 g16890(.A (n_317), .Y (n_292));
  NOR2XL g16891(.A (n_297), .B (n_298), .Y (n_317));
  NOR2XL g16892(.A (n_305), .B (n_291), .Y (n_315));
  NAND2XL g16893(.A (n_226), .B (n_306), .Y (n_300));
  NAND4XL g16894(.A (n_237), .B (n_236), .C (n_238), .D (n_290), .Y
       (n_304));
  AOI221X1 g16895(.A0 (\balance_db[0] [7]), .A1 (n_160), .B0
       (\balance_db[1] [7]), .B1 (n_161), .C0 (n_288), .Y (n_291));
  NAND2XL g16896(.A (n_235), .B (n_289), .Y (n_298));
  NOR2XL g16897(.A (n_301), .B (n_302), .Y (n_316));
  NAND3X1 g16898(.A (n_176), .B (n_198), .C (n_285), .Y (n_299));
  NAND4XL g16899(.A (n_247), .B (n_229), .C (n_232), .D (n_283), .Y
       (n_305));
  NAND4XL g16900(.A (n_223), .B (n_225), .C (n_224), .D (n_287), .Y
       (n_306));
  AOI211X1 g16901(.A0 (\balance_db[6] [11]), .A1 (n_155), .B0 (n_234),
       .C0 (n_278), .Y (n_290));
  NAND3X1 g16902(.A (n_201), .B (n_202), .C (n_284), .Y (n_303));
  OAI211X1 g16903(.A0 (n_139), .A1 (n_246), .B0 (n_211), .C0 (n_280),
       .Y (n_301));
  AOI211X1 g16904(.A0 (\balance_db[0] [5]), .A1 (n_160), .B0 (n_265),
       .C0 (n_286), .Y (n_289));
  NAND4XL g16905(.A (n_217), .B (n_216), .C (n_218), .D (n_281), .Y
       (n_307));
  OAI211X1 g16906(.A0 (n_139), .A1 (n_244), .B0 (n_203), .C0 (n_277),
       .Y (n_302));
  NAND4XL g16907(.A (n_209), .B (n_210), .C (n_208), .D (n_282), .Y
       (n_308));
  NAND3X1 g16908(.A (n_221), .B (n_222), .C (n_279), .Y (n_288));
  AOI221X1 g16909(.A0 (\balance_db[13] [13]), .A1 (n_164), .B0
       (\balance_db[5] [13]), .B1 (n_165), .C0 (n_273), .Y (n_287));
  OAI21X1 g16910(.A0 (n_136), .A1 (n_239), .B0 (n_276), .Y (n_286));
  AOI211X1 g16911(.A0 (\balance_db[0] [6]), .A1 (n_160), .B0 (n_274),
       .C0 (n_267), .Y (n_285));
  AOI211X1 g16912(.A0 (\balance_db[2] [10]), .A1 (n_156), .B0 (n_231),
       .C0 (n_270), .Y (n_284));
  AOI211X1 g16913(.A0 (\balance_db[1] [12]), .A1 (n_161), .B0 (n_255),
       .C0 (n_275), .Y (n_283));
  AOI2BB1X1 g16914(.A0N (n_311), .A1N (n_296), .B0 (n_320), .Y (n_314));
  AOI221X1 g16915(.A0 (\balance_db[0] [15]), .A1 (n_160), .B0
       (\balance_db[1] [15]), .B1 (n_161), .C0 (n_261), .Y (n_282));
  AOI221X1 g16916(.A0 (\balance_db[3] [14]), .A1 (n_153), .B0
       (\balance_db[11] [14]), .B1 (n_157), .C0 (n_260), .Y (n_281));
  AOI211X1 g16917(.A0 (n_137), .A1 (n_245), .B0 (n_256), .C0 (n_272),
       .Y (n_320));
  NAND3X1 g16918(.A (n_227), .B (n_264), .C (n_259), .Y (n_297));
  AOI221X1 g16919(.A0 (\balance_db[12] [8]), .A1 (n_154), .B0
       (\balance_db[5] [8]), .B1 (n_165), .C0 (n_269), .Y (n_280));
  AOI221X1 g16920(.A0 (\balance_db[8] [7]), .A1 (n_167), .B0
       (\balance_db[9] [7]), .B1 (n_166), .C0 (n_268), .Y (n_279));
  OAI211X1 g16921(.A0 (n_135), .A1 (n_250), .B0 (n_181), .C0 (n_233),
       .Y (n_278));
  AOI221X1 g16922(.A0 (\balance_db[12] [9]), .A1 (n_154), .B0
       (\balance_db[5] [9]), .B1 (n_165), .C0 (n_271), .Y (n_277));
  AOI221X1 g16923(.A0 (\balance_db[3] [5]), .A1 (n_153), .B0
       (\balance_db[11] [5]), .B1 (n_157), .C0 (n_266), .Y (n_276));
  OAI211X1 g16924(.A0 (n_135), .A1 (n_241), .B0 (n_179), .C0 (n_228),
       .Y (n_275));
  OAI211X1 g16925(.A0 (n_135), .A1 (n_242), .B0 (n_180), .C0 (n_230),
       .Y (n_274));
  NAND3X1 g16926(.A (n_219), .B (n_220), .C (n_263), .Y (n_273));
  OAI221X1 g16927(.A0 (n_141), .A1 (n_188), .B0 (n_139), .B1 (n_240),
       .C0 (n_178), .Y (n_272));
  OAI221X1 g16928(.A0 (n_135), .A1 (n_191), .B0 (n_139), .B1 (n_194),
       .C0 (n_258), .Y (n_296));
  OAI22X1 g16929(.A0 (n_141), .A1 (n_249), .B0 (n_136), .B1 (n_185), .Y
       (n_271));
  NAND4XL g16930(.A (n_215), .B (n_253), .C (n_200), .D (n_197), .Y
       (n_270));
  OAI22X1 g16931(.A0 (n_141), .A1 (n_252), .B0 (n_136), .B1 (n_189), .Y
       (n_269));
  OAI22X1 g16932(.A0 (n_135), .A1 (n_254), .B0 (n_139), .B1 (n_171), .Y
       (n_268));
  OAI221X1 g16933(.A0 (n_135), .A1 (n_186), .B0 (n_139), .B1 (n_195),
       .C0 (n_262), .Y (n_311));
  OAI31X1 g16934(.A0 (n_125), .A1 (n_139), .A2 (n_150), .B0 (n_257), .Y
       (n_267));
  NOR2XL g16935(.A (n_139), .B (n_248), .Y (n_266));
  NOR2XL g16936(.A (n_135), .B (n_251), .Y (n_265));
  AOI222XL g16937(.A0 (\balance_db[6] [4]), .A1 (n_155), .B0
       (\balance_db[7] [4]), .B1 (n_158), .C0 (n_196), .C1 (n_140), .Y
       (n_264));
  AOI222XL g16938(.A0 (n_137), .A1 (n_182), .B0 (\balance_db[0] [13]),
       .B1 (n_160), .C0 (n_157), .C1 (\balance_db[11] [13]), .Y
       (n_263));
  AOI22X1 g16939(.A0 (n_137), .A1 (n_184), .B0 (n_140), .B1 (n_192), .Y
       (n_262));
  NAND4XL g16940(.A (n_206), .B (n_207), .C (n_205), .D (n_204), .Y
       (n_261));
  NAND4XL g16941(.A (n_212), .B (n_213), .C (n_214), .D (n_199), .Y
       (n_260));
  AOI22X1 g16942(.A0 (n_137), .A1 (n_190), .B0 (n_134), .B1 (n_193), .Y
       (n_259));
  AOI22X1 g16943(.A0 (n_137), .A1 (n_183), .B0 (n_140), .B1 (n_187), .Y
       (n_258));
  AOI222XL g16944(.A0 (n_131), .A1 (n_177), .B0 (\balance_db[8] [6]),
       .B1 (n_167), .C0 (n_166), .C1 (\balance_db[9] [6]), .Y (n_257));
  AOI21X1 g16945(.A0 (n_172), .A1 (n_173), .B0 (n_135), .Y (n_256));
  NOR2XL g16946(.A (n_136), .B (n_243), .Y (n_255));
  AOI222XL g16947(.A0 (id_to_check[3]), .A1 (n_147), .B0
       (\balance_db[4] [7]), .B1 (n_133), .C0 (n_131), .C1
       (\balance_db[5] [7]), .Y (n_254));
  AOI222XL g16948(.A0 (\balance_db[6] [10]), .A1 (n_155), .B0
       (\balance_db[7] [10]), .B1 (n_158), .C0 (n_159), .C1
       (\balance_db[15] [10]), .Y (n_253));
  AOI222XL g16949(.A0 (\balance_db[11] [8]), .A1 (n_129), .B0 (n_125),
       .B1 (n_145), .C0 (n_127), .C1 (\balance_db[10] [8]), .Y (n_252));
  AOI222XL g16950(.A0 (n_125), .A1 (n_144), .B0 (\balance_db[12] [5]),
       .B1 (n_127), .C0 (n_129), .C1 (\balance_db[13] [5]), .Y (n_251));
  AOI222XL g16951(.A0 (\balance_db[13] [11]), .A1 (n_129), .B0 (n_125),
       .B1 (n_149), .C0 (n_127), .C1 (\balance_db[12] [11]), .Y
       (n_250));
  AOI222XL g16952(.A0 (\balance_db[11] [9]), .A1 (n_129), .B0 (n_125),
       .B1 (n_142), .C0 (n_127), .C1 (\balance_db[10] [9]), .Y (n_249));
  AOI222XL g16953(.A0 (n_125), .A1 (n_146), .B0 (\balance_db[14] [5]),
       .B1 (n_127), .C0 (n_129), .C1 (\balance_db[15] [5]), .Y (n_248));
  AOI22X1 g16954(.A0 (\balance_db[6] [12]), .A1 (n_155), .B0
       (\balance_db[7] [12]), .B1 (n_158), .Y (n_247));
  AOI221X1 g16955(.A0 (\balance_db[14] [8]), .A1 (n_127), .B0
       (\balance_db[15] [8]), .B1 (n_129), .C0 (n_174), .Y (n_246));
  NAND2XL g16956(.A (n_170), .B (n_175), .Y (n_245));
  AOI221X1 g16957(.A0 (\balance_db[14] [9]), .A1 (n_127), .B0
       (\balance_db[15] [9]), .B1 (n_129), .C0 (n_169), .Y (n_244));
  AOI222XL g16958(.A0 (\balance_db[0] [12]), .A1 (n_133), .B0
       (\balance_db[8] [12]), .B1 (n_127), .C0 (n_129), .C1
       (\balance_db[9] [12]), .Y (n_243));
  AOI22X1 g16959(.A0 (id_to_check[3]), .A1 (n_148), .B0
       (\balance_db[4] [6]), .B1 (n_133), .Y (n_242));
  AOI22X1 g16960(.A0 (id_to_check[3]), .A1 (n_143), .B0
       (\balance_db[5] [12]), .B1 (n_131), .Y (n_241));
  AOI22X1 g16961(.A0 (n_125), .A1 (n_151), .B0 (\balance_db[14] [3]),
       .B1 (n_127), .Y (n_240));
  AOI222XL g16962(.A0 (\balance_db[8] [5]), .A1 (n_127), .B0
       (\balance_db[9] [5]), .B1 (n_129), .C0 (n_131), .C1
       (\balance_db[1] [5]), .Y (n_239));
  AOI22X1 g16963(.A0 (\balance_db[14] [11]), .A1 (n_162), .B0
       (\balance_db[15] [11]), .B1 (n_159), .Y (n_238));
  AOI22X1 g16964(.A0 (\balance_db[2] [11]), .A1 (n_156), .B0
       (\balance_db[9] [11]), .B1 (n_166), .Y (n_237));
  AOI22X1 g16965(.A0 (\balance_db[8] [11]), .A1 (n_167), .B0
       (\balance_db[7] [11]), .B1 (n_158), .Y (n_236));
  AOI22X1 g16966(.A0 (\balance_db[2] [5]), .A1 (n_156), .B0
       (\balance_db[10] [5]), .B1 (n_152), .Y (n_235));
  AO22X1 g16967(.A0 (\balance_db[10] [11]), .A1 (n_152), .B0
       (\balance_db[11] [11]), .B1 (n_157), .Y (n_234));
  AOI22X1 g16968(.A0 (\balance_db[1] [11]), .A1 (n_161), .B0
       (\balance_db[3] [11]), .B1 (n_153), .Y (n_233));
  AOI22X1 g16969(.A0 (\balance_db[10] [12]), .A1 (n_152), .B0
       (\balance_db[11] [12]), .B1 (n_157), .Y (n_232));
  NOR2XL g16970(.A (n_136), .B (n_168), .Y (n_231));
  AOI22X1 g16971(.A0 (\balance_db[6] [6]), .A1 (n_155), .B0
       (\balance_db[11] [6]), .B1 (n_157), .Y (n_230));
  AOI22X1 g16972(.A0 (\balance_db[14] [12]), .A1 (n_162), .B0
       (\balance_db[15] [12]), .B1 (n_159), .Y (n_229));
  AOI22X1 g16973(.A0 (\balance_db[2] [12]), .A1 (n_156), .B0
       (\balance_db[3] [12]), .B1 (n_153), .Y (n_228));
  AOI22X1 g16974(.A0 (\balance_db[14] [4]), .A1 (n_162), .B0
       (\balance_db[15] [4]), .B1 (n_159), .Y (n_227));
  AOI22X1 g16975(.A0 (\balance_db[2] [7]), .A1 (n_156), .B0
       (\balance_db[3] [7]), .B1 (n_153), .Y (n_226));
  AOI22X1 g16976(.A0 (\balance_db[14] [13]), .A1 (n_162), .B0
       (\balance_db[15] [13]), .B1 (n_159), .Y (n_225));
  AOI22X1 g16977(.A0 (\balance_db[4] [13]), .A1 (n_163), .B0
       (\balance_db[12] [13]), .B1 (n_154), .Y (n_224));
  AOI22X1 g16978(.A0 (\balance_db[6] [13]), .A1 (n_155), .B0
       (\balance_db[7] [13]), .B1 (n_158), .Y (n_223));
  AOI22X1 g16979(.A0 (\balance_db[10] [7]), .A1 (n_152), .B0
       (\balance_db[11] [7]), .B1 (n_157), .Y (n_222));
  AOI22X1 g16980(.A0 (\balance_db[6] [7]), .A1 (n_155), .B0
       (\balance_db[7] [7]), .B1 (n_158), .Y (n_221));
  AOI22X1 g16981(.A0 (\balance_db[10] [13]), .A1 (n_152), .B0
       (\balance_db[3] [13]), .B1 (n_153), .Y (n_220));
  AOI22X1 g16982(.A0 (\balance_db[2] [13]), .A1 (n_156), .B0
       (\balance_db[1] [13]), .B1 (n_161), .Y (n_219));
  AOI22X1 g16983(.A0 (\balance_db[12] [14]), .A1 (n_154), .B0
       (\balance_db[13] [14]), .B1 (n_164), .Y (n_218));
  AOI22X1 g16984(.A0 (\balance_db[4] [14]), .A1 (n_163), .B0
       (\balance_db[5] [14]), .B1 (n_165), .Y (n_217));
  AOI22X1 g16985(.A0 (\balance_db[2] [14]), .A1 (n_156), .B0
       (\balance_db[10] [14]), .B1 (n_152), .Y (n_216));
  AOI22X1 g16986(.A0 (\balance_db[4] [10]), .A1 (n_163), .B0
       (\balance_db[5] [10]), .B1 (n_165), .Y (n_215));
  AOI22X1 g16987(.A0 (\balance_db[1] [14]), .A1 (n_161), .B0
       (\balance_db[15] [14]), .B1 (n_159), .Y (n_214));
  AOI22XL g16988(.A0 (n_155), .A1 (\balance_db[6] [14]), .B0 (n_166),
       .B1 (\balance_db[9] [14]), .Y (n_213));
  AOI22X1 g16989(.A0 (\balance_db[0] [14]), .A1 (n_160), .B0
       (\balance_db[8] [14]), .B1 (n_167), .Y (n_212));
  AOI22X1 g16990(.A0 (\balance_db[4] [8]), .A1 (n_163), .B0
       (\balance_db[13] [8]), .B1 (n_164), .Y (n_211));
  AOI22X1 g16991(.A0 (\balance_db[8] [15]), .A1 (n_167), .B0
       (\balance_db[9] [15]), .B1 (n_166), .Y (n_210));
  AOI22X1 g16992(.A0 (\balance_db[2] [15]), .A1 (n_156), .B0
       (\balance_db[3] [15]), .B1 (n_153), .Y (n_209));
  AOI22X1 g16993(.A0 (\balance_db[10] [15]), .A1 (n_152), .B0
       (\balance_db[11] [15]), .B1 (n_157), .Y (n_208));
  AOI22X1 g16994(.A0 (\balance_db[6] [15]), .A1 (n_155), .B0
       (\balance_db[15] [15]), .B1 (n_159), .Y (n_207));
  AOI22X1 g16995(.A0 (\balance_db[5] [15]), .A1 (n_165), .B0
       (\balance_db[7] [15]), .B1 (n_158), .Y (n_206));
  AOI22X1 g16996(.A0 (\balance_db[12] [15]), .A1 (n_154), .B0
       (\balance_db[14] [15]), .B1 (n_162), .Y (n_205));
  AOI22X1 g16997(.A0 (\balance_db[4] [15]), .A1 (n_163), .B0
       (\balance_db[13] [15]), .B1 (n_164), .Y (n_204));
  AOI22X1 g16998(.A0 (\balance_db[4] [9]), .A1 (n_163), .B0
       (\balance_db[13] [9]), .B1 (n_164), .Y (n_203));
  AOI22X1 g16999(.A0 (\balance_db[12] [10]), .A1 (n_154), .B0
       (\balance_db[13] [10]), .B1 (n_164), .Y (n_202));
  AOI22X1 g17000(.A0 (\balance_db[0] [10]), .A1 (n_160), .B0
       (\balance_db[1] [10]), .B1 (n_161), .Y (n_201));
  AOI22X1 g17001(.A0 (\balance_db[10] [10]), .A1 (n_152), .B0
       (\balance_db[3] [10]), .B1 (n_153), .Y (n_200));
  AOI22X1 g17002(.A0 (\balance_db[14] [14]), .A1 (n_162), .B0
       (\balance_db[7] [14]), .B1 (n_158), .Y (n_199));
  AOI22X1 g17003(.A0 (\balance_db[2] [6]), .A1 (n_156), .B0
       (\balance_db[3] [6]), .B1 (n_153), .Y (n_198));
  AOI22X1 g17004(.A0 (\balance_db[14] [10]), .A1 (n_162), .B0
       (\balance_db[11] [10]), .B1 (n_157), .Y (n_197));
  MX4XL g17005(.A (\balance_db[10] [4]), .B (\balance_db[2] [4]), .C
       (\balance_db[11] [4]), .D (\balance_db[3] [4]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_196));
  MXI4XL g17006(.A (\balance_db[14] [1]), .B (\balance_db[6] [1]), .C
       (\balance_db[15] [1]), .D (\balance_db[7] [1]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_195));
  MXI4XL g17007(.A (\balance_db[14] [2]), .B (\balance_db[6] [2]), .C
       (\balance_db[15] [2]), .D (\balance_db[7] [2]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_194));
  MX4XL g17008(.A (\balance_db[12] [4]), .B (\balance_db[4] [4]), .C
       (\balance_db[13] [4]), .D (\balance_db[5] [4]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_193));
  MX4XL g17009(.A (\balance_db[10] [1]), .B (\balance_db[2] [1]), .C
       (\balance_db[11] [1]), .D (\balance_db[3] [1]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_192));
  MXI4XL g17010(.A (\balance_db[12] [2]), .B (\balance_db[4] [2]), .C
       (\balance_db[13] [2]), .D (\balance_db[5] [2]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_191));
  MX4XL g17011(.A (\balance_db[8] [4]), .B (\balance_db[0] [4]), .C
       (\balance_db[9] [4]), .D (\balance_db[1] [4]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_190));
  MXI4XL g17012(.A (\balance_db[0] [8]), .B (\balance_db[8] [8]), .C
       (\balance_db[1] [8]), .D (\balance_db[9] [8]), .S0
       (id_to_check[3]), .S1 (id_to_check[0]), .Y (n_189));
  MXI4XL g17013(.A (\balance_db[10] [3]), .B (\balance_db[2] [3]), .C
       (\balance_db[11] [3]), .D (\balance_db[3] [3]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_188));
  MX4XL g17014(.A (\balance_db[10] [2]), .B (\balance_db[2] [2]), .C
       (\balance_db[11] [2]), .D (\balance_db[3] [2]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_187));
  MXI4XL g17015(.A (\balance_db[12] [1]), .B (\balance_db[4] [1]), .C
       (\balance_db[13] [1]), .D (\balance_db[5] [1]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_186));
  MXI4XL g17016(.A (\balance_db[0] [9]), .B (\balance_db[8] [9]), .C
       (\balance_db[1] [9]), .D (\balance_db[9] [9]), .S0
       (id_to_check[3]), .S1 (id_to_check[0]), .Y (n_185));
  MX4XL g17017(.A (\balance_db[8] [1]), .B (\balance_db[0] [1]), .C
       (\balance_db[9] [1]), .D (\balance_db[1] [1]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_184));
  MX4XL g17018(.A (\balance_db[8] [2]), .B (\balance_db[0] [2]), .C
       (\balance_db[9] [2]), .D (\balance_db[1] [2]), .S0 (n_125), .S1
       (id_to_check[0]), .Y (n_183));
  AO22XL g17019(.A0 (\balance_db[8] [13]), .A1 (n_127), .B0
       (\balance_db[9] [13]), .B1 (n_129), .Y (n_182));
  NAND2XL g17020(.A (\balance_db[0] [11]), .B (n_160), .Y (n_181));
  NAND2XL g17021(.A (\balance_db[10] [6]), .B (n_152), .Y (n_180));
  NAND2XL g17022(.A (\balance_db[4] [12]), .B (n_163), .Y (n_179));
  NAND2XL g17023(.A (\balance_db[15] [3]), .B (n_159), .Y (n_178));
  AO22XL g17024(.A0 (\balance_db[5] [6]), .A1 (n_134), .B0
       (\balance_db[7] [6]), .B1 (n_138), .Y (n_177));
  NAND2XL g17025(.A (\balance_db[1] [6]), .B (n_161), .Y (n_176));
  AOI22XL g17026(.A0 (n_127), .A1 (\balance_db[8] [3]), .B0 (n_129),
       .B1 (\balance_db[9] [3]), .Y (n_175));
  AO22X1 g17027(.A0 (\balance_db[6] [8]), .A1 (n_133), .B0
       (\balance_db[7] [8]), .B1 (n_131), .Y (n_174));
  AOI22X1 g17028(.A0 (\balance_db[12] [3]), .A1 (n_127), .B0
       (\balance_db[13] [3]), .B1 (n_129), .Y (n_173));
  AOI22X1 g17029(.A0 (\balance_db[4] [3]), .A1 (n_133), .B0
       (\balance_db[5] [3]), .B1 (n_131), .Y (n_172));
  AOI22X1 g17030(.A0 (\balance_db[14] [7]), .A1 (n_127), .B0
       (\balance_db[15] [7]), .B1 (n_129), .Y (n_171));
  AOI22XL g17031(.A0 (n_133), .A1 (\balance_db[0] [3]), .B0 (n_131),
       .B1 (\balance_db[1] [3]), .Y (n_170));
  AO22X1 g17032(.A0 (\balance_db[6] [9]), .A1 (n_133), .B0
       (\balance_db[7] [9]), .B1 (n_131), .Y (n_169));
  AOI22XL g17033(.A0 (n_127), .A1 (\balance_db[8] [10]), .B0 (n_129),
       .B1 (\balance_db[9] [10]), .Y (n_168));
  NOR2XL g17034(.A (n_136), .B (n_126), .Y (n_167));
  NOR2XL g17035(.A (n_136), .B (n_128), .Y (n_166));
  NOR2XL g17036(.A (n_135), .B (n_130), .Y (n_165));
  NOR2XL g17037(.A (n_135), .B (n_128), .Y (n_164));
  NOR2XL g17038(.A (n_135), .B (n_132), .Y (n_163));
  NOR2XL g17039(.A (n_139), .B (n_126), .Y (n_162));
  NOR2XL g17040(.A (n_136), .B (n_130), .Y (n_161));
  NOR2XL g17041(.A (n_136), .B (n_132), .Y (n_160));
  NOR2XL g17042(.A (n_139), .B (n_128), .Y (n_159));
  NOR2XL g17043(.A (n_139), .B (n_130), .Y (n_158));
  NOR2XL g17044(.A (n_141), .B (n_128), .Y (n_157));
  NOR2XL g17045(.A (n_141), .B (n_132), .Y (n_156));
  NOR2XL g17046(.A (n_139), .B (n_132), .Y (n_155));
  MX2X1 g17047(.A (\balance_db[6] [3]), .B (\balance_db[7] [3]), .S0
       (id_to_check[0]), .Y (n_151));
  MXI2XL g17048(.A (\balance_db[14] [6]), .B (\balance_db[15] [6]), .S0
       (id_to_check[0]), .Y (n_150));
  MX2X1 g17049(.A (\balance_db[4] [11]), .B (\balance_db[5] [11]), .S0
       (id_to_check[0]), .Y (n_149));
  MX2X1 g17050(.A (\balance_db[12] [6]), .B (\balance_db[13] [6]), .S0
       (id_to_check[0]), .Y (n_148));
  MX2X1 g17051(.A (\balance_db[12] [7]), .B (\balance_db[13] [7]), .S0
       (id_to_check[0]), .Y (n_147));
  MX2X1 g17052(.A (\balance_db[6] [5]), .B (\balance_db[7] [5]), .S0
       (id_to_check[0]), .Y (n_146));
  MX2X1 g17053(.A (\balance_db[2] [8]), .B (\balance_db[3] [8]), .S0
       (id_to_check[0]), .Y (n_145));
  MX2X1 g17054(.A (\balance_db[4] [5]), .B (\balance_db[5] [5]), .S0
       (id_to_check[0]), .Y (n_144));
  MX2X1 g17055(.A (\balance_db[12] [12]), .B (\balance_db[13] [12]),
       .S0 (id_to_check[0]), .Y (n_143));
  MX2X1 g17056(.A (\balance_db[2] [9]), .B (\balance_db[3] [9]), .S0
       (id_to_check[0]), .Y (n_142));
  NOR2XL g17057(.A (n_135), .B (n_126), .Y (n_154));
  NOR2XL g17058(.A (n_130), .B (n_141), .Y (n_153));
  NOR2XL g17059(.A (n_141), .B (n_126), .Y (n_152));
  CLKINVX1 g17060(.A (n_141), .Y (n_140));
  INVXL g17061(.A (n_139), .Y (n_138));
  CLKINVX1 g17062(.A (n_137), .Y (n_136));
  CLKINVX1 g17063(.A (n_135), .Y (n_134));
  NAND2BX1 g17064(.AN (id_to_check[2]), .B (id_to_check[1]), .Y
       (n_141));
  NAND2XL g17065(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_139));
  NOR2XL g17066(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_137));
  NAND2BX1 g17067(.AN (id_to_check[1]), .B (id_to_check[2]), .Y
       (n_135));
  CLKINVX1 g17068(.A (n_133), .Y (n_132));
  CLKINVX1 g17069(.A (n_131), .Y (n_130));
  CLKINVX1 g17070(.A (n_129), .Y (n_128));
  CLKINVX1 g17071(.A (n_127), .Y (n_126));
  NOR2XL g17072(.A (id_to_check[3]), .B (id_to_check[0]), .Y (n_133));
  NOR2XL g17073(.A (id_to_check[3]), .B (n_124), .Y (n_131));
  NOR2XL g17074(.A (n_125), .B (n_124), .Y (n_129));
  NOR2XL g17075(.A (id_to_check[0]), .B (n_125), .Y (n_127));
  CLKINVX1 g17076(.A (id_to_check[3]), .Y (n_125));
  CLKINVX1 g17077(.A (id_to_check[0]), .Y (n_124));
  SDFFQX1 \balance_db_reg[0][1] (.CK (clk), .D (\balance_db[0] [1]),
       .SI (n_4), .SE (n_46), .Q (\balance_db[0] [1]));
  SDFFQX1 \balance_db_reg[0][2] (.CK (clk), .D (\balance_db[0] [2]),
       .SI (n_40), .SE (n_46), .Q (\balance_db[0] [2]));
  SDFFQX1 \balance_db_reg[0][3] (.CK (clk), .D (\balance_db[0] [3]),
       .SI (n_58), .SE (n_46), .Q (\balance_db[0] [3]));
  SDFFQX1 \balance_db_reg[0][4] (.CK (clk), .D (\balance_db[0] [4]),
       .SI (n_41), .SE (n_46), .Q (\balance_db[0] [4]));
  SDFFQX1 \balance_db_reg[0][5] (.CK (clk), .D (\balance_db[0] [5]),
       .SI (n_57), .SE (n_46), .Q (\balance_db[0] [5]));
  SDFFQX1 \balance_db_reg[0][6] (.CK (clk), .D (\balance_db[0] [6]),
       .SI (n_55), .SE (n_46), .Q (\balance_db[0] [6]));
  SDFFQX1 \balance_db_reg[0][7] (.CK (clk), .D (\balance_db[0] [7]),
       .SI (n_70), .SE (n_46), .Q (\balance_db[0] [7]));
  SDFFQX1 \balance_db_reg[0][8] (.CK (clk), .D (\balance_db[0] [8]),
       .SI (n_19), .SE (n_46), .Q (\balance_db[0] [8]));
  SDFFQX1 \balance_db_reg[0][9] (.CK (clk), .D (\balance_db[0] [9]),
       .SI (n_59), .SE (n_46), .Q (\balance_db[0] [9]));
  SDFFQX1 \balance_db_reg[0][10] (.CK (clk), .D (\balance_db[0] [10]),
       .SI (n_32), .SE (n_46), .Q (\balance_db[0] [10]));
  SDFFQX1 \balance_db_reg[0][11] (.CK (clk), .D (\balance_db[0] [11]),
       .SI (n_71), .SE (n_46), .Q (\balance_db[0] [11]));
  SDFFQX1 \balance_db_reg[0][12] (.CK (clk), .D (\balance_db[0] [12]),
       .SI (n_33), .SE (n_46), .Q (\balance_db[0] [12]));
  SDFFQX1 \balance_db_reg[0][13] (.CK (clk), .D (\balance_db[0] [13]),
       .SI (n_72), .SE (n_46), .Q (\balance_db[0] [13]));
  SDFFQX1 \balance_db_reg[0][14] (.CK (clk), .D (\balance_db[0] [14]),
       .SI (n_47), .SE (n_46), .Q (\balance_db[0] [14]));
  SDFFQX1 \balance_db_reg[0][15] (.CK (clk), .D (\balance_db[0] [15]),
       .SI (n_78), .SE (n_46), .Q (\balance_db[0] [15]));
  DFFQX1 \balance_db_reg[1][1] (.CK (clk), .D (n_102), .Q
       (\balance_db[1] [1]));
  DFFQX1 \balance_db_reg[1][2] (.CK (clk), .D (n_112), .Q
       (\balance_db[1] [2]));
  DFFQX1 \balance_db_reg[1][3] (.CK (clk), .D (n_84), .Q
       (\balance_db[1] [3]));
  DFFQX1 \balance_db_reg[1][4] (.CK (clk), .D (n_101), .Q
       (\balance_db[1] [4]));
  DFFQX1 \balance_db_reg[1][5] (.CK (clk), .D (n_325), .Q
       (\balance_db[1] [5]));
  DFFQX1 \balance_db_reg[1][6] (.CK (clk), .D (n_110), .Q
       (\balance_db[1] [6]));
  DFFQX1 \balance_db_reg[1][7] (.CK (clk), .D (n_83), .Q
       (\balance_db[1] [7]));
  DFFQX1 \balance_db_reg[1][8] (.CK (clk), .D (n_100), .Q
       (\balance_db[1] [8]));
  DFFQX1 \balance_db_reg[1][9] (.CK (clk), .D (n_82), .Q
       (\balance_db[1] [9]));
  DFFQX1 \balance_db_reg[1][10] (.CK (clk), .D (n_99), .Q
       (\balance_db[1] [10]));
  DFFQX1 \balance_db_reg[1][11] (.CK (clk), .D (n_81), .Q
       (\balance_db[1] [11]));
  DFFQX1 \balance_db_reg[1][12] (.CK (clk), .D (n_98), .Q
       (\balance_db[1] [12]));
  DFFQX1 \balance_db_reg[1][13] (.CK (clk), .D (n_80), .Q
       (\balance_db[1] [13]));
  DFFQX1 \balance_db_reg[1][14] (.CK (clk), .D (n_120), .Q
       (\balance_db[1] [14]));
  DFFQX1 \balance_db_reg[1][15] (.CK (clk), .D (n_123), .Q
       (\balance_db[1] [15]));
  DFFQX1 \balance_db_reg[2][1] (.CK (clk), .D (n_96), .Q
       (\balance_db[2] [1]));
  DFFQX1 \balance_db_reg[2][2] (.CK (clk), .D (n_115), .Q
       (\balance_db[2] [2]));
  DFFQX1 \balance_db_reg[2][3] (.CK (clk), .D (n_79), .Q
       (\balance_db[2] [3]));
  DFFQX1 \balance_db_reg[2][4] (.CK (clk), .D (n_95), .Q
       (\balance_db[2] [4]));
  DFFQX1 \balance_db_reg[2][5] (.CK (clk), .D (n_97), .Q
       (\balance_db[2] [5]));
  DFFQX1 \balance_db_reg[2][6] (.CK (clk), .D (n_94), .Q
       (\balance_db[2] [6]));
  DFFQX1 \balance_db_reg[2][7] (.CK (clk), .D (n_116), .Q
       (\balance_db[2] [7]));
  DFFQX1 \balance_db_reg[2][8] (.CK (clk), .D (n_93), .Q
       (\balance_db[2] [8]));
  DFFQX1 \balance_db_reg[2][9] (.CK (clk), .D (n_117), .Q
       (\balance_db[2] [9]));
  DFFQX1 \balance_db_reg[2][10] (.CK (clk), .D (n_92), .Q
       (\balance_db[2] [10]));
  DFFQX1 \balance_db_reg[2][11] (.CK (clk), .D (n_118), .Q
       (\balance_db[2] [11]));
  DFFQX1 \balance_db_reg[2][12] (.CK (clk), .D (n_91), .Q
       (\balance_db[2] [12]));
  DFFQX1 \balance_db_reg[2][13] (.CK (clk), .D (n_119), .Q
       (\balance_db[2] [13]));
  DFFQX1 \balance_db_reg[2][14] (.CK (clk), .D (n_109), .Q
       (\balance_db[2] [14]));
  DFFQX1 \balance_db_reg[2][15] (.CK (clk), .D (n_121), .Q
       (\balance_db[2] [15]));
  DFFQX1 \balance_db_reg[3][1] (.CK (clk), .D (n_108), .Q
       (\balance_db[3] [1]));
  DFFQX1 \balance_db_reg[3][2] (.CK (clk), .D (n_113), .Q
       (\balance_db[3] [2]));
  DFFQX1 \balance_db_reg[3][3] (.CK (clk), .D (n_90), .Q
       (\balance_db[3] [3]));
  DFFQX1 \balance_db_reg[3][4] (.CK (clk), .D (n_111), .Q
       (\balance_db[3] [4]));
  DFFQX1 \balance_db_reg[3][5] (.CK (clk), .D (n_89), .Q
       (\balance_db[3] [5]));
  DFFQX1 \balance_db_reg[3][6] (.CK (clk), .D (n_107), .Q
       (\balance_db[3] [6]));
  DFFQX1 \balance_db_reg[3][7] (.CK (clk), .D (n_88), .Q
       (\balance_db[3] [7]));
  DFFQX1 \balance_db_reg[3][8] (.CK (clk), .D (n_106), .Q
       (\balance_db[3] [8]));
  DFFQX1 \balance_db_reg[3][9] (.CK (clk), .D (n_87), .Q
       (\balance_db[3] [9]));
  DFFQX1 \balance_db_reg[3][10] (.CK (clk), .D (n_105), .Q
       (\balance_db[3] [10]));
  DFFQX1 \balance_db_reg[3][11] (.CK (clk), .D (n_86), .Q
       (\balance_db[3] [11]));
  DFFQX1 \balance_db_reg[3][12] (.CK (clk), .D (n_104), .Q
       (\balance_db[3] [12]));
  DFFQX1 \balance_db_reg[3][13] (.CK (clk), .D (n_85), .Q
       (\balance_db[3] [13]));
  DFFQX1 \balance_db_reg[3][14] (.CK (clk), .D (n_103), .Q
       (\balance_db[3] [14]));
  DFFQX1 \balance_db_reg[3][15] (.CK (clk), .D (n_122), .Q
       (\balance_db[3] [15]));
  SDFFQX1 \balance_db_reg[4][1] (.CK (clk), .D (\balance_db[4] [1]),
       .SI (n_4), .SE (n_30), .Q (\balance_db[4] [1]));
  SDFFQX1 \balance_db_reg[4][2] (.CK (clk), .D (\balance_db[4] [2]),
       .SI (n_40), .SE (n_30), .Q (\balance_db[4] [2]));
  SDFFQX1 \balance_db_reg[4][3] (.CK (clk), .D (\balance_db[4] [3]),
       .SI (n_58), .SE (n_30), .Q (\balance_db[4] [3]));
  SDFFQX1 \balance_db_reg[4][4] (.CK (clk), .D (\balance_db[4] [4]),
       .SI (n_41), .SE (n_30), .Q (\balance_db[4] [4]));
  SDFFQX1 \balance_db_reg[4][5] (.CK (clk), .D (\balance_db[4] [5]),
       .SI (n_57), .SE (n_30), .Q (\balance_db[4] [5]));
  SDFFQX1 \balance_db_reg[4][6] (.CK (clk), .D (\balance_db[4] [6]),
       .SI (n_55), .SE (n_30), .Q (\balance_db[4] [6]));
  SDFFQX1 \balance_db_reg[4][7] (.CK (clk), .D (\balance_db[4] [7]),
       .SI (n_70), .SE (n_30), .Q (\balance_db[4] [7]));
  SDFFQX1 \balance_db_reg[4][8] (.CK (clk), .D (\balance_db[4] [8]),
       .SI (n_19), .SE (n_30), .Q (\balance_db[4] [8]));
  SDFFQX1 \balance_db_reg[4][9] (.CK (clk), .D (\balance_db[4] [9]),
       .SI (n_59), .SE (n_30), .Q (\balance_db[4] [9]));
  SDFFQX1 \balance_db_reg[4][10] (.CK (clk), .D (\balance_db[4] [10]),
       .SI (n_32), .SE (n_30), .Q (\balance_db[4] [10]));
  SDFFQX1 \balance_db_reg[4][11] (.CK (clk), .D (\balance_db[4] [11]),
       .SI (n_71), .SE (n_30), .Q (\balance_db[4] [11]));
  SDFFQX1 \balance_db_reg[4][12] (.CK (clk), .D (\balance_db[4] [12]),
       .SI (n_33), .SE (n_30), .Q (\balance_db[4] [12]));
  SDFFQX1 \balance_db_reg[4][13] (.CK (clk), .D (\balance_db[4] [13]),
       .SI (n_72), .SE (n_30), .Q (\balance_db[4] [13]));
  SDFFQX1 \balance_db_reg[4][14] (.CK (clk), .D (\balance_db[4] [14]),
       .SI (n_47), .SE (n_30), .Q (\balance_db[4] [14]));
  SDFFQX1 \balance_db_reg[4][15] (.CK (clk), .D (\balance_db[4] [15]),
       .SI (n_78), .SE (n_30), .Q (\balance_db[4] [15]));
  SDFFQX1 \balance_db_reg[5][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[5] [1]), .SE (n_0), .Q (\balance_db[5] [1]));
  SDFFQX1 \balance_db_reg[5][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[5] [2]), .SE (n_0), .Q (\balance_db[5] [2]));
  SDFFQX1 \balance_db_reg[5][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[5] [3]), .SE (n_0), .Q (\balance_db[5] [3]));
  SDFFQX1 \balance_db_reg[5][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[5] [4]), .SE (n_0), .Q (\balance_db[5] [4]));
  SDFFQX1 \balance_db_reg[5][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[5] [5]), .SE (n_0), .Q (\balance_db[5] [5]));
  SDFFQX1 \balance_db_reg[5][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[5] [6]), .SE (n_0), .Q (\balance_db[5] [6]));
  SDFFQX1 \balance_db_reg[5][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[5] [7]), .SE (n_0), .Q (\balance_db[5] [7]));
  SDFFQX1 \balance_db_reg[5][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[5] [8]), .SE (n_0), .Q (\balance_db[5] [8]));
  SDFFQX1 \balance_db_reg[5][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[5] [9]), .SE (n_0), .Q (\balance_db[5] [9]));
  SDFFQX1 \balance_db_reg[5][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[5] [10]), .SE (n_0), .Q (\balance_db[5] [10]));
  SDFFQX1 \balance_db_reg[5][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[5] [11]), .SE (n_0), .Q (\balance_db[5] [11]));
  SDFFQX1 \balance_db_reg[5][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[5] [12]), .SE (n_0), .Q (\balance_db[5] [12]));
  SDFFQX1 \balance_db_reg[5][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[5] [13]), .SE (n_0), .Q (\balance_db[5] [13]));
  SDFFQX1 \balance_db_reg[5][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[5] [14]), .SE (n_0), .Q (\balance_db[5] [14]));
  SDFFQX1 \balance_db_reg[5][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[5] [15]), .SE (n_0), .Q (\balance_db[5] [15]));
  SDFFQX1 \balance_db_reg[6][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[6] [1]), .SE (n_44), .Q (\balance_db[6] [1]));
  SDFFQX1 \balance_db_reg[6][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[6] [2]), .SE (n_44), .Q (\balance_db[6] [2]));
  SDFFQX1 \balance_db_reg[6][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[6] [3]), .SE (n_44), .Q (\balance_db[6] [3]));
  SDFFQX1 \balance_db_reg[6][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[6] [4]), .SE (n_44), .Q (\balance_db[6] [4]));
  SDFFQX1 \balance_db_reg[6][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[6] [5]), .SE (n_44), .Q (\balance_db[6] [5]));
  SDFFQX1 \balance_db_reg[6][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[6] [6]), .SE (n_44), .Q (\balance_db[6] [6]));
  SDFFQX1 \balance_db_reg[6][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[6] [7]), .SE (n_44), .Q (\balance_db[6] [7]));
  SDFFQX1 \balance_db_reg[6][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[6] [8]), .SE (n_44), .Q (\balance_db[6] [8]));
  SDFFQX1 \balance_db_reg[6][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[6] [9]), .SE (n_44), .Q (\balance_db[6] [9]));
  SDFFQX1 \balance_db_reg[6][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[6] [10]), .SE (n_44), .Q (\balance_db[6] [10]));
  SDFFQX1 \balance_db_reg[6][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[6] [11]), .SE (n_44), .Q (\balance_db[6] [11]));
  SDFFQX1 \balance_db_reg[6][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[6] [12]), .SE (n_44), .Q (\balance_db[6] [12]));
  SDFFQX1 \balance_db_reg[6][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[6] [13]), .SE (n_44), .Q (\balance_db[6] [13]));
  SDFFQX1 \balance_db_reg[6][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[6] [14]), .SE (n_44), .Q (\balance_db[6] [14]));
  SDFFQX1 \balance_db_reg[6][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[6] [15]), .SE (n_44), .Q (\balance_db[6] [15]));
  SDFFQX1 \balance_db_reg[7][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[7] [1]), .SE (n_43), .Q (\balance_db[7] [1]));
  SDFFQX1 \balance_db_reg[7][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[7] [2]), .SE (n_43), .Q (\balance_db[7] [2]));
  SDFFQX1 \balance_db_reg[7][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[7] [3]), .SE (n_43), .Q (\balance_db[7] [3]));
  SDFFQX1 \balance_db_reg[7][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[7] [4]), .SE (n_43), .Q (\balance_db[7] [4]));
  SDFFQX1 \balance_db_reg[7][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[7] [5]), .SE (n_43), .Q (\balance_db[7] [5]));
  SDFFQX1 \balance_db_reg[7][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[7] [6]), .SE (n_43), .Q (\balance_db[7] [6]));
  SDFFQX1 \balance_db_reg[7][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[7] [7]), .SE (n_43), .Q (\balance_db[7] [7]));
  SDFFQX1 \balance_db_reg[7][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[7] [8]), .SE (n_43), .Q (\balance_db[7] [8]));
  SDFFQX1 \balance_db_reg[7][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[7] [9]), .SE (n_43), .Q (\balance_db[7] [9]));
  SDFFQX1 \balance_db_reg[7][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[7] [10]), .SE (n_43), .Q (\balance_db[7] [10]));
  SDFFQX1 \balance_db_reg[7][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[7] [11]), .SE (n_43), .Q (\balance_db[7] [11]));
  SDFFQX1 \balance_db_reg[7][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[7] [12]), .SE (n_43), .Q (\balance_db[7] [12]));
  SDFFQX1 \balance_db_reg[7][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[7] [13]), .SE (n_43), .Q (\balance_db[7] [13]));
  SDFFQX1 \balance_db_reg[7][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[7] [14]), .SE (n_43), .Q (\balance_db[7] [14]));
  SDFFQX1 \balance_db_reg[7][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[7] [15]), .SE (n_43), .Q (\balance_db[7] [15]));
  SDFFQX1 \balance_db_reg[8][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[8] [1]), .SE (n_49), .Q (\balance_db[8] [1]));
  SDFFQX1 \balance_db_reg[8][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[8] [2]), .SE (n_49), .Q (\balance_db[8] [2]));
  SDFFQX1 \balance_db_reg[8][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[8] [3]), .SE (n_49), .Q (\balance_db[8] [3]));
  SDFFQX1 \balance_db_reg[8][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[8] [4]), .SE (n_49), .Q (\balance_db[8] [4]));
  SDFFQX1 \balance_db_reg[8][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[8] [5]), .SE (n_49), .Q (\balance_db[8] [5]));
  SDFFQX1 \balance_db_reg[8][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[8] [6]), .SE (n_49), .Q (\balance_db[8] [6]));
  SDFFQX1 \balance_db_reg[8][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[8] [7]), .SE (n_49), .Q (\balance_db[8] [7]));
  SDFFQX1 \balance_db_reg[8][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[8] [8]), .SE (n_49), .Q (\balance_db[8] [8]));
  SDFFQX1 \balance_db_reg[8][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[8] [9]), .SE (n_49), .Q (\balance_db[8] [9]));
  SDFFQX1 \balance_db_reg[8][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[8] [10]), .SE (n_49), .Q (\balance_db[8] [10]));
  SDFFQX1 \balance_db_reg[8][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[8] [11]), .SE (n_49), .Q (\balance_db[8] [11]));
  SDFFQX1 \balance_db_reg[8][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[8] [12]), .SE (n_49), .Q (\balance_db[8] [12]));
  SDFFQX1 \balance_db_reg[8][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[8] [13]), .SE (n_49), .Q (\balance_db[8] [13]));
  SDFFQX1 \balance_db_reg[8][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[8] [14]), .SE (n_49), .Q (\balance_db[8] [14]));
  SDFFQX1 \balance_db_reg[8][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[8] [15]), .SE (n_49), .Q (\balance_db[8] [15]));
  SDFFQX1 \balance_db_reg[9][1] (.CK (clk), .D (\balance_db[9] [1]),
       .SI (n_4), .SE (n_1), .Q (\balance_db[9] [1]));
  SDFFQX1 \balance_db_reg[9][2] (.CK (clk), .D (\balance_db[9] [2]),
       .SI (n_40), .SE (n_1), .Q (\balance_db[9] [2]));
  SDFFQX1 \balance_db_reg[9][3] (.CK (clk), .D (\balance_db[9] [3]),
       .SI (n_58), .SE (n_1), .Q (\balance_db[9] [3]));
  SDFFQX1 \balance_db_reg[9][4] (.CK (clk), .D (\balance_db[9] [4]),
       .SI (n_41), .SE (n_1), .Q (\balance_db[9] [4]));
  SDFFQX1 \balance_db_reg[9][5] (.CK (clk), .D (\balance_db[9] [5]),
       .SI (n_57), .SE (n_1), .Q (\balance_db[9] [5]));
  SDFFQX1 \balance_db_reg[9][6] (.CK (clk), .D (\balance_db[9] [6]),
       .SI (n_55), .SE (n_1), .Q (\balance_db[9] [6]));
  SDFFQX1 \balance_db_reg[9][7] (.CK (clk), .D (\balance_db[9] [7]),
       .SI (n_70), .SE (n_1), .Q (\balance_db[9] [7]));
  SDFFQX1 \balance_db_reg[9][8] (.CK (clk), .D (\balance_db[9] [8]),
       .SI (n_19), .SE (n_1), .Q (\balance_db[9] [8]));
  SDFFQX1 \balance_db_reg[9][9] (.CK (clk), .D (\balance_db[9] [9]),
       .SI (n_59), .SE (n_1), .Q (\balance_db[9] [9]));
  SDFFQX1 \balance_db_reg[9][10] (.CK (clk), .D (\balance_db[9] [10]),
       .SI (n_32), .SE (n_1), .Q (\balance_db[9] [10]));
  SDFFQX1 \balance_db_reg[9][11] (.CK (clk), .D (\balance_db[9] [11]),
       .SI (n_71), .SE (n_1), .Q (\balance_db[9] [11]));
  SDFFQX1 \balance_db_reg[9][12] (.CK (clk), .D (\balance_db[9] [12]),
       .SI (n_33), .SE (n_1), .Q (\balance_db[9] [12]));
  SDFFQX1 \balance_db_reg[9][13] (.CK (clk), .D (\balance_db[9] [13]),
       .SI (n_72), .SE (n_1), .Q (\balance_db[9] [13]));
  SDFFQX1 \balance_db_reg[9][14] (.CK (clk), .D (\balance_db[9] [14]),
       .SI (n_47), .SE (n_1), .Q (\balance_db[9] [14]));
  SDFFQX1 \balance_db_reg[9][15] (.CK (clk), .D (\balance_db[9] [15]),
       .SI (n_78), .SE (n_1), .Q (\balance_db[9] [15]));
  SDFFQX1 \balance_db_reg[10][1] (.CK (clk), .D (\balance_db[10] [1]),
       .SI (n_4), .SE (n_51), .Q (\balance_db[10] [1]));
  SDFFQX1 \balance_db_reg[10][2] (.CK (clk), .D (\balance_db[10] [2]),
       .SI (n_40), .SE (n_51), .Q (\balance_db[10] [2]));
  SDFFQX1 \balance_db_reg[10][3] (.CK (clk), .D (\balance_db[10] [3]),
       .SI (n_58), .SE (n_51), .Q (\balance_db[10] [3]));
  SDFFQX1 \balance_db_reg[10][4] (.CK (clk), .D (\balance_db[10] [4]),
       .SI (n_41), .SE (n_51), .Q (\balance_db[10] [4]));
  SDFFQX1 \balance_db_reg[10][5] (.CK (clk), .D (\balance_db[10] [5]),
       .SI (n_57), .SE (n_51), .Q (\balance_db[10] [5]));
  SDFFQX1 \balance_db_reg[10][6] (.CK (clk), .D (\balance_db[10] [6]),
       .SI (n_55), .SE (n_51), .Q (\balance_db[10] [6]));
  SDFFQX1 \balance_db_reg[10][7] (.CK (clk), .D (\balance_db[10] [7]),
       .SI (n_70), .SE (n_51), .Q (\balance_db[10] [7]));
  SDFFQX1 \balance_db_reg[10][8] (.CK (clk), .D (\balance_db[10] [8]),
       .SI (n_19), .SE (n_51), .Q (\balance_db[10] [8]));
  SDFFQX1 \balance_db_reg[10][9] (.CK (clk), .D (\balance_db[10] [9]),
       .SI (n_59), .SE (n_51), .Q (\balance_db[10] [9]));
  SDFFQX1 \balance_db_reg[10][10] (.CK (clk), .D (\balance_db[10]
       [10]), .SI (n_32), .SE (n_51), .Q (\balance_db[10] [10]));
  SDFFQX1 \balance_db_reg[10][11] (.CK (clk), .D (\balance_db[10]
       [11]), .SI (n_71), .SE (n_51), .Q (\balance_db[10] [11]));
  SDFFQX1 \balance_db_reg[10][12] (.CK (clk), .D (\balance_db[10]
       [12]), .SI (n_33), .SE (n_51), .Q (\balance_db[10] [12]));
  SDFFQX1 \balance_db_reg[10][13] (.CK (clk), .D (\balance_db[10]
       [13]), .SI (n_72), .SE (n_51), .Q (\balance_db[10] [13]));
  SDFFQX1 \balance_db_reg[10][14] (.CK (clk), .D (\balance_db[10]
       [14]), .SI (n_47), .SE (n_51), .Q (\balance_db[10] [14]));
  SDFFQX1 \balance_db_reg[10][15] (.CK (clk), .D (\balance_db[10]
       [15]), .SI (n_78), .SE (n_51), .Q (\balance_db[10] [15]));
  SDFFQX1 \balance_db_reg[11][1] (.CK (clk), .D (\balance_db[11] [1]),
       .SI (n_4), .SE (n_52), .Q (\balance_db[11] [1]));
  SDFFQX1 \balance_db_reg[11][2] (.CK (clk), .D (\balance_db[11] [2]),
       .SI (n_40), .SE (n_52), .Q (\balance_db[11] [2]));
  SDFFQX1 \balance_db_reg[11][3] (.CK (clk), .D (\balance_db[11] [3]),
       .SI (n_58), .SE (n_52), .Q (\balance_db[11] [3]));
  SDFFQX1 \balance_db_reg[11][4] (.CK (clk), .D (\balance_db[11] [4]),
       .SI (n_41), .SE (n_52), .Q (\balance_db[11] [4]));
  SDFFQX1 \balance_db_reg[11][5] (.CK (clk), .D (\balance_db[11] [5]),
       .SI (n_57), .SE (n_52), .Q (\balance_db[11] [5]));
  SDFFQX1 \balance_db_reg[11][6] (.CK (clk), .D (\balance_db[11] [6]),
       .SI (n_55), .SE (n_52), .Q (\balance_db[11] [6]));
  SDFFQX1 \balance_db_reg[11][7] (.CK (clk), .D (\balance_db[11] [7]),
       .SI (n_70), .SE (n_52), .Q (\balance_db[11] [7]));
  SDFFQX1 \balance_db_reg[11][8] (.CK (clk), .D (\balance_db[11] [8]),
       .SI (n_19), .SE (n_52), .Q (\balance_db[11] [8]));
  SDFFQX1 \balance_db_reg[11][9] (.CK (clk), .D (\balance_db[11] [9]),
       .SI (n_59), .SE (n_52), .Q (\balance_db[11] [9]));
  SDFFQX1 \balance_db_reg[11][10] (.CK (clk), .D (\balance_db[11]
       [10]), .SI (n_32), .SE (n_52), .Q (\balance_db[11] [10]));
  SDFFQX1 \balance_db_reg[11][11] (.CK (clk), .D (\balance_db[11]
       [11]), .SI (n_71), .SE (n_52), .Q (\balance_db[11] [11]));
  SDFFQX1 \balance_db_reg[11][12] (.CK (clk), .D (\balance_db[11]
       [12]), .SI (n_33), .SE (n_52), .Q (\balance_db[11] [12]));
  SDFFQX1 \balance_db_reg[11][13] (.CK (clk), .D (\balance_db[11]
       [13]), .SI (n_72), .SE (n_52), .Q (\balance_db[11] [13]));
  SDFFQX1 \balance_db_reg[11][14] (.CK (clk), .D (\balance_db[11]
       [14]), .SI (n_47), .SE (n_52), .Q (\balance_db[11] [14]));
  SDFFQX1 \balance_db_reg[11][15] (.CK (clk), .D (\balance_db[11]
       [15]), .SI (n_78), .SE (n_52), .Q (\balance_db[11] [15]));
  SDFFQX1 \balance_db_reg[12][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[12] [1]), .SE (n_48), .Q (\balance_db[12] [1]));
  SDFFQX1 \balance_db_reg[12][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[12] [2]), .SE (n_48), .Q (\balance_db[12] [2]));
  SDFFQX1 \balance_db_reg[12][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[12] [3]), .SE (n_48), .Q (\balance_db[12] [3]));
  SDFFQX1 \balance_db_reg[12][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[12] [4]), .SE (n_48), .Q (\balance_db[12] [4]));
  SDFFQX1 \balance_db_reg[12][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[12] [5]), .SE (n_48), .Q (\balance_db[12] [5]));
  SDFFQX1 \balance_db_reg[12][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[12] [6]), .SE (n_48), .Q (\balance_db[12] [6]));
  SDFFQX1 \balance_db_reg[12][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[12] [7]), .SE (n_48), .Q (\balance_db[12] [7]));
  SDFFQX1 \balance_db_reg[12][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[12] [8]), .SE (n_48), .Q (\balance_db[12] [8]));
  SDFFQX1 \balance_db_reg[12][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[12] [9]), .SE (n_48), .Q (\balance_db[12] [9]));
  SDFFQX1 \balance_db_reg[12][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[12] [10]), .SE (n_48), .Q (\balance_db[12] [10]));
  SDFFQX1 \balance_db_reg[12][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[12] [11]), .SE (n_48), .Q (\balance_db[12] [11]));
  SDFFQX1 \balance_db_reg[12][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[12] [12]), .SE (n_48), .Q (\balance_db[12] [12]));
  SDFFQX1 \balance_db_reg[12][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[12] [13]), .SE (n_48), .Q (\balance_db[12] [13]));
  SDFFQX1 \balance_db_reg[12][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[12] [14]), .SE (n_48), .Q (\balance_db[12] [14]));
  SDFFQX1 \balance_db_reg[12][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[12] [15]), .SE (n_48), .Q (\balance_db[12] [15]));
  SDFFQX1 \balance_db_reg[13][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[13] [1]), .SE (n_42), .Q (\balance_db[13] [1]));
  SDFFQX1 \balance_db_reg[13][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[13] [2]), .SE (n_42), .Q (\balance_db[13] [2]));
  SDFFQX1 \balance_db_reg[13][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[13] [3]), .SE (n_42), .Q (\balance_db[13] [3]));
  SDFFQX1 \balance_db_reg[13][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[13] [4]), .SE (n_42), .Q (\balance_db[13] [4]));
  SDFFQX1 \balance_db_reg[13][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[13] [5]), .SE (n_42), .Q (\balance_db[13] [5]));
  SDFFQX1 \balance_db_reg[13][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[13] [6]), .SE (n_42), .Q (\balance_db[13] [6]));
  SDFFQX1 \balance_db_reg[13][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[13] [7]), .SE (n_42), .Q (\balance_db[13] [7]));
  SDFFQX1 \balance_db_reg[13][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[13] [8]), .SE (n_42), .Q (\balance_db[13] [8]));
  SDFFQX1 \balance_db_reg[13][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[13] [9]), .SE (n_42), .Q (\balance_db[13] [9]));
  SDFFQX1 \balance_db_reg[13][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[13] [10]), .SE (n_42), .Q (\balance_db[13] [10]));
  SDFFQX1 \balance_db_reg[13][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[13] [11]), .SE (n_42), .Q (\balance_db[13] [11]));
  SDFFQX1 \balance_db_reg[13][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[13] [12]), .SE (n_42), .Q (\balance_db[13] [12]));
  SDFFQX1 \balance_db_reg[13][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[13] [13]), .SE (n_42), .Q (\balance_db[13] [13]));
  SDFFQX1 \balance_db_reg[13][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[13] [14]), .SE (n_42), .Q (\balance_db[13] [14]));
  SDFFQX1 \balance_db_reg[13][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[13] [15]), .SE (n_42), .Q (\balance_db[13] [15]));
  SDFFQX1 \balance_db_reg[14][1] (.CK (clk), .D (\balance_db[14] [1]),
       .SI (n_4), .SE (n_50), .Q (\balance_db[14] [1]));
  SDFFQX1 \balance_db_reg[14][2] (.CK (clk), .D (\balance_db[14] [2]),
       .SI (n_40), .SE (n_50), .Q (\balance_db[14] [2]));
  SDFFQX1 \balance_db_reg[14][3] (.CK (clk), .D (\balance_db[14] [3]),
       .SI (n_58), .SE (n_50), .Q (\balance_db[14] [3]));
  SDFFQX1 \balance_db_reg[14][4] (.CK (clk), .D (\balance_db[14] [4]),
       .SI (n_41), .SE (n_50), .Q (\balance_db[14] [4]));
  SDFFQX1 \balance_db_reg[14][5] (.CK (clk), .D (\balance_db[14] [5]),
       .SI (n_57), .SE (n_50), .Q (\balance_db[14] [5]));
  SDFFQX1 \balance_db_reg[14][6] (.CK (clk), .D (\balance_db[14] [6]),
       .SI (n_55), .SE (n_50), .Q (\balance_db[14] [6]));
  SDFFQX1 \balance_db_reg[14][7] (.CK (clk), .D (\balance_db[14] [7]),
       .SI (n_70), .SE (n_50), .Q (\balance_db[14] [7]));
  SDFFQX1 \balance_db_reg[14][8] (.CK (clk), .D (\balance_db[14] [8]),
       .SI (n_19), .SE (n_50), .Q (\balance_db[14] [8]));
  SDFFQX1 \balance_db_reg[14][9] (.CK (clk), .D (\balance_db[14] [9]),
       .SI (n_59), .SE (n_50), .Q (\balance_db[14] [9]));
  SDFFQX1 \balance_db_reg[14][10] (.CK (clk), .D (\balance_db[14]
       [10]), .SI (n_32), .SE (n_50), .Q (\balance_db[14] [10]));
  SDFFQX1 \balance_db_reg[14][11] (.CK (clk), .D (\balance_db[14]
       [11]), .SI (n_71), .SE (n_50), .Q (\balance_db[14] [11]));
  SDFFQX1 \balance_db_reg[14][12] (.CK (clk), .D (\balance_db[14]
       [12]), .SI (n_33), .SE (n_50), .Q (\balance_db[14] [12]));
  SDFFQX1 \balance_db_reg[14][13] (.CK (clk), .D (\balance_db[14]
       [13]), .SI (n_72), .SE (n_50), .Q (\balance_db[14] [13]));
  SDFFQX1 \balance_db_reg[14][14] (.CK (clk), .D (\balance_db[14]
       [14]), .SI (n_47), .SE (n_50), .Q (\balance_db[14] [14]));
  SDFFQX1 \balance_db_reg[14][15] (.CK (clk), .D (\balance_db[14]
       [15]), .SI (n_78), .SE (n_50), .Q (\balance_db[14] [15]));
  SDFFQX1 \balance_db_reg[15][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[15] [1]), .SE (n_45), .Q (\balance_db[15] [1]));
  SDFFQX1 \balance_db_reg[15][2] (.CK (clk), .D (n_40), .SI
       (\balance_db[15] [2]), .SE (n_45), .Q (\balance_db[15] [2]));
  SDFFQX1 \balance_db_reg[15][3] (.CK (clk), .D (n_58), .SI
       (\balance_db[15] [3]), .SE (n_45), .Q (\balance_db[15] [3]));
  SDFFQX1 \balance_db_reg[15][4] (.CK (clk), .D (n_41), .SI
       (\balance_db[15] [4]), .SE (n_45), .Q (\balance_db[15] [4]));
  SDFFQX1 \balance_db_reg[15][5] (.CK (clk), .D (n_57), .SI
       (\balance_db[15] [5]), .SE (n_45), .Q (\balance_db[15] [5]));
  SDFFQX1 \balance_db_reg[15][6] (.CK (clk), .D (n_55), .SI
       (\balance_db[15] [6]), .SE (n_45), .Q (\balance_db[15] [6]));
  SDFFQX1 \balance_db_reg[15][7] (.CK (clk), .D (n_70), .SI
       (\balance_db[15] [7]), .SE (n_45), .Q (\balance_db[15] [7]));
  SDFFQX1 \balance_db_reg[15][8] (.CK (clk), .D (n_19), .SI
       (\balance_db[15] [8]), .SE (n_45), .Q (\balance_db[15] [8]));
  SDFFQX1 \balance_db_reg[15][9] (.CK (clk), .D (n_59), .SI
       (\balance_db[15] [9]), .SE (n_45), .Q (\balance_db[15] [9]));
  SDFFQX1 \balance_db_reg[15][10] (.CK (clk), .D (n_32), .SI
       (\balance_db[15] [10]), .SE (n_45), .Q (\balance_db[15] [10]));
  SDFFQX1 \balance_db_reg[15][11] (.CK (clk), .D (n_71), .SI
       (\balance_db[15] [11]), .SE (n_45), .Q (\balance_db[15] [11]));
  SDFFQX1 \balance_db_reg[15][12] (.CK (clk), .D (n_33), .SI
       (\balance_db[15] [12]), .SE (n_45), .Q (\balance_db[15] [12]));
  SDFFQX1 \balance_db_reg[15][13] (.CK (clk), .D (n_72), .SI
       (\balance_db[15] [13]), .SE (n_45), .Q (\balance_db[15] [13]));
  SDFFQX1 \balance_db_reg[15][14] (.CK (clk), .D (n_47), .SI
       (\balance_db[15] [14]), .SE (n_45), .Q (\balance_db[15] [14]));
  SDFFQX1 \balance_db_reg[15][15] (.CK (clk), .D (n_78), .SI
       (\balance_db[15] [15]), .SE (n_45), .Q (\balance_db[15] [15]));
  AO22XL g3379(.A0 (n_64), .A1 (n_78), .B0 (n_75), .B1
       (\balance_db[1] [15]), .Y (n_123));
  AO22XL g3380(.A0 (n_63), .A1 (n_78), .B0 (n_74), .B1
       (\balance_db[3] [15]), .Y (n_122));
  AO22XL g3381(.A0 (n_60), .A1 (n_78), .B0 (n_73), .B1
       (\balance_db[2] [15]), .Y (n_121));
  AO22XL g3468(.A0 (n_64), .A1 (n_47), .B0 (n_75), .B1
       (\balance_db[1] [14]), .Y (n_120));
  AO22XL g3469(.A0 (n_60), .A1 (n_72), .B0 (n_73), .B1
       (\balance_db[2] [13]), .Y (n_119));
  AO22XL g3470(.A0 (n_60), .A1 (n_71), .B0 (n_73), .B1
       (\balance_db[2] [11]), .Y (n_118));
  AO22XL g3471(.A0 (n_60), .A1 (n_59), .B0 (n_73), .B1
       (\balance_db[2] [9]), .Y (n_117));
  AO22XL g3472(.A0 (n_60), .A1 (n_70), .B0 (n_73), .B1
       (\balance_db[2] [7]), .Y (n_116));
  NAND2XL g3473(.A (n_3), .B (n_77), .Y (n_115));
  OAI211X1 g3475(.A0 (n_21), .A1 (n_2), .B0 (n_3), .C0 (n_76), .Y
       (n_113));
  OAI211X1 g3476(.A0 (n_21), .A1 (n_65), .B0 (n_3), .C0 (n_68), .Y
       (n_112));
  OAI211X1 g3477(.A0 (n_20), .A1 (n_2), .B0 (n_3), .C0 (n_69), .Y
       (n_111));
  OAI211X1 g3478(.A0 (n_31), .A1 (n_65), .B0 (n_3), .C0 (n_66), .Y
       (n_110));
  AO22XL g3479(.A0 (n_60), .A1 (n_47), .B0 (n_73), .B1
       (\balance_db[2] [14]), .Y (n_109));
  AO22XL g3480(.A0 (n_74), .A1 (\balance_db[3] [1]), .B0 (n_63), .B1
       (n_4), .Y (n_108));
  AO22XL g3481(.A0 (n_63), .A1 (n_55), .B0 (n_74), .B1
       (\balance_db[3] [6]), .Y (n_107));
  AO22XL g3482(.A0 (n_63), .A1 (n_19), .B0 (n_74), .B1
       (\balance_db[3] [8]), .Y (n_106));
  AO22XL g3483(.A0 (n_63), .A1 (n_32), .B0 (n_74), .B1
       (\balance_db[3] [10]), .Y (n_105));
  AO22XL g3484(.A0 (n_63), .A1 (n_33), .B0 (n_74), .B1
       (\balance_db[3] [12]), .Y (n_104));
  AO22XL g3485(.A0 (n_63), .A1 (n_47), .B0 (n_74), .B1
       (\balance_db[3] [14]), .Y (n_103));
  AO22XL g3486(.A0 (n_75), .A1 (\balance_db[1] [1]), .B0 (n_64), .B1
       (n_4), .Y (n_102));
  AO22XL g3487(.A0 (n_64), .A1 (n_41), .B0 (n_75), .B1
       (\balance_db[1] [4]), .Y (n_101));
  AO22XL g3488(.A0 (n_64), .A1 (n_19), .B0 (n_75), .B1
       (\balance_db[1] [8]), .Y (n_100));
  AO22XL g3489(.A0 (n_64), .A1 (n_32), .B0 (n_75), .B1
       (\balance_db[1] [10]), .Y (n_99));
  AO22XL g3490(.A0 (n_64), .A1 (n_33), .B0 (n_75), .B1
       (\balance_db[1] [12]), .Y (n_98));
  AO22XL g3491(.A0 (n_60), .A1 (n_57), .B0 (n_73), .B1
       (\balance_db[2] [5]), .Y (n_97));
  AO22XL g3492(.A0 (n_73), .A1 (\balance_db[2] [1]), .B0 (n_60), .B1
       (n_4), .Y (n_96));
  AO22XL g3493(.A0 (n_60), .A1 (n_41), .B0 (n_73), .B1
       (\balance_db[2] [4]), .Y (n_95));
  AO22XL g3494(.A0 (n_60), .A1 (n_55), .B0 (n_73), .B1
       (\balance_db[2] [6]), .Y (n_94));
  AO22XL g3495(.A0 (n_60), .A1 (n_19), .B0 (n_73), .B1
       (\balance_db[2] [8]), .Y (n_93));
  AO22XL g3496(.A0 (n_60), .A1 (n_32), .B0 (n_73), .B1
       (\balance_db[2] [10]), .Y (n_92));
  AO22XL g3497(.A0 (n_60), .A1 (n_33), .B0 (n_73), .B1
       (\balance_db[2] [12]), .Y (n_91));
  AO22XL g3498(.A0 (n_63), .A1 (n_58), .B0 (n_74), .B1
       (\balance_db[3] [3]), .Y (n_90));
  AO22XL g3499(.A0 (n_63), .A1 (n_57), .B0 (n_74), .B1
       (\balance_db[3] [5]), .Y (n_89));
  AO22XL g3500(.A0 (n_63), .A1 (n_70), .B0 (n_74), .B1
       (\balance_db[3] [7]), .Y (n_88));
  AO22XL g3501(.A0 (n_63), .A1 (n_59), .B0 (n_74), .B1
       (\balance_db[3] [9]), .Y (n_87));
  AO22XL g3502(.A0 (n_63), .A1 (n_71), .B0 (n_74), .B1
       (\balance_db[3] [11]), .Y (n_86));
  AO22XL g3503(.A0 (n_63), .A1 (n_72), .B0 (n_74), .B1
       (\balance_db[3] [13]), .Y (n_85));
  AO22XL g3504(.A0 (n_64), .A1 (n_58), .B0 (n_75), .B1
       (\balance_db[1] [3]), .Y (n_84));
  AO22XL g3505(.A0 (n_64), .A1 (n_70), .B0 (n_75), .B1
       (\balance_db[1] [7]), .Y (n_83));
  AO22XL g3506(.A0 (n_64), .A1 (n_59), .B0 (n_75), .B1
       (\balance_db[1] [9]), .Y (n_82));
  AO22XL g3507(.A0 (n_64), .A1 (n_71), .B0 (n_75), .B1
       (\balance_db[1] [11]), .Y (n_81));
  AO22XL g3508(.A0 (n_64), .A1 (n_72), .B0 (n_75), .B1
       (\balance_db[1] [13]), .Y (n_80));
  AO22XL g3509(.A0 (n_60), .A1 (n_58), .B0 (n_73), .B1
       (\balance_db[2] [3]), .Y (n_79));
  MXI2XL g3557(.A (\balance_db[2] [2]), .B (n_40), .S0 (n_62), .Y
       (n_77));
  CLKXOR2X1 g3599(.A (n_308), .B (n_36), .Y (n_78));
  NAND2XL g3600(.A (\balance_db[3] [2]), .B (n_2), .Y (n_76));
  NAND2XL g3609(.A (\balance_db[3] [4]), .B (n_2), .Y (n_69));
  NAND2XL g3610(.A (\balance_db[1] [2]), .B (n_65), .Y (n_68));
  NAND2XL g3612(.A (\balance_db[1] [6]), .B (n_65), .Y (n_66));
  OAI21X1 g3613(.A0 (reset), .A1 (n_54), .B0 (n_13), .Y (n_75));
  NAND2XL g3614(.A (n_13), .B (n_61), .Y (n_74));
  NAND2XL g3615(.A (n_61), .B (n_8), .Y (n_73));
  CLKXOR2X1 g3616(.A (n_306), .B (n_27), .Y (n_72));
  CLKXOR2X1 g3617(.A (n_304), .B (n_25), .Y (n_71));
  CLKXOR2X1 g3618(.A (n_300), .B (n_26), .Y (n_70));
  NOR2XL g3619(.A (id_to_check[0]), .B (n_53), .Y (n_62));
  NAND2XL g3621(.A (id_to_check[0]), .B (n_54), .Y (n_65));
  NOR2BX1 g3622(.AN (n_54), .B (n_8), .Y (n_64));
  NOR2XL g3623(.A (n_8), .B (n_53), .Y (n_63));
  NAND2XL g3625(.A (n_3), .B (n_53), .Y (n_61));
  NOR2XL g3626(.A (n_13), .B (n_53), .Y (n_60));
  CLKXOR2X1 g3627(.A (n_302), .B (n_15), .Y (n_59));
  CLKXOR2X1 g3628(.A (n_320), .B (n_16), .Y (n_58));
  CLKXOR2X1 g3629(.A (n_298), .B (n_18), .Y (n_57));
  CLKINVX1 g3630(.A (n_31), .Y (n_55));
  NOR2BX1 g3632(.AN (n_35), .B (id_to_check[1]), .Y (n_54));
  NAND2XL g3633(.A (id_to_check[1]), .B (n_35), .Y (n_53));
  NOR2X1 g3634(.A (n_34), .B (id_to_check[2]), .Y (n_52));
  NOR2X1 g3635(.A (n_37), .B (id_to_check[2]), .Y (n_51));
  NOR2X1 g3636(.A (n_37), .B (n_5), .Y (n_50));
  NAND2X1 g3637(.A (n_38), .B (n_5), .Y (n_49));
  NAND2X1 g3638(.A (n_38), .B (id_to_check[2]), .Y (n_48));
  AO21X1 g3639(.A0 (n_307), .A1 (n_28), .B0 (n_36), .Y (n_47));
  AND3X1 g3640(.A (n_23), .B (n_5), .C (n_12), .Y (n_46));
  OR2X1 g3641(.A (n_34), .B (n_5), .Y (n_45));
  NAND3X1 g3643(.A (n_14), .B (id_to_check[1]), .C (n_22), .Y (n_44));
  NAND3X1 g3644(.A (n_7), .B (id_to_check[1]), .C (n_22), .Y (n_43));
  NAND2X1 g3645(.A (n_39), .B (id_to_check[2]), .Y (n_42));
  CLKINVX1 g3646(.A (n_20), .Y (n_41));
  CLKINVX1 g3647(.A (n_21), .Y (n_40));
  NOR2XL g3649(.A (n_24), .B (n_17), .Y (n_39));
  NOR2BX1 g3650(.AN (n_23), .B (n_17), .Y (n_38));
  NAND2XL g3651(.A (n_14), .B (n_29), .Y (n_37));
  NOR2XL g3652(.A (n_307), .B (n_28), .Y (n_36));
  NOR4BX1 g3654(.AN (fsm_charge_req), .B (id_to_check[2]), .C
       (id_to_check[3]), .D (n_309), .Y (n_35));
  NAND2XL g3655(.A (n_7), .B (n_29), .Y (n_34));
  AO21X1 g3656(.A0 (n_305), .A1 (n_9), .B0 (n_27), .Y (n_33));
  AO21X1 g3657(.A0 (n_303), .A1 (n_11), .B0 (n_25), .Y (n_32));
  AOI21X1 g3658(.A0 (n_299), .A1 (n_10), .B0 (n_26), .Y (n_31));
  AND2X1 g3659(.A (n_23), .B (n_22), .Y (n_30));
  NOR2XL g3660(.A (n_6), .B (n_17), .Y (n_29));
  NAND2BX1 g3661(.AN (n_9), .B (n_315), .Y (n_28));
  NOR2XL g3662(.A (n_305), .B (n_9), .Y (n_27));
  NOR2XL g3663(.A (n_299), .B (n_10), .Y (n_26));
  NOR2XL g3664(.A (n_303), .B (n_11), .Y (n_25));
  NAND2XL g3666(.A (n_7), .B (n_6), .Y (n_24));
  NOR2XL g3667(.A (n_13), .B (id_to_check[1]), .Y (n_23));
  AND2X1 g3668(.A (id_to_check[2]), .B (n_12), .Y (n_22));
  AOI21X1 g3669(.A0 (n_296), .A1 (n_311), .B0 (n_16), .Y (n_21));
  AOI21X1 g3670(.A0 (n_297), .A1 (n_314), .B0 (n_18), .Y (n_20));
  AO21X1 g3671(.A0 (n_301), .A1 (n_313), .B0 (n_15), .Y (n_19));
  CLKINVX1 g3672(.A (n_14), .Y (n_13));
  NOR2XL g3673(.A (n_297), .B (n_314), .Y (n_18));
  NAND2XL g3674(.A (id_to_check[3]), .B (n_310), .Y (n_17));
  NOR2XL g3675(.A (n_296), .B (n_311), .Y (n_16));
  NOR2XL g3676(.A (n_301), .B (n_313), .Y (n_15));
  NOR2XL g3677(.A (reset), .B (id_to_check[0]), .Y (n_14));
  INVX1 g3678(.A (n_8), .Y (n_7));
  NOR2BX1 g3679(.AN (n_310), .B (id_to_check[3]), .Y (n_12));
  NAND2BX1 g3680(.AN (n_313), .B (n_316), .Y (n_11));
  NAND2BX1 g3681(.AN (n_314), .B (n_317), .Y (n_10));
  NAND2BX1 g3682(.AN (n_313), .B (n_312), .Y (n_9));
  NAND2XL g3683(.A (n_3), .B (id_to_check[0]), .Y (n_8));
  CLKINVX1 g3684(.A (id_to_check[1]), .Y (n_6));
  CLKINVX1 g3685(.A (id_to_check[2]), .Y (n_5));
  CLKINVX1 g3686(.A (n_311), .Y (n_4));
  CLKINVX1 g3687(.A (reset), .Y (n_3));
  NAND2BX1 g2(.AN (n_53), .B (id_to_check[0]), .Y (n_2));
  NOR2BX1 g3688(.AN (n_39), .B (id_to_check[2]), .Y (n_1));
  NAND2BX1 g3689(.AN (n_24), .B (n_22), .Y (n_0));
  NOR2BXL g17078(.AN (n_310), .B (reset), .Y (n_323));
  NAND2XL g17079(.A (n_324), .B (n_3), .Y (n_325));
  MXI2XL g3(.A (n_57), .B (\balance_db[1] [5]), .S0 (n_65), .Y (n_324));
endmodule

module barrier_ctrl(clk, reset, fsm_open_en, fsm_close_en,
     barrier_open_cmd, barrier_close_cmd, gate_is_open, gate_is_closed);
  input clk, reset, fsm_open_en, fsm_close_en;
  output barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed;
  wire clk, reset, fsm_open_en, fsm_close_en;
  wire barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed;
  wire [2:0] barrier_position_counter;
  wire n_0, n_3, n_4, n_5, n_6, n_8, n_10, n_11;
  wire n_12, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_23, n_24, n_25, n_26, n_27, n_32, n_33, n_34;
  wire n_35;
  INVXL g223(.A (n_24), .Y (gate_is_closed));
  DFFQXL barrier_close_cmd_reg(.CK (clk), .D (n_20), .Q
       (barrier_close_cmd));
  DFFQXL barrier_open_cmd_reg(.CK (clk), .D (n_19), .Q
       (barrier_open_cmd));
  OAI21X1 g329(.A0 (n_26), .A1 (n_25), .B0 (n_16), .Y (n_20));
  INVXL g330(.A (n_18), .Y (n_19));
  AOI31X1 g331(.A0 (n_16), .A1 (fsm_open_en), .A2 (n_25), .B0 (n_26),
       .Y (n_18));
  NOR2XL g332(.A (reset), .B (n_23), .Y (n_26));
  OAI21X1 g333(.A0 (n_27), .A1 (n_17), .B0 (fsm_open_en), .Y (n_23));
  OR3X1 g334(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[2]), .C (barrier_position_counter[1]),
       .Y (n_24));
  NAND2XL g335(.A (barrier_position_counter[2]), .B
       (barrier_position_counter[1]), .Y (n_17));
  CLKINVX1 g336(.A (fsm_close_en), .Y (n_25));
  INVX1 g337(.A (barrier_position_counter[0]), .Y (n_27));
  INVX1 g338(.A (reset), .Y (n_16));
  DFFQX1 \barrier_position_counter_reg[2] (.CK (clk), .D (n_15), .Q
       (barrier_position_counter[2]));
  MXI2XL g473(.A (n_33), .B (n_32), .S0 (barrier_position_counter[2]),
       .Y (n_15));
  DFFQX1 \barrier_position_counter_reg[1] (.CK (clk), .D (n_12), .Q
       (barrier_position_counter[1]));
  DFFQX1 \barrier_position_counter_reg[0] (.CK (clk), .D (n_14), .Q
       (barrier_position_counter[0]));
  OAI2BB1X1 g476(.A0N (n_34), .A1N (barrier_position_counter[0]), .B0
       (n_11), .Y (n_14));
  OAI21X1 g478(.A0 (n_5), .A1 (n_4), .B0 (n_10), .Y (n_12));
  OAI21X1 g479(.A0 (n_6), .A1 (n_26), .B0 (n_27), .Y (n_11));
  AOI22X1 g480(.A0 (n_34), .A1 (barrier_position_counter[1]), .B0
       (n_26), .B1 (n_4), .Y (n_10));
  NOR2XL g482(.A (n_5), .B (n_3), .Y (n_8));
  CLKINVX1 g484(.A (n_6), .Y (n_5));
  NOR4BX1 g485(.AN (n_24), .B (reset), .C (n_25), .D (n_0), .Y (n_6));
  NOR2XL g486(.A (n_35), .B (n_3), .Y (n_4));
  NOR2XL g487(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_3));
  INVX1 g490(.A (n_23), .Y (n_0));
  NOR3XL g2(.A (n_26), .B (n_34), .C (n_8), .Y (n_32));
  NAND2XL g491(.A (n_26), .B (n_35), .Y (n_33));
  NOR3X1 g492(.A (fsm_close_en), .B (reset), .C (n_0), .Y (n_34));
  AND2X1 g493(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_35));
endmodule

module vehicle_interface(clk, reset, fsm_read_en, vehicle_id_in,
     id_to_check, id_valid);
  input clk, reset, fsm_read_en;
  input [7:0] vehicle_id_in;
  output [3:0] id_to_check;
  output id_valid;
  wire clk, reset, fsm_read_en;
  wire [7:0] vehicle_id_in;
  wire [3:0] id_to_check;
  wire id_valid;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_16;
  DFFQX1 id_valid_reg(.CK (clk), .D (n_16), .Q (id_valid));
  DFFQX1 \id_to_check_reg[0] (.CK (clk), .D (n_6), .Q (id_to_check[0]));
  DFFQX1 \id_to_check_reg[1] (.CK (clk), .D (n_7), .Q (id_to_check[1]));
  DFFQX1 \id_to_check_reg[3] (.CK (clk), .D (n_4), .Q (id_to_check[3]));
  DFFQX1 \id_to_check_reg[2] (.CK (clk), .D (n_5), .Q (id_to_check[2]));
  NOR2XL g25(.A (reset), .B (n_3), .Y (n_7));
  NOR2XL g26(.A (reset), .B (n_2), .Y (n_6));
  NOR2XL g27(.A (reset), .B (n_1), .Y (n_5));
  NOR2XL g28(.A (reset), .B (n_0), .Y (n_4));
  MXI2XL g29(.A (id_to_check[1]), .B (vehicle_id_in[1]), .S0
       (fsm_read_en), .Y (n_3));
  MXI2XL g30(.A (id_to_check[0]), .B (vehicle_id_in[0]), .S0
       (fsm_read_en), .Y (n_2));
  MXI2XL g31(.A (id_to_check[2]), .B (vehicle_id_in[2]), .S0
       (fsm_read_en), .Y (n_1));
  MXI2XL g32(.A (id_to_check[3]), .B (vehicle_id_in[3]), .S0
       (fsm_read_en), .Y (n_0));
  NOR2BXL g2(.AN (fsm_read_en), .B (reset), .Y (n_16));
endmodule

module toll_gate(clk, reset, sensor_vehicle_enter, sensor_vehicle_exit,
     vehicle_id_in, barrier_open_cmd, barrier_close_cmd, led_status,
     display_out);
  input clk, reset, sensor_vehicle_enter, sensor_vehicle_exit;
  input [7:0] vehicle_id_in;
  output barrier_open_cmd, barrier_close_cmd;
  output [1:0] led_status;
  output [7:0] display_out;
  wire clk, reset, sensor_vehicle_enter, sensor_vehicle_exit;
  wire [7:0] vehicle_id_in;
  wire barrier_open_cmd, barrier_close_cmd;
  wire [1:0] led_status;
  wire [7:0] display_out;
  wire [3:0] id_to_check;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire charge_done, gate_is_closed, gate_is_open, id_valid, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_19, n_20;
  wire n_21, n_22, n_28, n_29, n_32, n_35, n_36, sufficient_balance;
  assign display_out[4] = 1'b0;
  assign display_out[7] = 1'b0;
  account_balance u_account_balance(.clk (clk), .reset (reset),
       .id_to_check ({UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED, id_to_check}), .fsm_check_req (n_28),
       .fsm_charge_req (n_35), .sufficient_balance
       (sufficient_balance), .charge_done (charge_done));
  barrier_ctrl u_barrier_ctrl(.clk (clk), .reset (reset), .fsm_open_en
       (n_32), .fsm_close_en (n_29), .barrier_open_cmd
       (barrier_open_cmd), .barrier_close_cmd (barrier_close_cmd),
       .gate_is_open (gate_is_open), .gate_is_closed (gate_is_closed));
  vehicle_interface u_vehicle_interface(.clk (clk), .reset (reset),
       .fsm_read_en (n_36), .vehicle_id_in ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       vehicle_id_in[3:0]}), .id_to_check (id_to_check), .id_valid
       (id_valid));
  INVXL g482(.A (n_32), .Y (led_status[0]));
  INVXL g481(.A (display_out[5]), .Y (display_out[6]));
  INVXL g483(.A (sensor_vehicle_enter), .Y (n_22));
  OR2X1 g662(.A (n_32), .B (n_35), .Y (led_status[1]));
  NAND2BXL g663(.AN (n_32), .B (display_out[2]), .Y (display_out[1]));
  NOR2XL g664(.A (n_1), .B (n_21), .Y (display_out[5]));
  OAI211XL g665(.A0 (state[2]), .A1 (state[0]), .B0 (n_1), .C0 (n_21),
       .Y (display_out[0]));
  NOR2XL g666(.A (state[1]), .B (n_21), .Y (n_32));
  OAI21XL g667(.A0 (n_20), .A1 (n_17), .B0 (display_out[2]), .Y
       (display_out[3]));
  OAI32X1 g668(.A0 (state[2]), .A1 (state[0]), .A2 (state[1]), .B0
       (n_17), .B1 (n_19), .Y (n_29));
  NAND2XL g669(.A (n_17), .B (n_20), .Y (display_out[2]));
  NOR3X1 g670(.A (state[2]), .B (state[1]), .C (n_0), .Y (n_36));
  NOR3X1 g671(.A (state[2]), .B (n_0), .C (n_1), .Y (n_35));
  NAND2XL g672(.A (state[0]), .B (state[2]), .Y (n_21));
  CLKINVX1 g673(.A (n_19), .Y (n_20));
  NOR2XL g674(.A (state[2]), .B (n_1), .Y (n_28));
  NAND2XL g675(.A (state[1]), .B (n_0), .Y (n_19));
  CLKINVX1 g676(.A (state[1]), .Y (n_1));
  CLKINVX1 g677(.A (state[0]), .Y (n_0));
  INVX1 g678(.A (state[2]), .Y (n_17));
  DFFQX1 \state_reg[1] (.CK (clk), .D (n_16), .Q (state[1]));
  DFFQX1 \state_reg[0] (.CK (clk), .D (n_15), .Q (state[0]));
  OAI221X1 g779(.A0 (n_12), .A1 (n_0), .B0 (n_8), .B1 (n_6), .C0
       (n_10), .Y (n_16));
  DFFQX1 \state_reg[2] (.CK (clk), .D (n_14), .Q (state[2]));
  OAI221XL g781(.A0 (n_8), .A1 (n_3), .B0 (sensor_vehicle_exit), .B1
       (n_11), .C0 (n_13), .Y (n_15));
  OAI211X1 g782(.A0 (n_8), .A1 (n_5), .B0 (n_10), .C0 (n_11), .Y
       (n_14));
  NAND2XL g783(.A (n_4), .B (n_9), .Y (n_13));
  AOI32X1 g784(.A0 (n_4), .A1 (id_valid), .A2 (n_1), .B0
       (sensor_vehicle_exit), .B1 (n_7), .Y (n_12));
  NAND2BX1 g785(.AN (n_0), .B (n_7), .Y (n_11));
  OAI32X1 g786(.A0 (n_22), .A1 (state[1]), .A2 (state[0]), .B0
       (id_valid), .B1 (n_0), .Y (n_9));
  OR4XL g787(.A (n_2), .B (state[0]), .C (n_1), .D (gate_is_closed), .Y
       (n_10));
  NAND2XL g788(.A (n_4), .B (state[1]), .Y (n_8));
  INVXL g789(.A (n_5), .Y (n_6));
  NOR2XL g790(.A (n_2), .B (state[1]), .Y (n_7));
  AOI21X1 g791(.A0 (charge_done), .A1 (state[0]), .B0 (n_3), .Y (n_5));
  NOR2XL g792(.A (reset), .B (state[2]), .Y (n_4));
  NOR2XL g793(.A (state[0]), .B (sufficient_balance), .Y (n_3));
  NAND2BX1 g794(.AN (reset), .B (state[2]), .Y (n_2));
endmodule

