
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 11 2025 19:10:29 IST (Oct 11 2025 13:40:29 UTC)

// Verification Directory fv/toll_gate 

module account_balance(clk, reset, id_to_check, fsm_check_req,
     fsm_charge_req, sufficient_balance, charge_done);
  input clk, reset, fsm_check_req, fsm_charge_req;
  input [7:0] id_to_check;
  output sufficient_balance, charge_done;
  wire clk, reset, fsm_check_req, fsm_charge_req;
  wire [7:0] id_to_check;
  wire sufficient_balance, charge_done;
  wire [15:0] \balance_db[4] ;
  wire [15:0] \balance_db[14] ;
  wire [15:0] \balance_db[5] ;
  wire [15:0] \balance_db[6] ;
  wire [15:0] \balance_db[12] ;
  wire [15:0] \balance_db[11] ;
  wire [15:0] \balance_db[10] ;
  wire [15:0] \balance_db[1] ;
  wire [15:0] \balance_db[13] ;
  wire [15:0] \balance_db[7] ;
  wire [15:0] \balance_db[0] ;
  wire [15:0] \balance_db[3] ;
  wire [15:0] \balance_db[8] ;
  wire [15:0] \balance_db[9] ;
  wire [15:0] \balance_db[2] ;
  wire [15:0] \balance_db[15] ;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_7, n_8;
  wire n_9, n_10, n_11, n_12, n_13, n_14, n_15, n_16;
  wire n_17, n_18, n_19, n_20, n_21, n_22, n_23, n_24;
  wire n_25, n_26, n_27, n_28, n_29, n_30, n_31, n_32;
  wire n_33, n_34, n_35, n_36, n_37, n_38, n_39, n_40;
  wire n_41, n_42, n_43, n_44, n_45, n_46, n_47, n_48;
  wire n_49, n_50, n_51, n_52, n_53, n_54, n_55, n_56;
  wire n_57, n_58, n_59, n_60, n_61, n_62, n_64, n_65;
  wire n_66, n_67, n_68, n_69, n_70, n_71, n_72, n_73;
  wire n_74, n_75, n_76, n_77, n_79, n_81, n_82, n_83;
  wire n_84, n_85, n_86, n_87, n_88, n_89, n_90, n_91;
  wire n_92, n_93, n_94, n_95, n_97, n_98, n_99, n_100;
  wire n_101, n_102, n_103, n_104, n_105, n_106, n_107, n_108;
  wire n_109, n_110, n_111, n_112, n_113, n_114, n_116, n_117;
  wire n_118, n_119, n_120, n_121, n_122, n_123, n_124, n_125;
  wire n_126, n_127, n_128, n_129, n_130, n_131, n_132, n_134;
  wire n_135, n_136, n_137, n_138, n_139, n_140, n_141, n_142;
  wire n_143, n_144, n_145, n_147, n_148, n_152, n_153, n_154;
  wire n_155, n_156, n_157, n_158, n_159, n_160, n_161, n_162;
  wire n_163, n_164, n_165, n_166, n_167, n_168, n_169, n_170;
  wire n_171, n_172, n_173, n_174, n_175, n_176, n_177, n_178;
  wire n_179, n_180, n_181, n_182, n_183, n_184, n_185, n_186;
  wire n_187, n_188, n_189, n_190, n_191, n_192, n_193, n_194;
  wire n_195, n_196, n_197, n_198, n_199, n_200, n_202, n_203;
  wire n_204, n_205, n_206, n_207, n_209, n_210, n_211, n_212;
  wire n_213, n_214, n_215, n_216, n_217, n_218, n_219, n_220;
  wire n_221, n_222, n_223, n_224, n_225, n_226, n_227, n_228;
  wire n_229, n_230, n_231, n_233, n_234, n_235, n_236, n_237;
  wire n_238, n_239, n_240, n_241, n_243, n_244, n_245, n_246;
  wire n_247, n_248, n_249, n_250, n_251, n_252, n_253, n_254;
  wire n_255, n_257, n_258, n_259, n_260, n_261, n_262, n_263;
  wire n_264, n_265, n_266, n_267, n_268, n_269, n_270, n_271;
  wire n_272, n_273, n_274, n_275, n_276, n_277, n_278, n_280;
  wire n_281, n_282, n_283, n_284, n_285, n_286, n_287, n_288;
  wire n_289, n_290, n_291, n_292, n_293, n_294, n_295, n_296;
  wire n_297, n_298, n_299, n_300, n_301, n_302, n_303, n_304;
  wire n_305, n_306, n_307, n_308, n_309, n_310, n_311, n_312;
  wire n_313, n_314, n_315, n_316, n_317, n_318, n_319, n_320;
  wire n_321, n_322, n_323, n_324, n_325, n_326, n_327, n_328;
  wire n_329, n_330, n_331, n_332, n_333, n_334, n_335, n_336;
  wire n_337, n_338, n_339, n_340, n_341, n_342, n_343, n_344;
  wire n_345, n_346, n_347, n_348, n_349, n_350, n_351, n_352;
  wire n_353, n_354, n_355, n_356, n_357, n_359, n_360, n_361;
  wire n_362, n_363, n_364, n_365, n_366, n_367, n_371, n_372;
  wire n_373, n_374, n_375, n_376, n_377, n_378, n_379, n_380;
  wire n_381, n_382, n_384, n_385, n_386, n_387, n_388, n_389;
  wire n_390, n_391, n_392, n_395, n_398, n_399, n_400, n_401;
  wire n_404, n_405, n_406, n_407, n_408;
  INVXL g1597(.A (n_384), .Y (sufficient_balance));
  DFFQX1 charge_done_reg(.CK (clk), .D (n_398), .Q (charge_done));
  NOR2BX1 g17134(.AN (fsm_charge_req), .B (n_384), .Y (n_385));
  OAI21X1 g17135(.A0 (n_388), .A1 (n_367), .B0 (fsm_check_req), .Y
       (n_384));
  NAND4BXL g17136(.AN (n_382), .B (n_365), .C (n_390), .D (n_387), .Y
       (n_367));
  NAND3BX1 g17137(.AN (n_374), .B (n_392), .C (n_366), .Y (n_388));
  NOR3BX1 g17138(.AN (n_391), .B (n_378), .C (n_379), .Y (n_387));
  NOR2XL g17139(.A (n_381), .B (n_380), .Y (n_390));
  NOR2XL g17140(.A (n_377), .B (n_376), .Y (n_391));
  NOR2XL g17141(.A (n_389), .B (n_375), .Y (n_366));
  NOR2XL g17142(.A (n_372), .B (n_373), .Y (n_392));
  NAND3X1 g17143(.A (n_277), .B (n_347), .C (n_364), .Y (n_373));
  NAND2XL g17144(.A (n_363), .B (n_408), .Y (n_376));
  NAND4XL g17145(.A (n_355), .B (n_283), .C (n_284), .D (n_315), .Y
       (n_380));
  NAND3X1 g17146(.A (n_353), .B (n_308), .C (n_342), .Y (n_379));
  NAND3X1 g17147(.A (n_275), .B (n_352), .C (n_362), .Y (n_377));
  AOI2BB1X1 g17148(.A0N (n_386), .A1N (n_371), .B0 (n_395), .Y (n_389));
  NAND4BXL g17150(.AN (n_324), .B (n_323), .C (n_311), .D (n_345), .Y
       (n_381));
  AOI2BB1X1 g17151(.A0N (n_171), .A1N (n_303), .B0 (n_356), .Y (n_395));
  NOR2XL g17152(.A (n_360), .B (n_350), .Y (n_365));
  NAND4XL g17153(.A (n_309), .B (n_317), .C (n_280), .D (n_357), .Y
       (n_382));
  AOI211X1 g17154(.A0 (\balance_db[4] [5]), .A1 (n_209), .B0 (n_351),
       .C0 (n_325), .Y (n_364));
  AOI211X1 g17155(.A0 (\balance_db[4] [8]), .A1 (n_209), .B0 (n_348),
       .C0 (n_326), .Y (n_363));
  AOI21X1 g17156(.A0 (n_167), .A1 (n_295), .B0 (n_354), .Y (n_362));
  NAND3X1 g17157(.A (n_316), .B (n_340), .C (n_359), .Y (n_374));
  OAI211X1 g17158(.A0 (n_166), .A1 (n_333), .B0 (n_329), .C0 (n_361),
       .Y (n_375));
  NOR2BX1 g17159(.AN (n_310), .B (n_343), .Y (n_361));
  OAI211X1 g17160(.A0 (n_168), .A1 (n_297), .B0 (n_278), .C0 (n_307),
       .Y (n_360));
  AOI21X1 g17161(.A0 (n_167), .A1 (n_332), .B0 (n_330), .Y (n_359));
  NAND2XL g17163(.A (n_338), .B (n_344), .Y (n_372));
  NAND4XL g17164(.A (n_306), .B (n_274), .C (n_273), .D (n_346), .Y
       (n_378));
  AOI211X1 g17165(.A0 (\balance_db[14] [14]), .A1 (n_219), .B0 (n_334),
       .C0 (n_322), .Y (n_357));
  OAI222XL g17166(.A0 (n_166), .A1 (n_271), .B0 (n_165), .B1 (n_301),
       .C0 (n_263), .C1 (n_168), .Y (n_356));
  OA22X1 g17167(.A0 (n_166), .A1 (n_312), .B0 (n_165), .B1 (n_314), .Y
       (n_355));
  OAI21X1 g17168(.A0 (n_165), .A1 (n_300), .B0 (n_255), .Y (n_354));
  OA22X1 g17169(.A0 (n_166), .A1 (n_304), .B0 (n_165), .B1 (n_305), .Y
       (n_353));
  NAND2XL g17170(.A (n_337), .B (n_339), .Y (n_371));
  NAND3X1 g17171(.A (n_336), .B (n_331), .C (n_341), .Y (n_386));
  AOI21X1 g17172(.A0 (\balance_db[5] [9]), .A1 (n_210), .B0 (n_319), .Y
       (n_352));
  NOR2XL g17173(.A (n_166), .B (n_299), .Y (n_351));
  OAI211X1 g17174(.A0 (n_171), .A1 (n_240), .B0 (n_287), .C0 (n_328),
       .Y (n_350));
  OAI2BB1X1 g17175(.A0N (\balance_db[5] [8]), .A1N (n_210), .B0
       (n_321), .Y (n_349));
  NOR2XL g17176(.A (n_166), .B (n_302), .Y (n_348));
  AOI21X1 g17177(.A0 (\balance_db[5] [5]), .A1 (n_210), .B0 (n_320), .Y
       (n_347));
  AOI21X1 g17178(.A0 (n_167), .A1 (n_294), .B0 (n_318), .Y (n_346));
  AOI221X1 g17179(.A0 (\balance_db[4] [13]), .A1 (n_209), .B0
       (\balance_db[6] [13]), .B1 (n_215), .C0 (n_335), .Y (n_345));
  AOI22X1 g17180(.A0 (n_167), .A1 (n_264), .B0 (n_170), .B1 (n_267), .Y
       (n_344));
  OAI211X1 g17181(.A0 (n_165), .A1 (n_243), .B0 (n_257), .C0 (n_281),
       .Y (n_343));
  AOI221X1 g17182(.A0 (\balance_db[12] [11]), .A1 (n_216), .B0
       (\balance_db[11] [11]), .B1 (n_218), .C0 (n_327), .Y (n_342));
  AOI22X1 g17183(.A0 (n_167), .A1 (n_259), .B0 (n_170), .B1 (n_266), .Y
       (n_341));
  AOI221X1 g17184(.A0 (\balance_db[10] [6]), .A1 (n_213), .B0
       (\balance_db[11] [6]), .B1 (n_218), .C0 (n_313), .Y (n_340));
  AOI22X1 g17185(.A0 (n_167), .A1 (n_260), .B0 (n_170), .B1 (n_262), .Y
       (n_339));
  AOI22X1 g17186(.A0 (n_169), .A1 (n_268), .B0 (n_164), .B1 (n_272), .Y
       (n_338));
  AOI22X1 g17187(.A0 (n_169), .A1 (n_265), .B0 (n_164), .B1 (n_269), .Y
       (n_337));
  NAND2XL g17188(.A (n_169), .B (n_261), .Y (n_336));
  NOR2XL g17189(.A (n_168), .B (n_291), .Y (n_335));
  NOR2XL g17190(.A (n_165), .B (n_289), .Y (n_334));
  AOI21X1 g17191(.A0 (\balance_db[1] [7]), .A1 (n_158), .B0 (n_298), .Y
       (n_333));
  OAI2BB1X1 g17192(.A0N (\balance_db[1] [6]), .A1N (n_158), .B0
       (n_293), .Y (n_332));
  NAND2XL g17193(.A (n_164), .B (n_270), .Y (n_331));
  NAND2XL g17194(.A (n_285), .B (n_286), .Y (n_330));
  AOI221X1 g17195(.A0 (\balance_db[12] [7]), .A1 (n_143), .B0
       (\balance_db[13] [7]), .B1 (n_211), .C0 (n_282), .Y (n_329));
  AOI221X1 g17196(.A0 (\balance_db[10] [15]), .A1 (n_213), .B0
       (\balance_db[7] [15]), .B1 (n_214), .C0 (n_276), .Y (n_328));
  NOR2XL g17197(.A (n_168), .B (n_292), .Y (n_327));
  AOI21X1 g17198(.A0 (n_239), .A1 (n_238), .B0 (n_165), .Y (n_326));
  AOI21X1 g17199(.A0 (n_231), .A1 (n_230), .B0 (n_165), .Y (n_325));
  AOI21XL g17200(.A0 (n_248), .A1 (n_249), .B0 (n_171), .Y (n_324));
  OAI2BB1XL g17201(.A0N (n_246), .A1N (n_247), .B0 (n_167), .Y (n_323));
  AOI21X1 g17202(.A0 (n_244), .A1 (n_245), .B0 (n_171), .Y (n_322));
  OAI21X1 g17203(.A0 (n_405), .A1 (n_404), .B0 (n_170), .Y (n_321));
  AOI21X1 g17204(.A0 (n_236), .A1 (n_237), .B0 (n_171), .Y (n_320));
  AOI21X1 g17205(.A0 (n_234), .A1 (n_235), .B0 (n_171), .Y (n_319));
  AOI21X1 g17206(.A0 (n_229), .A1 (n_228), .B0 (n_171), .Y (n_318));
  AOI222XL g17207(.A0 (\balance_db[0] [14]), .A1 (n_223), .B0
       (\balance_db[1] [14]), .B1 (n_222), .C0 (\balance_db[5] [14]),
       .C1 (n_210), .Y (n_317));
  AOI222XL g17208(.A0 (\balance_db[6] [6]), .A1 (n_215), .B0
       (\balance_db[3] [6]), .B1 (n_217), .C0 (n_214), .C1
       (\balance_db[7] [6]), .Y (n_316));
  AOI221X1 g17209(.A0 (\balance_db[10] [12]), .A1 (n_213), .B0
       (\balance_db[3] [12]), .B1 (n_217), .C0 (n_288), .Y (n_315));
  AOI222XL g17210(.A0 (n_144), .A1 (n_177), .B0 (\balance_db[6] [12]),
       .B1 (n_160), .C0 (n_158), .C1 (\balance_db[7] [12]), .Y (n_314));
  OAI21X1 g17211(.A0 (n_165), .A1 (n_251), .B0 (n_258), .Y (n_313));
  AOI222XL g17212(.A0 (n_152), .A1 (n_176), .B0 (\balance_db[1] [12]),
       .B1 (n_158), .C0 (n_160), .C1 (\balance_db[0] [12]), .Y (n_312));
  AOI21X1 g17213(.A0 (\balance_db[7] [13]), .A1 (n_214), .B0 (n_296),
       .Y (n_311));
  AOI222XL g17214(.A0 (\balance_db[6] [7]), .A1 (n_215), .B0
       (\balance_db[3] [7]), .B1 (n_217), .C0 (n_214), .C1
       (\balance_db[7] [7]), .Y (n_310));
  AOI222XL g17215(.A0 (\balance_db[4] [14]), .A1 (n_209), .B0
       (\balance_db[8] [14]), .B1 (n_221), .C0 (n_220), .C1
       (\balance_db[9] [14]), .Y (n_309));
  AOI222XL g17216(.A0 (\balance_db[2] [11]), .A1 (n_212), .B0
       (\balance_db[10] [11]), .B1 (n_213), .C0 (n_217), .C1
       (\balance_db[3] [11]), .Y (n_308));
  AOI222XL g17217(.A0 (\balance_db[0] [15]), .A1 (n_223), .B0
       (\balance_db[1] [15]), .B1 (n_222), .C0 (n_209), .C1
       (\balance_db[4] [15]), .Y (n_307));
  OA22X1 g17218(.A0 (n_162), .A1 (n_224), .B0 (n_156), .B1 (n_225), .Y
       (n_306));
  AOI222XL g17219(.A0 (n_147), .A1 (n_179), .B0 (\balance_db[14] [11]),
       .B1 (n_161), .C0 (n_155), .C1 (\balance_db[15] [11]), .Y
       (n_305));
  AOI222XL g17220(.A0 (n_147), .A1 (n_178), .B0 (\balance_db[9] [11]),
       .B1 (n_155), .C0 (n_161), .C1 (\balance_db[8] [11]), .Y (n_304));
  AOI222XL g17221(.A0 (n_147), .A1 (n_175), .B0 (\balance_db[10] [3]),
       .B1 (n_163), .C0 (n_155), .C1 (\balance_db[11] [3]), .Y (n_303));
  AOI221X1 g17222(.A0 (\balance_db[8] [8]), .A1 (n_163), .B0
       (\balance_db[9] [8]), .B1 (n_155), .C0 (n_253), .Y (n_302));
  AOI222XL g17223(.A0 (n_147), .A1 (n_174), .B0 (\balance_db[14] [3]),
       .B1 (n_163), .C0 (n_155), .C1 (\balance_db[15] [3]), .Y (n_301));
  AOI221X1 g17224(.A0 (\balance_db[7] [9]), .A1 (n_158), .B0
       (\balance_db[15] [9]), .B1 (n_155), .C0 (n_254), .Y (n_300));
  AOI222XL g17225(.A0 (n_154), .A1 (n_181), .B0 (\balance_db[1] [5]),
       .B1 (n_158), .C0 (n_155), .C1 (\balance_db[9] [5]), .Y (n_299));
  INVXL g17226(.A (n_290), .Y (n_298));
  AOI222XL g17227(.A0 (\balance_db[12] [15]), .A1 (n_161), .B0
       (\balance_db[13] [15]), .B1 (n_155), .C0 (n_158), .C1
       (\balance_db[5] [15]), .Y (n_297));
  NOR2XL g17228(.A (n_165), .B (n_250), .Y (n_296));
  NAND2XL g17229(.A (n_233), .B (n_241), .Y (n_295));
  NAND2XL g17230(.A (n_227), .B (n_226), .Y (n_294));
  AOI222XL g17231(.A0 (\balance_db[0] [6]), .A1 (n_160), .B0
       (\balance_db[8] [6]), .B1 (n_163), .C0 (n_155), .C1
       (\balance_db[9] [6]), .Y (n_293));
  AOI222XL g17232(.A0 (\balance_db[4] [11]), .A1 (n_160), .B0
       (\balance_db[5] [11]), .B1 (n_158), .C0 (n_155), .C1
       (\balance_db[13] [11]), .Y (n_292));
  AOI222XL g17233(.A0 (\balance_db[12] [13]), .A1 (n_161), .B0
       (\balance_db[13] [13]), .B1 (n_155), .C0 (n_158), .C1
       (\balance_db[5] [13]), .Y (n_291));
  AOI222XL g17234(.A0 (\balance_db[0] [7]), .A1 (n_160), .B0
       (\balance_db[8] [7]), .B1 (n_163), .C0 (n_155), .C1
       (\balance_db[9] [7]), .Y (n_290));
  AOI222XL g17235(.A0 (\balance_db[6] [14]), .A1 (n_160), .B0
       (\balance_db[7] [14]), .B1 (n_158), .C0 (n_155), .C1
       (\balance_db[15] [14]), .Y (n_289));
  NOR2XL g17236(.A (n_168), .B (n_252), .Y (n_288));
  AOI32X1 g17237(.A0 (\balance_db[15] [15]), .A1 (n_164), .A2 (n_155),
       .B0 (\balance_db[14] [15]), .B1 (n_219), .Y (n_287));
  AOI22XL g17238(.A0 (n_143), .A1 (\balance_db[12] [6]), .B0 (n_211),
       .B1 (\balance_db[13] [6]), .Y (n_286));
  AOI22X1 g17239(.A0 (\balance_db[4] [6]), .A1 (n_209), .B0
       (\balance_db[5] [6]), .B1 (n_210), .Y (n_285));
  AOI22X1 g17240(.A0 (\balance_db[12] [12]), .A1 (n_143), .B0
       (\balance_db[11] [12]), .B1 (n_218), .Y (n_284));
  AOI22X1 g17241(.A0 (\balance_db[2] [12]), .A1 (n_212), .B0
       (\balance_db[13] [12]), .B1 (n_211), .Y (n_283));
  AO22XL g17242(.A0 (\balance_db[4] [7]), .A1 (n_209), .B0
       (\balance_db[5] [7]), .B1 (n_210), .Y (n_282));
  AOI22X1 g17243(.A0 (\balance_db[10] [7]), .A1 (n_213), .B0
       (\balance_db[11] [7]), .B1 (n_218), .Y (n_281));
  AOI22X1 g17244(.A0 (\balance_db[12] [14]), .A1 (n_216), .B0
       (\balance_db[13] [14]), .B1 (n_211), .Y (n_280));
  AOI22X1 g17246(.A0 (\balance_db[8] [15]), .A1 (n_221), .B0
       (\balance_db[9] [15]), .B1 (n_220), .Y (n_278));
  AOI22X1 g17247(.A0 (\balance_db[12] [5]), .A1 (n_216), .B0
       (\balance_db[13] [5]), .B1 (n_211), .Y (n_277));
  AO22X1 g17248(.A0 (\balance_db[2] [15]), .A1 (n_212), .B0
       (\balance_db[6] [15]), .B1 (n_215), .Y (n_276));
  AOI22X1 g17249(.A0 (\balance_db[12] [9]), .A1 (n_216), .B0
       (\balance_db[13] [9]), .B1 (n_211), .Y (n_275));
  AOI22X1 g17250(.A0 (\balance_db[6] [10]), .A1 (n_215), .B0
       (\balance_db[7] [10]), .B1 (n_214), .Y (n_274));
  AOI22X1 g17251(.A0 (\balance_db[4] [10]), .A1 (n_209), .B0
       (\balance_db[5] [10]), .B1 (n_210), .Y (n_273));
  OAI22X1 g17252(.A0 (id_to_check[0]), .A1 (n_207), .B0 (n_154), .B1
       (n_205), .Y (n_272));
  MXI4XL g17253(.A (\balance_db[8] [3]), .B (\balance_db[0] [3]), .C
       (\balance_db[9] [3]), .D (\balance_db[1] [3]), .S0 (n_145), .S1
       (id_to_check[0]), .Y (n_271));
  MXI2XL g17254(.A (n_189), .B (n_203), .S0 (n_154), .Y (n_270));
  OAI22X1 g17255(.A0 (id_to_check[0]), .A1 (n_190), .B0 (n_154), .B1
       (n_197), .Y (n_269));
  OAI22X1 g17256(.A0 (id_to_check[0]), .A1 (n_196), .B0 (n_154), .B1
       (n_185), .Y (n_268));
  OAI22X1 g17257(.A0 (id_to_check[0]), .A1 (n_204), .B0 (n_154), .B1
       (n_195), .Y (n_267));
  OAI22X1 g17258(.A0 (id_to_check[0]), .A1 (n_188), .B0 (n_154), .B1
       (n_192), .Y (n_266));
  OAI22X1 g17259(.A0 (id_to_check[0]), .A1 (n_191), .B0 (n_154), .B1
       (n_194), .Y (n_265));
  OAI22X1 g17260(.A0 (id_to_check[0]), .A1 (n_193), .B0 (n_154), .B1
       (n_206), .Y (n_264));
  MXI4XL g17261(.A (\balance_db[12] [3]), .B (\balance_db[4] [3]), .C
       (\balance_db[13] [3]), .D (\balance_db[5] [3]), .S0 (n_145), .S1
       (id_to_check[0]), .Y (n_263));
  OAI22X1 g17262(.A0 (id_to_check[0]), .A1 (n_186), .B0 (n_154), .B1
       (n_187), .Y (n_262));
  MXI2XL g17263(.A (n_184), .B (n_200), .S0 (n_154), .Y (n_261));
  OAI22X1 g17264(.A0 (id_to_check[0]), .A1 (n_180), .B0 (n_154), .B1
       (n_183), .Y (n_260));
  OAI22X1 g17265(.A0 (id_to_check[0]), .A1 (n_202), .B0 (n_154), .B1
       (n_182), .Y (n_259));
  NAND2XL g17266(.A (\balance_db[2] [6]), .B (n_212), .Y (n_258));
  NAND2XL g17267(.A (\balance_db[2] [7]), .B (n_212), .Y (n_257));
  NAND2XL g17269(.A (\balance_db[4] [9]), .B (n_209), .Y (n_255));
  NOR2XL g17270(.A (id_to_check[0]), .B (n_198), .Y (n_254));
  NOR2XL g17271(.A (n_153), .B (n_173), .Y (n_253));
  AOI22XL g17272(.A0 (n_160), .A1 (\balance_db[4] [12]), .B0 (n_158),
       .B1 (\balance_db[5] [12]), .Y (n_252));
  AOI22X1 g17273(.A0 (\balance_db[14] [6]), .A1 (n_161), .B0
       (\balance_db[15] [6]), .B1 (n_155), .Y (n_251));
  AOI22X1 g17274(.A0 (\balance_db[14] [13]), .A1 (n_161), .B0
       (\balance_db[15] [13]), .B1 (n_155), .Y (n_250));
  AOI22XL g17275(.A0 (n_161), .A1 (\balance_db[10] [13]), .B0 (n_155),
       .B1 (\balance_db[11] [13]), .Y (n_249));
  AOI22XL g17276(.A0 (n_160), .A1 (\balance_db[2] [13]), .B0 (n_158),
       .B1 (\balance_db[3] [13]), .Y (n_248));
  AOI22XL g17277(.A0 (n_161), .A1 (\balance_db[8] [13]), .B0 (n_155),
       .B1 (\balance_db[9] [13]), .Y (n_247));
  AOI22XL g17278(.A0 (n_160), .A1 (\balance_db[0] [13]), .B0 (n_158),
       .B1 (\balance_db[1] [13]), .Y (n_246));
  AOI22X1 g17279(.A0 (\balance_db[10] [14]), .A1 (n_161), .B0
       (\balance_db[11] [14]), .B1 (n_155), .Y (n_245));
  AOI22X1 g17280(.A0 (\balance_db[2] [14]), .A1 (n_160), .B0
       (\balance_db[3] [14]), .B1 (n_158), .Y (n_244));
  AOI22X1 g17281(.A0 (\balance_db[14] [7]), .A1 (n_161), .B0
       (\balance_db[15] [7]), .B1 (n_155), .Y (n_243));
  AOI22X1 g17283(.A0 (\balance_db[0] [9]), .A1 (n_160), .B0
       (\balance_db[9] [9]), .B1 (n_155), .Y (n_241));
  AOI22X1 g17284(.A0 (\balance_db[3] [15]), .A1 (n_158), .B0
       (\balance_db[11] [15]), .B1 (n_155), .Y (n_240));
  AOI22X1 g17285(.A0 (\balance_db[14] [8]), .A1 (n_163), .B0
       (\balance_db[7] [8]), .B1 (n_158), .Y (n_239));
  AOI22X1 g17286(.A0 (\balance_db[6] [8]), .A1 (n_160), .B0
       (\balance_db[15] [8]), .B1 (n_155), .Y (n_238));
  AOI22X1 g17287(.A0 (\balance_db[10] [5]), .A1 (n_163), .B0
       (\balance_db[3] [5]), .B1 (n_158), .Y (n_237));
  AOI22X1 g17288(.A0 (\balance_db[2] [5]), .A1 (n_172), .B0
       (\balance_db[11] [5]), .B1 (n_142), .Y (n_236));
  AOI22X1 g17289(.A0 (\balance_db[10] [9]), .A1 (n_163), .B0
       (\balance_db[3] [9]), .B1 (n_158), .Y (n_235));
  AOI22X1 g17290(.A0 (\balance_db[2] [9]), .A1 (n_172), .B0
       (\balance_db[11] [9]), .B1 (n_142), .Y (n_234));
  AOI22XL g17291(.A0 (n_163), .A1 (\balance_db[8] [9]), .B0 (n_158),
       .B1 (\balance_db[1] [9]), .Y (n_233));
  AOI22X1 g17293(.A0 (\balance_db[14] [5]), .A1 (n_163), .B0
       (\balance_db[7] [5]), .B1 (n_158), .Y (n_231));
  AOI22X1 g17294(.A0 (\balance_db[6] [5]), .A1 (n_160), .B0
       (\balance_db[15] [5]), .B1 (n_155), .Y (n_230));
  AOI22X1 g17295(.A0 (\balance_db[10] [10]), .A1 (n_161), .B0
       (\balance_db[11] [10]), .B1 (n_155), .Y (n_229));
  AOI22X1 g17296(.A0 (\balance_db[2] [10]), .A1 (n_160), .B0
       (\balance_db[3] [10]), .B1 (n_158), .Y (n_228));
  AOI22XL g17297(.A0 (n_161), .A1 (\balance_db[8] [10]), .B0 (n_155),
       .B1 (\balance_db[9] [10]), .Y (n_227));
  AOI22XL g17298(.A0 (n_160), .A1 (\balance_db[0] [10]), .B0 (n_158),
       .B1 (\balance_db[1] [10]), .Y (n_226));
  AOI22X1 g17299(.A0 (\balance_db[13] [10]), .A1 (n_169), .B0
       (\balance_db[15] [10]), .B1 (n_164), .Y (n_225));
  AOI22XL g17300(.A0 (n_169), .A1 (\balance_db[12] [10]), .B0 (n_164),
       .B1 (\balance_db[14] [10]), .Y (n_224));
  CLKINVX1 g17301(.A (n_199), .Y (n_210));
  AOI22X1 g17303(.A0 (\balance_db[6] [4]), .A1 (n_145), .B0
       (\balance_db[14] [4]), .B1 (n_153), .Y (n_207));
  AOI22X1 g17304(.A0 (\balance_db[1] [4]), .A1 (n_145), .B0
       (\balance_db[9] [4]), .B1 (n_144), .Y (n_206));
  AOI22X1 g17305(.A0 (\balance_db[7] [4]), .A1 (n_147), .B0
       (\balance_db[15] [4]), .B1 (n_153), .Y (n_205));
  AOI22X1 g17306(.A0 (\balance_db[2] [4]), .A1 (n_145), .B0
       (\balance_db[10] [4]), .B1 (n_144), .Y (n_204));
  AOI22XL g17307(.A0 (n_145), .A1 (\balance_db[6] [1]), .B0 (n_152),
       .B1 (\balance_db[14] [1]), .Y (n_203));
  AOI22X1 g17308(.A0 (\balance_db[0] [1]), .A1 (n_145), .B0
       (\balance_db[8] [1]), .B1 (n_152), .Y (n_202));
  AOI22XL g17310(.A0 (n_145), .A1 (\balance_db[4] [1]), .B0 (n_152),
       .B1 (\balance_db[12] [1]), .Y (n_200));
  NOR2XL g17311(.A (n_166), .B (n_159), .Y (n_223));
  NOR2XL g17312(.A (n_166), .B (n_157), .Y (n_222));
  NOR2XL g17313(.A (n_166), .B (n_162), .Y (n_221));
  NOR2XL g17314(.A (n_166), .B (n_156), .Y (n_220));
  NOR2XL g17315(.A (n_165), .B (n_162), .Y (n_219));
  NOR2XL g17317(.A (n_171), .B (n_156), .Y (n_218));
  NOR2XL g17318(.A (n_171), .B (n_157), .Y (n_217));
  NOR2XL g17319(.A (n_168), .B (n_162), .Y (n_216));
  NOR2XL g17320(.A (n_165), .B (n_159), .Y (n_215));
  NOR2XL g17321(.A (n_165), .B (n_157), .Y (n_214));
  NOR2XL g17322(.A (n_171), .B (n_162), .Y (n_213));
  NOR2XL g17323(.A (n_171), .B (n_159), .Y (n_212));
  NOR2X1 g17324(.A (n_168), .B (n_156), .Y (n_211));
  NAND2XL g17325(.A (n_169), .B (n_158), .Y (n_199));
  AND2X1 g17326(.A (n_169), .B (n_160), .Y (n_209));
  AOI22XL g17327(.A0 (n_145), .A1 (\balance_db[6] [9]), .B0
       (id_to_check[3]), .B1 (\balance_db[14] [9]), .Y (n_198));
  AOI22X1 g17328(.A0 (\balance_db[7] [2]), .A1 (n_147), .B0
       (\balance_db[15] [2]), .B1 (n_153), .Y (n_197));
  AOI22X1 g17329(.A0 (\balance_db[4] [4]), .A1 (n_145), .B0
       (\balance_db[12] [4]), .B1 (n_144), .Y (n_196));
  AOI22X1 g17330(.A0 (\balance_db[3] [4]), .A1 (n_147), .B0
       (\balance_db[11] [4]), .B1 (n_153), .Y (n_195));
  AOI22X1 g17331(.A0 (\balance_db[5] [2]), .A1 (n_147), .B0
       (\balance_db[13] [2]), .B1 (n_153), .Y (n_194));
  AOI22X1 g17332(.A0 (\balance_db[0] [4]), .A1 (n_145), .B0
       (\balance_db[8] [4]), .B1 (n_144), .Y (n_193));
  AOI22X1 g17333(.A0 (\balance_db[3] [1]), .A1 (n_147), .B0
       (\balance_db[11] [1]), .B1 (n_152), .Y (n_192));
  AOI22X1 g17334(.A0 (\balance_db[4] [2]), .A1 (n_145), .B0
       (\balance_db[12] [2]), .B1 (n_153), .Y (n_191));
  AOI22X1 g17335(.A0 (\balance_db[6] [2]), .A1 (n_147), .B0
       (\balance_db[14] [2]), .B1 (n_153), .Y (n_190));
  AOI22XL g17336(.A0 (n_145), .A1 (\balance_db[7] [1]), .B0 (n_152),
       .B1 (\balance_db[15] [1]), .Y (n_189));
  AOI22X1 g17337(.A0 (\balance_db[2] [1]), .A1 (n_145), .B0
       (\balance_db[10] [1]), .B1 (n_152), .Y (n_188));
  AOI22X1 g17338(.A0 (\balance_db[3] [2]), .A1 (n_145), .B0
       (\balance_db[11] [2]), .B1 (n_153), .Y (n_187));
  AOI22X1 g17339(.A0 (\balance_db[2] [2]), .A1 (n_147), .B0
       (\balance_db[10] [2]), .B1 (n_153), .Y (n_186));
  AOI22X1 g17340(.A0 (\balance_db[5] [4]), .A1 (n_145), .B0
       (\balance_db[13] [4]), .B1 (n_144), .Y (n_185));
  AOI22XL g17341(.A0 (n_145), .A1 (\balance_db[5] [1]), .B0 (n_152),
       .B1 (\balance_db[13] [1]), .Y (n_184));
  AOI22X1 g17342(.A0 (\balance_db[1] [2]), .A1 (n_147), .B0
       (\balance_db[9] [2]), .B1 (n_153), .Y (n_183));
  AOI22X1 g17343(.A0 (\balance_db[1] [1]), .A1 (n_145), .B0
       (\balance_db[9] [1]), .B1 (n_152), .Y (n_182));
  MX2X1 g17344(.A (\balance_db[0] [5]), .B (\balance_db[8] [5]), .S0
       (n_152), .Y (n_181));
  AOI22X1 g17345(.A0 (\balance_db[0] [2]), .A1 (n_145), .B0
       (\balance_db[8] [2]), .B1 (n_144), .Y (n_180));
  MX2X1 g17346(.A (\balance_db[6] [11]), .B (\balance_db[7] [11]), .S0
       (id_to_check[0]), .Y (n_179));
  MX2X1 g17347(.A (\balance_db[0] [11]), .B (\balance_db[1] [11]), .S0
       (id_to_check[0]), .Y (n_178));
  MX2X1 g17348(.A (\balance_db[14] [12]), .B (\balance_db[15] [12]),
       .S0 (id_to_check[0]), .Y (n_177));
  MX2X1 g17349(.A (\balance_db[8] [12]), .B (\balance_db[9] [12]), .S0
       (id_to_check[0]), .Y (n_176));
  MX2X1 g17350(.A (\balance_db[3] [3]), .B (\balance_db[2] [3]), .S0
       (n_154), .Y (n_175));
  MX2X1 g17351(.A (\balance_db[6] [3]), .B (\balance_db[7] [3]), .S0
       (id_to_check[0]), .Y (n_174));
  AOI22X1 g17352(.A0 (\balance_db[0] [8]), .A1 (n_154), .B0
       (\balance_db[1] [8]), .B1 (id_to_check[0]), .Y (n_173));
  CLKINVX1 g17353(.A (n_171), .Y (n_170));
  CLKINVX1 g17354(.A (n_169), .Y (n_168));
  CLKINVX1 g17355(.A (n_167), .Y (n_166));
  CLKINVX1 g17356(.A (n_165), .Y (n_164));
  NOR2XL g17357(.A (n_148), .B (id_to_check[0]), .Y (n_172));
  NAND2BX1 g17358(.AN (id_to_check[2]), .B (id_to_check[1]), .Y
       (n_171));
  NOR2BX2 g17359(.AN (id_to_check[2]), .B (id_to_check[1]), .Y (n_169));
  NOR2X1 g17360(.A (id_to_check[1]), .B (id_to_check[2]), .Y (n_167));
  NAND2X1 g17361(.A (id_to_check[1]), .B (id_to_check[2]), .Y (n_165));
  CLKINVX1 g17363(.A (n_162), .Y (n_161));
  CLKINVX1 g17364(.A (n_160), .Y (n_159));
  INVX1 g17365(.A (n_158), .Y (n_157));
  CLKINVX2 g17366(.A (n_156), .Y (n_155));
  NOR2X1 g17368(.A (id_to_check[0]), .B (n_145), .Y (n_163));
  NAND2X1 g17369(.A (n_154), .B (n_148), .Y (n_162));
  NOR2X2 g17370(.A (id_to_check[3]), .B (id_to_check[0]), .Y (n_160));
  CLKAND2X3 g17371(.A (id_to_check[0]), .B (n_145), .Y (n_158));
  NAND2XL g17372(.A (id_to_check[3]), .B (id_to_check[0]), .Y (n_156));
  CLKINVX2 g17373(.A (id_to_check[0]), .Y (n_154));
  CLKINVX1 g17376(.A (n_145), .Y (n_148));
  CLKINVX3 g17377(.A (id_to_check[3]), .Y (n_145));
  CLKINVX1 g17389(.A (n_153), .Y (n_147));
  BUFX2 g17390(.A (id_to_check[3]), .Y (n_153));
  CLKINVX1 g17391(.A (n_145), .Y (n_152));
  CLKINVX1 g17412(.A (n_145), .Y (n_144));
  NOR2BX1 g2(.AN (n_163), .B (n_168), .Y (n_143));
  NOR2BX1 g17416(.AN (id_to_check[3]), .B (n_154), .Y (n_142));
  SDFFQX1 \balance_db_reg[0][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[0] [1]), .SE (n_54), .Q (\balance_db[0] [1]));
  SDFFQX1 \balance_db_reg[0][2] (.CK (clk), .D (n_25), .SI
       (\balance_db[0] [2]), .SE (n_54), .Q (\balance_db[0] [2]));
  SDFFQX1 \balance_db_reg[0][3] (.CK (clk), .D (n_66), .SI
       (\balance_db[0] [3]), .SE (n_54), .Q (\balance_db[0] [3]));
  SDFFQX1 \balance_db_reg[0][4] (.CK (clk), .D (n_50), .SI
       (\balance_db[0] [4]), .SE (n_54), .Q (\balance_db[0] [4]));
  SDFFQX1 \balance_db_reg[0][5] (.CK (clk), .D (n_64), .SI
       (\balance_db[0] [5]), .SE (n_54), .Q (\balance_db[0] [5]));
  SDFFQX1 \balance_db_reg[0][6] (.CK (clk), .D (n_60), .SI
       (\balance_db[0] [6]), .SE (n_54), .Q (\balance_db[0] [6]));
  SDFFQX1 \balance_db_reg[0][7] (.CK (clk), .D (n_83), .SI
       (\balance_db[0] [7]), .SE (n_54), .Q (\balance_db[0] [7]));
  SDFFQX1 \balance_db_reg[0][8] (.CK (clk), .D (n_51), .SI
       (\balance_db[0] [8]), .SE (n_54), .Q (\balance_db[0] [8]));
  SDFFQX1 \balance_db_reg[0][9] (.CK (clk), .D (n_65), .SI
       (\balance_db[0] [9]), .SE (n_54), .Q (\balance_db[0] [9]));
  SDFFQX1 \balance_db_reg[0][10] (.CK (clk), .D (n_61), .SI
       (\balance_db[0] [10]), .SE (n_54), .Q (\balance_db[0] [10]));
  SDFFQX1 \balance_db_reg[0][11] (.CK (clk), .D (n_84), .SI
       (\balance_db[0] [11]), .SE (n_54), .Q (\balance_db[0] [11]));
  SDFFQX1 \balance_db_reg[0][12] (.CK (clk), .D (n_62), .SI
       (\balance_db[0] [12]), .SE (n_54), .Q (\balance_db[0] [12]));
  SDFFQX1 \balance_db_reg[0][13] (.CK (clk), .D (n_82), .SI
       (\balance_db[0] [13]), .SE (n_54), .Q (\balance_db[0] [13]));
  SDFFQX1 \balance_db_reg[0][14] (.CK (clk), .D (n_57), .SI
       (\balance_db[0] [14]), .SE (n_54), .Q (\balance_db[0] [14]));
  SDFFQX1 \balance_db_reg[0][15] (.CK (clk), .D (n_401), .SI
       (\balance_db[0] [15]), .SE (n_54), .Q (\balance_db[0] [15]));
  DFFQX1 \balance_db_reg[1][1] (.CK (clk), .D (n_125), .Q
       (\balance_db[1] [1]));
  DFFQX1 \balance_db_reg[1][2] (.CK (clk), .D (n_136), .Q
       (\balance_db[1] [2]));
  DFFQX1 \balance_db_reg[1][3] (.CK (clk), .D (n_124), .Q
       (\balance_db[1] [3]));
  DFFQX1 \balance_db_reg[1][4] (.CK (clk), .D (n_123), .Q
       (\balance_db[1] [4]));
  DFFQX1 \balance_db_reg[1][5] (.CK (clk), .D (n_400), .Q
       (\balance_db[1] [5]));
  DFFQX1 \balance_db_reg[1][6] (.CK (clk), .D (n_137), .Q
       (\balance_db[1] [6]));
  DFFQX1 \balance_db_reg[1][7] (.CK (clk), .D (n_122), .Q
       (\balance_db[1] [7]));
  DFFQX1 \balance_db_reg[1][8] (.CK (clk), .D (n_121), .Q
       (\balance_db[1] [8]));
  DFFQX1 \balance_db_reg[1][9] (.CK (clk), .D (n_120), .Q
       (\balance_db[1] [9]));
  DFFQX1 \balance_db_reg[1][10] (.CK (clk), .D (n_119), .Q
       (\balance_db[1] [10]));
  DFFQX1 \balance_db_reg[1][11] (.CK (clk), .D (n_118), .Q
       (\balance_db[1] [11]));
  DFFQX1 \balance_db_reg[1][12] (.CK (clk), .D (n_117), .Q
       (\balance_db[1] [12]));
  DFFQX1 \balance_db_reg[1][13] (.CK (clk), .D (n_116), .Q
       (\balance_db[1] [13]));
  DFFQX1 \balance_db_reg[1][14] (.CK (clk), .D (n_138), .Q
       (\balance_db[1] [14]));
  DFFQX1 \balance_db_reg[1][15] (.CK (clk), .D (n_140), .Q
       (\balance_db[1] [15]));
  DFFQX1 \balance_db_reg[2][1] (.CK (clk), .D (n_114), .Q
       (\balance_db[2] [1]));
  DFFQX1 \balance_db_reg[2][2] (.CK (clk), .D (n_407), .Q
       (\balance_db[2] [2]));
  DFFQX1 \balance_db_reg[2][3] (.CK (clk), .D (n_113), .Q
       (\balance_db[2] [3]));
  DFFQX1 \balance_db_reg[2][4] (.CK (clk), .D (n_112), .Q
       (\balance_db[2] [4]));
  DFFQX1 \balance_db_reg[2][5] (.CK (clk), .D (n_111), .Q
       (\balance_db[2] [5]));
  DFFQX1 \balance_db_reg[2][6] (.CK (clk), .D (n_110), .Q
       (\balance_db[2] [6]));
  DFFQX1 \balance_db_reg[2][7] (.CK (clk), .D (n_109), .Q
       (\balance_db[2] [7]));
  DFFQX1 \balance_db_reg[2][8] (.CK (clk), .D (n_108), .Q
       (\balance_db[2] [8]));
  DFFQX1 \balance_db_reg[2][9] (.CK (clk), .D (n_107), .Q
       (\balance_db[2] [9]));
  DFFQX1 \balance_db_reg[2][10] (.CK (clk), .D (n_106), .Q
       (\balance_db[2] [10]));
  DFFQX1 \balance_db_reg[2][11] (.CK (clk), .D (n_105), .Q
       (\balance_db[2] [11]));
  DFFQX1 \balance_db_reg[2][12] (.CK (clk), .D (n_104), .Q
       (\balance_db[2] [12]));
  DFFQX1 \balance_db_reg[2][13] (.CK (clk), .D (n_103), .Q
       (\balance_db[2] [13]));
  DFFQX1 \balance_db_reg[2][14] (.CK (clk), .D (n_132), .Q
       (\balance_db[2] [14]));
  DFFQX1 \balance_db_reg[2][15] (.CK (clk), .D (n_139), .Q
       (\balance_db[2] [15]));
  DFFQX1 \balance_db_reg[3][1] (.CK (clk), .D (n_131), .Q
       (\balance_db[3] [1]));
  DFFQX1 \balance_db_reg[3][2] (.CK (clk), .D (n_134), .Q
       (\balance_db[3] [2]));
  DFFQX1 \balance_db_reg[3][3] (.CK (clk), .D (n_102), .Q
       (\balance_db[3] [3]));
  DFFQX1 \balance_db_reg[3][4] (.CK (clk), .D (n_135), .Q
       (\balance_db[3] [4]));
  DFFQX1 \balance_db_reg[3][5] (.CK (clk), .D (n_101), .Q
       (\balance_db[3] [5]));
  DFFQX1 \balance_db_reg[3][6] (.CK (clk), .D (n_130), .Q
       (\balance_db[3] [6]));
  DFFQX1 \balance_db_reg[3][7] (.CK (clk), .D (n_100), .Q
       (\balance_db[3] [7]));
  DFFQX1 \balance_db_reg[3][8] (.CK (clk), .D (n_129), .Q
       (\balance_db[3] [8]));
  DFFQX1 \balance_db_reg[3][9] (.CK (clk), .D (n_99), .Q
       (\balance_db[3] [9]));
  DFFQX1 \balance_db_reg[3][10] (.CK (clk), .D (n_128), .Q
       (\balance_db[3] [10]));
  DFFQX1 \balance_db_reg[3][11] (.CK (clk), .D (n_98), .Q
       (\balance_db[3] [11]));
  DFFQX1 \balance_db_reg[3][12] (.CK (clk), .D (n_127), .Q
       (\balance_db[3] [12]));
  DFFQX1 \balance_db_reg[3][13] (.CK (clk), .D (n_97), .Q
       (\balance_db[3] [13]));
  DFFQX1 \balance_db_reg[3][14] (.CK (clk), .D (n_126), .Q
       (\balance_db[3] [14]));
  DFFQX1 \balance_db_reg[3][15] (.CK (clk), .D (n_141), .Q
       (\balance_db[3] [15]));
  SDFFQX1 \balance_db_reg[4][1] (.CK (clk), .D (\balance_db[4] [1]),
       .SI (n_4), .SE (n_45), .Q (\balance_db[4] [1]));
  SDFFQX1 \balance_db_reg[4][2] (.CK (clk), .D (\balance_db[4] [2]),
       .SI (n_25), .SE (n_45), .Q (\balance_db[4] [2]));
  SDFFQX1 \balance_db_reg[4][3] (.CK (clk), .D (\balance_db[4] [3]),
       .SI (n_66), .SE (n_45), .Q (\balance_db[4] [3]));
  SDFFQX1 \balance_db_reg[4][4] (.CK (clk), .D (\balance_db[4] [4]),
       .SI (n_50), .SE (n_45), .Q (\balance_db[4] [4]));
  SDFFQX1 \balance_db_reg[4][5] (.CK (clk), .D (\balance_db[4] [5]),
       .SI (n_64), .SE (n_45), .Q (\balance_db[4] [5]));
  SDFFQX1 \balance_db_reg[4][6] (.CK (clk), .D (\balance_db[4] [6]),
       .SI (n_60), .SE (n_45), .Q (\balance_db[4] [6]));
  SDFFQX1 \balance_db_reg[4][7] (.CK (clk), .D (\balance_db[4] [7]),
       .SI (n_83), .SE (n_45), .Q (\balance_db[4] [7]));
  SDFFQX1 \balance_db_reg[4][8] (.CK (clk), .D (\balance_db[4] [8]),
       .SI (n_51), .SE (n_45), .Q (\balance_db[4] [8]));
  SDFFQX1 \balance_db_reg[4][9] (.CK (clk), .D (\balance_db[4] [9]),
       .SI (n_65), .SE (n_45), .Q (\balance_db[4] [9]));
  SDFFQX1 \balance_db_reg[4][10] (.CK (clk), .D (\balance_db[4] [10]),
       .SI (n_61), .SE (n_45), .Q (\balance_db[4] [10]));
  SDFFQX1 \balance_db_reg[4][11] (.CK (clk), .D (\balance_db[4] [11]),
       .SI (n_84), .SE (n_45), .Q (\balance_db[4] [11]));
  SDFFQX1 \balance_db_reg[4][12] (.CK (clk), .D (\balance_db[4] [12]),
       .SI (n_62), .SE (n_45), .Q (\balance_db[4] [12]));
  SDFFQX1 \balance_db_reg[4][13] (.CK (clk), .D (\balance_db[4] [13]),
       .SI (n_82), .SE (n_45), .Q (\balance_db[4] [13]));
  SDFFQX1 \balance_db_reg[4][14] (.CK (clk), .D (\balance_db[4] [14]),
       .SI (n_57), .SE (n_45), .Q (\balance_db[4] [14]));
  SDFFQX1 \balance_db_reg[4][15] (.CK (clk), .D (\balance_db[4] [15]),
       .SI (n_401), .SE (n_45), .Q (\balance_db[4] [15]));
  SDFFQX1 \balance_db_reg[5][1] (.CK (clk), .D (\balance_db[5] [1]),
       .SI (n_4), .SE (n_38), .Q (\balance_db[5] [1]));
  SDFFQX1 \balance_db_reg[5][2] (.CK (clk), .D (\balance_db[5] [2]),
       .SI (n_25), .SE (n_38), .Q (\balance_db[5] [2]));
  SDFFQX1 \balance_db_reg[5][3] (.CK (clk), .D (\balance_db[5] [3]),
       .SI (n_66), .SE (n_38), .Q (\balance_db[5] [3]));
  SDFFQX1 \balance_db_reg[5][4] (.CK (clk), .D (\balance_db[5] [4]),
       .SI (n_50), .SE (n_38), .Q (\balance_db[5] [4]));
  SDFFQX1 \balance_db_reg[5][5] (.CK (clk), .D (\balance_db[5] [5]),
       .SI (n_64), .SE (n_38), .Q (\balance_db[5] [5]));
  SDFFQX1 \balance_db_reg[5][6] (.CK (clk), .D (\balance_db[5] [6]),
       .SI (n_60), .SE (n_38), .Q (\balance_db[5] [6]));
  SDFFQX1 \balance_db_reg[5][7] (.CK (clk), .D (\balance_db[5] [7]),
       .SI (n_83), .SE (n_38), .Q (\balance_db[5] [7]));
  SDFFQX1 \balance_db_reg[5][8] (.CK (clk), .D (\balance_db[5] [8]),
       .SI (n_51), .SE (n_38), .Q (\balance_db[5] [8]));
  SDFFQX1 \balance_db_reg[5][9] (.CK (clk), .D (\balance_db[5] [9]),
       .SI (n_65), .SE (n_38), .Q (\balance_db[5] [9]));
  SDFFQX1 \balance_db_reg[5][10] (.CK (clk), .D (\balance_db[5] [10]),
       .SI (n_61), .SE (n_38), .Q (\balance_db[5] [10]));
  SDFFQX1 \balance_db_reg[5][11] (.CK (clk), .D (\balance_db[5] [11]),
       .SI (n_84), .SE (n_38), .Q (\balance_db[5] [11]));
  SDFFQX1 \balance_db_reg[5][12] (.CK (clk), .D (\balance_db[5] [12]),
       .SI (n_62), .SE (n_38), .Q (\balance_db[5] [12]));
  SDFFQX1 \balance_db_reg[5][13] (.CK (clk), .D (\balance_db[5] [13]),
       .SI (n_82), .SE (n_38), .Q (\balance_db[5] [13]));
  SDFFQX1 \balance_db_reg[5][14] (.CK (clk), .D (\balance_db[5] [14]),
       .SI (n_57), .SE (n_38), .Q (\balance_db[5] [14]));
  SDFFQX1 \balance_db_reg[5][15] (.CK (clk), .D (\balance_db[5] [15]),
       .SI (n_401), .SE (n_38), .Q (\balance_db[5] [15]));
  SDFFQX1 \balance_db_reg[6][1] (.CK (clk), .D (\balance_db[6] [1]),
       .SI (n_4), .SE (n_0), .Q (\balance_db[6] [1]));
  SDFFQX1 \balance_db_reg[6][2] (.CK (clk), .D (\balance_db[6] [2]),
       .SI (n_25), .SE (n_0), .Q (\balance_db[6] [2]));
  SDFFQX1 \balance_db_reg[6][3] (.CK (clk), .D (\balance_db[6] [3]),
       .SI (n_66), .SE (n_0), .Q (\balance_db[6] [3]));
  SDFFQX1 \balance_db_reg[6][4] (.CK (clk), .D (\balance_db[6] [4]),
       .SI (n_50), .SE (n_0), .Q (\balance_db[6] [4]));
  SDFFQX1 \balance_db_reg[6][5] (.CK (clk), .D (\balance_db[6] [5]),
       .SI (n_64), .SE (n_0), .Q (\balance_db[6] [5]));
  SDFFQX1 \balance_db_reg[6][6] (.CK (clk), .D (\balance_db[6] [6]),
       .SI (n_60), .SE (n_0), .Q (\balance_db[6] [6]));
  SDFFQX1 \balance_db_reg[6][7] (.CK (clk), .D (\balance_db[6] [7]),
       .SI (n_83), .SE (n_0), .Q (\balance_db[6] [7]));
  SDFFQX1 \balance_db_reg[6][8] (.CK (clk), .D (\balance_db[6] [8]),
       .SI (n_51), .SE (n_0), .Q (\balance_db[6] [8]));
  SDFFQX1 \balance_db_reg[6][9] (.CK (clk), .D (\balance_db[6] [9]),
       .SI (n_65), .SE (n_0), .Q (\balance_db[6] [9]));
  SDFFQX1 \balance_db_reg[6][10] (.CK (clk), .D (\balance_db[6] [10]),
       .SI (n_61), .SE (n_0), .Q (\balance_db[6] [10]));
  SDFFQX1 \balance_db_reg[6][11] (.CK (clk), .D (\balance_db[6] [11]),
       .SI (n_84), .SE (n_0), .Q (\balance_db[6] [11]));
  SDFFQX1 \balance_db_reg[6][12] (.CK (clk), .D (\balance_db[6] [12]),
       .SI (n_62), .SE (n_0), .Q (\balance_db[6] [12]));
  SDFFQX1 \balance_db_reg[6][13] (.CK (clk), .D (\balance_db[6] [13]),
       .SI (n_82), .SE (n_0), .Q (\balance_db[6] [13]));
  SDFFQX1 \balance_db_reg[6][14] (.CK (clk), .D (\balance_db[6] [14]),
       .SI (n_57), .SE (n_0), .Q (\balance_db[6] [14]));
  SDFFQX1 \balance_db_reg[6][15] (.CK (clk), .D (\balance_db[6] [15]),
       .SI (n_401), .SE (n_0), .Q (\balance_db[6] [15]));
  SDFFQX1 \balance_db_reg[7][1] (.CK (clk), .D (\balance_db[7] [1]),
       .SI (n_4), .SE (n_35), .Q (\balance_db[7] [1]));
  SDFFQX1 \balance_db_reg[7][2] (.CK (clk), .D (\balance_db[7] [2]),
       .SI (n_25), .SE (n_35), .Q (\balance_db[7] [2]));
  SDFFQX1 \balance_db_reg[7][3] (.CK (clk), .D (\balance_db[7] [3]),
       .SI (n_66), .SE (n_35), .Q (\balance_db[7] [3]));
  SDFFQX1 \balance_db_reg[7][4] (.CK (clk), .D (\balance_db[7] [4]),
       .SI (n_50), .SE (n_35), .Q (\balance_db[7] [4]));
  SDFFQX1 \balance_db_reg[7][5] (.CK (clk), .D (\balance_db[7] [5]),
       .SI (n_64), .SE (n_35), .Q (\balance_db[7] [5]));
  SDFFQX1 \balance_db_reg[7][6] (.CK (clk), .D (\balance_db[7] [6]),
       .SI (n_60), .SE (n_35), .Q (\balance_db[7] [6]));
  SDFFQX1 \balance_db_reg[7][7] (.CK (clk), .D (\balance_db[7] [7]),
       .SI (n_83), .SE (n_35), .Q (\balance_db[7] [7]));
  SDFFQX1 \balance_db_reg[7][8] (.CK (clk), .D (\balance_db[7] [8]),
       .SI (n_51), .SE (n_35), .Q (\balance_db[7] [8]));
  SDFFQX1 \balance_db_reg[7][9] (.CK (clk), .D (\balance_db[7] [9]),
       .SI (n_65), .SE (n_35), .Q (\balance_db[7] [9]));
  SDFFQX1 \balance_db_reg[7][10] (.CK (clk), .D (\balance_db[7] [10]),
       .SI (n_61), .SE (n_35), .Q (\balance_db[7] [10]));
  SDFFQX1 \balance_db_reg[7][11] (.CK (clk), .D (\balance_db[7] [11]),
       .SI (n_84), .SE (n_35), .Q (\balance_db[7] [11]));
  SDFFQX1 \balance_db_reg[7][12] (.CK (clk), .D (\balance_db[7] [12]),
       .SI (n_62), .SE (n_35), .Q (\balance_db[7] [12]));
  SDFFQX1 \balance_db_reg[7][13] (.CK (clk), .D (\balance_db[7] [13]),
       .SI (n_82), .SE (n_35), .Q (\balance_db[7] [13]));
  SDFFQX1 \balance_db_reg[7][14] (.CK (clk), .D (\balance_db[7] [14]),
       .SI (n_57), .SE (n_35), .Q (\balance_db[7] [14]));
  SDFFQX1 \balance_db_reg[7][15] (.CK (clk), .D (\balance_db[7] [15]),
       .SI (n_401), .SE (n_35), .Q (\balance_db[7] [15]));
  SDFFQX1 \balance_db_reg[8][1] (.CK (clk), .D (\balance_db[8] [1]),
       .SI (n_4), .SE (n_56), .Q (\balance_db[8] [1]));
  SDFFQX1 \balance_db_reg[8][2] (.CK (clk), .D (\balance_db[8] [2]),
       .SI (n_25), .SE (n_56), .Q (\balance_db[8] [2]));
  SDFFQX1 \balance_db_reg[8][3] (.CK (clk), .D (\balance_db[8] [3]),
       .SI (n_66), .SE (n_56), .Q (\balance_db[8] [3]));
  SDFFQX1 \balance_db_reg[8][4] (.CK (clk), .D (\balance_db[8] [4]),
       .SI (n_50), .SE (n_56), .Q (\balance_db[8] [4]));
  SDFFQX1 \balance_db_reg[8][5] (.CK (clk), .D (\balance_db[8] [5]),
       .SI (n_64), .SE (n_56), .Q (\balance_db[8] [5]));
  SDFFQX1 \balance_db_reg[8][6] (.CK (clk), .D (\balance_db[8] [6]),
       .SI (n_60), .SE (n_56), .Q (\balance_db[8] [6]));
  SDFFQX1 \balance_db_reg[8][7] (.CK (clk), .D (\balance_db[8] [7]),
       .SI (n_83), .SE (n_56), .Q (\balance_db[8] [7]));
  SDFFQX1 \balance_db_reg[8][8] (.CK (clk), .D (\balance_db[8] [8]),
       .SI (n_51), .SE (n_56), .Q (\balance_db[8] [8]));
  SDFFQX1 \balance_db_reg[8][9] (.CK (clk), .D (\balance_db[8] [9]),
       .SI (n_65), .SE (n_56), .Q (\balance_db[8] [9]));
  SDFFQX1 \balance_db_reg[8][10] (.CK (clk), .D (\balance_db[8] [10]),
       .SI (n_61), .SE (n_56), .Q (\balance_db[8] [10]));
  SDFFQX1 \balance_db_reg[8][11] (.CK (clk), .D (\balance_db[8] [11]),
       .SI (n_84), .SE (n_56), .Q (\balance_db[8] [11]));
  SDFFQX1 \balance_db_reg[8][12] (.CK (clk), .D (\balance_db[8] [12]),
       .SI (n_62), .SE (n_56), .Q (\balance_db[8] [12]));
  SDFFQX1 \balance_db_reg[8][13] (.CK (clk), .D (\balance_db[8] [13]),
       .SI (n_82), .SE (n_56), .Q (\balance_db[8] [13]));
  SDFFQX1 \balance_db_reg[8][14] (.CK (clk), .D (\balance_db[8] [14]),
       .SI (n_57), .SE (n_56), .Q (\balance_db[8] [14]));
  SDFFQX1 \balance_db_reg[8][15] (.CK (clk), .D (\balance_db[8] [15]),
       .SI (n_401), .SE (n_56), .Q (\balance_db[8] [15]));
  SDFFQX1 \balance_db_reg[9][1] (.CK (clk), .D (\balance_db[9] [1]),
       .SI (n_4), .SE (n_1), .Q (\balance_db[9] [1]));
  SDFFQX1 \balance_db_reg[9][2] (.CK (clk), .D (\balance_db[9] [2]),
       .SI (n_25), .SE (n_1), .Q (\balance_db[9] [2]));
  SDFFQX1 \balance_db_reg[9][3] (.CK (clk), .D (\balance_db[9] [3]),
       .SI (n_66), .SE (n_1), .Q (\balance_db[9] [3]));
  SDFFQX1 \balance_db_reg[9][4] (.CK (clk), .D (\balance_db[9] [4]),
       .SI (n_50), .SE (n_1), .Q (\balance_db[9] [4]));
  SDFFQX1 \balance_db_reg[9][5] (.CK (clk), .D (\balance_db[9] [5]),
       .SI (n_64), .SE (n_1), .Q (\balance_db[9] [5]));
  SDFFQX1 \balance_db_reg[9][6] (.CK (clk), .D (\balance_db[9] [6]),
       .SI (n_60), .SE (n_1), .Q (\balance_db[9] [6]));
  SDFFQX1 \balance_db_reg[9][7] (.CK (clk), .D (\balance_db[9] [7]),
       .SI (n_83), .SE (n_1), .Q (\balance_db[9] [7]));
  SDFFQX1 \balance_db_reg[9][8] (.CK (clk), .D (\balance_db[9] [8]),
       .SI (n_51), .SE (n_1), .Q (\balance_db[9] [8]));
  SDFFQX1 \balance_db_reg[9][9] (.CK (clk), .D (\balance_db[9] [9]),
       .SI (n_65), .SE (n_1), .Q (\balance_db[9] [9]));
  SDFFQX1 \balance_db_reg[9][10] (.CK (clk), .D (\balance_db[9] [10]),
       .SI (n_61), .SE (n_1), .Q (\balance_db[9] [10]));
  SDFFQX1 \balance_db_reg[9][11] (.CK (clk), .D (\balance_db[9] [11]),
       .SI (n_84), .SE (n_1), .Q (\balance_db[9] [11]));
  SDFFQX1 \balance_db_reg[9][12] (.CK (clk), .D (\balance_db[9] [12]),
       .SI (n_62), .SE (n_1), .Q (\balance_db[9] [12]));
  SDFFQX1 \balance_db_reg[9][13] (.CK (clk), .D (\balance_db[9] [13]),
       .SI (n_82), .SE (n_1), .Q (\balance_db[9] [13]));
  SDFFQX1 \balance_db_reg[9][14] (.CK (clk), .D (\balance_db[9] [14]),
       .SI (n_57), .SE (n_1), .Q (\balance_db[9] [14]));
  SDFFQX1 \balance_db_reg[9][15] (.CK (clk), .D (\balance_db[9] [15]),
       .SI (n_401), .SE (n_1), .Q (\balance_db[9] [15]));
  SDFFQX1 \balance_db_reg[10][1] (.CK (clk), .D (\balance_db[10] [1]),
       .SI (n_4), .SE (n_53), .Q (\balance_db[10] [1]));
  SDFFQX1 \balance_db_reg[10][2] (.CK (clk), .D (\balance_db[10] [2]),
       .SI (n_25), .SE (n_53), .Q (\balance_db[10] [2]));
  SDFFQX1 \balance_db_reg[10][3] (.CK (clk), .D (\balance_db[10] [3]),
       .SI (n_66), .SE (n_53), .Q (\balance_db[10] [3]));
  SDFFQX1 \balance_db_reg[10][4] (.CK (clk), .D (\balance_db[10] [4]),
       .SI (n_50), .SE (n_53), .Q (\balance_db[10] [4]));
  SDFFQX1 \balance_db_reg[10][5] (.CK (clk), .D (\balance_db[10] [5]),
       .SI (n_64), .SE (n_53), .Q (\balance_db[10] [5]));
  SDFFQX1 \balance_db_reg[10][6] (.CK (clk), .D (\balance_db[10] [6]),
       .SI (n_60), .SE (n_53), .Q (\balance_db[10] [6]));
  SDFFQX1 \balance_db_reg[10][7] (.CK (clk), .D (\balance_db[10] [7]),
       .SI (n_83), .SE (n_53), .Q (\balance_db[10] [7]));
  SDFFQX1 \balance_db_reg[10][8] (.CK (clk), .D (\balance_db[10] [8]),
       .SI (n_51), .SE (n_53), .Q (\balance_db[10] [8]));
  SDFFQX1 \balance_db_reg[10][9] (.CK (clk), .D (\balance_db[10] [9]),
       .SI (n_65), .SE (n_53), .Q (\balance_db[10] [9]));
  SDFFQX1 \balance_db_reg[10][10] (.CK (clk), .D (\balance_db[10]
       [10]), .SI (n_61), .SE (n_53), .Q (\balance_db[10] [10]));
  SDFFQX1 \balance_db_reg[10][11] (.CK (clk), .D (\balance_db[10]
       [11]), .SI (n_84), .SE (n_53), .Q (\balance_db[10] [11]));
  SDFFQX1 \balance_db_reg[10][12] (.CK (clk), .D (\balance_db[10]
       [12]), .SI (n_62), .SE (n_53), .Q (\balance_db[10] [12]));
  SDFFQX1 \balance_db_reg[10][13] (.CK (clk), .D (\balance_db[10]
       [13]), .SI (n_82), .SE (n_53), .Q (\balance_db[10] [13]));
  SDFFQX1 \balance_db_reg[10][14] (.CK (clk), .D (\balance_db[10]
       [14]), .SI (n_57), .SE (n_53), .Q (\balance_db[10] [14]));
  SDFFQX1 \balance_db_reg[10][15] (.CK (clk), .D (\balance_db[10]
       [15]), .SI (n_401), .SE (n_53), .Q (\balance_db[10] [15]));
  SDFFQX1 \balance_db_reg[11][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[11] [1]), .SE (n_36), .Q (\balance_db[11] [1]));
  SDFFQX1 \balance_db_reg[11][2] (.CK (clk), .D (n_25), .SI
       (\balance_db[11] [2]), .SE (n_36), .Q (\balance_db[11] [2]));
  SDFFQX1 \balance_db_reg[11][3] (.CK (clk), .D (n_66), .SI
       (\balance_db[11] [3]), .SE (n_36), .Q (\balance_db[11] [3]));
  SDFFQX1 \balance_db_reg[11][4] (.CK (clk), .D (n_50), .SI
       (\balance_db[11] [4]), .SE (n_36), .Q (\balance_db[11] [4]));
  SDFFQX1 \balance_db_reg[11][5] (.CK (clk), .D (n_64), .SI
       (\balance_db[11] [5]), .SE (n_36), .Q (\balance_db[11] [5]));
  SDFFQX1 \balance_db_reg[11][6] (.CK (clk), .D (n_60), .SI
       (\balance_db[11] [6]), .SE (n_36), .Q (\balance_db[11] [6]));
  SDFFQX1 \balance_db_reg[11][7] (.CK (clk), .D (n_83), .SI
       (\balance_db[11] [7]), .SE (n_36), .Q (\balance_db[11] [7]));
  SDFFQX1 \balance_db_reg[11][8] (.CK (clk), .D (n_51), .SI
       (\balance_db[11] [8]), .SE (n_36), .Q (\balance_db[11] [8]));
  SDFFQX1 \balance_db_reg[11][9] (.CK (clk), .D (n_65), .SI
       (\balance_db[11] [9]), .SE (n_36), .Q (\balance_db[11] [9]));
  SDFFQX1 \balance_db_reg[11][10] (.CK (clk), .D (n_61), .SI
       (\balance_db[11] [10]), .SE (n_36), .Q (\balance_db[11] [10]));
  SDFFQX1 \balance_db_reg[11][11] (.CK (clk), .D (n_84), .SI
       (\balance_db[11] [11]), .SE (n_36), .Q (\balance_db[11] [11]));
  SDFFQX1 \balance_db_reg[11][12] (.CK (clk), .D (n_62), .SI
       (\balance_db[11] [12]), .SE (n_36), .Q (\balance_db[11] [12]));
  SDFFQX1 \balance_db_reg[11][13] (.CK (clk), .D (n_82), .SI
       (\balance_db[11] [13]), .SE (n_36), .Q (\balance_db[11] [13]));
  SDFFQX1 \balance_db_reg[11][14] (.CK (clk), .D (n_57), .SI
       (\balance_db[11] [14]), .SE (n_36), .Q (\balance_db[11] [14]));
  SDFFQX1 \balance_db_reg[11][15] (.CK (clk), .D (n_401), .SI
       (\balance_db[11] [15]), .SE (n_36), .Q (\balance_db[11] [15]));
  SDFFQX1 \balance_db_reg[12][1] (.CK (clk), .D (\balance_db[12] [1]),
       .SI (n_4), .SE (n_52), .Q (\balance_db[12] [1]));
  SDFFQX1 \balance_db_reg[12][2] (.CK (clk), .D (\balance_db[12] [2]),
       .SI (n_25), .SE (n_52), .Q (\balance_db[12] [2]));
  SDFFQX1 \balance_db_reg[12][3] (.CK (clk), .D (\balance_db[12] [3]),
       .SI (n_66), .SE (n_52), .Q (\balance_db[12] [3]));
  SDFFQX1 \balance_db_reg[12][4] (.CK (clk), .D (\balance_db[12] [4]),
       .SI (n_50), .SE (n_52), .Q (\balance_db[12] [4]));
  SDFFQX1 \balance_db_reg[12][5] (.CK (clk), .D (\balance_db[12] [5]),
       .SI (n_64), .SE (n_52), .Q (\balance_db[12] [5]));
  SDFFQX1 \balance_db_reg[12][6] (.CK (clk), .D (\balance_db[12] [6]),
       .SI (n_60), .SE (n_52), .Q (\balance_db[12] [6]));
  SDFFQX1 \balance_db_reg[12][7] (.CK (clk), .D (\balance_db[12] [7]),
       .SI (n_83), .SE (n_52), .Q (\balance_db[12] [7]));
  SDFFQX1 \balance_db_reg[12][8] (.CK (clk), .D (\balance_db[12] [8]),
       .SI (n_51), .SE (n_52), .Q (\balance_db[12] [8]));
  SDFFQX1 \balance_db_reg[12][9] (.CK (clk), .D (\balance_db[12] [9]),
       .SI (n_65), .SE (n_52), .Q (\balance_db[12] [9]));
  SDFFQX1 \balance_db_reg[12][10] (.CK (clk), .D (\balance_db[12]
       [10]), .SI (n_61), .SE (n_52), .Q (\balance_db[12] [10]));
  SDFFQX1 \balance_db_reg[12][11] (.CK (clk), .D (\balance_db[12]
       [11]), .SI (n_84), .SE (n_52), .Q (\balance_db[12] [11]));
  SDFFQX1 \balance_db_reg[12][12] (.CK (clk), .D (\balance_db[12]
       [12]), .SI (n_62), .SE (n_52), .Q (\balance_db[12] [12]));
  SDFFQX1 \balance_db_reg[12][13] (.CK (clk), .D (\balance_db[12]
       [13]), .SI (n_82), .SE (n_52), .Q (\balance_db[12] [13]));
  SDFFQX1 \balance_db_reg[12][14] (.CK (clk), .D (\balance_db[12]
       [14]), .SI (n_57), .SE (n_52), .Q (\balance_db[12] [14]));
  SDFFQX1 \balance_db_reg[12][15] (.CK (clk), .D (\balance_db[12]
       [15]), .SI (n_401), .SE (n_52), .Q (\balance_db[12] [15]));
  SDFFQX1 \balance_db_reg[13][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[13] [1]), .SE (n_37), .Q (\balance_db[13] [1]));
  SDFFQX1 \balance_db_reg[13][2] (.CK (clk), .D (n_25), .SI
       (\balance_db[13] [2]), .SE (n_37), .Q (\balance_db[13] [2]));
  SDFFQX1 \balance_db_reg[13][3] (.CK (clk), .D (n_66), .SI
       (\balance_db[13] [3]), .SE (n_37), .Q (\balance_db[13] [3]));
  SDFFQX1 \balance_db_reg[13][4] (.CK (clk), .D (n_50), .SI
       (\balance_db[13] [4]), .SE (n_37), .Q (\balance_db[13] [4]));
  SDFFQX1 \balance_db_reg[13][5] (.CK (clk), .D (n_64), .SI
       (\balance_db[13] [5]), .SE (n_37), .Q (\balance_db[13] [5]));
  SDFFQX1 \balance_db_reg[13][6] (.CK (clk), .D (n_60), .SI
       (\balance_db[13] [6]), .SE (n_37), .Q (\balance_db[13] [6]));
  SDFFQX1 \balance_db_reg[13][7] (.CK (clk), .D (n_83), .SI
       (\balance_db[13] [7]), .SE (n_37), .Q (\balance_db[13] [7]));
  SDFFQX1 \balance_db_reg[13][8] (.CK (clk), .D (n_51), .SI
       (\balance_db[13] [8]), .SE (n_37), .Q (\balance_db[13] [8]));
  SDFFQX1 \balance_db_reg[13][9] (.CK (clk), .D (n_65), .SI
       (\balance_db[13] [9]), .SE (n_37), .Q (\balance_db[13] [9]));
  SDFFQX1 \balance_db_reg[13][10] (.CK (clk), .D (n_61), .SI
       (\balance_db[13] [10]), .SE (n_37), .Q (\balance_db[13] [10]));
  SDFFQX1 \balance_db_reg[13][11] (.CK (clk), .D (n_84), .SI
       (\balance_db[13] [11]), .SE (n_37), .Q (\balance_db[13] [11]));
  SDFFQX1 \balance_db_reg[13][12] (.CK (clk), .D (n_62), .SI
       (\balance_db[13] [12]), .SE (n_37), .Q (\balance_db[13] [12]));
  SDFFQX1 \balance_db_reg[13][13] (.CK (clk), .D (n_82), .SI
       (\balance_db[13] [13]), .SE (n_37), .Q (\balance_db[13] [13]));
  SDFFQX1 \balance_db_reg[13][14] (.CK (clk), .D (n_57), .SI
       (\balance_db[13] [14]), .SE (n_37), .Q (\balance_db[13] [14]));
  SDFFQX1 \balance_db_reg[13][15] (.CK (clk), .D (n_401), .SI
       (\balance_db[13] [15]), .SE (n_37), .Q (\balance_db[13] [15]));
  SDFFQX1 \balance_db_reg[14][1] (.CK (clk), .D (\balance_db[14] [1]),
       .SI (n_4), .SE (n_55), .Q (\balance_db[14] [1]));
  SDFFQX1 \balance_db_reg[14][2] (.CK (clk), .D (\balance_db[14] [2]),
       .SI (n_25), .SE (n_55), .Q (\balance_db[14] [2]));
  SDFFQX1 \balance_db_reg[14][3] (.CK (clk), .D (\balance_db[14] [3]),
       .SI (n_66), .SE (n_55), .Q (\balance_db[14] [3]));
  SDFFQX1 \balance_db_reg[14][4] (.CK (clk), .D (\balance_db[14] [4]),
       .SI (n_50), .SE (n_55), .Q (\balance_db[14] [4]));
  SDFFQX1 \balance_db_reg[14][5] (.CK (clk), .D (\balance_db[14] [5]),
       .SI (n_64), .SE (n_55), .Q (\balance_db[14] [5]));
  SDFFQX1 \balance_db_reg[14][6] (.CK (clk), .D (\balance_db[14] [6]),
       .SI (n_60), .SE (n_55), .Q (\balance_db[14] [6]));
  SDFFQX1 \balance_db_reg[14][7] (.CK (clk), .D (\balance_db[14] [7]),
       .SI (n_83), .SE (n_55), .Q (\balance_db[14] [7]));
  SDFFQX1 \balance_db_reg[14][8] (.CK (clk), .D (\balance_db[14] [8]),
       .SI (n_51), .SE (n_55), .Q (\balance_db[14] [8]));
  SDFFQX1 \balance_db_reg[14][9] (.CK (clk), .D (\balance_db[14] [9]),
       .SI (n_65), .SE (n_55), .Q (\balance_db[14] [9]));
  SDFFQX1 \balance_db_reg[14][10] (.CK (clk), .D (\balance_db[14]
       [10]), .SI (n_61), .SE (n_55), .Q (\balance_db[14] [10]));
  SDFFQX1 \balance_db_reg[14][11] (.CK (clk), .D (\balance_db[14]
       [11]), .SI (n_84), .SE (n_55), .Q (\balance_db[14] [11]));
  SDFFQX1 \balance_db_reg[14][12] (.CK (clk), .D (\balance_db[14]
       [12]), .SI (n_62), .SE (n_55), .Q (\balance_db[14] [12]));
  SDFFQX1 \balance_db_reg[14][13] (.CK (clk), .D (\balance_db[14]
       [13]), .SI (n_82), .SE (n_55), .Q (\balance_db[14] [13]));
  SDFFQX1 \balance_db_reg[14][14] (.CK (clk), .D (\balance_db[14]
       [14]), .SI (n_57), .SE (n_55), .Q (\balance_db[14] [14]));
  SDFFQX1 \balance_db_reg[14][15] (.CK (clk), .D (\balance_db[14]
       [15]), .SI (n_401), .SE (n_55), .Q (\balance_db[14] [15]));
  SDFFQX1 \balance_db_reg[15][1] (.CK (clk), .D (n_4), .SI
       (\balance_db[15] [1]), .SE (n_39), .Q (\balance_db[15] [1]));
  SDFFQX1 \balance_db_reg[15][2] (.CK (clk), .D (n_25), .SI
       (\balance_db[15] [2]), .SE (n_39), .Q (\balance_db[15] [2]));
  SDFFQX1 \balance_db_reg[15][3] (.CK (clk), .D (n_66), .SI
       (\balance_db[15] [3]), .SE (n_39), .Q (\balance_db[15] [3]));
  SDFFQX1 \balance_db_reg[15][4] (.CK (clk), .D (n_50), .SI
       (\balance_db[15] [4]), .SE (n_39), .Q (\balance_db[15] [4]));
  SDFFQX1 \balance_db_reg[15][5] (.CK (clk), .D (n_64), .SI
       (\balance_db[15] [5]), .SE (n_39), .Q (\balance_db[15] [5]));
  SDFFQX1 \balance_db_reg[15][6] (.CK (clk), .D (n_60), .SI
       (\balance_db[15] [6]), .SE (n_39), .Q (\balance_db[15] [6]));
  SDFFQX1 \balance_db_reg[15][7] (.CK (clk), .D (n_83), .SI
       (\balance_db[15] [7]), .SE (n_39), .Q (\balance_db[15] [7]));
  SDFFQX1 \balance_db_reg[15][8] (.CK (clk), .D (n_51), .SI
       (\balance_db[15] [8]), .SE (n_39), .Q (\balance_db[15] [8]));
  SDFFQX1 \balance_db_reg[15][9] (.CK (clk), .D (n_65), .SI
       (\balance_db[15] [9]), .SE (n_39), .Q (\balance_db[15] [9]));
  SDFFQX1 \balance_db_reg[15][10] (.CK (clk), .D (n_61), .SI
       (\balance_db[15] [10]), .SE (n_39), .Q (\balance_db[15] [10]));
  SDFFQX1 \balance_db_reg[15][11] (.CK (clk), .D (n_84), .SI
       (\balance_db[15] [11]), .SE (n_39), .Q (\balance_db[15] [11]));
  SDFFQX1 \balance_db_reg[15][12] (.CK (clk), .D (n_62), .SI
       (\balance_db[15] [12]), .SE (n_39), .Q (\balance_db[15] [12]));
  SDFFQX1 \balance_db_reg[15][13] (.CK (clk), .D (n_82), .SI
       (\balance_db[15] [13]), .SE (n_39), .Q (\balance_db[15] [13]));
  SDFFQX1 \balance_db_reg[15][14] (.CK (clk), .D (n_57), .SI
       (\balance_db[15] [14]), .SE (n_39), .Q (\balance_db[15] [14]));
  SDFFQX1 \balance_db_reg[15][15] (.CK (clk), .D (n_401), .SI
       (\balance_db[15] [15]), .SE (n_39), .Q (\balance_db[15] [15]));
  AO22XL g3334(.A0 (n_67), .A1 (n_401), .B0 (n_85), .B1
       (\balance_db[3] [15]), .Y (n_141));
  AO22X1 g3335(.A0 (n_72), .A1 (n_401), .B0 (n_86), .B1
       (\balance_db[1] [15]), .Y (n_140));
  AO22XL g3336(.A0 (n_70), .A1 (n_401), .B0 (n_3), .B1
       (\balance_db[2] [15]), .Y (n_139));
  AO22X1 g3423(.A0 (n_72), .A1 (n_57), .B0 (n_86), .B1
       (\balance_db[1] [14]), .Y (n_138));
  OAI211XL g3424(.A0 (n_73), .A1 (n_47), .B0 (n_5), .C0 (n_79), .Y
       (n_137));
  OAI211XL g3425(.A0 (n_73), .A1 (n_49), .B0 (n_5), .C0 (n_77), .Y
       (n_136));
  OAI211XL g3426(.A0 (n_74), .A1 (n_26), .B0 (n_5), .C0 (n_81), .Y
       (n_135));
  OAI211XL g3427(.A0 (n_74), .A1 (n_49), .B0 (n_5), .C0 (n_76), .Y
       (n_134));
  AO22XL g3429(.A0 (n_70), .A1 (n_57), .B0 (n_3), .B1
       (\balance_db[2] [14]), .Y (n_132));
  AO22XL g3430(.A0 (n_85), .A1 (\balance_db[3] [1]), .B0 (n_67), .B1
       (n_4), .Y (n_131));
  AO22XL g3431(.A0 (n_67), .A1 (n_60), .B0 (n_85), .B1
       (\balance_db[3] [6]), .Y (n_130));
  AO22XL g3432(.A0 (n_67), .A1 (n_51), .B0 (n_85), .B1
       (\balance_db[3] [8]), .Y (n_129));
  AO22XL g3433(.A0 (n_67), .A1 (n_61), .B0 (n_85), .B1
       (\balance_db[3] [10]), .Y (n_128));
  AO22XL g3434(.A0 (n_67), .A1 (n_62), .B0 (n_85), .B1
       (\balance_db[3] [12]), .Y (n_127));
  AO22XL g3435(.A0 (n_67), .A1 (n_57), .B0 (n_85), .B1
       (\balance_db[3] [14]), .Y (n_126));
  AO22XL g3436(.A0 (n_86), .A1 (\balance_db[1] [1]), .B0 (n_72), .B1
       (n_4), .Y (n_125));
  AO22XL g3437(.A0 (n_72), .A1 (n_66), .B0 (n_86), .B1
       (\balance_db[1] [3]), .Y (n_124));
  OAI21XL g3438(.A0 (n_26), .A1 (n_71), .B0 (n_87), .Y (n_123));
  AO22XL g3439(.A0 (n_72), .A1 (n_83), .B0 (n_86), .B1
       (\balance_db[1] [7]), .Y (n_122));
  OAI21XL g3440(.A0 (n_24), .A1 (n_71), .B0 (n_94), .Y (n_121));
  AO22XL g3441(.A0 (n_72), .A1 (n_65), .B0 (n_86), .B1
       (\balance_db[1] [9]), .Y (n_120));
  OAI21XL g3442(.A0 (n_40), .A1 (n_71), .B0 (n_93), .Y (n_119));
  AO22XL g3443(.A0 (n_72), .A1 (n_84), .B0 (n_86), .B1
       (\balance_db[1] [11]), .Y (n_118));
  OAI21XL g3444(.A0 (n_46), .A1 (n_71), .B0 (n_92), .Y (n_117));
  AO22XL g3445(.A0 (n_72), .A1 (n_82), .B0 (n_86), .B1
       (\balance_db[1] [13]), .Y (n_116));
  AO22XL g3447(.A0 (n_3), .A1 (\balance_db[2] [1]), .B0 (n_70), .B1
       (n_4), .Y (n_114));
  AO22XL g3448(.A0 (n_70), .A1 (n_66), .B0 (n_3), .B1
       (\balance_db[2] [3]), .Y (n_113));
  OAI21X1 g3449(.A0 (n_69), .A1 (n_26), .B0 (n_91), .Y (n_112));
  AO22XL g3450(.A0 (n_70), .A1 (n_64), .B0 (n_3), .B1
       (\balance_db[2] [5]), .Y (n_111));
  OAI21X1 g3451(.A0 (n_69), .A1 (n_47), .B0 (n_90), .Y (n_110));
  AO22XL g3452(.A0 (n_70), .A1 (n_83), .B0 (n_3), .B1
       (\balance_db[2] [7]), .Y (n_109));
  OAI21X1 g3453(.A0 (n_69), .A1 (n_24), .B0 (n_89), .Y (n_108));
  AO22XL g3454(.A0 (n_70), .A1 (n_65), .B0 (n_3), .B1
       (\balance_db[2] [9]), .Y (n_107));
  OAI21X1 g3455(.A0 (n_69), .A1 (n_40), .B0 (n_88), .Y (n_106));
  AO22XL g3456(.A0 (n_70), .A1 (n_84), .B0 (n_3), .B1
       (\balance_db[2] [11]), .Y (n_105));
  OAI21X1 g3457(.A0 (n_69), .A1 (n_46), .B0 (n_95), .Y (n_104));
  AO22XL g3458(.A0 (n_70), .A1 (n_82), .B0 (n_3), .B1
       (\balance_db[2] [13]), .Y (n_103));
  AO22XL g3459(.A0 (n_67), .A1 (n_66), .B0 (n_85), .B1
       (\balance_db[3] [3]), .Y (n_102));
  AO22XL g3460(.A0 (n_67), .A1 (n_64), .B0 (n_85), .B1
       (\balance_db[3] [5]), .Y (n_101));
  AO22XL g3461(.A0 (n_67), .A1 (n_83), .B0 (n_85), .B1
       (\balance_db[3] [7]), .Y (n_100));
  AO22XL g3462(.A0 (n_67), .A1 (n_65), .B0 (n_85), .B1
       (\balance_db[3] [9]), .Y (n_99));
  AO22XL g3463(.A0 (n_67), .A1 (n_84), .B0 (n_85), .B1
       (\balance_db[3] [11]), .Y (n_98));
  AO22XL g3464(.A0 (n_67), .A1 (n_82), .B0 (n_85), .B1
       (\balance_db[3] [13]), .Y (n_97));
  NAND2XL g3504(.A (n_3), .B (\balance_db[2] [12]), .Y (n_95));
  NAND2XL g3505(.A (n_86), .B (\balance_db[1] [8]), .Y (n_94));
  NAND2XL g3506(.A (n_86), .B (\balance_db[1] [10]), .Y (n_93));
  NAND2XL g3507(.A (n_86), .B (\balance_db[1] [12]), .Y (n_92));
  NAND2XL g3508(.A (n_3), .B (\balance_db[2] [4]), .Y (n_91));
  NAND2XL g3509(.A (n_3), .B (\balance_db[2] [6]), .Y (n_90));
  NAND2XL g3510(.A (n_3), .B (\balance_db[2] [8]), .Y (n_89));
  NAND2XL g3511(.A (n_3), .B (\balance_db[2] [10]), .Y (n_88));
  NAND2XL g3512(.A (n_86), .B (\balance_db[1] [4]), .Y (n_87));
  NAND2XL g3561(.A (\balance_db[3] [4]), .B (n_74), .Y (n_81));
  NAND2XL g3563(.A (\balance_db[1] [6]), .B (n_73), .Y (n_79));
  NAND2XL g3565(.A (\balance_db[1] [2]), .B (n_73), .Y (n_77));
  NAND2XL g3566(.A (\balance_db[3] [2]), .B (n_74), .Y (n_76));
  OAI21X1 g3577(.A0 (reset), .A1 (n_59), .B0 (n_13), .Y (n_86));
  OR2X1 g3578(.A (n_68), .B (n_14), .Y (n_85));
  CLKXOR2X1 g3580(.A (n_379), .B (n_33), .Y (n_84));
  CLKXOR2X1 g3581(.A (n_375), .B (n_31), .Y (n_83));
  CLKXOR2X1 g3582(.A (n_381), .B (n_32), .Y (n_82));
  CLKINVX1 g3583(.A (n_72), .Y (n_71));
  CLKINVX1 g3584(.A (n_70), .Y (n_69));
  NOR2XL g3585(.A (id_to_check[0]), .B (n_2), .Y (n_75));
  NAND2XL g3586(.A (id_to_check[0]), .B (n_58), .Y (n_74));
  NAND2XL g3587(.A (id_to_check[0]), .B (n_59), .Y (n_73));
  NOR2BX1 g3588(.AN (n_59), .B (n_12), .Y (n_72));
  NOR2XL g3589(.A (n_13), .B (n_2), .Y (n_70));
  NOR2XL g3592(.A (reset), .B (n_58), .Y (n_68));
  NOR2XL g3593(.A (n_12), .B (n_2), .Y (n_67));
  CLKXOR2X1 g3594(.A (n_395), .B (n_19), .Y (n_66));
  CLKXOR2X1 g3595(.A (n_377), .B (n_18), .Y (n_65));
  CLKXOR2X1 g3596(.A (n_373), .B (n_20), .Y (n_64));
  CLKINVX1 g3597(.A (n_46), .Y (n_62));
  CLKINVX1 g3598(.A (n_40), .Y (n_61));
  CLKINVX1 g3599(.A (n_47), .Y (n_60));
  CLKINVX1 g3600(.A (n_2), .Y (n_58));
  NOR2XL g3601(.A (id_to_check[1]), .B (n_41), .Y (n_59));
  AO21X1 g3603(.A0 (n_382), .A1 (n_34), .B0 (n_48), .Y (n_57));
  AND2X1 g3604(.A (n_42), .B (n_15), .Y (n_56));
  AND2X1 g3605(.A (n_43), .B (n_15), .Y (n_55));
  NAND3X1 g3606(.A (n_27), .B (n_22), .C (n_385), .Y (n_54));
  AND2X1 g3607(.A (n_44), .B (n_15), .Y (n_53));
  AND3X1 g3608(.A (n_27), .B (id_to_check[2]), .C (n_15), .Y (n_52));
  CLKINVX1 g3609(.A (n_24), .Y (n_51));
  CLKINVX1 g3610(.A (n_26), .Y (n_50));
  CLKINVX1 g3611(.A (n_25), .Y (n_49));
  NOR2XL g3612(.A (n_30), .B (id_to_check[2]), .Y (n_44));
  NOR2XL g3613(.A (n_30), .B (n_7), .Y (n_43));
  NOR2BX1 g3614(.AN (n_27), .B (id_to_check[2]), .Y (n_42));
  NOR2XL g3615(.A (n_382), .B (n_34), .Y (n_48));
  AOI21X1 g3616(.A0 (n_374), .A1 (n_16), .B0 (n_31), .Y (n_47));
  AOI21X1 g3617(.A0 (n_380), .A1 (n_17), .B0 (n_32), .Y (n_46));
  AND2X1 g3619(.A (n_27), .B (n_28), .Y (n_45));
  NAND3BX1 g3621(.AN (n_384), .B (n_22), .C (fsm_charge_req), .Y
       (n_41));
  AOI21X1 g3622(.A0 (n_378), .A1 (n_21), .B0 (n_33), .Y (n_40));
  OR2X1 g3623(.A (n_29), .B (n_8), .Y (n_39));
  AND2X1 g3624(.A (n_23), .B (n_28), .Y (n_38));
  OR3X1 g3626(.A (n_29), .B (id_to_check[1]), .C (n_7), .Y (n_37));
  OR2X1 g3627(.A (n_29), .B (n_10), .Y (n_36));
  AND3X1 g3628(.A (n_11), .B (id_to_check[1]), .C (n_28), .Y (n_35));
  NAND2BX1 g3630(.AN (n_17), .B (n_390), .Y (n_34));
  NOR2XL g3631(.A (n_378), .B (n_21), .Y (n_33));
  NOR2XL g3632(.A (n_380), .B (n_17), .Y (n_32));
  NOR2XL g3633(.A (n_374), .B (n_16), .Y (n_31));
  NAND2XL g3634(.A (n_14), .B (id_to_check[1]), .Y (n_30));
  NAND2XL g3635(.A (n_11), .B (n_15), .Y (n_29));
  NOR2XL g3637(.A (n_12), .B (id_to_check[1]), .Y (n_23));
  NOR3BX1 g3638(.AN (n_385), .B (id_to_check[3]), .C (n_7), .Y (n_28));
  NOR2XL g3639(.A (n_13), .B (id_to_check[1]), .Y (n_27));
  AOI21X1 g3640(.A0 (n_372), .A1 (n_389), .B0 (n_20), .Y (n_26));
  AO21X1 g3641(.A0 (n_371), .A1 (n_386), .B0 (n_19), .Y (n_25));
  AOI21X1 g3642(.A0 (n_376), .A1 (n_388), .B0 (n_18), .Y (n_24));
  NOR2XL g3643(.A (id_to_check[3]), .B (id_to_check[2]), .Y (n_22));
  NAND2BX1 g3644(.AN (n_388), .B (n_391), .Y (n_21));
  NOR2XL g3645(.A (n_372), .B (n_389), .Y (n_20));
  NOR2XL g3646(.A (n_371), .B (n_386), .Y (n_19));
  NOR2XL g3647(.A (n_376), .B (n_388), .Y (n_18));
  NAND2BX1 g3648(.AN (n_388), .B (n_387), .Y (n_17));
  CLKINVX1 g3649(.A (n_14), .Y (n_13));
  CLKINVX1 g3650(.A (n_12), .Y (n_11));
  NAND2XL g3651(.A (id_to_check[1]), .B (n_7), .Y (n_10));
  NOR2XL g3652(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_9));
  NAND2XL g3653(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_8));
  NAND2BX1 g3654(.AN (n_389), .B (n_392), .Y (n_16));
  AND2X1 g3655(.A (id_to_check[3]), .B (n_385), .Y (n_15));
  NOR2XL g3656(.A (reset), .B (id_to_check[0]), .Y (n_14));
  NAND2XL g3657(.A (n_5), .B (id_to_check[0]), .Y (n_12));
  CLKINVX1 g3658(.A (id_to_check[2]), .Y (n_7));
  CLKINVX1 g3660(.A (reset), .Y (n_5));
  CLKINVX1 g3661(.A (n_386), .Y (n_4));
  NAND2BX1 g17417(.AN (n_68), .B (n_12), .Y (n_3));
  NAND2BX1 g3662(.AN (n_41), .B (id_to_check[1]), .Y (n_2));
  NOR2BX1 g3663(.AN (n_9), .B (n_29), .Y (n_1));
  NOR2BX1 g3664(.AN (n_28), .B (n_30), .Y (n_0));
  NOR2BXL g17418(.AN (n_385), .B (reset), .Y (n_398));
  NAND2XL g17419(.A (n_399), .B (n_5), .Y (n_400));
  MXI2XL g3(.A (n_64), .B (\balance_db[1] [5]), .S0 (n_73), .Y (n_399));
  XNOR2X1 g17420(.A (n_365), .B (n_48), .Y (n_401));
  AO22XL g17423(.A0 (\balance_db[3] [8]), .A1 (n_158), .B0
       (\balance_db[10] [8]), .B1 (n_163), .Y (n_404));
  AO22XL g17424(.A0 (\balance_db[2] [8]), .A1 (n_172), .B0
       (\balance_db[11] [8]), .B1 (n_142), .Y (n_405));
  NAND2XL g17425(.A (n_406), .B (n_5), .Y (n_407));
  MXI2XL g17426(.A (\balance_db[2] [2]), .B (n_25), .S0 (n_75), .Y
       (n_406));
  AOI221X1 g17427(.A0 (\balance_db[13] [8]), .A1 (n_211), .B0
       (\balance_db[12] [8]), .B1 (n_216), .C0 (n_349), .Y (n_408));
endmodule

module barrier_ctrl(clk, reset, fsm_open_en, fsm_close_en,
     barrier_open_cmd, barrier_close_cmd, gate_is_open, gate_is_closed);
  input clk, reset, fsm_open_en, fsm_close_en;
  output barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed;
  wire clk, reset, fsm_open_en, fsm_close_en;
  wire barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed;
  wire [2:0] barrier_position_counter;
  wire n_0, n_1, n_2, n_4, n_5, n_7, n_8, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_17, n_18, n_19;
  wire n_22, n_23, n_24, n_25, n_26, n_31, n_32, n_33;
  INVXL g223(.A (n_23), .Y (gate_is_closed));
  DFFQXL barrier_close_cmd_reg(.CK (clk), .D (n_19), .Q
       (barrier_close_cmd));
  DFFQXL barrier_open_cmd_reg(.CK (clk), .D (n_18), .Q
       (barrier_open_cmd));
  OAI21X1 g317(.A0 (n_25), .A1 (n_24), .B0 (n_15), .Y (n_19));
  INVXL g318(.A (n_17), .Y (n_18));
  AOI31X1 g319(.A0 (n_15), .A1 (fsm_open_en), .A2 (n_24), .B0 (n_25),
       .Y (n_17));
  NOR2XL g320(.A (reset), .B (n_22), .Y (n_25));
  NAND2XL g321(.A (n_16), .B (fsm_open_en), .Y (n_22));
  NAND3X1 g322(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .C (barrier_position_counter[2]),
       .Y (n_16));
  OR3X1 g323(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[2]), .C (barrier_position_counter[1]),
       .Y (n_23));
  CLKINVX1 g324(.A (fsm_close_en), .Y (n_24));
  INVXL g325(.A (barrier_position_counter[0]), .Y (n_26));
  INVX1 g326(.A (reset), .Y (n_15));
  DFFQX1 \barrier_position_counter_reg[2] (.CK (clk), .D (n_14), .Q
       (barrier_position_counter[2]));
  DFFQX1 \barrier_position_counter_reg[1] (.CK (clk), .D (n_12), .Q
       (barrier_position_counter[1]));
  MXI2XL g464(.A (n_31), .B (n_32), .S0 (barrier_position_counter[2]),
       .Y (n_14));
  DFFQX1 \barrier_position_counter_reg[0] (.CK (clk), .D (n_13), .Q
       (barrier_position_counter[0]));
  OAI2BB1X1 g466(.A0N (n_33), .A1N (barrier_position_counter[0]), .B0
       (n_11), .Y (n_13));
  OAI2BB1X1 g467(.A0N (n_33), .A1N (barrier_position_counter[1]), .B0
       (n_8), .Y (n_12));
  OAI21X1 g468(.A0 (n_5), .A1 (n_25), .B0 (n_26), .Y (n_11));
  MXI2XL g471(.A (n_25), .B (n_5), .S0 (n_4), .Y (n_8));
  NOR2BX1 g472(.AN (n_5), .B (n_1), .Y (n_7));
  NOR4BX1 g474(.AN (n_23), .B (reset), .C (n_24), .D (n_0), .Y (n_5));
  NAND2BX1 g475(.AN (n_1), .B (n_2), .Y (n_4));
  NAND2XL g477(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_2));
  NOR2XL g478(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_1));
  INVX1 g479(.A (n_22), .Y (n_0));
  NAND2BX1 g2(.AN (n_2), .B (n_25), .Y (n_31));
  NOR3XL g480(.A (n_25), .B (n_33), .C (n_7), .Y (n_32));
  NOR3X1 g481(.A (fsm_close_en), .B (reset), .C (n_0), .Y (n_33));
endmodule

module vehicle_interface(clk, reset, fsm_read_en, vehicle_id_in,
     id_to_check, id_valid);
  input clk, reset, fsm_read_en;
  input [7:0] vehicle_id_in;
  output [3:0] id_to_check;
  output id_valid;
  wire clk, reset, fsm_read_en;
  wire [7:0] vehicle_id_in;
  wire [3:0] id_to_check;
  wire id_valid;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_16;
  DFFQX1 id_valid_reg(.CK (clk), .D (n_16), .Q (id_valid));
  DFFQX1 \id_to_check_reg[0] (.CK (clk), .D (n_6), .Q (id_to_check[0]));
  DFFQX1 \id_to_check_reg[1] (.CK (clk), .D (n_7), .Q (id_to_check[1]));
  DFFQX1 \id_to_check_reg[3] (.CK (clk), .D (n_4), .Q (id_to_check[3]));
  DFFQX1 \id_to_check_reg[2] (.CK (clk), .D (n_5), .Q (id_to_check[2]));
  NOR2XL g25(.A (reset), .B (n_3), .Y (n_7));
  NOR2XL g26(.A (reset), .B (n_2), .Y (n_6));
  NOR2XL g27(.A (reset), .B (n_1), .Y (n_5));
  NOR2XL g28(.A (reset), .B (n_0), .Y (n_4));
  MXI2XL g29(.A (id_to_check[1]), .B (vehicle_id_in[1]), .S0
       (fsm_read_en), .Y (n_3));
  MXI2XL g30(.A (id_to_check[0]), .B (vehicle_id_in[0]), .S0
       (fsm_read_en), .Y (n_2));
  MXI2XL g31(.A (id_to_check[2]), .B (vehicle_id_in[2]), .S0
       (fsm_read_en), .Y (n_1));
  MXI2XL g32(.A (id_to_check[3]), .B (vehicle_id_in[3]), .S0
       (fsm_read_en), .Y (n_0));
  NOR2BXL g2(.AN (fsm_read_en), .B (reset), .Y (n_16));
endmodule

module toll_gate(clk, reset, sensor_vehicle_enter, sensor_vehicle_exit,
     vehicle_id_in, barrier_open_cmd, barrier_close_cmd, led_status,
     display_out);
  input clk, reset, sensor_vehicle_enter, sensor_vehicle_exit;
  input [7:0] vehicle_id_in;
  output barrier_open_cmd, barrier_close_cmd;
  output [1:0] led_status;
  output [7:0] display_out;
  wire clk, reset, sensor_vehicle_enter, sensor_vehicle_exit;
  wire [7:0] vehicle_id_in;
  wire barrier_open_cmd, barrier_close_cmd;
  wire [1:0] led_status;
  wire [7:0] display_out;
  wire [3:0] id_to_check;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire charge_done, gate_is_closed, gate_is_open, id_valid, n_0, n_1,
       n_2, n_3;
  wire n_4, n_5, n_6, n_7, n_8, n_9, n_10, n_11;
  wire n_12, n_13, n_14, n_15, n_16, n_18, n_19, n_20;
  wire n_21, n_22, n_24, n_30, n_31, n_34, n_37, n_38;
  wire sufficient_balance;
  assign display_out[4] = 1'b0;
  assign display_out[7] = 1'b0;
  account_balance u_account_balance(.clk (clk), .reset (reset),
       .id_to_check ({UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED, id_to_check[3:1], n_24}), .fsm_check_req (n_30),
       .fsm_charge_req (n_37), .sufficient_balance
       (sufficient_balance), .charge_done (charge_done));
  barrier_ctrl u_barrier_ctrl(.clk (clk), .reset (reset), .fsm_open_en
       (n_34), .fsm_close_en (n_31), .barrier_open_cmd
       (barrier_open_cmd), .barrier_close_cmd (barrier_close_cmd),
       .gate_is_open (gate_is_open), .gate_is_closed (gate_is_closed));
  vehicle_interface u_vehicle_interface(.clk (clk), .reset (reset),
       .fsm_read_en (n_38), .vehicle_id_in ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       vehicle_id_in[3:0]}), .id_to_check (id_to_check), .id_valid
       (id_valid));
  INVXL g481(.A (display_out[5]), .Y (display_out[6]));
  INVXL g483(.A (n_34), .Y (led_status[0]));
  BUFX6 g484(.A (id_to_check[0]), .Y (n_24));
  INVXL g485(.A (sensor_vehicle_enter), .Y (n_22));
  OR2X1 g651(.A (n_34), .B (n_37), .Y (led_status[1]));
  NAND2BXL g652(.AN (n_34), .B (display_out[2]), .Y (display_out[1]));
  NOR2XL g653(.A (state[1]), .B (n_19), .Y (n_34));
  NOR2XL g654(.A (n_1), .B (n_19), .Y (display_out[5]));
  OAI211XL g655(.A0 (state[0]), .A1 (state[2]), .B0 (n_1), .C0 (n_19),
       .Y (display_out[0]));
  OAI2BB1XL g656(.A0N (state[2]), .A1N (n_18), .B0 (display_out[2]), .Y
       (display_out[3]));
  OAI2BB1X1 g657(.A0N (n_0), .A1N (n_20), .B0 (n_21), .Y (n_31));
  AND2X1 g658(.A (state[0]), .B (n_20), .Y (n_38));
  OR2X1 g659(.A (state[2]), .B (n_18), .Y (display_out[2]));
  NAND2BX1 g660(.AN (n_18), .B (state[2]), .Y (n_21));
  AND2X1 g661(.A (state[0]), .B (n_30), .Y (n_37));
  NOR2XL g662(.A (state[1]), .B (state[2]), .Y (n_20));
  NAND2XL g663(.A (state[2]), .B (state[0]), .Y (n_19));
  NOR2XL g664(.A (state[2]), .B (n_1), .Y (n_30));
  NAND2XL g665(.A (state[1]), .B (n_0), .Y (n_18));
  INVX1 g666(.A (state[0]), .Y (n_0));
  INVX1 g667(.A (state[1]), .Y (n_1));
  DFFQX1 \state_reg[1] (.CK (clk), .D (n_16), .Q (state[1]));
  DFFQX1 \state_reg[0] (.CK (clk), .D (n_15), .Q (state[0]));
  OAI221XL g765(.A0 (n_8), .A1 (n_6), .B0 (n_12), .B1 (n_0), .C0
       (n_10), .Y (n_16));
  DFFQX1 \state_reg[2] (.CK (clk), .D (n_14), .Q (state[2]));
  OAI221X1 g767(.A0 (n_8), .A1 (n_2), .B0 (sensor_vehicle_exit), .B1
       (n_11), .C0 (n_13), .Y (n_15));
  OAI211X1 g768(.A0 (n_8), .A1 (n_5), .B0 (n_10), .C0 (n_11), .Y
       (n_14));
  NAND2XL g769(.A (n_4), .B (n_9), .Y (n_13));
  AOI32X1 g770(.A0 (n_4), .A1 (id_valid), .A2 (n_1), .B0
       (sensor_vehicle_exit), .B1 (n_7), .Y (n_12));
  NAND2BX1 g771(.AN (n_0), .B (n_7), .Y (n_11));
  OAI32X1 g772(.A0 (n_22), .A1 (state[1]), .A2 (state[0]), .B0
       (id_valid), .B1 (n_0), .Y (n_9));
  OR4XL g773(.A (n_3), .B (state[0]), .C (n_1), .D (gate_is_closed), .Y
       (n_10));
  NAND2XL g774(.A (n_4), .B (state[1]), .Y (n_8));
  INVXL g775(.A (n_5), .Y (n_6));
  NOR2XL g776(.A (n_3), .B (state[1]), .Y (n_7));
  AOI21X1 g777(.A0 (charge_done), .A1 (state[0]), .B0 (n_2), .Y (n_5));
  NOR2XL g778(.A (reset), .B (state[2]), .Y (n_4));
  NAND2BX1 g779(.AN (reset), .B (state[2]), .Y (n_3));
  NOR2XL g780(.A (state[0]), .B (sufficient_balance), .Y (n_2));
endmodule

