
// Generated by Cadence Genus(TM) Synthesis Solution 19.13-s073_1
// Generated on: Oct 11 2025 19:53:45 IST (Oct 11 2025 14:23:45 UTC)

// Verification Directory fv/toll_gate 

module account_balance(clk, reset, id_to_check, fsm_check_req,
     fsm_charge_req, sufficient_balance, charge_done, DFT_sdi, DFT_sen,
     DFT_sdo, DFT_sdi_1);
  input clk, reset, fsm_check_req, fsm_charge_req, DFT_sdi, DFT_sen,
       DFT_sdi_1;
  input [7:0] id_to_check;
  output sufficient_balance, charge_done, DFT_sdo;
  wire clk, reset, fsm_check_req, fsm_charge_req, DFT_sdi, DFT_sen,
       DFT_sdi_1;
  wire [7:0] id_to_check;
  wire sufficient_balance, charge_done, DFT_sdo;
  wire [15:0] \balance_db[0] ;
  wire [15:0] \balance_db[4] ;
  wire [15:0] \balance_db[5] ;
  wire [15:0] \balance_db[6] ;
  wire [15:0] \balance_db[7] ;
  wire [15:0] \balance_db[8] ;
  wire [15:0] \balance_db[9] ;
  wire [15:0] \balance_db[10] ;
  wire [15:0] \balance_db[11] ;
  wire [15:0] \balance_db[12] ;
  wire [15:0] \balance_db[13] ;
  wire [15:0] \balance_db[14] ;
  wire [15:0] \balance_db[15] ;
  wire [15:0] \balance_db[3] ;
  wire [15:0] \balance_db[1] ;
  wire [15:0] \balance_db[2] ;
  wire n_67, n_114, n_294, n_295, n_318, n_319, n_321, n_322;
  wire n_326, n_327, n_328, n_329, n_330, n_331, n_332, n_333;
  wire n_334, n_335, n_336, n_337, n_338, n_339, n_340, n_341;
  wire n_342, n_343, n_344, n_345, n_346, n_347, n_348, n_349;
  wire n_350, n_351, n_352, n_353, n_354, n_355, n_356, n_357;
  wire n_358, n_359, n_360, n_361, n_362, n_363, n_364, n_365;
  wire n_366, n_367, n_368, n_369, n_370, n_371, n_372, n_373;
  wire n_374, n_375, n_376, n_377, n_378, n_379, n_380, n_381;
  wire n_382, n_383, n_384, n_385, n_386, n_387, n_388, n_389;
  wire n_390, n_391, n_392, n_393, n_394, n_395, n_396, n_397;
  wire n_398, n_399, n_400, n_401, n_402, n_403, n_404, n_405;
  wire n_406, n_407, n_408, n_409, n_410, n_411, n_412, n_413;
  wire n_414, n_415, n_416, n_417, n_418, n_419, n_420, n_421;
  wire n_422, n_423, n_424, n_425, n_426, n_427, n_428, n_429;
  wire n_430, n_431, n_432, n_433, n_434, n_435, n_436, n_437;
  wire n_438, n_439, n_440, n_441, n_442, n_443, n_444, n_445;
  wire n_446, n_447, n_448, n_449, n_450, n_451, n_452, n_453;
  wire n_454, n_455, n_456, n_457, n_458, n_459, n_460, n_461;
  wire n_462, n_463, n_464, n_465, n_466, n_467, n_468, n_469;
  wire n_470, n_471, n_472, n_473, n_474, n_475, n_476, n_477;
  wire n_478, n_479, n_480, n_481, n_482, n_483, n_484, n_485;
  wire n_486, n_487, n_488, n_489, n_490, n_491, n_492, n_493;
  wire n_494, n_495, n_496, n_497, n_498, n_499, n_500, n_501;
  wire n_502, n_503, n_504, n_505, n_506, n_507, n_508, n_509;
  wire n_510, n_511, n_512, n_513, n_514, n_515, n_516, n_517;
  wire n_518, n_519, n_520, n_521, n_522, n_523, n_524, n_525;
  wire n_526, n_527, n_528, n_529, n_530, n_531, n_532, n_533;
  wire n_534, n_535, n_536, n_537, n_538, n_539, n_540, n_541;
  wire n_542, n_543, n_544, n_545, n_546, n_547, n_548, n_549;
  wire n_550, n_551, n_552, n_553, n_554, n_555, n_556, n_557;
  wire n_558, n_559, n_560, n_561, n_562, n_563, n_564, n_565;
  wire n_566, n_567, n_568, n_569, n_570, n_571, n_572, n_573;
  wire n_574, n_575, n_576, n_577, n_578, n_579, n_580, n_581;
  wire n_582, n_583, n_584, n_585, n_586, n_587, n_588, n_589;
  wire n_590, n_591, n_592, n_593, n_594, n_595, n_596, n_597;
  wire n_598, n_599, n_600, n_601, n_602, n_603, n_604, n_605;
  wire n_606, n_607, n_608, n_609, n_610, n_611, n_612, n_613;
  wire n_614, n_615, n_616, n_618, n_619, n_620, n_621, n_626;
  wire n_627, n_631, n_632, n_633, n_634, n_636, n_637, n_638;
  wire n_640, n_641, n_642, n_643, n_644, n_645, n_646, n_647;
  wire n_648, n_649, n_650, n_651, n_652, n_653, n_654, n_655;
  wire n_656, n_1821_BAR, n_1832_BAR, n_1833_BAR;
  SDFFQX1 \balance_db_reg[0][1] (.CK (clk), .D (\balance_db[0] [1]),
       .SI (n_618), .SE (n_646), .Q (\balance_db[0] [1]));
  SDFFQX1 \balance_db_reg[0][2] (.CK (clk), .D (\balance_db[0] [2]),
       .SI (n_1833_BAR), .SE (n_646), .Q (\balance_db[0] [2]));
  SDFFQX1 \balance_db_reg[0][3] (.CK (clk), .D (\balance_db[0] [3]),
       .SI (n_637), .SE (n_646), .Q (\balance_db[0] [3]));
  SDFFQX1 \balance_db_reg[0][4] (.CK (clk), .D (\balance_db[0] [4]),
       .SI (n_1832_BAR), .SE (n_646), .Q (\balance_db[0] [4]));
  SDFFQX1 \balance_db_reg[0][5] (.CK (clk), .D (\balance_db[0] [5]),
       .SI (n_638), .SE (n_646), .Q (\balance_db[0] [5]));
  SDFFQX1 \balance_db_reg[0][6] (.CK (clk), .D (\balance_db[0] [6]),
       .SI (n_1821_BAR), .SE (n_646), .Q (\balance_db[0] [6]));
  SDFFQX1 \balance_db_reg[0][7] (.CK (clk), .D (\balance_db[0] [7]),
       .SI (n_634), .SE (n_646), .Q (\balance_db[0] [7]));
  SDFFQX1 \balance_db_reg[0][8] (.CK (clk), .D (\balance_db[0] [8]),
       .SI (n_654), .SE (n_646), .Q (\balance_db[0] [8]));
  SDFFQX1 \balance_db_reg[0][9] (.CK (clk), .D (\balance_db[0] [9]),
       .SI (n_636), .SE (n_646), .Q (\balance_db[0] [9]));
  SDFFQX1 \balance_db_reg[0][10] (.CK (clk), .D (\balance_db[0] [10]),
       .SI (n_652), .SE (n_646), .Q (\balance_db[0] [10]));
  SDFFQX1 \balance_db_reg[0][11] (.CK (clk), .D (\balance_db[0] [11]),
       .SI (n_633), .SE (n_646), .Q (\balance_db[0] [11]));
  SDFFQX1 \balance_db_reg[0][12] (.CK (clk), .D (\balance_db[0] [12]),
       .SI (n_651), .SE (n_646), .Q (\balance_db[0] [12]));
  SDFFQX1 \balance_db_reg[0][13] (.CK (clk), .D (\balance_db[0] [13]),
       .SI (n_632), .SE (n_646), .Q (\balance_db[0] [13]));
  SDFFQX1 \balance_db_reg[0][14] (.CK (clk), .D (\balance_db[0] [14]),
       .SI (n_645), .SE (n_646), .Q (\balance_db[0] [14]));
  SDFFQX1 \balance_db_reg[0][15] (.CK (clk), .D (\balance_db[0] [15]),
       .SI (n_631), .SE (n_646), .Q (\balance_db[0] [15]));
  SDFFQX1 \balance_db_reg[4][1] (.CK (clk), .D (\balance_db[4] [1]),
       .SI (n_618), .SE (n_653), .Q (\balance_db[4] [1]));
  SDFFQX1 \balance_db_reg[4][2] (.CK (clk), .D (\balance_db[4] [2]),
       .SI (n_1833_BAR), .SE (n_653), .Q (\balance_db[4] [2]));
  SDFFQX1 \balance_db_reg[4][3] (.CK (clk), .D (\balance_db[4] [3]),
       .SI (n_637), .SE (n_653), .Q (\balance_db[4] [3]));
  SDFFQX1 \balance_db_reg[4][4] (.CK (clk), .D (\balance_db[4] [4]),
       .SI (n_1832_BAR), .SE (n_653), .Q (\balance_db[4] [4]));
  SDFFQX1 \balance_db_reg[4][5] (.CK (clk), .D (\balance_db[4] [5]),
       .SI (n_638), .SE (n_653), .Q (\balance_db[4] [5]));
  SDFFQX1 \balance_db_reg[4][6] (.CK (clk), .D (\balance_db[4] [6]),
       .SI (n_1821_BAR), .SE (n_653), .Q (\balance_db[4] [6]));
  SDFFQX1 \balance_db_reg[4][7] (.CK (clk), .D (\balance_db[4] [7]),
       .SI (n_634), .SE (n_653), .Q (\balance_db[4] [7]));
  SDFFQX1 \balance_db_reg[4][8] (.CK (clk), .D (\balance_db[4] [8]),
       .SI (n_654), .SE (n_653), .Q (\balance_db[4] [8]));
  SDFFQX1 \balance_db_reg[4][9] (.CK (clk), .D (\balance_db[4] [9]),
       .SI (n_636), .SE (n_653), .Q (\balance_db[4] [9]));
  SDFFQX1 \balance_db_reg[4][10] (.CK (clk), .D (\balance_db[4] [10]),
       .SI (n_652), .SE (n_653), .Q (\balance_db[4] [10]));
  SDFFQX1 \balance_db_reg[4][11] (.CK (clk), .D (\balance_db[4] [11]),
       .SI (n_633), .SE (n_653), .Q (\balance_db[4] [11]));
  SDFFQX1 \balance_db_reg[4][12] (.CK (clk), .D (\balance_db[4] [12]),
       .SI (n_651), .SE (n_653), .Q (\balance_db[4] [12]));
  SDFFQX1 \balance_db_reg[4][13] (.CK (clk), .D (\balance_db[4] [13]),
       .SI (n_632), .SE (n_653), .Q (\balance_db[4] [13]));
  SDFFQX1 \balance_db_reg[4][14] (.CK (clk), .D (\balance_db[4] [14]),
       .SI (n_645), .SE (n_653), .Q (\balance_db[4] [14]));
  SDFFQX1 \balance_db_reg[4][15] (.CK (clk), .D (\balance_db[4] [15]),
       .SI (n_631), .SE (n_653), .Q (\balance_db[4] [15]));
  SDFFQX1 \balance_db_reg[5][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[5] [1]), .SE (n_656), .Q (\balance_db[5] [1]));
  SDFFQX1 \balance_db_reg[5][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[5] [2]), .SE (n_656), .Q (\balance_db[5] [2]));
  SDFFQX1 \balance_db_reg[5][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[5] [3]), .SE (n_656), .Q (\balance_db[5] [3]));
  SDFFQX1 \balance_db_reg[5][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[5] [4]), .SE (n_656), .Q (\balance_db[5] [4]));
  SDFFQX1 \balance_db_reg[5][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[5] [5]), .SE (n_656), .Q (\balance_db[5] [5]));
  SDFFQX1 \balance_db_reg[5][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[5] [6]), .SE (n_656), .Q (\balance_db[5] [6]));
  SDFFQX1 \balance_db_reg[5][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[5] [7]), .SE (n_656), .Q (\balance_db[5] [7]));
  SDFFQX1 \balance_db_reg[5][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[5] [8]), .SE (n_656), .Q (\balance_db[5] [8]));
  SDFFQX1 \balance_db_reg[5][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[5] [9]), .SE (n_656), .Q (\balance_db[5] [9]));
  SDFFQX1 \balance_db_reg[5][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[5] [10]), .SE (n_656), .Q (\balance_db[5] [10]));
  SDFFQX1 \balance_db_reg[5][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[5] [11]), .SE (n_656), .Q (\balance_db[5] [11]));
  SDFFQX1 \balance_db_reg[5][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[5] [12]), .SE (n_656), .Q (\balance_db[5] [12]));
  SDFFQX1 \balance_db_reg[5][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[5] [13]), .SE (n_656), .Q (\balance_db[5] [13]));
  SDFFQX1 \balance_db_reg[5][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[5] [14]), .SE (n_656), .Q (\balance_db[5] [14]));
  SDFFQX1 \balance_db_reg[5][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[5] [15]), .SE (n_656), .Q (\balance_db[5] [15]));
  SDFFQX1 \balance_db_reg[6][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[6] [1]), .SE (n_648), .Q (\balance_db[6] [1]));
  SDFFQX1 \balance_db_reg[6][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[6] [2]), .SE (n_648), .Q (\balance_db[6] [2]));
  SDFFQX1 \balance_db_reg[6][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[6] [3]), .SE (n_648), .Q (\balance_db[6] [3]));
  SDFFQX1 \balance_db_reg[6][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[6] [4]), .SE (n_648), .Q (\balance_db[6] [4]));
  SDFFQX1 \balance_db_reg[6][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[6] [5]), .SE (n_648), .Q (\balance_db[6] [5]));
  SDFFQX1 \balance_db_reg[6][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[6] [6]), .SE (n_648), .Q (\balance_db[6] [6]));
  SDFFQX1 \balance_db_reg[6][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[6] [7]), .SE (n_648), .Q (\balance_db[6] [7]));
  SDFFQX1 \balance_db_reg[6][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[6] [8]), .SE (n_648), .Q (\balance_db[6] [8]));
  SDFFQX1 \balance_db_reg[6][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[6] [9]), .SE (n_648), .Q (\balance_db[6] [9]));
  SDFFQX1 \balance_db_reg[6][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[6] [10]), .SE (n_648), .Q (\balance_db[6] [10]));
  SDFFQX1 \balance_db_reg[6][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[6] [11]), .SE (n_648), .Q (\balance_db[6] [11]));
  SDFFQX1 \balance_db_reg[6][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[6] [12]), .SE (n_648), .Q (\balance_db[6] [12]));
  SDFFQX1 \balance_db_reg[6][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[6] [13]), .SE (n_648), .Q (\balance_db[6] [13]));
  SDFFQX1 \balance_db_reg[6][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[6] [14]), .SE (n_648), .Q (\balance_db[6] [14]));
  SDFFQX1 \balance_db_reg[6][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[6] [15]), .SE (n_648), .Q (\balance_db[6] [15]));
  SDFFQX1 \balance_db_reg[7][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[7] [1]), .SE (n_649), .Q (\balance_db[7] [1]));
  SDFFQX1 \balance_db_reg[7][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[7] [2]), .SE (n_649), .Q (\balance_db[7] [2]));
  SDFFQX1 \balance_db_reg[7][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[7] [3]), .SE (n_649), .Q (\balance_db[7] [3]));
  SDFFQX1 \balance_db_reg[7][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[7] [4]), .SE (n_649), .Q (\balance_db[7] [4]));
  SDFFQX1 \balance_db_reg[7][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[7] [5]), .SE (n_649), .Q (\balance_db[7] [5]));
  SDFFQX1 \balance_db_reg[7][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[7] [6]), .SE (n_649), .Q (\balance_db[7] [6]));
  SDFFQX1 \balance_db_reg[7][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[7] [7]), .SE (n_649), .Q (\balance_db[7] [7]));
  SDFFQX1 \balance_db_reg[7][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[7] [8]), .SE (n_649), .Q (\balance_db[7] [8]));
  SDFFQX1 \balance_db_reg[7][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[7] [9]), .SE (n_649), .Q (\balance_db[7] [9]));
  SDFFQX1 \balance_db_reg[7][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[7] [10]), .SE (n_649), .Q (\balance_db[7] [10]));
  SDFFQX1 \balance_db_reg[7][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[7] [11]), .SE (n_649), .Q (\balance_db[7] [11]));
  SDFFQX1 \balance_db_reg[7][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[7] [12]), .SE (n_649), .Q (\balance_db[7] [12]));
  SDFFQX1 \balance_db_reg[7][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[7] [13]), .SE (n_649), .Q (\balance_db[7] [13]));
  SDFFQX1 \balance_db_reg[7][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[7] [14]), .SE (n_649), .Q (\balance_db[7] [14]));
  SDFFQX1 \balance_db_reg[7][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[7] [15]), .SE (n_649), .Q (\balance_db[7] [15]));
  SDFFQX1 \balance_db_reg[8][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[8] [1]), .SE (n_643), .Q (\balance_db[8] [1]));
  SDFFQX1 \balance_db_reg[8][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[8] [2]), .SE (n_643), .Q (\balance_db[8] [2]));
  SDFFQX1 \balance_db_reg[8][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[8] [3]), .SE (n_643), .Q (\balance_db[8] [3]));
  SDFFQX1 \balance_db_reg[8][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[8] [4]), .SE (n_643), .Q (\balance_db[8] [4]));
  SDFFQX1 \balance_db_reg[8][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[8] [5]), .SE (n_643), .Q (\balance_db[8] [5]));
  SDFFQX1 \balance_db_reg[8][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[8] [6]), .SE (n_643), .Q (\balance_db[8] [6]));
  SDFFQX1 \balance_db_reg[8][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[8] [7]), .SE (n_643), .Q (\balance_db[8] [7]));
  SDFFQX1 \balance_db_reg[8][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[8] [8]), .SE (n_643), .Q (\balance_db[8] [8]));
  SDFFQX1 \balance_db_reg[8][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[8] [9]), .SE (n_643), .Q (\balance_db[8] [9]));
  SDFFQX1 \balance_db_reg[8][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[8] [10]), .SE (n_643), .Q (\balance_db[8] [10]));
  SDFFQX1 \balance_db_reg[8][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[8] [11]), .SE (n_643), .Q (\balance_db[8] [11]));
  SDFFQX1 \balance_db_reg[8][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[8] [12]), .SE (n_643), .Q (\balance_db[8] [12]));
  SDFFQX1 \balance_db_reg[8][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[8] [13]), .SE (n_643), .Q (\balance_db[8] [13]));
  SDFFQX1 \balance_db_reg[8][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[8] [14]), .SE (n_643), .Q (\balance_db[8] [14]));
  SDFFQX1 \balance_db_reg[8][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[8] [15]), .SE (n_643), .Q (\balance_db[8] [15]));
  SDFFQX1 \balance_db_reg[9][1] (.CK (clk), .D (\balance_db[9] [1]),
       .SI (n_618), .SE (n_655), .Q (\balance_db[9] [1]));
  SDFFQX1 \balance_db_reg[9][2] (.CK (clk), .D (\balance_db[9] [2]),
       .SI (n_1833_BAR), .SE (n_655), .Q (\balance_db[9] [2]));
  SDFFQX1 \balance_db_reg[9][3] (.CK (clk), .D (\balance_db[9] [3]),
       .SI (n_637), .SE (n_655), .Q (\balance_db[9] [3]));
  SDFFQX1 \balance_db_reg[9][4] (.CK (clk), .D (\balance_db[9] [4]),
       .SI (n_1832_BAR), .SE (n_655), .Q (\balance_db[9] [4]));
  SDFFQX1 \balance_db_reg[9][5] (.CK (clk), .D (\balance_db[9] [5]),
       .SI (n_638), .SE (n_655), .Q (\balance_db[9] [5]));
  SDFFQX1 \balance_db_reg[9][6] (.CK (clk), .D (\balance_db[9] [6]),
       .SI (n_1821_BAR), .SE (n_655), .Q (\balance_db[9] [6]));
  SDFFQX1 \balance_db_reg[9][7] (.CK (clk), .D (\balance_db[9] [7]),
       .SI (n_634), .SE (n_655), .Q (\balance_db[9] [7]));
  SDFFQX1 \balance_db_reg[9][8] (.CK (clk), .D (\balance_db[9] [8]),
       .SI (n_654), .SE (n_655), .Q (\balance_db[9] [8]));
  SDFFQX1 \balance_db_reg[9][9] (.CK (clk), .D (\balance_db[9] [9]),
       .SI (n_636), .SE (n_655), .Q (\balance_db[9] [9]));
  SDFFQX1 \balance_db_reg[9][10] (.CK (clk), .D (\balance_db[9] [10]),
       .SI (n_652), .SE (n_655), .Q (\balance_db[9] [10]));
  SDFFQX1 \balance_db_reg[9][11] (.CK (clk), .D (\balance_db[9] [11]),
       .SI (n_633), .SE (n_655), .Q (\balance_db[9] [11]));
  SDFFQX1 \balance_db_reg[9][12] (.CK (clk), .D (\balance_db[9] [12]),
       .SI (n_651), .SE (n_655), .Q (\balance_db[9] [12]));
  SDFFQX1 \balance_db_reg[9][13] (.CK (clk), .D (\balance_db[9] [13]),
       .SI (n_632), .SE (n_655), .Q (\balance_db[9] [13]));
  SDFFQX1 \balance_db_reg[9][14] (.CK (clk), .D (\balance_db[9] [14]),
       .SI (n_645), .SE (n_655), .Q (\balance_db[9] [14]));
  SDFFQX1 \balance_db_reg[9][15] (.CK (clk), .D (\balance_db[9] [15]),
       .SI (n_631), .SE (n_655), .Q (\balance_db[9] [15]));
  SDFFQX1 \balance_db_reg[10][1] (.CK (clk), .D (\balance_db[10] [1]),
       .SI (n_618), .SE (n_641), .Q (\balance_db[10] [1]));
  SDFFQX1 \balance_db_reg[10][2] (.CK (clk), .D (\balance_db[10] [2]),
       .SI (n_1833_BAR), .SE (n_641), .Q (\balance_db[10] [2]));
  SDFFQX1 \balance_db_reg[10][3] (.CK (clk), .D (\balance_db[10] [3]),
       .SI (n_637), .SE (n_641), .Q (\balance_db[10] [3]));
  SDFFQX1 \balance_db_reg[10][4] (.CK (clk), .D (\balance_db[10] [4]),
       .SI (n_1832_BAR), .SE (n_641), .Q (\balance_db[10] [4]));
  SDFFQX1 \balance_db_reg[10][5] (.CK (clk), .D (\balance_db[10] [5]),
       .SI (n_638), .SE (n_641), .Q (\balance_db[10] [5]));
  SDFFQX1 \balance_db_reg[10][6] (.CK (clk), .D (\balance_db[10] [6]),
       .SI (n_1821_BAR), .SE (n_641), .Q (\balance_db[10] [6]));
  SDFFQX1 \balance_db_reg[10][7] (.CK (clk), .D (\balance_db[10] [7]),
       .SI (n_634), .SE (n_641), .Q (\balance_db[10] [7]));
  SDFFQX1 \balance_db_reg[10][8] (.CK (clk), .D (\balance_db[10] [8]),
       .SI (n_654), .SE (n_641), .Q (\balance_db[10] [8]));
  SDFFQX1 \balance_db_reg[10][9] (.CK (clk), .D (\balance_db[10] [9]),
       .SI (n_636), .SE (n_641), .Q (\balance_db[10] [9]));
  SDFFQX1 \balance_db_reg[10][10] (.CK (clk), .D (\balance_db[10]
       [10]), .SI (n_652), .SE (n_641), .Q (\balance_db[10] [10]));
  SDFFQX1 \balance_db_reg[10][11] (.CK (clk), .D (\balance_db[10]
       [11]), .SI (n_633), .SE (n_641), .Q (\balance_db[10] [11]));
  SDFFQX1 \balance_db_reg[10][12] (.CK (clk), .D (\balance_db[10]
       [12]), .SI (n_651), .SE (n_641), .Q (\balance_db[10] [12]));
  SDFFQX1 \balance_db_reg[10][13] (.CK (clk), .D (\balance_db[10]
       [13]), .SI (n_632), .SE (n_641), .Q (\balance_db[10] [13]));
  SDFFQX1 \balance_db_reg[10][14] (.CK (clk), .D (\balance_db[10]
       [14]), .SI (n_645), .SE (n_641), .Q (\balance_db[10] [14]));
  SDFFQX1 \balance_db_reg[10][15] (.CK (clk), .D (\balance_db[10]
       [15]), .SI (n_631), .SE (n_641), .Q (\balance_db[10] [15]));
  SDFFQX1 \balance_db_reg[11][1] (.CK (clk), .D (\balance_db[11] [1]),
       .SI (n_618), .SE (n_640), .Q (\balance_db[11] [1]));
  SDFFQX1 \balance_db_reg[11][2] (.CK (clk), .D (\balance_db[11] [2]),
       .SI (n_1833_BAR), .SE (n_640), .Q (\balance_db[11] [2]));
  SDFFQX1 \balance_db_reg[11][3] (.CK (clk), .D (\balance_db[11] [3]),
       .SI (n_637), .SE (n_640), .Q (\balance_db[11] [3]));
  SDFFQX1 \balance_db_reg[11][4] (.CK (clk), .D (\balance_db[11] [4]),
       .SI (n_1832_BAR), .SE (n_640), .Q (\balance_db[11] [4]));
  SDFFQX1 \balance_db_reg[11][5] (.CK (clk), .D (\balance_db[11] [5]),
       .SI (n_638), .SE (n_640), .Q (\balance_db[11] [5]));
  SDFFQX1 \balance_db_reg[11][6] (.CK (clk), .D (\balance_db[11] [6]),
       .SI (n_1821_BAR), .SE (n_640), .Q (\balance_db[11] [6]));
  SDFFQX1 \balance_db_reg[11][7] (.CK (clk), .D (\balance_db[11] [7]),
       .SI (n_634), .SE (n_640), .Q (\balance_db[11] [7]));
  SDFFQX1 \balance_db_reg[11][8] (.CK (clk), .D (\balance_db[11] [8]),
       .SI (n_654), .SE (n_640), .Q (\balance_db[11] [8]));
  SDFFQX1 \balance_db_reg[11][9] (.CK (clk), .D (\balance_db[11] [9]),
       .SI (n_636), .SE (n_640), .Q (\balance_db[11] [9]));
  SDFFQX1 \balance_db_reg[11][10] (.CK (clk), .D (\balance_db[11]
       [10]), .SI (n_652), .SE (n_640), .Q (\balance_db[11] [10]));
  SDFFQX1 \balance_db_reg[11][11] (.CK (clk), .D (\balance_db[11]
       [11]), .SI (n_633), .SE (n_640), .Q (\balance_db[11] [11]));
  SDFFQX1 \balance_db_reg[11][12] (.CK (clk), .D (\balance_db[11]
       [12]), .SI (n_651), .SE (n_640), .Q (\balance_db[11] [12]));
  SDFFQX1 \balance_db_reg[11][13] (.CK (clk), .D (\balance_db[11]
       [13]), .SI (n_632), .SE (n_640), .Q (\balance_db[11] [13]));
  SDFFQX1 \balance_db_reg[11][14] (.CK (clk), .D (\balance_db[11]
       [14]), .SI (n_645), .SE (n_640), .Q (\balance_db[11] [14]));
  SDFFQX1 \balance_db_reg[11][15] (.CK (clk), .D (\balance_db[11]
       [15]), .SI (n_631), .SE (n_640), .Q (\balance_db[11] [15]));
  SDFFQX1 \balance_db_reg[12][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[12] [1]), .SE (n_644), .Q (\balance_db[12] [1]));
  SDFFQX1 \balance_db_reg[12][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[12] [2]), .SE (n_644), .Q (\balance_db[12] [2]));
  SDFFQX1 \balance_db_reg[12][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[12] [3]), .SE (n_644), .Q (\balance_db[12] [3]));
  SDFFQX1 \balance_db_reg[12][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[12] [4]), .SE (n_644), .Q (\balance_db[12] [4]));
  SDFFQX1 \balance_db_reg[12][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[12] [5]), .SE (n_644), .Q (\balance_db[12] [5]));
  SDFFQX1 \balance_db_reg[12][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[12] [6]), .SE (n_644), .Q (\balance_db[12] [6]));
  SDFFQX1 \balance_db_reg[12][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[12] [7]), .SE (n_644), .Q (\balance_db[12] [7]));
  SDFFQX1 \balance_db_reg[12][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[12] [8]), .SE (n_644), .Q (\balance_db[12] [8]));
  SDFFQX1 \balance_db_reg[12][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[12] [9]), .SE (n_644), .Q (\balance_db[12] [9]));
  SDFFQX1 \balance_db_reg[12][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[12] [10]), .SE (n_644), .Q (\balance_db[12] [10]));
  SDFFQX1 \balance_db_reg[12][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[12] [11]), .SE (n_644), .Q (\balance_db[12] [11]));
  SDFFQX1 \balance_db_reg[12][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[12] [12]), .SE (n_644), .Q (\balance_db[12] [12]));
  SDFFQX1 \balance_db_reg[12][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[12] [13]), .SE (n_644), .Q (\balance_db[12] [13]));
  SDFFQX1 \balance_db_reg[12][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[12] [14]), .SE (n_644), .Q (\balance_db[12] [14]));
  SDFFQX1 \balance_db_reg[12][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[12] [15]), .SE (n_644), .Q (\balance_db[12] [15]));
  SDFFQX1 \balance_db_reg[13][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[13] [1]), .SE (n_650), .Q (\balance_db[13] [1]));
  SDFFQX1 \balance_db_reg[13][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[13] [2]), .SE (n_650), .Q (\balance_db[13] [2]));
  SDFFQX1 \balance_db_reg[13][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[13] [3]), .SE (n_650), .Q (\balance_db[13] [3]));
  SDFFQX1 \balance_db_reg[13][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[13] [4]), .SE (n_650), .Q (\balance_db[13] [4]));
  SDFFQX1 \balance_db_reg[13][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[13] [5]), .SE (n_650), .Q (\balance_db[13] [5]));
  SDFFQX1 \balance_db_reg[13][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[13] [6]), .SE (n_650), .Q (\balance_db[13] [6]));
  SDFFQX1 \balance_db_reg[13][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[13] [7]), .SE (n_650), .Q (\balance_db[13] [7]));
  SDFFQX1 \balance_db_reg[13][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[13] [8]), .SE (n_650), .Q (\balance_db[13] [8]));
  SDFFQX1 \balance_db_reg[13][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[13] [9]), .SE (n_650), .Q (\balance_db[13] [9]));
  SDFFQX1 \balance_db_reg[13][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[13] [10]), .SE (n_650), .Q (\balance_db[13] [10]));
  SDFFQX1 \balance_db_reg[13][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[13] [11]), .SE (n_650), .Q (\balance_db[13] [11]));
  SDFFQX1 \balance_db_reg[13][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[13] [12]), .SE (n_650), .Q (\balance_db[13] [12]));
  SDFFQX1 \balance_db_reg[13][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[13] [13]), .SE (n_650), .Q (\balance_db[13] [13]));
  SDFFQX1 \balance_db_reg[13][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[13] [14]), .SE (n_650), .Q (\balance_db[13] [14]));
  SDFFQX1 \balance_db_reg[13][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[13] [15]), .SE (n_650), .Q (\balance_db[13] [15]));
  SDFFQX1 \balance_db_reg[14][1] (.CK (clk), .D (\balance_db[14] [1]),
       .SI (n_618), .SE (n_642), .Q (\balance_db[14] [1]));
  SDFFQX1 \balance_db_reg[14][2] (.CK (clk), .D (\balance_db[14] [2]),
       .SI (n_1833_BAR), .SE (n_642), .Q (\balance_db[14] [2]));
  SDFFQX1 \balance_db_reg[14][3] (.CK (clk), .D (\balance_db[14] [3]),
       .SI (n_637), .SE (n_642), .Q (\balance_db[14] [3]));
  SDFFQX1 \balance_db_reg[14][4] (.CK (clk), .D (\balance_db[14] [4]),
       .SI (n_1832_BAR), .SE (n_642), .Q (\balance_db[14] [4]));
  SDFFQX1 \balance_db_reg[14][5] (.CK (clk), .D (\balance_db[14] [5]),
       .SI (n_638), .SE (n_642), .Q (\balance_db[14] [5]));
  SDFFQX1 \balance_db_reg[14][6] (.CK (clk), .D (\balance_db[14] [6]),
       .SI (n_1821_BAR), .SE (n_642), .Q (\balance_db[14] [6]));
  SDFFQX1 \balance_db_reg[14][7] (.CK (clk), .D (\balance_db[14] [7]),
       .SI (n_634), .SE (n_642), .Q (\balance_db[14] [7]));
  SDFFQX1 \balance_db_reg[14][8] (.CK (clk), .D (\balance_db[14] [8]),
       .SI (n_654), .SE (n_642), .Q (\balance_db[14] [8]));
  SDFFQX1 \balance_db_reg[14][9] (.CK (clk), .D (\balance_db[14] [9]),
       .SI (n_636), .SE (n_642), .Q (\balance_db[14] [9]));
  SDFFQX1 \balance_db_reg[14][10] (.CK (clk), .D (\balance_db[14]
       [10]), .SI (n_652), .SE (n_642), .Q (\balance_db[14] [10]));
  SDFFQX1 \balance_db_reg[14][11] (.CK (clk), .D (\balance_db[14]
       [11]), .SI (n_633), .SE (n_642), .Q (\balance_db[14] [11]));
  SDFFQX1 \balance_db_reg[14][12] (.CK (clk), .D (\balance_db[14]
       [12]), .SI (n_651), .SE (n_642), .Q (\balance_db[14] [12]));
  SDFFQX1 \balance_db_reg[14][13] (.CK (clk), .D (\balance_db[14]
       [13]), .SI (n_632), .SE (n_642), .Q (\balance_db[14] [13]));
  SDFFQX1 \balance_db_reg[14][14] (.CK (clk), .D (\balance_db[14]
       [14]), .SI (n_645), .SE (n_642), .Q (\balance_db[14] [14]));
  SDFFQX1 \balance_db_reg[14][15] (.CK (clk), .D (\balance_db[14]
       [15]), .SI (n_631), .SE (n_642), .Q (\balance_db[14] [15]));
  SDFFQX1 \balance_db_reg[15][1] (.CK (clk), .D (n_618), .SI
       (\balance_db[15] [1]), .SE (n_647), .Q (\balance_db[15] [1]));
  SDFFQX1 \balance_db_reg[15][2] (.CK (clk), .D (n_1833_BAR), .SI
       (\balance_db[15] [2]), .SE (n_647), .Q (\balance_db[15] [2]));
  SDFFQX1 \balance_db_reg[15][3] (.CK (clk), .D (n_637), .SI
       (\balance_db[15] [3]), .SE (n_647), .Q (\balance_db[15] [3]));
  SDFFQX1 \balance_db_reg[15][4] (.CK (clk), .D (n_1832_BAR), .SI
       (\balance_db[15] [4]), .SE (n_647), .Q (\balance_db[15] [4]));
  SDFFQX1 \balance_db_reg[15][5] (.CK (clk), .D (n_638), .SI
       (\balance_db[15] [5]), .SE (n_647), .Q (\balance_db[15] [5]));
  SDFFQX1 \balance_db_reg[15][6] (.CK (clk), .D (n_1821_BAR), .SI
       (\balance_db[15] [6]), .SE (n_647), .Q (\balance_db[15] [6]));
  SDFFQX1 \balance_db_reg[15][7] (.CK (clk), .D (n_634), .SI
       (\balance_db[15] [7]), .SE (n_647), .Q (\balance_db[15] [7]));
  SDFFQX1 \balance_db_reg[15][8] (.CK (clk), .D (n_654), .SI
       (\balance_db[15] [8]), .SE (n_647), .Q (\balance_db[15] [8]));
  SDFFQX1 \balance_db_reg[15][9] (.CK (clk), .D (n_636), .SI
       (\balance_db[15] [9]), .SE (n_647), .Q (\balance_db[15] [9]));
  SDFFQX1 \balance_db_reg[15][10] (.CK (clk), .D (n_652), .SI
       (\balance_db[15] [10]), .SE (n_647), .Q (\balance_db[15] [10]));
  SDFFQX1 \balance_db_reg[15][11] (.CK (clk), .D (n_633), .SI
       (\balance_db[15] [11]), .SE (n_647), .Q (\balance_db[15] [11]));
  SDFFQX1 \balance_db_reg[15][12] (.CK (clk), .D (n_651), .SI
       (\balance_db[15] [12]), .SE (n_647), .Q (\balance_db[15] [12]));
  SDFFQX1 \balance_db_reg[15][13] (.CK (clk), .D (n_632), .SI
       (\balance_db[15] [13]), .SE (n_647), .Q (\balance_db[15] [13]));
  SDFFQX1 \balance_db_reg[15][14] (.CK (clk), .D (n_645), .SI
       (\balance_db[15] [14]), .SE (n_647), .Q (\balance_db[15] [14]));
  SDFFQX1 \balance_db_reg[15][15] (.CK (clk), .D (n_631), .SI
       (\balance_db[15] [15]), .SE (n_647), .Q (\balance_db[15] [15]));
  CLKINVX1 g3022(.A (n_627), .Y (sufficient_balance));
  CLKINVX1 g3020(.A (n_1821_BAR), .Y (n_616));
  CLKINVX1 g3018(.A (n_626), .Y (n_618));
  CLKINVX1 g3019(.A (n_1832_BAR), .Y (n_615));
  CLKINVX1 g3021(.A (n_1833_BAR), .Y (n_614));
  SDFFQX1 charge_done_reg(.CK (clk), .D (n_604), .SI
       (\balance_db[3] [14]), .SE (DFT_sen), .Q (charge_done));
  OAI21X1 g11884(.A0 (n_584), .A1 (n_613), .B0 (n_393), .Y (n_633));
  AO21X1 g11885(.A0 (n_575), .A1 (n_606), .B0 (n_613), .Y (n_652));
  NAND2BX1 g11886(.AN (n_611), .B (id_to_check[1]), .Y (n_648));
  NOR2XL g11887(.A (n_575), .B (n_606), .Y (n_613));
  NOR2X1 g11888(.A (id_to_check[1]), .B (n_611), .Y (n_653));
  OR2X1 g11889(.A (id_to_check[1]), .B (n_612), .Y (n_656));
  NAND2BX1 g11890(.AN (n_612), .B (id_to_check[1]), .Y (n_649));
  NOR2X1 g11891(.A (n_412), .B (n_609), .Y (n_640));
  OR2X1 g11892(.A (n_390), .B (n_609), .Y (n_650));
  OR2X1 g11893(.A (n_410), .B (n_609), .Y (n_647));
  NOR2X1 g11894(.A (n_408), .B (n_609), .Y (n_655));
  NAND2XL g11895(.A (n_413), .B (n_610), .Y (n_612));
  NAND2XL g11896(.A (n_619), .B (n_610), .Y (n_611));
  OAI21X1 g11897(.A0 (n_585), .A1 (n_601), .B0 (n_599), .Y (n_631));
  NOR2X1 g11898(.A (n_410), .B (n_607), .Y (n_642));
  NOR2X1 g11899(.A (n_412), .B (n_607), .Y (n_641));
  NAND2X1 g11900(.A (n_404), .B (n_608), .Y (n_644));
  NOR3X2 g11901(.A (id_to_check[3]), .B (n_408), .C (n_605), .Y
       (n_646));
  OAI21X1 g11902(.A0 (n_579), .A1 (n_600), .B0 (n_597), .Y (n_632));
  NAND2X1 g11903(.A (n_407), .B (n_608), .Y (n_643));
  OAI21X1 g11905(.A0 (n_587), .A1 (n_598), .B0 (n_606), .Y (n_636));
  INVX1 g11906(.A (n_608), .Y (n_607));
  NOR3X1 g11907(.A (n_396), .B (id_to_check[3]), .C (n_603), .Y
       (n_610));
  NAND3X1 g11908(.A (id_to_check[3]), .B (n_413), .C (n_602), .Y
       (n_609));
  NOR2XL g11909(.A (n_395), .B (n_605), .Y (n_608));
  NAND2XL g11910(.A (n_587), .B (n_598), .Y (n_606));
  NOR2XL g11911(.A (reset), .B (n_603), .Y (n_604));
  NAND2XL g11912(.A (n_619), .B (n_602), .Y (n_605));
  NAND2XL g11913(.A (fsm_check_req), .B (n_599), .Y (n_627));
  AO21X1 g11914(.A0 (n_574), .A1 (n_393), .B0 (n_600), .Y (n_651));
  INVX1 g11915(.A (n_603), .Y (n_602));
  AO21X1 g11916(.A0 (n_576), .A1 (n_597), .B0 (n_601), .Y (n_645));
  NAND3X1 g11917(.A (fsm_check_req), .B (fsm_charge_req), .C (n_599),
       .Y (n_603));
  NOR2XL g11918(.A (n_576), .B (n_597), .Y (n_601));
  NOR2XL g11919(.A (n_574), .B (n_393), .Y (n_600));
  AO21X1 g11920(.A0 (n_573), .A1 (n_596), .B0 (n_598), .Y (n_654));
  NAND3BX1 g11921(.AN (n_576), .B (n_585), .C (n_392), .Y (n_599));
  NOR2XL g11922(.A (n_573), .B (n_596), .Y (n_598));
  INVX1 g11923(.A (n_392), .Y (n_597));
  OAI21X1 g11927(.A0 (n_577), .A1 (n_595), .B0 (n_596), .Y (n_634));
  NAND2XL g11928(.A (n_577), .B (n_595), .Y (n_596));
  AO21X1 g11929(.A0 (n_588), .A1 (n_594), .B0 (n_595), .Y (n_1821_BAR));
  NOR2XL g11930(.A (n_588), .B (n_594), .Y (n_595));
  OAI21X1 g11931(.A0 (n_578), .A1 (n_593), .B0 (n_594), .Y (n_638));
  NAND2XL g11932(.A (n_578), .B (n_593), .Y (n_594));
  AO21X1 g11933(.A0 (n_592), .A1 (n_590), .B0 (n_593), .Y (n_1832_BAR));
  NOR2XL g11934(.A (n_592), .B (n_590), .Y (n_593));
  CLKXOR2X1 g11935(.A (n_586), .B (n_589), .Y (n_637));
  NOR2XL g11936(.A (n_586), .B (n_589), .Y (n_592));
  NOR4BX1 g11938(.AN (n_587), .B (n_573), .C (n_583), .D (n_575), .Y
       (n_591));
  AO21X1 g11939(.A0 (n_626), .A1 (n_582), .B0 (n_589), .Y (n_1833_BAR));
  NAND2XL g11940(.A (n_504), .B (n_581), .Y (n_590));
  NOR2XL g11941(.A (n_626), .B (n_582), .Y (n_589));
  NAND3X1 g11942(.A (n_463), .B (n_462), .C (n_580), .Y (n_588));
  AOI211X1 g11943(.A0 (\balance_db[14] [9]), .A1 (n_431), .B0 (n_512),
       .C0 (n_568), .Y (n_587));
  AOI211X1 g11944(.A0 (\balance_db[5] [3]), .A1 (n_420), .B0 (n_536),
       .C0 (n_571), .Y (n_586));
  INVXL g11945(.A (n_583), .Y (n_584));
  AOI221X1 g11946(.A0 (\balance_db[6] [4]), .A1 (n_432), .B0
       (\balance_db[15] [4]), .B1 (n_429), .C0 (n_561), .Y (n_581));
  AOI221X1 g11947(.A0 (\balance_db[10] [6]), .A1 (n_422), .B0
       (\balance_db[0] [6]), .B1 (n_434), .C0 (n_557), .Y (n_580));
  AOI221X1 g11948(.A0 (\balance_db[13] [15]), .A1 (n_421), .B0
       (\balance_db[7] [15]), .B1 (n_433), .C0 (n_570), .Y (n_585));
  NAND3X1 g11949(.A (n_508), .B (n_484), .C (n_567), .Y (n_583));
  OAI31X1 g11950(.A0 (n_390), .A1 (n_427), .A2 (n_519), .B0 (n_572), .Y
       (n_582));
  AND4X1 g11951(.A (n_488), .B (n_486), .C (n_485), .D (n_565), .Y
       (n_579));
  AND4X1 g11952(.A (n_516), .B (n_515), .C (n_514), .D (n_560), .Y
       (n_578));
  AND4X1 g11953(.A (n_471), .B (n_470), .C (n_475), .D (n_559), .Y
       (n_577));
  NAND4XL g11954(.A (n_501), .B (n_503), .C (n_455), .D (n_564), .Y
       (n_576));
  NAND4XL g11955(.A (n_469), .B (n_464), .C (n_467), .D (n_566), .Y
       (n_575));
  NAND4XL g11956(.A (n_513), .B (n_457), .C (n_509), .D (n_562), .Y
       (n_574));
  NOR2XL g11957(.A (n_546), .B (n_558), .Y (n_572));
  OAI211X1 g11958(.A0 (n_408), .A1 (n_520), .B0 (n_494), .C0 (n_556),
       .Y (n_571));
  NAND3X1 g11959(.A (n_492), .B (n_495), .C (n_563), .Y (n_573));
  INVX1 g11960(.A (n_569), .Y (n_570));
  AOI221X1 g11961(.A0 (\balance_db[0] [15]), .A1 (n_434), .B0
       (\balance_db[5] [15]), .B1 (n_420), .C0 (n_549), .Y (n_569));
  NAND4XL g11962(.A (n_450), .B (n_502), .C (n_505), .D (n_554), .Y
       (n_568));
  AOI221X1 g11963(.A0 (\balance_db[6] [11]), .A1 (n_432), .B0
       (\balance_db[7] [11]), .B1 (n_433), .C0 (n_555), .Y (n_567));
  OAI221X1 g11964(.A0 (n_390), .A1 (n_538), .B0 (n_410), .B1 (n_525),
       .C0 (n_553), .Y (n_626));
  AOI21X1 g11965(.A0 (\balance_db[8] [10]), .A1 (n_430), .B0 (n_548),
       .Y (n_566));
  AOI21X1 g11966(.A0 (\balance_db[15] [13]), .A1 (n_429), .B0 (n_552),
       .Y (n_565));
  AOI21X1 g11967(.A0 (\balance_db[13] [14]), .A1 (n_421), .B0 (n_551),
       .Y (n_564));
  AOI211X1 g11968(.A0 (\balance_db[3] [8]), .A1 (n_424), .B0 (n_542),
       .C0 (n_541), .Y (n_563));
  AOI221X1 g11969(.A0 (\balance_db[10] [12]), .A1 (n_422), .B0
       (\balance_db[9] [12]), .B1 (n_437), .C0 (n_540), .Y (n_562));
  OAI211X1 g11970(.A0 (n_390), .A1 (n_523), .B0 (n_451), .C0 (n_550),
       .Y (n_561));
  AOI211X1 g11971(.A0 (\balance_db[0] [5]), .A1 (n_434), .B0 (n_537),
       .C0 (n_547), .Y (n_560));
  AOI221X1 g11972(.A0 (\balance_db[1] [7]), .A1 (n_436), .B0
       (\balance_db[8] [7]), .B1 (n_430), .C0 (n_539), .Y (n_559));
  OAI211X1 g11973(.A0 (n_412), .A1 (n_529), .B0 (n_452), .C0 (n_530),
       .Y (n_558));
  NAND4XL g11974(.A (n_460), .B (n_459), .C (n_456), .D (n_543), .Y
       (n_557));
  AOI222XL g11975(.A0 (\balance_db[6] [3]), .A1 (n_432), .B0
       (\balance_db[15] [3]), .B1 (n_429), .C0 (n_531), .C1 (n_411), .Y
       (n_556));
  NAND4XL g11976(.A (n_481), .B (n_480), .C (n_476), .D (n_535), .Y
       (n_555));
  AOI21X1 g11977(.A0 (\balance_db[10] [9]), .A1 (n_422), .B0 (n_544),
       .Y (n_554));
  AOI221X1 g11978(.A0 (\balance_db[0] [1]), .A1 (n_434), .B0
       (\balance_db[8] [1]), .B1 (n_430), .C0 (n_545), .Y (n_553));
  NAND4XL g11979(.A (n_478), .B (n_473), .C (n_482), .D (n_528), .Y
       (n_552));
  NAND4XL g11980(.A (n_472), .B (n_483), .C (n_477), .D (n_527), .Y
       (n_551));
  AOI211X1 g11981(.A0 (\balance_db[3] [4]), .A1 (n_424), .B0 (n_532),
       .C0 (n_534), .Y (n_550));
  NAND4XL g11982(.A (n_491), .B (n_506), .C (n_479), .D (n_526), .Y
       (n_549));
  NAND4XL g11983(.A (n_458), .B (n_489), .C (n_461), .D (n_533), .Y
       (n_548));
  OAI211X1 g11984(.A0 (n_410), .A1 (n_449), .B0 (n_454), .C0 (n_507),
       .Y (n_547));
  AOI211X1 g11985(.A0 (n_394), .A1 (n_399), .B0 (n_410), .C0 (n_518),
       .Y (n_546));
  OAI22X1 g11986(.A0 (n_412), .A1 (n_490), .B0 (n_408), .B1 (n_439), .Y
       (n_545));
  OAI32X1 g11987(.A0 (n_408), .A1 (n_443), .A2 (n_444), .B0 (n_412),
       .B1 (n_522), .Y (n_544));
  AOI222XL g11988(.A0 (\balance_db[1] [6]), .A1 (n_436), .B0 (n_402),
       .B1 (n_446), .C0 (n_430), .C1 (\balance_db[8] [6]), .Y (n_543));
  OAI31X1 g11989(.A0 (n_408), .A1 (n_440), .A2 (n_441), .B0 (n_487), .Y
       (n_542));
  OAI211X1 g11990(.A0 (n_410), .A1 (n_445), .B0 (n_453), .C0 (n_524),
       .Y (n_541));
  NAND4XL g11991(.A (n_493), .B (n_497), .C (n_500), .D (n_496), .Y
       (n_540));
  NAND4XL g11992(.A (n_517), .B (n_465), .C (n_466), .D (n_468), .Y
       (n_539));
  OAI222XL g11993(.A0 (id_to_check[3]), .A1 (n_418), .B0
       (\balance_db[12] [1]), .B1 (n_403), .C0 (n_391), .C1
       (\balance_db[13] [1]), .Y (n_538));
  NAND2XL g11994(.A (n_511), .B (n_510), .Y (n_537));
  NAND2XL g11995(.A (n_498), .B (n_499), .Y (n_536));
  AOI221X1 g11996(.A0 (\balance_db[8] [11]), .A1 (n_430), .B0
       (\balance_db[13] [11]), .B1 (n_421), .C0 (n_474), .Y (n_535));
  AOI21X1 g11997(.A0 (n_447), .A1 (n_438), .B0 (n_408), .Y (n_534));
  AOI222XL g11998(.A0 (\balance_db[4] [10]), .A1 (n_419), .B0
       (\balance_db[5] [10]), .B1 (n_420), .C0 (n_431), .C1
       (\balance_db[14] [10]), .Y (n_533));
  NOR2XL g11999(.A (n_412), .B (n_521), .Y (n_532));
  AOI211XL g12000(.A0 (n_415), .A1 (id_to_check[0]), .B0 (n_426), .C0
       (n_428), .Y (n_531));
  AOI22X1 g12001(.A0 (n_407), .A1 (n_448), .B0 (\balance_db[8] [2]),
       .B1 (n_430), .Y (n_530));
  OAI222XL g12002(.A0 (\balance_db[10] [2]), .A1 (n_403), .B0
       (id_to_check[3]), .B1 (n_416), .C0 (n_391), .C1
       (\balance_db[11] [2]), .Y (n_529));
  AOI222XL g12003(.A0 (\balance_db[1] [13]), .A1 (n_436), .B0
       (\balance_db[8] [13]), .B1 (n_430), .C0 (n_431), .C1
       (\balance_db[14] [13]), .Y (n_528));
  AOI222XL g12004(.A0 (\balance_db[1] [14]), .A1 (n_436), .B0
       (\balance_db[12] [14]), .B1 (n_425), .C0 (n_431), .C1
       (\balance_db[14] [14]), .Y (n_527));
  AOI222XL g12005(.A0 (\balance_db[15] [15]), .A1 (n_429), .B0
       (\balance_db[12] [15]), .B1 (n_425), .C0 (n_423), .C1
       (\balance_db[11] [15]), .Y (n_526));
  OAI222XL g12006(.A0 (id_to_check[3]), .A1 (n_417), .B0
       (\balance_db[14] [1]), .B1 (n_403), .C0 (n_391), .C1
       (\balance_db[15] [1]), .Y (n_525));
  AOI22XL g12007(.A0 (n_419), .A1 (\balance_db[4] [8]), .B0 (n_420),
       .B1 (\balance_db[5] [8]), .Y (n_524));
  AOI22X1 g12008(.A0 (id_to_check[0]), .A1 (n_414), .B0
       (\balance_db[12] [4]), .B1 (n_402), .Y (n_523));
  AOI222XL g12009(.A0 (\balance_db[2] [9]), .A1 (n_399), .B0
       (\balance_db[11] [9]), .B1 (n_397), .C0 (n_400), .C1
       (\balance_db[3] [9]), .Y (n_522));
  AOI222XL g12010(.A0 (\balance_db[2] [4]), .A1 (n_399), .B0
       (\balance_db[11] [4]), .B1 (n_397), .C0 (n_402), .C1
       (\balance_db[10] [4]), .Y (n_521));
  AOI222XL g12011(.A0 (\balance_db[9] [3]), .A1 (n_397), .B0
       (\balance_db[0] [3]), .B1 (n_399), .C0 (n_400), .C1
       (\balance_db[1] [3]), .Y (n_520));
  OAI222XL g12012(.A0 (\balance_db[5] [2]), .A1 (n_401), .B0
       (\balance_db[12] [2]), .B1 (n_403), .C0 (n_391), .C1
       (\balance_db[13] [2]), .Y (n_519));
  OAI222XL g12013(.A0 (\balance_db[7] [2]), .A1 (n_401), .B0
       (\balance_db[14] [2]), .B1 (n_403), .C0 (n_391), .C1
       (\balance_db[15] [2]), .Y (n_518));
  AOI32X1 g12014(.A0 (\balance_db[12] [7]), .A1 (n_406), .A2 (n_404),
       .B0 (\balance_db[15] [7]), .B1 (n_429), .Y (n_517));
  AOI22X1 g12015(.A0 (\balance_db[2] [5]), .A1 (n_435), .B0
       (\balance_db[13] [5]), .B1 (n_421), .Y (n_516));
  AOI22X1 g12016(.A0 (\balance_db[4] [5]), .A1 (n_419), .B0
       (\balance_db[12] [5]), .B1 (n_425), .Y (n_515));
  AOI22X1 g12017(.A0 (\balance_db[10] [5]), .A1 (n_422), .B0
       (\balance_db[5] [5]), .B1 (n_420), .Y (n_514));
  AOI22XL g12018(.A0 (n_432), .A1 (\balance_db[6] [12]), .B0 (n_429),
       .B1 (\balance_db[15] [12]), .Y (n_513));
  AO22X1 g12019(.A0 (\balance_db[6] [9]), .A1 (n_432), .B0
       (\balance_db[12] [9]), .B1 (n_425), .Y (n_512));
  AOI22XL g12020(.A0 (n_431), .A1 (\balance_db[14] [5]), .B0 (n_429),
       .B1 (\balance_db[15] [5]), .Y (n_511));
  AOI22XL g12021(.A0 (n_436), .A1 (\balance_db[1] [5]), .B0 (n_424),
       .B1 (\balance_db[3] [5]), .Y (n_510));
  AOI22XL g12022(.A0 (n_430), .A1 (\balance_db[8] [12]), .B0 (n_433),
       .B1 (\balance_db[7] [12]), .Y (n_509));
  AOI22X1 g12023(.A0 (\balance_db[10] [11]), .A1 (n_422), .B0
       (\balance_db[11] [11]), .B1 (n_423), .Y (n_508));
  AOI22X1 g12024(.A0 (\balance_db[8] [5]), .A1 (n_430), .B0
       (\balance_db[9] [5]), .B1 (n_437), .Y (n_507));
  AOI22XL g12025(.A0 (n_419), .A1 (\balance_db[4] [15]), .B0 (n_431),
       .B1 (\balance_db[14] [15]), .Y (n_506));
  AOI22XL g12026(.A0 (n_420), .A1 (\balance_db[5] [9]), .B0 (n_429),
       .B1 (\balance_db[15] [9]), .Y (n_505));
  AOI22X1 g12027(.A0 (\balance_db[14] [4]), .A1 (n_431), .B0
       (\balance_db[7] [4]), .B1 (n_433), .Y (n_504));
  AOI22XL g12028(.A0 (n_422), .A1 (\balance_db[10] [14]), .B0 (n_424),
       .B1 (\balance_db[3] [14]), .Y (n_503));
  AOI22X1 g12029(.A0 (\balance_db[4] [9]), .A1 (n_419), .B0
       (\balance_db[13] [9]), .B1 (n_421), .Y (n_502));
  AOI22XL g12030(.A0 (n_435), .A1 (DFT_sdo), .B0 (n_423), .B1
       (\balance_db[11] [14]), .Y (n_501));
  AOI22XL g12031(.A0 (n_425), .A1 (\balance_db[12] [12]), .B0 (n_421),
       .B1 (\balance_db[13] [12]), .Y (n_500));
  AOI22X1 g12032(.A0 (\balance_db[4] [3]), .A1 (n_419), .B0
       (\balance_db[13] [3]), .B1 (n_421), .Y (n_499));
  AOI22X1 g12033(.A0 (\balance_db[8] [3]), .A1 (n_430), .B0
       (\balance_db[12] [3]), .B1 (n_425), .Y (n_498));
  AOI22X1 g12034(.A0 (\balance_db[2] [12]), .A1 (n_435), .B0
       (\balance_db[3] [12]), .B1 (n_424), .Y (n_497));
  AOI22XL g12035(.A0 (n_419), .A1 (\balance_db[4] [12]), .B0 (n_420),
       .B1 (\balance_db[5] [12]), .Y (n_496));
  AOI22X1 g12036(.A0 (\balance_db[13] [8]), .A1 (n_421), .B0
       (\balance_db[11] [8]), .B1 (n_423), .Y (n_495));
  AOI22X1 g12037(.A0 (\balance_db[14] [3]), .A1 (n_431), .B0
       (\balance_db[7] [3]), .B1 (n_433), .Y (n_494));
  AOI22XL g12038(.A0 (n_434), .A1 (\balance_db[0] [12]), .B0 (n_436),
       .B1 (\balance_db[1] [12]), .Y (n_493));
  AOI22X1 g12039(.A0 (\balance_db[2] [8]), .A1 (n_435), .B0
       (\balance_db[10] [8]), .B1 (n_422), .Y (n_492));
  AOI22XL g12040(.A0 (n_430), .A1 (\balance_db[8] [15]), .B0 (n_437),
       .B1 (\balance_db[9] [15]), .Y (n_491));
  AOI221X1 g12041(.A0 (\balance_db[2] [1]), .A1 (n_399), .B0
       (\balance_db[3] [1]), .B1 (n_400), .C0 (n_442), .Y (n_490));
  AOI22XL g12042(.A0 (n_422), .A1 (\balance_db[10] [10]), .B0 (n_429),
       .B1 (\balance_db[15] [10]), .Y (n_489));
  AOI22XL g12043(.A0 (n_421), .A1 (\balance_db[13] [13]), .B0 (n_433),
       .B1 (\balance_db[7] [13]), .Y (n_488));
  AOI22X1 g12044(.A0 (\balance_db[14] [8]), .A1 (n_431), .B0
       (\balance_db[15] [8]), .B1 (n_429), .Y (n_487));
  AOI22XL g12045(.A0 (n_419), .A1 (\balance_db[4] [13]), .B0 (n_432),
       .B1 (\balance_db[6] [13]), .Y (n_486));
  AOI22XL g12046(.A0 (n_425), .A1 (\balance_db[12] [13]), .B0 (n_420),
       .B1 (\balance_db[5] [13]), .Y (n_485));
  AOI22X1 g12047(.A0 (\balance_db[2] [11]), .A1 (n_435), .B0
       (\balance_db[9] [11]), .B1 (n_437), .Y (n_484));
  AOI22XL g12048(.A0 (n_430), .A1 (\balance_db[8] [14]), .B0 (n_432),
       .B1 (\balance_db[6] [14]), .Y (n_483));
  AOI22X1 g12049(.A0 (\balance_db[10] [13]), .A1 (n_422), .B0
       (\balance_db[11] [13]), .B1 (n_423), .Y (n_482));
  AOI22XL g12050(.A0 (n_436), .A1 (\balance_db[1] [11]), .B0 (n_425),
       .B1 (\balance_db[12] [11]), .Y (n_481));
  AOI22XL g12051(.A0 (n_434), .A1 (\balance_db[0] [11]), .B0 (n_424),
       .B1 (\balance_db[3] [11]), .Y (n_480));
  AOI22XL g12052(.A0 (n_432), .A1 (\balance_db[6] [15]), .B0 (n_422),
       .B1 (\balance_db[10] [15]), .Y (n_479));
  AOI22XL g12053(.A0 (n_434), .A1 (\balance_db[0] [13]), .B0 (n_437),
       .B1 (\balance_db[9] [13]), .Y (n_478));
  AOI22XL g12054(.A0 (n_434), .A1 (\balance_db[0] [14]), .B0 (n_433),
       .B1 (\balance_db[7] [14]), .Y (n_477));
  AOI22X1 g12055(.A0 (\balance_db[4] [11]), .A1 (n_419), .B0
       (\balance_db[5] [11]), .B1 (n_420), .Y (n_476));
  AOI22X1 g12056(.A0 (\balance_db[10] [7]), .A1 (n_422), .B0
       (\balance_db[7] [7]), .B1 (n_433), .Y (n_475));
  AO22XL g12057(.A0 (\balance_db[14] [11]), .A1 (n_431), .B0
       (\balance_db[15] [11]), .B1 (n_429), .Y (n_474));
  AOI22X1 g12058(.A0 (\balance_db[2] [13]), .A1 (n_435), .B0
       (\balance_db[3] [13]), .B1 (n_424), .Y (n_473));
  AOI22XL g12059(.A0 (n_437), .A1 (\balance_db[9] [14]), .B0 (n_429),
       .B1 (\balance_db[15] [14]), .Y (n_472));
  AOI22XL g12060(.A0 (n_432), .A1 (\balance_db[6] [7]), .B0 (n_423),
       .B1 (\balance_db[11] [7]), .Y (n_471));
  AOI22X1 g12061(.A0 (\balance_db[2] [7]), .A1 (n_435), .B0
       (\balance_db[3] [7]), .B1 (n_424), .Y (n_470));
  AOI22XL g12062(.A0 (n_436), .A1 (\balance_db[1] [10]), .B0 (n_425),
       .B1 (\balance_db[12] [10]), .Y (n_469));
  AOI22XL g12063(.A0 (n_420), .A1 (\balance_db[5] [7]), .B0 (n_431),
       .B1 (\balance_db[14] [7]), .Y (n_468));
  AOI22XL g12064(.A0 (n_434), .A1 (\balance_db[0] [10]), .B0 (n_421),
       .B1 (\balance_db[13] [10]), .Y (n_467));
  AOI22X1 g12065(.A0 (\balance_db[4] [7]), .A1 (n_419), .B0
       (\balance_db[9] [7]), .B1 (n_437), .Y (n_466));
  AOI22XL g12066(.A0 (n_434), .A1 (\balance_db[0] [7]), .B0 (n_421),
       .B1 (\balance_db[13] [7]), .Y (n_465));
  AOI22X1 g12067(.A0 (\balance_db[2] [10]), .A1 (n_435), .B0
       (\balance_db[9] [10]), .B1 (n_437), .Y (n_464));
  AOI22X1 g12068(.A0 (\balance_db[3] [6]), .A1 (n_424), .B0
       (\balance_db[11] [6]), .B1 (n_423), .Y (n_463));
  AOI22X1 g12069(.A0 (\balance_db[2] [6]), .A1 (n_435), .B0
       (\balance_db[6] [6]), .B1 (n_432), .Y (n_462));
  AOI22XL g12070(.A0 (n_424), .A1 (\balance_db[3] [10]), .B0 (n_423),
       .B1 (\balance_db[11] [10]), .Y (n_461));
  AOI22XL g12071(.A0 (n_421), .A1 (\balance_db[13] [6]), .B0 (n_429),
       .B1 (\balance_db[15] [6]), .Y (n_460));
  AOI22X1 g12072(.A0 (\balance_db[4] [6]), .A1 (n_419), .B0
       (\balance_db[9] [6]), .B1 (n_437), .Y (n_459));
  AOI22XL g12073(.A0 (n_432), .A1 (\balance_db[6] [10]), .B0 (n_433),
       .B1 (\balance_db[7] [10]), .Y (n_458));
  AOI22XL g12074(.A0 (n_431), .A1 (\balance_db[14] [12]), .B0 (n_423),
       .B1 (\balance_db[11] [12]), .Y (n_457));
  AOI22XL g12075(.A0 (n_420), .A1 (\balance_db[5] [6]), .B0 (n_433),
       .B1 (\balance_db[7] [6]), .Y (n_456));
  AOI22XL g12076(.A0 (n_419), .A1 (\balance_db[4] [14]), .B0 (n_420),
       .B1 (\balance_db[5] [14]), .Y (n_455));
  NAND2XL g12077(.A (\balance_db[11] [5]), .B (n_423), .Y (n_454));
  NAND2XL g12078(.A (\balance_db[12] [8]), .B (n_425), .Y (n_453));
  NAND2XL g12079(.A (\balance_db[1] [2]), .B (n_436), .Y (n_452));
  NAND2XL g12080(.A (\balance_db[4] [4]), .B (n_419), .Y (n_451));
  NAND2XL g12081(.A (\balance_db[7] [9]), .B (n_433), .Y (n_450));
  AOI22X1 g12082(.A0 (\balance_db[6] [5]), .A1 (n_399), .B0
       (\balance_db[7] [5]), .B1 (n_400), .Y (n_449));
  AO22XL g12083(.A0 (\balance_db[0] [2]), .A1 (n_399), .B0
       (\balance_db[9] [2]), .B1 (n_397), .Y (n_448));
  AOI22X1 g12084(.A0 (\balance_db[8] [4]), .A1 (n_406), .B0
       (\balance_db[9] [4]), .B1 (n_397), .Y (n_447));
  AO22XL g12085(.A0 (\balance_db[12] [6]), .A1 (n_404), .B0
       (\balance_db[14] [6]), .B1 (n_409), .Y (n_446));
  AOI22X1 g12086(.A0 (\balance_db[6] [8]), .A1 (n_399), .B0
       (\balance_db[7] [8]), .B1 (n_400), .Y (n_445));
  OAI22X1 g12087(.A0 (\balance_db[1] [9]), .A1 (n_401), .B0
       (\balance_db[9] [9]), .B1 (n_391), .Y (n_444));
  OAI22X1 g12088(.A0 (\balance_db[0] [9]), .A1 (n_398), .B0
       (\balance_db[8] [9]), .B1 (n_405), .Y (n_443));
  AO22XL g12089(.A0 (\balance_db[10] [1]), .A1 (n_406), .B0
       (\balance_db[11] [1]), .B1 (n_397), .Y (n_442));
  OAI22X1 g12090(.A0 (\balance_db[8] [8]), .A1 (n_403), .B0
       (\balance_db[1] [8]), .B1 (n_401), .Y (n_441));
  OAI22X1 g12091(.A0 (\balance_db[0] [8]), .A1 (n_398), .B0
       (\balance_db[9] [8]), .B1 (n_391), .Y (n_440));
  AOI22X1 g12092(.A0 (\balance_db[1] [1]), .A1 (n_400), .B0
       (\balance_db[9] [1]), .B1 (n_397), .Y (n_439));
  AOI22X1 g12093(.A0 (\balance_db[0] [4]), .A1 (n_399), .B0
       (\balance_db[1] [4]), .B1 (n_400), .Y (n_438));
  NOR2XL g12094(.A (\balance_db[2] [3]), .B (n_398), .Y (n_428));
  NOR2XL g12095(.A (\balance_db[4] [2]), .B (n_398), .Y (n_427));
  NOR2XL g12096(.A (\balance_db[10] [3]), .B (n_403), .Y (n_426));
  NOR2XL g12097(.A (n_408), .B (n_391), .Y (n_437));
  NOR2XL g12098(.A (n_408), .B (n_401), .Y (n_436));
  NOR2XL g12099(.A (n_412), .B (n_398), .Y (n_435));
  NOR2XL g12100(.A (n_408), .B (n_398), .Y (n_434));
  NOR2XL g12101(.A (n_410), .B (n_401), .Y (n_433));
  NOR2XL g12102(.A (n_410), .B (n_398), .Y (n_432));
  NOR2XL g12103(.A (n_410), .B (n_403), .Y (n_431));
  NOR2XL g12104(.A (n_408), .B (n_403), .Y (n_430));
  NOR2XL g12105(.A (n_410), .B (n_391), .Y (n_429));
  MX2X1 g12106(.A (\balance_db[4] [1]), .B (\balance_db[5] [1]), .S0
       (id_to_check[0]), .Y (n_418));
  MX2X1 g12107(.A (\balance_db[6] [1]), .B (\balance_db[7] [1]), .S0
       (id_to_check[0]), .Y (n_417));
  MX2X1 g12108(.A (\balance_db[2] [2]), .B (\balance_db[3] [2]), .S0
       (id_to_check[0]), .Y (n_416));
  OAI22XL g12109(.A0 (id_to_check[3]), .A1 (\balance_db[3] [3]), .B0
       (n_395), .B1 (\balance_db[11] [3]), .Y (n_415));
  MX2X1 g12110(.A (\balance_db[5] [4]), .B (\balance_db[13] [4]), .S0
       (id_to_check[3]), .Y (n_414));
  NOR2XL g12111(.A (n_390), .B (n_403), .Y (n_425));
  NOR2XL g12112(.A (n_412), .B (n_401), .Y (n_424));
  NOR2XL g12113(.A (n_412), .B (n_391), .Y (n_423));
  NOR2XL g12114(.A (n_412), .B (n_403), .Y (n_422));
  NOR2XL g12115(.A (n_390), .B (n_391), .Y (n_421));
  NOR2XL g12116(.A (n_390), .B (n_401), .Y (n_420));
  NOR2XL g12117(.A (n_390), .B (n_398), .Y (n_419));
  CLKINVX1 g12118(.A (n_620), .Y (n_413));
  INVXL g12119(.A (n_412), .Y (n_411));
  INVXL g12120(.A (n_410), .Y (n_409));
  INVX1 g12121(.A (n_408), .Y (n_407));
  NAND2XL g12122(.A (n_621), .B (id_to_check[0]), .Y (n_620));
  NOR2XL g12123(.A (reset), .B (id_to_check[0]), .Y (n_619));
  NAND2XL g12124(.A (id_to_check[1]), .B (n_396), .Y (n_412));
  NAND2XL g12125(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_410));
  OR2X1 g12126(.A (id_to_check[2]), .B (id_to_check[1]), .Y (n_408));
  INVXL g12127(.A (n_406), .Y (n_405));
  CLKINVX1 g12128(.A (n_390), .Y (n_404));
  INVX1 g12129(.A (n_403), .Y (n_402));
  CLKINVX1 g12130(.A (n_401), .Y (n_400));
  CLKINVX1 g12131(.A (n_399), .Y (n_398));
  CLKINVX1 g12132(.A (n_391), .Y (n_397));
  NOR2XL g12133(.A (id_to_check[0]), .B (n_395), .Y (n_406));
  OR2X1 g12135(.A (id_to_check[0]), .B (n_395), .Y (n_403));
  NAND2XL g12136(.A (id_to_check[0]), .B (n_395), .Y (n_401));
  NOR2XL g12137(.A (id_to_check[3]), .B (id_to_check[0]), .Y (n_399));
  INVX1 g12139(.A (id_to_check[2]), .Y (n_396));
  CLKINVX1 g12141(.A (id_to_check[3]), .Y (n_395));
  INVX1 g12142(.A (\balance_db[6] [2]), .Y (n_394));
  NAND2BX1 g2(.AN (n_596), .B (n_591), .Y (n_393));
  NOR4BBX1 g12145(.AN (n_591), .BN (n_579), .C (n_574), .D (n_596), .Y
       (n_392));
  NAND2BXL g12146(.AN (n_395), .B (id_to_check[0]), .Y (n_391));
  NAND2BX1 g12147(.AN (id_to_check[1]), .B (id_to_check[2]), .Y
       (n_390));
  SDFFQX1 \balance_db_reg[1][1] (.CK (clk), .D (n_380), .SI (DFT_sdi),
       .SE (DFT_sen), .Q (\balance_db[1] [1]));
  SDFFQX1 \balance_db_reg[1][2] (.CK (clk), .D (n_387), .SI
       (\balance_db[1] [1]), .SE (DFT_sen), .Q (\balance_db[1] [2]));
  SDFFQX1 \balance_db_reg[1][3] (.CK (clk), .D (n_371), .SI
       (\balance_db[1] [2]), .SE (DFT_sen), .Q (\balance_db[1] [3]));
  SDFFQX1 \balance_db_reg[1][4] (.CK (clk), .D (n_379), .SI
       (\balance_db[1] [3]), .SE (DFT_sen), .Q (\balance_db[1] [4]));
  SDFFQX1 \balance_db_reg[1][5] (.CK (clk), .D (n_388), .SI
       (\balance_db[1] [4]), .SE (DFT_sen), .Q (\balance_db[1] [5]));
  SDFFQX1 \balance_db_reg[1][6] (.CK (clk), .D (n_386), .SI
       (\balance_db[1] [5]), .SE (DFT_sen), .Q (\balance_db[1] [6]));
  SDFFQX1 \balance_db_reg[1][7] (.CK (clk), .D (n_362), .SI
       (\balance_db[1] [6]), .SE (DFT_sen), .Q (\balance_db[1] [7]));
  SDFFQX1 \balance_db_reg[1][8] (.CK (clk), .D (n_359), .SI
       (\balance_db[1] [7]), .SE (DFT_sen), .Q (\balance_db[1] [8]));
  SDFFQX1 \balance_db_reg[1][9] (.CK (clk), .D (n_356), .SI
       (\balance_db[1] [8]), .SE (DFT_sen), .Q (\balance_db[1] [9]));
  SDFFQX1 \balance_db_reg[1][10] (.CK (clk), .D (n_354), .SI
       (\balance_db[1] [9]), .SE (DFT_sen), .Q (\balance_db[1] [10]));
  SDFFQX1 \balance_db_reg[1][11] (.CK (clk), .D (n_352), .SI
       (\balance_db[1] [10]), .SE (DFT_sen), .Q (\balance_db[1] [11]));
  SDFFQX1 \balance_db_reg[1][12] (.CK (clk), .D (n_368), .SI
       (\balance_db[1] [11]), .SE (DFT_sen), .Q (\balance_db[1] [12]));
  SDFFQX1 \balance_db_reg[1][13] (.CK (clk), .D (n_376), .SI
       (\balance_db[1] [12]), .SE (DFT_sen), .Q (\balance_db[1] [13]));
  SDFFQX1 \balance_db_reg[1][14] (.CK (clk), .D (n_375), .SI
       (\balance_db[1] [13]), .SE (DFT_sen), .Q (\balance_db[1] [14]));
  SDFFQX1 \balance_db_reg[2][1] (.CK (clk), .D (n_383), .SI
       (\balance_db[1] [14]), .SE (DFT_sen), .Q (\balance_db[2] [1]));
  SDFFQX1 \balance_db_reg[2][2] (.CK (clk), .D (n_369), .SI
       (\balance_db[2] [1]), .SE (DFT_sen), .Q (\balance_db[2] [2]));
  SDFFQX1 \balance_db_reg[2][3] (.CK (clk), .D (n_374), .SI
       (\balance_db[2] [2]), .SE (DFT_sen), .Q (\balance_db[2] [3]));
  SDFFQX1 \balance_db_reg[2][4] (.CK (clk), .D (n_382), .SI
       (\balance_db[2] [3]), .SE (DFT_sen), .Q (\balance_db[2] [4]));
  SDFFQX1 \balance_db_reg[2][5] (.CK (clk), .D (n_373), .SI
       (\balance_db[2] [4]), .SE (DFT_sen), .Q (\balance_db[2] [5]));
  SDFFQX1 \balance_db_reg[2][6] (.CK (clk), .D (n_381), .SI
       (\balance_db[2] [5]), .SE (DFT_sen), .Q (\balance_db[2] [6]));
  SDFFQX1 \balance_db_reg[2][7] (.CK (clk), .D (n_372), .SI
       (\balance_db[2] [6]), .SE (DFT_sen), .Q (\balance_db[2] [7]));
  SDFFQX1 \balance_db_reg[2][8] (.CK (clk), .D (n_370), .SI
       (\balance_db[2] [7]), .SE (DFT_sen), .Q (\balance_db[2] [8]));
  SDFFQX1 \balance_db_reg[2][9] (.CK (clk), .D (n_348), .SI
       (\balance_db[2] [8]), .SE (DFT_sen), .Q (\balance_db[2] [9]));
  SDFFQX1 \balance_db_reg[2][10] (.CK (clk), .D (n_367), .SI
       (\balance_db[2] [9]), .SE (DFT_sen), .Q (\balance_db[2] [10]));
  SDFFQX1 \balance_db_reg[2][11] (.CK (clk), .D (n_366), .SI
       (\balance_db[2] [10]), .SE (DFT_sen), .Q (\balance_db[2] [11]));
  SDFFQX1 \balance_db_reg[2][12] (.CK (clk), .D (n_365), .SI
       (\balance_db[2] [11]), .SE (DFT_sen), .Q (\balance_db[2] [12]));
  SDFFQX1 \balance_db_reg[2][13] (.CK (clk), .D (n_364), .SI
       (\balance_db[2] [12]), .SE (DFT_sen), .Q (\balance_db[2] [13]));
  SDFFQX1 \balance_db_reg[2][14] (.CK (clk), .D (n_363), .SI
       (\balance_db[2] [13]), .SE (DFT_sen), .Q (DFT_sdo));
  SDFFQX1 \balance_db_reg[3][1] (.CK (clk), .D (n_378), .SI
       (DFT_sdi_1), .SE (DFT_sen), .Q (\balance_db[3] [1]));
  SDFFQX1 \balance_db_reg[3][2] (.CK (clk), .D (n_385), .SI
       (\balance_db[3] [1]), .SE (DFT_sen), .Q (\balance_db[3] [2]));
  SDFFQX1 \balance_db_reg[3][3] (.CK (clk), .D (n_361), .SI
       (\balance_db[3] [2]), .SE (DFT_sen), .Q (\balance_db[3] [3]));
  SDFFQX1 \balance_db_reg[3][4] (.CK (clk), .D (n_384), .SI
       (\balance_db[3] [3]), .SE (DFT_sen), .Q (\balance_db[3] [4]));
  SDFFQX1 \balance_db_reg[3][5] (.CK (clk), .D (n_360), .SI
       (\balance_db[3] [4]), .SE (DFT_sen), .Q (\balance_db[3] [5]));
  SDFFQX1 \balance_db_reg[3][6] (.CK (clk), .D (n_377), .SI
       (\balance_db[3] [5]), .SE (DFT_sen), .Q (\balance_db[3] [6]));
  SDFFQX1 \balance_db_reg[3][7] (.CK (clk), .D (n_358), .SI
       (\balance_db[3] [6]), .SE (DFT_sen), .Q (\balance_db[3] [7]));
  SDFFQX1 \balance_db_reg[3][8] (.CK (clk), .D (n_357), .SI
       (\balance_db[3] [7]), .SE (DFT_sen), .Q (\balance_db[3] [8]));
  SDFFQX1 \balance_db_reg[3][9] (.CK (clk), .D (n_355), .SI
       (\balance_db[3] [8]), .SE (DFT_sen), .Q (\balance_db[3] [9]));
  SDFFQX1 \balance_db_reg[3][10] (.CK (clk), .D (n_353), .SI
       (\balance_db[3] [9]), .SE (DFT_sen), .Q (\balance_db[3] [10]));
  SDFFQX1 \balance_db_reg[3][11] (.CK (clk), .D (n_351), .SI
       (\balance_db[3] [10]), .SE (DFT_sen), .Q (\balance_db[3] [11]));
  SDFFQX1 \balance_db_reg[3][12] (.CK (clk), .D (n_350), .SI
       (\balance_db[3] [11]), .SE (DFT_sen), .Q (\balance_db[3] [12]));
  SDFFQX1 \balance_db_reg[3][13] (.CK (clk), .D (n_349), .SI
       (\balance_db[3] [12]), .SE (DFT_sen), .Q (\balance_db[3] [13]));
  SDFFQX1 \balance_db_reg[3][14] (.CK (clk), .D (n_389), .SI
       (\balance_db[3] [13]), .SE (DFT_sen), .Q (\balance_db[3] [14]));
  AO22XL g3925(.A0 (n_334), .A1 (\balance_db[3] [14]), .B0 (n_330), .B1
       (n_645), .Y (n_389));
  NAND2XL g3926(.A (n_621), .B (n_340), .Y (n_388));
  OAI211X1 g3927(.A0 (n_614), .A1 (n_321), .B0 (n_621), .C0 (n_338), .Y
       (n_387));
  OAI211X1 g3928(.A0 (n_616), .A1 (n_321), .B0 (n_621), .C0 (n_332), .Y
       (n_386));
  OAI211X1 g3929(.A0 (n_614), .A1 (n_331), .B0 (n_621), .C0 (n_336), .Y
       (n_385));
  OAI211X1 g3930(.A0 (n_615), .A1 (n_331), .B0 (n_621), .C0 (n_333), .Y
       (n_384));
  OAI21X1 g3931(.A0 (n_327), .A1 (n_626), .B0 (n_346), .Y (n_383));
  OAI21X1 g3932(.A0 (n_327), .A1 (n_615), .B0 (n_347), .Y (n_382));
  OAI21X1 g3933(.A0 (n_327), .A1 (n_616), .B0 (n_344), .Y (n_381));
  OAI21XL g3934(.A0 (n_626), .A1 (n_318), .B0 (n_345), .Y (n_380));
  OAI21XL g3935(.A0 (n_615), .A1 (n_318), .B0 (n_341), .Y (n_379));
  OAI21X1 g3936(.A0 (n_329), .A1 (n_626), .B0 (n_342), .Y (n_378));
  OAI21X1 g3937(.A0 (n_329), .A1 (n_616), .B0 (n_343), .Y (n_377));
  AO22XL g3938(.A0 (n_335), .A1 (\balance_db[1] [13]), .B0 (n_319), .B1
       (n_632), .Y (n_376));
  AO22XL g3939(.A0 (n_335), .A1 (\balance_db[1] [14]), .B0 (n_319), .B1
       (n_645), .Y (n_375));
  AO22XL g3940(.A0 (n_339), .A1 (\balance_db[2] [3]), .B0 (n_328), .B1
       (n_637), .Y (n_374));
  AO22XL g3941(.A0 (n_339), .A1 (\balance_db[2] [5]), .B0 (n_328), .B1
       (n_638), .Y (n_373));
  AO22XL g3942(.A0 (n_339), .A1 (\balance_db[2] [7]), .B0 (n_328), .B1
       (n_634), .Y (n_372));
  AO22XL g3943(.A0 (n_335), .A1 (\balance_db[1] [3]), .B0 (n_319), .B1
       (n_637), .Y (n_371));
  AO22XL g3944(.A0 (n_339), .A1 (\balance_db[2] [8]), .B0 (n_328), .B1
       (n_654), .Y (n_370));
  OAI211X1 g3945(.A0 (n_614), .A1 (n_326), .B0 (n_621), .C0 (n_337), .Y
       (n_369));
  AO22XL g3946(.A0 (n_335), .A1 (\balance_db[1] [12]), .B0 (n_319), .B1
       (n_651), .Y (n_368));
  AO22XL g3947(.A0 (n_339), .A1 (\balance_db[2] [10]), .B0 (n_328), .B1
       (n_652), .Y (n_367));
  AO22XL g3948(.A0 (n_339), .A1 (\balance_db[2] [11]), .B0 (n_328), .B1
       (n_633), .Y (n_366));
  AO22XL g3949(.A0 (n_339), .A1 (\balance_db[2] [12]), .B0 (n_328), .B1
       (n_651), .Y (n_365));
  AO22XL g3950(.A0 (n_339), .A1 (\balance_db[2] [13]), .B0 (n_328), .B1
       (n_632), .Y (n_364));
  AO22XL g3951(.A0 (n_339), .A1 (DFT_sdo), .B0 (n_328), .B1 (n_645), .Y
       (n_363));
  AO22XL g3952(.A0 (n_335), .A1 (\balance_db[1] [7]), .B0 (n_319), .B1
       (n_634), .Y (n_362));
  AO22XL g3953(.A0 (n_334), .A1 (\balance_db[3] [3]), .B0 (n_330), .B1
       (n_637), .Y (n_361));
  AO22XL g3954(.A0 (n_334), .A1 (\balance_db[3] [5]), .B0 (n_330), .B1
       (n_638), .Y (n_360));
  AO22XL g3955(.A0 (n_335), .A1 (\balance_db[1] [8]), .B0 (n_319), .B1
       (n_654), .Y (n_359));
  AO22XL g3956(.A0 (n_334), .A1 (\balance_db[3] [7]), .B0 (n_330), .B1
       (n_634), .Y (n_358));
  AO22XL g3957(.A0 (n_334), .A1 (\balance_db[3] [8]), .B0 (n_330), .B1
       (n_654), .Y (n_357));
  AO22XL g3958(.A0 (n_335), .A1 (\balance_db[1] [9]), .B0 (n_319), .B1
       (n_636), .Y (n_356));
  AO22XL g3959(.A0 (n_334), .A1 (\balance_db[3] [9]), .B0 (n_330), .B1
       (n_636), .Y (n_355));
  AO22XL g3960(.A0 (n_335), .A1 (\balance_db[1] [10]), .B0 (n_319), .B1
       (n_652), .Y (n_354));
  AO22XL g3961(.A0 (n_334), .A1 (\balance_db[3] [10]), .B0 (n_330), .B1
       (n_652), .Y (n_353));
  AO22XL g3962(.A0 (n_335), .A1 (\balance_db[1] [11]), .B0 (n_319), .B1
       (n_633), .Y (n_352));
  AO22XL g3963(.A0 (n_334), .A1 (\balance_db[3] [11]), .B0 (n_330), .B1
       (n_633), .Y (n_351));
  AO22XL g3964(.A0 (n_334), .A1 (\balance_db[3] [12]), .B0 (n_330), .B1
       (n_651), .Y (n_350));
  AO22XL g3965(.A0 (n_334), .A1 (\balance_db[3] [13]), .B0 (n_330), .B1
       (n_632), .Y (n_349));
  AO22XL g3966(.A0 (n_339), .A1 (\balance_db[2] [9]), .B0 (n_328), .B1
       (n_636), .Y (n_348));
  NAND2XL g3967(.A (n_339), .B (\balance_db[2] [4]), .Y (n_347));
  NAND2XL g3968(.A (n_339), .B (\balance_db[2] [1]), .Y (n_346));
  NAND2XL g3969(.A (n_335), .B (\balance_db[1] [1]), .Y (n_345));
  NAND2XL g3970(.A (n_339), .B (\balance_db[2] [6]), .Y (n_344));
  NAND2XL g3971(.A (n_334), .B (\balance_db[3] [6]), .Y (n_343));
  NAND2XL g3972(.A (n_334), .B (\balance_db[3] [1]), .Y (n_342));
  NAND2XL g3973(.A (n_335), .B (\balance_db[1] [4]), .Y (n_341));
  MXI2XL g3974(.A (n_638), .B (\balance_db[1] [5]), .S0 (n_321), .Y
       (n_340));
  NAND2XL g3975(.A (\balance_db[1] [2]), .B (n_321), .Y (n_338));
  NAND2XL g3976(.A (\balance_db[2] [2]), .B (n_326), .Y (n_337));
  NAND2XL g3977(.A (\balance_db[3] [2]), .B (n_331), .Y (n_336));
  NAND2XL g3978(.A (n_322), .B (n_620), .Y (n_339));
  NAND2XL g3979(.A (\balance_db[3] [4]), .B (n_331), .Y (n_333));
  NAND2XL g3980(.A (\balance_db[1] [6]), .B (n_321), .Y (n_332));
  AO21X1 g3981(.A0 (n_621), .A1 (n_295), .B0 (n_619), .Y (n_335));
  NAND2BX1 g3982(.AN (n_619), .B (n_322), .Y (n_334));
  INVX1 g3983(.A (n_330), .Y (n_329));
  CLKINVX1 g3984(.A (n_328), .Y (n_327));
  NAND2XL g3985(.A (id_to_check[0]), .B (n_114), .Y (n_331));
  NOR2XL g3986(.A (n_620), .B (n_294), .Y (n_330));
  NOR2BX1 g3987(.AN (n_619), .B (n_294), .Y (n_328));
  CLKINVX1 g3988(.A (n_319), .Y (n_318));
  NAND2BX1 g3989(.AN (id_to_check[0]), .B (n_114), .Y (n_326));
  NAND2XL g3990(.A (n_621), .B (n_294), .Y (n_322));
  NAND2BX1 g3991(.AN (n_295), .B (id_to_check[0]), .Y (n_321));
  NOR2XL g3992(.A (n_620), .B (n_295), .Y (n_319));
  NAND2BX1 g3993(.AN (id_to_check[1]), .B (n_67), .Y (n_295));
  INVX1 g3994(.A (n_294), .Y (n_114));
  NAND2XL g3995(.A (id_to_check[1]), .B (n_67), .Y (n_294));
  NOR4BX1 g3996(.AN (fsm_charge_req), .B (id_to_check[3]), .C
       (id_to_check[2]), .D (n_627), .Y (n_67));
  CLKINVX1 g3997(.A (reset), .Y (n_621));
endmodule

module barrier_ctrl(clk, reset, fsm_open_en, fsm_close_en,
     barrier_open_cmd, barrier_close_cmd, gate_is_open, gate_is_closed,
     DFT_sdi, DFT_sen, DFT_sdo);
  input clk, reset, fsm_open_en, fsm_close_en, DFT_sdi, DFT_sen;
  output barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed, DFT_sdo;
  wire clk, reset, fsm_open_en, fsm_close_en, DFT_sdi, DFT_sen;
  wire barrier_open_cmd, barrier_close_cmd, gate_is_open,
       gate_is_closed, DFT_sdo;
  wire [2:0] barrier_position_counter;
  wire n_7, n_13, n_21, n_28, n_29, n_30, n_31, n_36;
  wire n_37, n_38, n_39, n_40, n_41, n_42, n_43, n_45;
  wire n_46, n_47, n_54;
  INVXL g162(.A (n_46), .Y (gate_is_closed));
  SDFFQX1 barrier_close_cmd_reg(.CK (clk), .D (n_43), .SI (DFT_sdi),
       .SE (DFT_sen), .Q (barrier_close_cmd));
  SDFFQX1 barrier_open_cmd_reg(.CK (clk), .D (n_42), .SI
       (barrier_close_cmd), .SE (DFT_sen), .Q (barrier_open_cmd));
  AO21X1 g229(.A0 (n_41), .A1 (fsm_close_en), .B0 (reset), .Y (n_43));
  OAI31X1 g230(.A0 (reset), .A1 (n_39), .A2 (fsm_close_en), .B0 (n_41),
       .Y (n_42));
  CLKINVX1 g231(.A (n_45), .Y (n_41));
  NOR2XL g232(.A (reset), .B (n_47), .Y (n_45));
  NAND2XL g233(.A (n_40), .B (fsm_open_en), .Y (n_47));
  NAND3X1 g234(.A (DFT_sdo), .B (barrier_position_counter[1]), .C
       (barrier_position_counter[0]), .Y (n_40));
  OR3X1 g235(.A (barrier_position_counter[1]), .B
       (barrier_position_counter[0]), .C (DFT_sdo), .Y (n_46));
  INVXL g236(.A (fsm_open_en), .Y (n_39));
  SDFFQX1 \barrier_position_counter_reg[2] (.CK (clk), .D (n_38), .SI
       (barrier_position_counter[1]), .SE (DFT_sen), .Q (DFT_sdo));
  NAND2XL g319(.A (n_7), .B (n_37), .Y (n_38));
  SDFFQX1 \barrier_position_counter_reg[1] (.CK (clk), .D (n_36), .SI
       (barrier_position_counter[0]), .SE (DFT_sen), .Q
       (barrier_position_counter[1]));
  OAI31X1 g321(.A0 (n_45), .A1 (n_13), .A2 (n_29), .B0 (DFT_sdo), .Y
       (n_37));
  SMDFFHQX1 \barrier_position_counter_reg[0] (.CK (clk), .D0 (n_30),
       .D1 (n_13), .S0 (barrier_position_counter[0]), .SI
       (barrier_open_cmd), .SE (DFT_sen), .Q
       (barrier_position_counter[0]));
  OAI211X1 g323(.A0 (n_21), .A1 (n_54), .B0 (n_31), .C0 (n_28), .Y
       (n_36));
  NAND2XL g324(.A (n_45), .B (n_54), .Y (n_31));
  NAND2BXL g325(.AN (n_45), .B (n_21), .Y (n_30));
  AOI2BB1X1 g326(.A0N (barrier_position_counter[0]), .A1N
       (barrier_position_counter[1]), .B0 (n_21), .Y (n_29));
  NAND2XL g327(.A (n_13), .B (barrier_position_counter[1]), .Y (n_28));
  NAND4BXL g328(.AN (reset), .B (n_46), .C (fsm_close_en), .D (n_47),
       .Y (n_21));
  NOR3BX1 g329(.AN (n_47), .B (reset), .C (fsm_close_en), .Y (n_13));
  NAND3X1 g330(.A (n_45), .B (barrier_position_counter[0]), .C
       (barrier_position_counter[1]), .Y (n_7));
  CLKXOR2X1 g2(.A (barrier_position_counter[0]), .B
       (barrier_position_counter[1]), .Y (n_54));
endmodule

module vehicle_interface(clk, reset, fsm_read_en, vehicle_id_in,
     id_to_check, id_valid, DFT_sdi, DFT_sen);
  input clk, reset, fsm_read_en, DFT_sdi, DFT_sen;
  input [7:0] vehicle_id_in;
  output [3:0] id_to_check;
  output id_valid;
  wire clk, reset, fsm_read_en, DFT_sdi, DFT_sen;
  wire [7:0] vehicle_id_in;
  wire [3:0] id_to_check;
  wire id_valid;
  wire n_8, n_10, n_11, n_12, n_13, n_28;
  SDFFQX1 id_valid_reg(.CK (clk), .D (n_28), .SI (id_to_check[3]), .SE
       (DFT_sen), .Q (id_valid));
  SDFFQX1 \id_to_check_reg[0] (.CK (clk), .D (n_12), .SI (DFT_sdi), .SE
       (DFT_sen), .Q (id_to_check[0]));
  SDFFQX1 \id_to_check_reg[1] (.CK (clk), .D (n_13), .SI
       (id_to_check[0]), .SE (DFT_sen), .Q (id_to_check[1]));
  SDFFQX1 \id_to_check_reg[2] (.CK (clk), .D (n_11), .SI
       (id_to_check[1]), .SE (DFT_sen), .Q (id_to_check[2]));
  SDFFQX1 \id_to_check_reg[3] (.CK (clk), .D (n_10), .SI
       (id_to_check[2]), .SE (DFT_sen), .Q (id_to_check[3]));
  AO22XL g196(.A0 (n_8), .A1 (id_to_check[1]), .B0 (vehicle_id_in[1]),
       .B1 (n_28), .Y (n_13));
  AO22XL g197(.A0 (n_8), .A1 (id_to_check[0]), .B0 (vehicle_id_in[0]),
       .B1 (n_28), .Y (n_12));
  AO22XL g198(.A0 (n_8), .A1 (id_to_check[2]), .B0 (vehicle_id_in[2]),
       .B1 (n_28), .Y (n_11));
  AO22XL g199(.A0 (n_8), .A1 (id_to_check[3]), .B0 (vehicle_id_in[3]),
       .B1 (n_28), .Y (n_10));
  NOR2XL g201(.A (reset), .B (fsm_read_en), .Y (n_8));
  NOR2BX1 g202(.AN (fsm_read_en), .B (reset), .Y (n_28));
endmodule

module toll_gate(clk, reset, sensor_vehicle_enter, sensor_vehicle_exit,
     vehicle_id_in, barrier_open_cmd, barrier_close_cmd, led_status,
     display_out, scan_en, DFT_sdi_1, DFT_sdo_1, DFT_sdi_2, DFT_sdo_2);
  input clk, reset, sensor_vehicle_enter, sensor_vehicle_exit, scan_en,
       DFT_sdi_1, DFT_sdi_2;
  input [7:0] vehicle_id_in;
  output barrier_open_cmd, barrier_close_cmd, DFT_sdo_1, DFT_sdo_2;
  output [1:0] led_status;
  output [7:0] display_out;
  wire clk, reset, sensor_vehicle_enter, sensor_vehicle_exit, scan_en,
       DFT_sdi_1, DFT_sdi_2;
  wire [7:0] vehicle_id_in;
  wire barrier_open_cmd, barrier_close_cmd, DFT_sdo_1, DFT_sdo_2;
  wire [1:0] led_status;
  wire [7:0] display_out;
  wire [3:0] id_to_check;
  wire [2:0] state;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED_HIER_Z, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z1,
       UNCONNECTED_HIER_Z2;
  wire charge_done, gate_is_closed, gate_is_open, id_valid, n_18, n_23,
       n_24, n_25;
  wire n_26, n_27, n_30, n_31, n_33, n_34, n_37, n_38;
  wire n_39, n_40, n_41, n_42, n_43, n_44, n_45, n_46;
  wire n_47, n_48, n_49, n_50, n_54, n_63, n_64, n_67;
  wire n_70, n_71, n_80, sufficient_balance;
  assign display_out[4] = 1'b0;
  assign display_out[7] = 1'b0;
  account_balance u_account_balance(.clk (clk), .reset (reset),
       .id_to_check ({UNCONNECTED2, UNCONNECTED1, UNCONNECTED0,
       UNCONNECTED, id_to_check}), .fsm_check_req (n_71),
       .fsm_charge_req (n_64), .sufficient_balance
       (sufficient_balance), .charge_done (charge_done), .DFT_sdi
       (DFT_sdi_1), .DFT_sen (scan_en), .DFT_sdo (DFT_sdo_1),
       .DFT_sdi_1 (DFT_sdi_2));
  barrier_ctrl u_barrier_ctrl(.clk (clk), .reset (reset), .fsm_open_en
       (n_67), .fsm_close_en (n_70), .barrier_open_cmd
       (barrier_open_cmd), .barrier_close_cmd (barrier_close_cmd),
       .gate_is_open (gate_is_open), .gate_is_closed (gate_is_closed),
       .DFT_sdi (charge_done), .DFT_sen (scan_en), .DFT_sdo (n_80));
  vehicle_interface u_vehicle_interface(.clk (clk), .reset (reset),
       .fsm_read_en (n_63), .vehicle_id_in ({UNCONNECTED_HIER_Z2,
       UNCONNECTED_HIER_Z1, UNCONNECTED_HIER_Z0, UNCONNECTED_HIER_Z,
       vehicle_id_in[3:0]}), .id_to_check (id_to_check), .id_valid
       (id_valid), .DFT_sdi (n_80), .DFT_sen (scan_en));
  INVXL g252(.A (display_out[5]), .Y (display_out[6]));
  INVXL g253(.A (n_67), .Y (led_status[0]));
  INVXL g254(.A (sensor_vehicle_enter), .Y (n_50));
  NAND2BXL g395(.AN (n_67), .B (display_out[2]), .Y (display_out[1]));
  AO21X1 g396(.A0 (state[0]), .A1 (n_71), .B0 (n_67), .Y
       (led_status[1]));
  OAI21XL g397(.A0 (n_46), .A1 (n_45), .B0 (display_out[2]), .Y
       (display_out[3]));
  NAND3BXL g398(.AN (n_49), .B (n_54), .C (n_48), .Y (display_out[0]));
  AO22X1 g399(.A0 (n_54), .A1 (n_49), .B0 (DFT_sdo_2), .B1 (n_46), .Y
       (n_70));
  NOR2XL g400(.A (n_54), .B (n_48), .Y (display_out[5]));
  NOR2XL g401(.A (state[1]), .B (n_48), .Y (n_67));
  NOR2XL g402(.A (state[1]), .B (n_47), .Y (n_63));
  NOR2XL g403(.A (n_54), .B (n_47), .Y (n_64));
  NAND2XL g404(.A (n_45), .B (n_46), .Y (display_out[2]));
  NOR2XL g405(.A (state[0]), .B (DFT_sdo_2), .Y (n_49));
  NAND2XL g406(.A (state[0]), .B (DFT_sdo_2), .Y (n_48));
  NAND2XL g407(.A (state[0]), .B (n_45), .Y (n_47));
  NOR2XL g408(.A (DFT_sdo_2), .B (n_54), .Y (n_71));
  NOR2XL g409(.A (state[0]), .B (n_54), .Y (n_46));
  CLKINVX1 g410(.A (state[1]), .Y (n_54));
  INVX1 g411(.A (DFT_sdo_2), .Y (n_45));
  SDFFQX1 \state_reg[0] (.CK (clk), .D (n_43), .SI (id_valid), .SE
       (scan_en), .Q (state[0]));
  SDFFQX1 \state_reg[1] (.CK (clk), .D (n_44), .SI (state[0]), .SE
       (scan_en), .Q (state[1]));
  SDFFQX1 \state_reg[2] (.CK (clk), .D (n_42), .SI (state[1]), .SE
       (scan_en), .Q (DFT_sdo_2));
  OAI221X1 g463(.A0 (n_39), .A1 (n_30), .B0 (n_37), .B1 (n_33), .C0
       (n_40), .Y (n_44));
  OAI221X1 g464(.A0 (sensor_vehicle_exit), .A1 (n_34), .B0 (n_37), .B1
       (n_27), .C0 (n_41), .Y (n_43));
  OAI211X1 g465(.A0 (n_37), .A1 (n_31), .B0 (n_34), .C0 (n_40), .Y
       (n_42));
  NAND2XL g466(.A (n_24), .B (n_38), .Y (n_41));
  OR4XL g467(.A (n_26), .B (state[0]), .C (n_54), .D (gate_is_closed),
       .Y (n_40));
  AOI22X1 g468(.A0 (n_24), .A1 (id_valid), .B0 (sensor_vehicle_exit),
       .B1 (n_25), .Y (n_39));
  OAI32X1 g469(.A0 (n_50), .A1 (state[0]), .A2 (state[1]), .B0
       (id_valid), .B1 (n_18), .Y (n_38));
  NAND2XL g470(.A (n_24), .B (state[1]), .Y (n_37));
  INVX1 g471(.A (n_31), .Y (n_33));
  OR2X1 g472(.A (n_26), .B (n_30), .Y (n_34));
  OAI22X1 g473(.A0 (charge_done), .A1 (n_18), .B0 (state[0]), .B1
       (n_23), .Y (n_31));
  NOR2XL g474(.A (state[0]), .B (sufficient_balance), .Y (n_27));
  NAND2BX1 g475(.AN (state[1]), .B (state[0]), .Y (n_30));
  INVXL g476(.A (n_26), .Y (n_25));
  NAND2BX1 g477(.AN (reset), .B (DFT_sdo_2), .Y (n_26));
  NOR2XL g478(.A (reset), .B (DFT_sdo_2), .Y (n_24));
  CLKINVX1 g488(.A (state[0]), .Y (n_18));
  INVX1 g489(.A (sufficient_balance), .Y (n_23));
endmodule

